# 🎶 Traducción de Letras de Canciones

## Objetivo
El objetivo de este notebook es detectar el idioma de las canciones y traducir aquellas que no estén en inglés. Esto nos permitirá entrenar eficazmente un modelo de Roberta con canciones de distintos países y variedad. 🌍🎤

## Descripción del Proceso

1. **Importación de Módulos y Configuración Inicial** 📦
    - Importamos las bibliotecas necesarias como `pandas`, `langdetect`, `googletrans`, `deep_translator`, entre otras.
    - Configuramos los límites de tamaño de campo y rutas de los archivos.

2. **Carga y Filtrado de Datos** 📂
    - Cargamos los archivos CSV con las letras de canciones.
    - Filtramos las canciones que no están en inglés y aquellas que no tienen traducción.

3. **Detección de Idioma y Traducción** 🌐
    - Utilizamos `langdetect` para detectar el idioma de las letras.
    - Traducimos las letras no inglesas usando `googletrans` y `deep_translator`.

4. **Limpieza y Procesamiento de Texto** 🧹
    - Limpiamos las letras eliminando saltos de línea y espacios múltiples.
    - Dividimos textos largos para evitar errores en la traducción.

5. **Guardado de Resultados y Manejo de Errores** 💾
    - Guardamos las letras traducidas en un nuevo archivo CSV.
    - Registramos los errores encontrados durante el proceso de traducción.

6. **Verificación y Análisis** 🔍
    - Verificamos las traducciones y analizamos los resultados.
    - Fusionamos los datos traducidos con el archivo original para obtener un dataset completo.

## Herramientas Utilizadas
- `pandas` para manipulación de datos.
- `langdetect` para detección de idioma.
- `googletrans` y `deep_translator` para traducción automática.
- `tqdm` para mostrar el progreso del procesamiento.
- `transformers` para utilizar modelos avanzados de traducción como MarianMT.

## Resultados Esperados
Al final del proyecto, esperamos tener un dataset completo con letras de canciones traducidas al inglés, listo para ser utilizado en el entrenamiento de modelos de procesamiento de lenguaje natural (NLP). 🎯📊

## Cosas que se han probado
- `transformers` para utilizar modelos avanzados de traducción como MarianMT.

Facebook traductor

In [3]:
import pandas as pd

# Ruta del archivo combinado
file_path = r"C:\Users\solan\MoodTune\data\procesando\df_80-200_p7_last.csv"
output_filtered_path = r"C:\Users\solan\MoodTune\data\procesando\df_80-200_p7_to_translate.csv"

# Cargar el archivo CSV combinado
df = pd.read_csv(file_path, encoding='utf-8')

# Filtrar las filas donde la columna 'language' es nula o no es inglés
df_to_translate = df[df['language'].isnull() | (df['language'] != 'en')]

# Guardar el DataFrame filtrado en un nuevo archivo CSV
df_to_translate.to_csv(output_filtered_path, index=False, encoding='utf-8')

print(f"✅ Canciones con 'language' nulo o no en inglés guardadas en {output_filtered_path}")

C:\Users\solan\AppData\Local\Temp\ipykernel_34520\18425513.py:8: DtypeWarning: Columns (74,75,76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, encoding='utf-8')

✅ Canciones con 'language' nulo o no en inglés guardadas en C:\Users\solan\MoodTune\data\procesando\df_80-200_p7_to_translate.csv

In [ ]:
import sys
import csv
import pandas as pd
from langdetect import detect
from deep_translator import GoogleTranslator
import re
from tqdm import tqdm  # Barra de progreso
import time
import os
from collections import deque  # Para mostrar solo los últimos 20 procesos

# 📌 Aumentar el límite del tamaño de campo
sys.setrecursionlimit(10000)
csv.field_size_limit(10**9)

# 📌 Configuración de archivos con los directorios correctos
PROCESANDO_DIR = "C:/Users/solan/MoodTune/data/procesando/"
PROCESADO_DIR = "C:/Users/solan/MoodTune/data/procesando/"

# 📌 Buscar el archivo más reciente en `procesando/`
file_path = os.path.join(PROCESANDO_DIR, "df_80-200_p7_to_translate.csv")

# 📌 Nombre del archivo de salida y errores
output_file_path = os.path.join(PROCESANDO_DIR, "df_80-200_p7_last_traducidas.csv")
error_file_path = os.path.join(PROCESANDO_DIR, "errors_log_traduccion.csv")

# 📌 Crear la carpeta si no existe
os.makedirs(PROCESANDO_DIR, exist_ok=True)

# 📌 Inicializar el traductor
translator = GoogleTranslator(source="auto", target="en")

# 🔹 Función para limpiar texto antes de traducir
def clean_text(text):
    if pd.isna(text):
        return ""
    return re.sub(r'\s+', ' ', text.replace('\n', ' ').strip())

# 🔹 Función para dividir textos largas (GoogleTranslator tiene un límite)
def split_text(text, max_length=500):
    return [text[i:i+max_length] for i in range(0, len(text), max_length)]

# 📌 Cargar datos originales
data = pd.read_csv(file_path, encoding='utf-8', engine='python')

# 📌 Verificar si `translated_lyrics` y `language` existen, si no, crearlas
if 'translated_lyrics' not in data.columns:
    data['translated_lyrics'] = pd.NA

if 'language' not in data.columns:
    data['language'] = pd.NA  # Crear la columna de idioma si no existe

# 📌 Crear DataFrame para errores
errors = pd.DataFrame(columns=['index', 'recording_id', 'error_message'])

# 📌 Mantener solo los últimos 20 logs en la terminal
last_logs = deque(maxlen=20)

# 🔁 Procesar y traducir
for index, row in tqdm(data.iterrows(), total=data.shape[0], desc="🔄 Traduciendo canciones"):
    try:
        # Saltar si ya está traducido
        if pd.notnull(row['translated_lyrics']) and str(row['translated_lyrics']).strip() != "":
            continue  

        lyrics_cleaned = clean_text(row['lyrics'])

        # 🔹 Evitar traducciones de textos vacíos
        if not lyrics_cleaned.strip():
            last_logs.append(f"⚠️ Letra vacía para {row['recording_id']}. Saltando...")
            continue

        # 🔹 Detectar idioma si no está en la columna "language"
        if pd.isna(row['language']) or row['language'] == "":
            try:
                lang = detect(lyrics_cleaned)
                data.at[index, 'language'] = lang  # Guardar idioma detectado
            except:
                lang = "unknown"  # Si langdetect falla, marcar como "desconocido"
        else:
            lang = row['language']

        last_logs.append(f"🧐 Procesando {index}/{len(data)} - {row['recording_id']} | Idioma detectado: {lang}")

        # 🔥 Si la canción ya está en inglés, no traducirla
        if lang == "en":
            last_logs.append(f"✅ {row['recording_id']} ya está en inglés. Saltando...")
            continue

        # 🔹 Intentar traducir hasta 3 veces si la traducción es vacía
        max_retries = 3
        translation = ""
        for attempt in range(max_retries):
            try:
                text_parts = split_text(lyrics_cleaned)
                translation = " ".join([translator.translate(part) for part in text_parts])
                if translation.strip() != "":
                    break  # Si la traducción es válida, salir del loop
            except:
                last_logs.append(f"⚠️ Intento {attempt + 1} fallido para {row['recording_id']}. Reintentando...")
                time.sleep(1)

        if translation.strip() == "":
            last_logs.append(f"❌ No se pudo traducir {row['recording_id']}. Guardando como error.")
            errors = pd.concat([errors, pd.DataFrame({'index': [index], 'recording_id': [row['recording_id']], 'error_message': ["Traducción vacía después de reintentos"]})])
            continue

        # 📌 Guardar la traducción en el DataFrame
        data.at[index, 'translated_lyrics'] = translation

        # 📌 Guardar inmediatamente en el archivo CSV para no perder datos
        pd.DataFrame({
            'recording_id': [row['recording_id']], 
            'translated_lyrics': [translation], 
            'language': [lang]  
        }).to_csv(output_file_path, mode='a', header=not os.path.exists(output_file_path), index=False, encoding='utf-8', sep=",", quoting=csv.QUOTE_MINIMAL)

        # 🔹 Mostrar progreso cada 10 traducciones
        if index % 10 == 0:
            print("\n".join(last_logs))

        time.sleep(0.2)  # Pausa para evitar bloqueos

    except Exception as e:
        errors = pd.concat([errors, pd.DataFrame({'index': [index], 'recording_id': [row['recording_id']], 'error_message': [str(e)]})])

# 📌 Guardar errores en archivo
errors.to_csv(error_file_path, index=False, encoding="utf-8")

print("\n".join(last_logs))
print(f"✅ Proceso completado. Archivo traducido guardado en {output_file_path}")

🔄 Traduciendo canciones:   0%|          | 10/7144 [00:21<4:05:26,  2.06s/it]

🧐 Procesando 0/7144 - 06150574-7d3b-409f-955a-c32b7c1dad33 | Idioma detectado: en
✅ 06150574-7d3b-409f-955a-c32b7c1dad33 ya está en inglés. Saltando...
🧐 Procesando 1/7144 - 779263a9-c234-474a-aacb-6e1ce6c9c49e | Idioma detectado: es
🧐 Procesando 2/7144 - c5ded84c-98e6-4099-bf7b-a19bf6cb7291 | Idioma detectado: fi
🧐 Procesando 3/7144 - 551aee08-e3f7-46bb-bf06-793d95f76213 | Idioma detectado: fr
🧐 Procesando 4/7144 - c105eac0-24a5-48d1-b86e-4dc0024e03e8 | Idioma detectado: it
🧐 Procesando 5/7144 - 44a5b1ba-fa9d-40dd-9c58-d39702f6457e | Idioma detectado: de
🧐 Procesando 6/7144 - cffec82e-fe60-4fbc-a36b-501e77efd21d | Idioma detectado: de
🧐 Procesando 7/7144 - 7024c111-4c20-4619-ad61-bf23b2cf14fb | Idioma detectado: fr
🧐 Procesando 8/7144 - a97b4568-4bb6-4242-a208-5720c6183e86 | Idioma detectado: es
🧐 Procesando 9/7144 - 44c7281d-a7a6-48f3-ae01-5f6832a533cc | Idioma detectado: es
🧐 Procesando 10/7144 - 70dfd89b-f7f8-4d3e-b0ab-a21b40f54c3f | Idioma detectado: fr

🔄 Traduciendo canciones:   0%|          | 20/7144 [00:50<6:07:49,  3.10s/it]

🧐 Procesando 1/7144 - 779263a9-c234-474a-aacb-6e1ce6c9c49e | Idioma detectado: es
🧐 Procesando 2/7144 - c5ded84c-98e6-4099-bf7b-a19bf6cb7291 | Idioma detectado: fi
🧐 Procesando 3/7144 - 551aee08-e3f7-46bb-bf06-793d95f76213 | Idioma detectado: fr
🧐 Procesando 4/7144 - c105eac0-24a5-48d1-b86e-4dc0024e03e8 | Idioma detectado: it
🧐 Procesando 5/7144 - 44a5b1ba-fa9d-40dd-9c58-d39702f6457e | Idioma detectado: de
🧐 Procesando 6/7144 - cffec82e-fe60-4fbc-a36b-501e77efd21d | Idioma detectado: de
🧐 Procesando 7/7144 - 7024c111-4c20-4619-ad61-bf23b2cf14fb | Idioma detectado: fr
🧐 Procesando 8/7144 - a97b4568-4bb6-4242-a208-5720c6183e86 | Idioma detectado: es
🧐 Procesando 9/7144 - 44c7281d-a7a6-48f3-ae01-5f6832a533cc | Idioma detectado: es
🧐 Procesando 10/7144 - 70dfd89b-f7f8-4d3e-b0ab-a21b40f54c3f | Idioma detectado: fr
🧐 Procesando 11/7144 - 2162fb60-3838-4cda-ac6f-0c3d259f9dad | Idioma detectado: de
🧐 Procesando 12/7144 - 496e1a36-6ad0-417e-bb5e-0ec2f006b616 | Idioma detectado: fi
🧐 Procesando 13/7144 - c6ac45f6-dfb4-4067-acb9-45d4e6a4d643 | Idioma detectado: sv
🧐 Procesando 14/7144 - 1cc4ca94-5e53-44f4-af1b-f3965da02a48 | Idioma detectado: ja
🧐 Procesando 15/7144 - 36618bcd-0f68-4b99-a97d-25cc0cd8e0b0 | Idioma detectado: de
🧐 Procesando 16/7144 - 27d3bfa6-7dd5-41a3-aaec-8bd30f544a4f | Idioma detectado: es
🧐 Procesando 17/7144 - 46b7237f-49ae-4ecb-9b6c-22de1e3158d2 | Idioma detectado: it
🧐 Procesando 18/7144 - c9719aa8-3163-43df-8ac0-2c57eee49484 | Idioma detectado: de
🧐 Procesando 19/7144 - 8107f7d6-c080-4cc4-aa7e-76af5729a687 | Idioma detectado: fr
🧐 Procesando 20/7144 - 1955ec01-0471-4aa8-84ce-5de94648c89b | Idioma detectado: fr

🔄 Traduciendo canciones:   0%|          | 31/7144 [01:18<5:35:27,  2.83s/it]

🧐 Procesando 11/7144 - 2162fb60-3838-4cda-ac6f-0c3d259f9dad | Idioma detectado: de
🧐 Procesando 12/7144 - 496e1a36-6ad0-417e-bb5e-0ec2f006b616 | Idioma detectado: fi
🧐 Procesando 13/7144 - c6ac45f6-dfb4-4067-acb9-45d4e6a4d643 | Idioma detectado: sv
🧐 Procesando 14/7144 - 1cc4ca94-5e53-44f4-af1b-f3965da02a48 | Idioma detectado: ja
🧐 Procesando 15/7144 - 36618bcd-0f68-4b99-a97d-25cc0cd8e0b0 | Idioma detectado: de
🧐 Procesando 16/7144 - 27d3bfa6-7dd5-41a3-aaec-8bd30f544a4f | Idioma detectado: es
🧐 Procesando 17/7144 - 46b7237f-49ae-4ecb-9b6c-22de1e3158d2 | Idioma detectado: it
🧐 Procesando 18/7144 - c9719aa8-3163-43df-8ac0-2c57eee49484 | Idioma detectado: de
🧐 Procesando 19/7144 - 8107f7d6-c080-4cc4-aa7e-76af5729a687 | Idioma detectado: fr
🧐 Procesando 20/7144 - 1955ec01-0471-4aa8-84ce-5de94648c89b | Idioma detectado: fr
🧐 Procesando 21/7144 - 2676ce27-803b-4c0f-9175-3944418fbb3f | Idioma detectado: fi
🧐 Procesando 22/7144 - 8b8b5639-2867-4145-bf33-83b0bda7aeb3 | Idioma detectado: de
🧐 Procesando 23/7144 - b306c23e-37d0-43da-91ef-8fb10acceac9 | Idioma detectado: it
🧐 Procesando 24/7144 - a0d59430-dbcb-42ac-9673-99300e646d9a | Idioma detectado: es
🧐 Procesando 25/7144 - 38aa8cf5-4e76-46d0-a822-f2ff1854fbf4 | Idioma detectado: de
🧐 Procesando 26/7144 - 98718806-d15f-491b-a8a0-42fe184a1c2f | Idioma detectado: de
🧐 Procesando 27/7144 - 614b7dbb-3e2f-44a5-a715-53035a2b5dbf | Idioma detectado: fr
🧐 Procesando 28/7144 - c25816a8-1948-4290-80d4-e54f01fb040f | Idioma detectado: fi
🧐 Procesando 29/7144 - 9a0cd86e-5c6d-426a-8f03-fe0b7898e9aa | Idioma detectado: fr
🧐 Procesando 30/7144 - be4477f0-b607-4600-b7d2-0fb78d131f34 | Idioma detectado: nl

🔄 Traduciendo canciones:   1%|          | 41/7144 [01:43<4:05:44,  2.08s/it]

🧐 Procesando 21/7144 - 2676ce27-803b-4c0f-9175-3944418fbb3f | Idioma detectado: fi
🧐 Procesando 22/7144 - 8b8b5639-2867-4145-bf33-83b0bda7aeb3 | Idioma detectado: de
🧐 Procesando 23/7144 - b306c23e-37d0-43da-91ef-8fb10acceac9 | Idioma detectado: it
🧐 Procesando 24/7144 - a0d59430-dbcb-42ac-9673-99300e646d9a | Idioma detectado: es
🧐 Procesando 25/7144 - 38aa8cf5-4e76-46d0-a822-f2ff1854fbf4 | Idioma detectado: de
🧐 Procesando 26/7144 - 98718806-d15f-491b-a8a0-42fe184a1c2f | Idioma detectado: de
🧐 Procesando 27/7144 - 614b7dbb-3e2f-44a5-a715-53035a2b5dbf | Idioma detectado: fr
🧐 Procesando 28/7144 - c25816a8-1948-4290-80d4-e54f01fb040f | Idioma detectado: fi
🧐 Procesando 29/7144 - 9a0cd86e-5c6d-426a-8f03-fe0b7898e9aa | Idioma detectado: fr
🧐 Procesando 30/7144 - be4477f0-b607-4600-b7d2-0fb78d131f34 | Idioma detectado: nl
🧐 Procesando 31/7144 - 8a747ee9-ee1a-424c-945e-e40c5fafb872 | Idioma detectado: co
🧐 Procesando 32/7144 - 665e8ddc-a6bb-4829-88ea-cb13e6fed60e | Idioma detectado: es
🧐 Procesando 33/7144 - a3b257bc-9534-4534-bbea-78b27bae535a | Idioma detectado: fr
🧐 Procesando 34/7144 - f69a765e-24c7-4cc2-ac2a-137b292afe73 | Idioma detectado: hi
🧐 Procesando 35/7144 - 329e63e8-6c4b-4d30-a2a3-a8d50ad75c3a | Idioma detectado: it
🧐 Procesando 36/7144 - 9af75a7c-521b-4e80-8895-87c8d96a06c1 | Idioma detectado: hu
🧐 Procesando 37/7144 - eaf734de-53a3-487d-aa10-2830d9d5c3b0 | Idioma detectado: no
🧐 Procesando 38/7144 - 17b68268-75f7-4195-b285-287ff670b989 | Idioma detectado: es
🧐 Procesando 39/7144 - 7e88797b-d4c3-4268-9af5-2a6ce4eb9bda | Idioma detectado: de
🧐 Procesando 40/7144 - 358b653f-ac87-4dce-b24e-46913f7ffa1c | Idioma detectado: fr

🔄 Traduciendo canciones:   1%|          | 51/7144 [02:08<5:00:11,  2.54s/it]

🧐 Procesando 31/7144 - 8a747ee9-ee1a-424c-945e-e40c5fafb872 | Idioma detectado: co
🧐 Procesando 32/7144 - 665e8ddc-a6bb-4829-88ea-cb13e6fed60e | Idioma detectado: es
🧐 Procesando 33/7144 - a3b257bc-9534-4534-bbea-78b27bae535a | Idioma detectado: fr
🧐 Procesando 34/7144 - f69a765e-24c7-4cc2-ac2a-137b292afe73 | Idioma detectado: hi
🧐 Procesando 35/7144 - 329e63e8-6c4b-4d30-a2a3-a8d50ad75c3a | Idioma detectado: it
🧐 Procesando 36/7144 - 9af75a7c-521b-4e80-8895-87c8d96a06c1 | Idioma detectado: hu
🧐 Procesando 37/7144 - eaf734de-53a3-487d-aa10-2830d9d5c3b0 | Idioma detectado: no
🧐 Procesando 38/7144 - 17b68268-75f7-4195-b285-287ff670b989 | Idioma detectado: es
🧐 Procesando 39/7144 - 7e88797b-d4c3-4268-9af5-2a6ce4eb9bda | Idioma detectado: de
🧐 Procesando 40/7144 - 358b653f-ac87-4dce-b24e-46913f7ffa1c | Idioma detectado: fr
🧐 Procesando 41/7144 - 4e3672b6-00e5-4467-83ec-601595126744 | Idioma detectado: pt
🧐 Procesando 42/7144 - f4f11494-1b6a-42b8-81bc-b40115d4a316 | Idioma detectado: de
🧐 Procesando 43/7144 - bc3b42cd-a6e1-4991-8cc3-988eae7ac7a1 | Idioma detectado: es
🧐 Procesando 44/7144 - ecf3e24a-e09b-423f-8d7d-45e9c70c2ef2 | Idioma detectado: nl
🧐 Procesando 45/7144 - 515dbeac-98f6-4d85-b6bd-8bc9c97c6e5b | Idioma detectado: it
🧐 Procesando 46/7144 - eb6b53cc-a48b-4965-851d-cf1548c4fd32 | Idioma detectado: es
🧐 Procesando 47/7144 - 7ca7e939-b176-4a96-8aa4-9510d2f8e49e | Idioma detectado: sv
🧐 Procesando 48/7144 - 53832f71-9dc1-49ca-8f54-2a17be2662f4 | Idioma detectado: it
🧐 Procesando 49/7144 - 48d5fabf-064f-49ce-a700-0f46f156531e | Idioma detectado: fr
🧐 Procesando 50/7144 - 85497adb-b792-436b-8474-25c00bf5e317 | Idioma detectado: la

🔄 Traduciendo canciones:   1%|          | 61/7144 [02:31<4:39:50,  2.37s/it]

🧐 Procesando 42/7144 - f4f11494-1b6a-42b8-81bc-b40115d4a316 | Idioma detectado: de
🧐 Procesando 43/7144 - bc3b42cd-a6e1-4991-8cc3-988eae7ac7a1 | Idioma detectado: es
🧐 Procesando 44/7144 - ecf3e24a-e09b-423f-8d7d-45e9c70c2ef2 | Idioma detectado: nl
🧐 Procesando 45/7144 - 515dbeac-98f6-4d85-b6bd-8bc9c97c6e5b | Idioma detectado: it
🧐 Procesando 46/7144 - eb6b53cc-a48b-4965-851d-cf1548c4fd32 | Idioma detectado: es
🧐 Procesando 47/7144 - 7ca7e939-b176-4a96-8aa4-9510d2f8e49e | Idioma detectado: sv
🧐 Procesando 48/7144 - 53832f71-9dc1-49ca-8f54-2a17be2662f4 | Idioma detectado: it
🧐 Procesando 49/7144 - 48d5fabf-064f-49ce-a700-0f46f156531e | Idioma detectado: fr
🧐 Procesando 50/7144 - 85497adb-b792-436b-8474-25c00bf5e317 | Idioma detectado: la
🧐 Procesando 51/7144 - 6d2ec2d6-f2a5-4ac3-a5a0-bfc43accd5f4 | Idioma detectado: de
🧐 Procesando 52/7144 - ccdb3994-13d3-4f9e-980b-f2f1065b12f1 | Idioma detectado: de
🧐 Procesando 53/7144 - 36b337ea-7006-4819-aa69-498250e6005e | Idioma detectado: de
🧐 Procesando 54/7144 - 33c87019-9568-4dc2-9e24-1ade4e7dcbf0 | Idioma detectado: is
🧐 Procesando 55/7144 - af6962d9-aa76-48ae-bead-a54e2cf04170 | Idioma detectado: en
✅ af6962d9-aa76-48ae-bead-a54e2cf04170 ya está en inglés. Saltando...
🧐 Procesando 56/7144 - c4ba5ed5-99b3-4f88-ae59-a524a3db71a6 | Idioma detectado: es
🧐 Procesando 57/7144 - e5df4bb3-03d3-4d56-bf27-75059431d1e0 | Idioma detectado: es
🧐 Procesando 58/7144 - dd47db9f-db1d-4456-b027-c8d20c81027f | Idioma detectado: de
🧐 Procesando 59/7144 - 4637c242-3fb8-469f-ae5b-dd5e8fd6f4b3 | Idioma detectado: es
🧐 Procesando 60/7144 - 01d5138d-2f0b-43a1-873a-72df45b8d927 | Idioma detectado: sv

🔄 Traduciendo canciones:   1%|          | 71/7144 [02:55<6:06:54,  3.11s/it]

🧐 Procesando 52/7144 - ccdb3994-13d3-4f9e-980b-f2f1065b12f1 | Idioma detectado: de
🧐 Procesando 53/7144 - 36b337ea-7006-4819-aa69-498250e6005e | Idioma detectado: de
🧐 Procesando 54/7144 - 33c87019-9568-4dc2-9e24-1ade4e7dcbf0 | Idioma detectado: is
🧐 Procesando 55/7144 - af6962d9-aa76-48ae-bead-a54e2cf04170 | Idioma detectado: en
✅ af6962d9-aa76-48ae-bead-a54e2cf04170 ya está en inglés. Saltando...
🧐 Procesando 56/7144 - c4ba5ed5-99b3-4f88-ae59-a524a3db71a6 | Idioma detectado: es
🧐 Procesando 57/7144 - e5df4bb3-03d3-4d56-bf27-75059431d1e0 | Idioma detectado: es
🧐 Procesando 58/7144 - dd47db9f-db1d-4456-b027-c8d20c81027f | Idioma detectado: de
🧐 Procesando 59/7144 - 4637c242-3fb8-469f-ae5b-dd5e8fd6f4b3 | Idioma detectado: es
🧐 Procesando 60/7144 - 01d5138d-2f0b-43a1-873a-72df45b8d927 | Idioma detectado: sv
🧐 Procesando 61/7144 - b8f8d034-069f-4250-9dc0-bae2ff219616 | Idioma detectado: fr
🧐 Procesando 62/7144 - f1504df9-6c3f-43cc-8eb8-6ae24edfc311 | Idioma detectado: pl
🧐 Procesando 63/7144 - 48cca5ce-6119-479b-8dbe-de69b74ae471 | Idioma detectado: pt
🧐 Procesando 64/7144 - acfefa0f-fe63-41cc-980a-b6fef3f6e74a | Idioma detectado: es
🧐 Procesando 65/7144 - aebc6b1e-4c3a-4fee-8036-2f6ffe1335cb | Idioma detectado: it
🧐 Procesando 66/7144 - 56e19114-f7a8-45a6-b938-3f5503b381b0 | Idioma detectado: pl
🧐 Procesando 67/7144 - 66c257f7-54ce-4d3d-a852-7d5f1f1e181c | Idioma detectado: es
🧐 Procesando 68/7144 - 5426e97b-b93d-4257-824b-bf953c2ecbdd | Idioma detectado: es
🧐 Procesando 69/7144 - 3c2d34b3-c608-44a4-84b4-ad174552255a | Idioma detectado: fr
🧐 Procesando 70/7144 - 775751e3-f0f4-4068-81ec-187cdc6dbd54 | Idioma detectado: fi

🔄 Traduciendo canciones:   1%|          | 80/7144 [03:35<14:16:27,  7.27s/it]

🧐 Procesando 65/7144 - aebc6b1e-4c3a-4fee-8036-2f6ffe1335cb | Idioma detectado: it
🧐 Procesando 66/7144 - 56e19114-f7a8-45a6-b938-3f5503b381b0 | Idioma detectado: pl
🧐 Procesando 67/7144 - 66c257f7-54ce-4d3d-a852-7d5f1f1e181c | Idioma detectado: es
🧐 Procesando 68/7144 - 5426e97b-b93d-4257-824b-bf953c2ecbdd | Idioma detectado: es
🧐 Procesando 69/7144 - 3c2d34b3-c608-44a4-84b4-ad174552255a | Idioma detectado: fr
🧐 Procesando 70/7144 - 775751e3-f0f4-4068-81ec-187cdc6dbd54 | Idioma detectado: fi
🧐 Procesando 71/7144 - d318dde6-7847-4759-8aec-970da95ed15b | Idioma detectado: es
🧐 Procesando 72/7144 - dcc6f354-714a-46b3-a5ac-12e9c40a5ebb | Idioma detectado: de
🧐 Procesando 73/7144 - af64188e-b531-4a1e-9f1c-7794ce57f40e | Idioma detectado: it
🧐 Procesando 74/7144 - 86bc1022-f4ab-4b79-879b-c466dd42959c | Idioma detectado: it
🧐 Procesando 75/7144 - d7de2557-ab34-410a-89ce-428012f9ef27 | Idioma detectado: es
🧐 Procesando 76/7144 - 16992dfe-b850-4889-9e4f-93664668b243 | Idioma detectado: pt
🧐 Procesando 77/7144 - 259c5a4f-a36c-4032-8302-41d7dfde4735 | Idioma detectado: fr
⚠️ Letra vacía para 0876306d-dda1-4bcc-91ae-23a507a3fa5b. Saltando...
🧐 Procesando 79/7144 - 368efe19-c80f-4ba9-9673-16087f4ef574 | Idioma detectado: nl
⚠️ Intento 1 fallido para 368efe19-c80f-4ba9-9673-16087f4ef574. Reintentando...
⚠️ Intento 2 fallido para 368efe19-c80f-4ba9-9673-16087f4ef574. Reintentando...
⚠️ Intento 3 fallido para 368efe19-c80f-4ba9-9673-16087f4ef574. Reintentando...
❌ No se pudo traducir 368efe19-c80f-4ba9-9673-16087f4ef574. Guardando como error.
🧐 Procesando 80/7144 - e474f5eb-12da-4f20-bfa6-1f89285e4766 | Idioma detectado: it

🔄 Traduciendo canciones:   1%|          | 87/7144 [03:55<5:18:22,  2.71s/it]

In [1]:
import sys
import csv
import pandas as pd
from langdetect import detect
from deep_translator import GoogleTranslator
import re
from tqdm import tqdm  # Barra de progreso
import time
import os
from collections import deque  # Para mostrar solo los últimos 20 procesos

# 📌 Aumentar el límite del tamaño de campo
sys.setrecursionlimit(10000)
csv.field_size_limit(10**9)

# 📌 Configuración de archivos con los directorios correctos
PROCESANDO_DIR = "C:/Users/solan/MoodTune/data/procesando/"
PROCESADO_DIR = "C:/Users/solan/MoodTune/data/procesado/"

# 📌 Buscar el archivo más reciente en `procesando/`
files = [f for f in os.listdir(PROCESANDO_DIR) if f.startswith("df_80-200_p1_with-lyrics") and f.endswith(".csv")]
if not files:
    raise FileNotFoundError("No se encontró ningún archivo en la carpeta 'procesando/' que comience con '0_for_last_'.")

files.sort(reverse=True)  # Ordenar por nombre (fecha y hora)
file_path = os.path.join(PROCESANDO_DIR, files[0])  # Seleccionar el más reciente

# 📌 Nombre del archivo de salida y errores
output_file_path = os.path.join(PROCESANDO_DIR, "df_80-200_p1_traducidas.csv")
error_file_path = os.path.join(PROCESANDO_DIR, "errors_log_traduccion.csv")

# 📌 Crear la carpeta si no existe
os.makedirs(PROCESANDO_DIR, exist_ok=True)

# 📌 Inicializar el traductor
translator = GoogleTranslator(source="auto", target="en")

# 🔹 Función para limpiar texto antes de traducir
def clean_text(text):
    if pd.isna(text):
        return ""
    return re.sub(r'\s+', ' ', text.replace('\n', ' ').strip())

# 🔹 Función para dividir textos largas (GoogleTranslator tiene un límite)
def split_text(text, max_length=500):
    return [text[i:i+max_length] for i in range(0, len(text), max_length)]

# 📌 Cargar datos originales
data = pd.read_csv(file_path, encoding='utf-8', engine='python')

# 📌 Verificar si `translated_lyrics` y `language` existen, si no, crearlas
if 'translated_lyrics' not in data.columns:
    data['translated_lyrics'] = pd.NA

if 'language' not in data.columns:
    data['language'] = pd.NA  # Crear la columna de idioma si no existe

# 📌 Crear DataFrame para errores
errors = pd.DataFrame(columns=['index', 'recording_id', 'error_message'])

# 📌 Mantener solo los últimos 20 logs en la terminal
last_logs = deque(maxlen=20)

# 🔁 Procesar y traducir
for index, row in tqdm(data.iterrows(), total=data.shape[0], desc="🔄 Traduciendo canciones"):
    try:
        # Saltar si ya está traducido
        if pd.notnull(row['translated_lyrics']) and str(row['translated_lyrics']).strip() != "":
            continue  

        lyrics_cleaned = clean_text(row['lyrics'])

        # 🔹 Evitar traducciones de textos vacíos
        if not lyrics_cleaned.strip():
            last_logs.append(f"⚠️ Letra vacía para {row['recording_id']}. Saltando...")
            continue

        # 🔹 Detectar idioma si no está en la columna "language"
        if pd.isna(row['language']) or row['language'] == "":
            try:
                lang = detect(lyrics_cleaned)
                data.at[index, 'language'] = lang  # Guardar idioma detectado
            except:
                lang = "unknown"  # Si langdetect falla, marcar como "desconocido"
        else:
            lang = row['language']

        last_logs.append(f"🧐 Procesando {index}/{len(data)} - {row['recording_id']} | Idioma detectado: {lang}")

        # 🔥 Si la canción ya está en inglés, no traducirla
        if lang == "en":
            last_logs.append(f"✅ {row['recording_id']} ya está en inglés. Saltando...")
            continue

        # 🔹 Intentar traducir hasta 3 veces si la traducción es vacía
        max_retries = 3
        translation = ""
        for attempt in range(max_retries):
            try:
                text_parts = split_text(lyrics_cleaned)
                translation = " ".join([translator.translate(part) for part in text_parts])
                if translation.strip() != "":
                    break  # Si la traducción es válida, salir del loop
            except:
                last_logs.append(f"⚠️ Intento {attempt + 1} fallido para {row['recording_id']}. Reintentando...")
                time.sleep(1)

        if translation.strip() == "":
            last_logs.append(f"❌ No se pudo traducir {row['recording_id']}. Guardando como error.")
            errors = pd.concat([errors, pd.DataFrame({'index': [index], 'recording_id': [row['recording_id']], 'error_message': ["Traducción vacía después de reintentos"]})])
            continue

        # 📌 Guardar la traducción en el DataFrame
        data.at[index, 'translated_lyrics'] = translation

        # 📌 Guardar inmediatamente en el archivo CSV para no perder datos
        pd.DataFrame({
            'recording_id': [row['recording_id']], 
            'translated_lyrics': [translation], 
            'language': [lang]  
        }).to_csv(output_file_path, mode='a', header=not os.path.exists(output_file_path), index=False, encoding='utf-8', sep=",", quoting=csv.QUOTE_MINIMAL)

        # 🔹 Mostrar progreso cada 10 traducciones
        if index % 10 == 0:
            print("\n".join(last_logs))

        time.sleep(0.2)  # Pausa para evitar bloqueos

    except Exception as e:
        errors = pd.concat([errors, pd.DataFrame({'index': [index], 'recording_id': [row['recording_id']], 'error_message': [str(e)]})])

# 📌 Guardar errores en archivo
errors.to_csv(error_file_path, index=False, encoding="utf-8")

print("\n".join(last_logs))
print(f"✅ Proceso completado. Archivo traducido guardado en {output_file_path}")

🔄 Traduciendo canciones:   2%|▏         | 351/17048 [00:28<33:03,  8.42it/s]

✅ 26120a3b-7c94-4229-877c-0ce536a4f8e4 ya está en inglés. Saltando...
🧐 Procesando 341/17048 - 7150fc7e-2f09-486a-b9c3-0aae34276b65 | Idioma detectado: en
✅ 7150fc7e-2f09-486a-b9c3-0aae34276b65 ya está en inglés. Saltando...
🧐 Procesando 342/17048 - fa0b9443-cbda-4c61-aa1e-74ece0772e06 | Idioma detectado: en
✅ fa0b9443-cbda-4c61-aa1e-74ece0772e06 ya está en inglés. Saltando...
🧐 Procesando 343/17048 - 443e75ce-7d1f-4190-b584-658d3900a8de | Idioma detectado: en
✅ 443e75ce-7d1f-4190-b584-658d3900a8de ya está en inglés. Saltando...
🧐 Procesando 344/17048 - 6a32e7b6-306e-4623-ab93-82eeecf298d9 | Idioma detectado: en
✅ 6a32e7b6-306e-4623-ab93-82eeecf298d9 ya está en inglés. Saltando...
🧐 Procesando 345/17048 - 6a258ee9-6e2e-4c99-94a2-03e418b942cd | Idioma detectado: en
✅ 6a258ee9-6e2e-4c99-94a2-03e418b942cd ya está en inglés. Saltando...
🧐 Procesando 346/17048 - e044c3af-7b28-4dce-b904-e0e6cbf91e0c | Idioma detectado: en
✅ e044c3af-7b28-4dce-b904-e0e6cbf91e0c ya está en inglés. Saltando...
🧐 Procesando 347/17048 - a76ddfb1-4762-42c7-829d-1ee12304bd1a | Idioma detectado: en
✅ a76ddfb1-4762-42c7-829d-1ee12304bd1a ya está en inglés. Saltando...
🧐 Procesando 348/17048 - 2083abe1-8db4-44c9-bc89-e5aa2827629b | Idioma detectado: en
✅ 2083abe1-8db4-44c9-bc89-e5aa2827629b ya está en inglés. Saltando...
🧐 Procesando 349/17048 - c0e35595-003e-4db8-ab0b-bc0db4ee2d4a | Idioma detectado: en
✅ c0e35595-003e-4db8-ab0b-bc0db4ee2d4a ya está en inglés. Saltando...
🧐 Procesando 350/17048 - bab9058f-8bc6-4a07-85c5-37aefae304fb | Idioma detectado: fr

🔄 Traduciendo canciones:   2%|▏         | 381/17048 [00:43<1:09:41,  3.99it/s]

🧐 Procesando 370/17048 - c10cfef0-69b0-4834-ba92-3e95e4c6f28b | Idioma detectado: en
✅ c10cfef0-69b0-4834-ba92-3e95e4c6f28b ya está en inglés. Saltando...
🧐 Procesando 371/17048 - 53733f2e-12bb-4d0a-8dfc-c58d93e0060d | Idioma detectado: fr
🧐 Procesando 372/17048 - 2830f016-9968-432d-b6d9-83f0fbac135f | Idioma detectado: en
✅ 2830f016-9968-432d-b6d9-83f0fbac135f ya está en inglés. Saltando...
🧐 Procesando 373/17048 - 06128fee-a368-44b5-b061-c679a3f77fd3 | Idioma detectado: en
✅ 06128fee-a368-44b5-b061-c679a3f77fd3 ya está en inglés. Saltando...
🧐 Procesando 374/17048 - c6ec7923-fae4-4d68-b906-37e484115c0a | Idioma detectado: en
✅ c6ec7923-fae4-4d68-b906-37e484115c0a ya está en inglés. Saltando...
🧐 Procesando 375/17048 - e01b91ea-3967-4444-9573-ff8f5b3d8726 | Idioma detectado: en
✅ e01b91ea-3967-4444-9573-ff8f5b3d8726 ya está en inglés. Saltando...
🧐 Procesando 376/17048 - 1c751b9f-111c-4412-91e7-9b95ad1f6216 | Idioma detectado: en
✅ 1c751b9f-111c-4412-91e7-9b95ad1f6216 ya está en inglés. Saltando...
🧐 Procesando 377/17048 - 773c8e47-08dd-44fd-ad1d-ecc328117416 | Idioma detectado: en
✅ 773c8e47-08dd-44fd-ad1d-ecc328117416 ya está en inglés. Saltando...
🧐 Procesando 378/17048 - d4d95245-c234-4d90-a079-f9c306385e10 | Idioma detectado: en
✅ d4d95245-c234-4d90-a079-f9c306385e10 ya está en inglés. Saltando...
🧐 Procesando 379/17048 - 978951a2-884a-478a-a34b-b28c1ca6c6bd | Idioma detectado: en
✅ 978951a2-884a-478a-a34b-b28c1ca6c6bd ya está en inglés. Saltando...
🧐 Procesando 380/17048 - d5d21b53-3fcb-40f2-a5a6-c6ac1a158784 | Idioma detectado: fr

🔄 Traduciendo canciones:   9%|▉         | 1531/17048 [00:47<02:24, 107.21it/s]

✅ c92af97d-5b45-4edd-8c23-b73dd807f3c2 ya está en inglés. Saltando...
🧐 Procesando 1661/17048 - 312cdc22-4eb8-4c73-8970-2d10f4c22264 | Idioma detectado: en
✅ 312cdc22-4eb8-4c73-8970-2d10f4c22264 ya está en inglés. Saltando...
🧐 Procesando 1662/17048 - 52d84e25-b302-4895-9a48-26f01a29d07a | Idioma detectado: en
✅ 52d84e25-b302-4895-9a48-26f01a29d07a ya está en inglés. Saltando...
🧐 Procesando 1663/17048 - e194c39d-6866-4179-aba4-a8c60a89b46b | Idioma detectado: en
✅ e194c39d-6866-4179-aba4-a8c60a89b46b ya está en inglés. Saltando...
🧐 Procesando 1664/17048 - 4e5dffac-4756-44b2-9610-9ca4a4966770 | Idioma detectado: en
✅ 4e5dffac-4756-44b2-9610-9ca4a4966770 ya está en inglés. Saltando...
🧐 Procesando 1665/17048 - 83413714-7ad1-41d8-96e1-0168fa952d92 | Idioma detectado: en
✅ 83413714-7ad1-41d8-96e1-0168fa952d92 ya está en inglés. Saltando...
🧐 Procesando 1666/17048 - d543cbb3-cd6c-4f08-8b07-cd6f262fc06f | Idioma detectado: en
✅ d543cbb3-cd6c-4f08-8b07-cd6f262fc06f ya está en inglés. Saltando...
🧐 Procesando 1667/17048 - 1e45b14d-b2fd-46e7-97a3-2b238483ce79 | Idioma detectado: en
✅ 1e45b14d-b2fd-46e7-97a3-2b238483ce79 ya está en inglés. Saltando...
🧐 Procesando 1668/17048 - 739ecec1-a6b4-4e99-930a-ec0207d1ffdc | Idioma detectado: en
✅ 739ecec1-a6b4-4e99-930a-ec0207d1ffdc ya está en inglés. Saltando...
🧐 Procesando 1669/17048 - 7aaa6246-cff3-426c-b2fc-9539392b4c66 | Idioma detectado: en
✅ 7aaa6246-cff3-426c-b2fc-9539392b4c66 ya está en inglés. Saltando...
🧐 Procesando 1670/17048 - fe7ff43f-c7fa-4c61-aa69-9f7f459ccc5b | Idioma detectado: fr

🔄 Traduciendo canciones:  29%|██▉       | 4966/17048 [01:20<01:43, 116.56it/s]

✅ 4031bd43-821e-466f-9b53-8ee6f9d63d77 ya está en inglés. Saltando...
🧐 Procesando 4960/17048 - adb150c9-9970-47d8-bc90-4246b3f3207a | Idioma detectado: en
✅ adb150c9-9970-47d8-bc90-4246b3f3207a ya está en inglés. Saltando...
🧐 Procesando 4961/17048 - ac14908a-ef68-41f4-8a47-919c0ebb1255 | Idioma detectado: en
✅ ac14908a-ef68-41f4-8a47-919c0ebb1255 ya está en inglés. Saltando...
🧐 Procesando 4962/17048 - fa77299b-721d-4f8e-9374-76115a512081 | Idioma detectado: en
✅ fa77299b-721d-4f8e-9374-76115a512081 ya está en inglés. Saltando...
🧐 Procesando 4963/17048 - 6ce74fa5-5bcd-48f8-87ea-83664436b40f | Idioma detectado: en
✅ 6ce74fa5-5bcd-48f8-87ea-83664436b40f ya está en inglés. Saltando...
🧐 Procesando 4964/17048 - cc740588-95d7-4ed9-b4fe-45ed94f8b98f | Idioma detectado: en
✅ cc740588-95d7-4ed9-b4fe-45ed94f8b98f ya está en inglés. Saltando...
🧐 Procesando 4965/17048 - 30bd324e-3dee-4076-98b7-afc765c4b4df | Idioma detectado: fr
🧐 Procesando 4966/17048 - 0d9938ae-ce22-4ad2-90a5-f8dce6b5c8d2 | Idioma detectado: fr
🧐 Procesando 4967/17048 - 48c972fb-458b-4e03-9f8a-5e5fd08e8f8e | Idioma detectado: en
✅ 48c972fb-458b-4e03-9f8a-5e5fd08e8f8e ya está en inglés. Saltando...
🧐 Procesando 4968/17048 - eab17f72-5727-4535-99f3-fa067addefc6 | Idioma detectado: en
✅ eab17f72-5727-4535-99f3-fa067addefc6 ya está en inglés. Saltando...
🧐 Procesando 4969/17048 - d428a715-7991-4322-aa46-c7838928c0fc | Idioma detectado: en
✅ d428a715-7991-4322-aa46-c7838928c0fc ya está en inglés. Saltando...
🧐 Procesando 4970/17048 - 0f9b3256-95ba-4163-a2fb-d7b15ebe0298 | Idioma detectado: fr

🔄 Traduciendo canciones:  29%|██▉       | 4972/17048 [01:46<06:08, 32.79it/s]

✅ d428a715-7991-4322-aa46-c7838928c0fc ya está en inglés. Saltando...
🧐 Procesando 4970/17048 - 0f9b3256-95ba-4163-a2fb-d7b15ebe0298 | Idioma detectado: fr
🧐 Procesando 4971/17048 - 7d71d671-a14d-4c80-b4f8-08ef57677da2 | Idioma detectado: fr
🧐 Procesando 4972/17048 - ba311af7-79c9-41c0-96e1-7212f087dc36 | Idioma detectado: en
✅ ba311af7-79c9-41c0-96e1-7212f087dc36 ya está en inglés. Saltando...
🧐 Procesando 4973/17048 - 3a5dd197-8c8c-4923-bab5-d46246dba650 | Idioma detectado: en
✅ 3a5dd197-8c8c-4923-bab5-d46246dba650 ya está en inglés. Saltando...
🧐 Procesando 4974/17048 - b2803a83-febe-44d7-8662-1a66bda28e71 | Idioma detectado: en
✅ b2803a83-febe-44d7-8662-1a66bda28e71 ya está en inglés. Saltando...
🧐 Procesando 4975/17048 - 553f8ecd-0ebb-4ec6-8394-9b496220d5da | Idioma detectado: en
✅ 553f8ecd-0ebb-4ec6-8394-9b496220d5da ya está en inglés. Saltando...
🧐 Procesando 4976/17048 - aa2b7445-934d-4f02-97f4-e10a5f802914 | Idioma detectado: en
✅ aa2b7445-934d-4f02-97f4-e10a5f802914 ya está en inglés. Saltando...
🧐 Procesando 4977/17048 - 0df5439d-9077-4ff7-9d80-5f65d7a1192b | Idioma detectado: en
✅ 0df5439d-9077-4ff7-9d80-5f65d7a1192b ya está en inglés. Saltando...
🧐 Procesando 4978/17048 - 95cbb231-cc4c-49d7-b09e-c3fbc1b48d81 | Idioma detectado: en
✅ 95cbb231-cc4c-49d7-b09e-c3fbc1b48d81 ya está en inglés. Saltando...
🧐 Procesando 4979/17048 - d085e126-91d5-40b5-89b0-20151b13d51f | Idioma detectado: en
✅ d085e126-91d5-40b5-89b0-20151b13d51f ya está en inglés. Saltando...
🧐 Procesando 4980/17048 - dbf156d2-b729-4ca1-82f1-e032e454d772 | Idioma detectado: de

🔄 Traduciendo canciones:  29%|██▉       | 4991/17048 [02:10<13:16, 15.14it/s]

✅ d085e126-91d5-40b5-89b0-20151b13d51f ya está en inglés. Saltando...
🧐 Procesando 4980/17048 - dbf156d2-b729-4ca1-82f1-e032e454d772 | Idioma detectado: de
🧐 Procesando 4981/17048 - 2380cc1a-eaf8-490c-a8d2-4e87dac2e41e | Idioma detectado: en
✅ 2380cc1a-eaf8-490c-a8d2-4e87dac2e41e ya está en inglés. Saltando...
🧐 Procesando 4982/17048 - fb720754-243f-4f6d-be0a-2e1efe1fdc3c | Idioma detectado: en
✅ fb720754-243f-4f6d-be0a-2e1efe1fdc3c ya está en inglés. Saltando...
🧐 Procesando 4983/17048 - d1dd5686-c05d-4730-99f3-28652b1cbc3f | Idioma detectado: en
✅ d1dd5686-c05d-4730-99f3-28652b1cbc3f ya está en inglés. Saltando...
🧐 Procesando 4984/17048 - 28baf362-79f8-4b59-bea1-2e4d46e7ca99 | Idioma detectado: de
🧐 Procesando 4985/17048 - 888408fd-3768-4303-bfd1-b5cdf7201e86 | Idioma detectado: en
✅ 888408fd-3768-4303-bfd1-b5cdf7201e86 ya está en inglés. Saltando...
🧐 Procesando 4986/17048 - 80279047-297c-45e9-8f10-68d0bd3c7d58 | Idioma detectado: en
✅ 80279047-297c-45e9-8f10-68d0bd3c7d58 ya está en inglés. Saltando...
🧐 Procesando 4987/17048 - b434b0c1-4c80-4b3a-8071-eebeb6eb4c66 | Idioma detectado: en
✅ b434b0c1-4c80-4b3a-8071-eebeb6eb4c66 ya está en inglés. Saltando...
🧐 Procesando 4988/17048 - bc036149-b192-42b8-87ec-383e4811d872 | Idioma detectado: en
✅ bc036149-b192-42b8-87ec-383e4811d872 ya está en inglés. Saltando...
🧐 Procesando 4989/17048 - d50fa441-ba5a-41b2-a7f5-5cf35d7f8a3b | Idioma detectado: en
✅ d50fa441-ba5a-41b2-a7f5-5cf35d7f8a3b ya está en inglés. Saltando...
🧐 Procesando 4990/17048 - 5e6c801e-ef3f-42a6-97bd-7afb1d5f5f2a | Idioma detectado: pt

🔄 Traduciendo canciones:  30%|██▉       | 5040/17048 [03:35<1:45:15,  1.90it/s]

✅ 9c2cad66-a9a4-42ef-bd9e-e6e083ce61fd ya está en inglés. Saltando...
🧐 Procesando 5029/17048 - 30e8205f-67f0-4081-8a10-1a42e71fda45 | Idioma detectado: en
✅ 30e8205f-67f0-4081-8a10-1a42e71fda45 ya está en inglés. Saltando...
🧐 Procesando 5030/17048 - 8fe1a5e3-d9ad-4877-bdcf-8e5c1e969a48 | Idioma detectado: en
✅ 8fe1a5e3-d9ad-4877-bdcf-8e5c1e969a48 ya está en inglés. Saltando...
🧐 Procesando 5031/17048 - 47ac256c-6c1d-4841-a182-7138e3dd681f | Idioma detectado: en
✅ 47ac256c-6c1d-4841-a182-7138e3dd681f ya está en inglés. Saltando...
🧐 Procesando 5032/17048 - 254b5f99-3600-420a-a224-4f77a3a200d1 | Idioma detectado: de
🧐 Procesando 5033/17048 - 6e9755b1-7353-446b-9eeb-47f88fcac438 | Idioma detectado: en
✅ 6e9755b1-7353-446b-9eeb-47f88fcac438 ya está en inglés. Saltando...
🧐 Procesando 5034/17048 - b98d3d0a-4656-4eff-a952-fc8e3c94bf6f | Idioma detectado: en
✅ b98d3d0a-4656-4eff-a952-fc8e3c94bf6f ya está en inglés. Saltando...
🧐 Procesando 5035/17048 - e0b97295-49d1-4106-8ec5-c1614a284210 | Idioma detectado: en
✅ e0b97295-49d1-4106-8ec5-c1614a284210 ya está en inglés. Saltando...
🧐 Procesando 5036/17048 - e57f7a97-cfda-463f-b972-58fe7dbd31b2 | Idioma detectado: fr
🧐 Procesando 5037/17048 - 816433fa-2d23-47df-abf6-732e1f9bc4cf | Idioma detectado: en
✅ 816433fa-2d23-47df-abf6-732e1f9bc4cf ya está en inglés. Saltando...
🧐 Procesando 5038/17048 - cafd3fbf-adef-4625-954e-2e0d6307cac2 | Idioma detectado: fr
🧐 Procesando 5039/17048 - bb9350ea-134f-430d-8cf4-aed0c8d8629f | Idioma detectado: fr
🧐 Procesando 5040/17048 - bc559ff8-4d87-4367-a5a0-96543e092fb7 | Idioma detectado: fr

🔄 Traduciendo canciones:  30%|██▉       | 5096/17048 [05:44<4:05:51,  1.23s/it]

🧐 Procesando 5090/17048 - 7443b1da-f059-414f-90bc-03d9d7bc1296 | Idioma detectado: en
✅ 7443b1da-f059-414f-90bc-03d9d7bc1296 ya está en inglés. Saltando...
🧐 Procesando 5091/17048 - c4b2e926-d5c3-4e76-9fc8-0d516a3a5842 | Idioma detectado: en
✅ c4b2e926-d5c3-4e76-9fc8-0d516a3a5842 ya está en inglés. Saltando...
🧐 Procesando 5092/17048 - 655a82fc-394a-4118-a5f6-5dc6230d5f8c | Idioma detectado: en
✅ 655a82fc-394a-4118-a5f6-5dc6230d5f8c ya está en inglés. Saltando...
🧐 Procesando 5093/17048 - ad436c76-21a7-4cbb-a7b4-29a26c4059ab | Idioma detectado: en
✅ ad436c76-21a7-4cbb-a7b4-29a26c4059ab ya está en inglés. Saltando...
🧐 Procesando 5094/17048 - 411bf157-750e-4533-b852-c7be4aaaff29 | Idioma detectado: en
✅ 411bf157-750e-4533-b852-c7be4aaaff29 ya está en inglés. Saltando...
🧐 Procesando 5095/17048 - 9faaeb8b-38e4-4c09-919b-64d0d7ba1a09 | Idioma detectado: fr
🧐 Procesando 5096/17048 - 19766688-1281-44de-8c2d-3ebffc79d14f | Idioma detectado: en
✅ 19766688-1281-44de-8c2d-3ebffc79d14f ya está en inglés. Saltando...
🧐 Procesando 5097/17048 - 9361f466-4aec-445d-a079-7fd5447d42d0 | Idioma detectado: en
✅ 9361f466-4aec-445d-a079-7fd5447d42d0 ya está en inglés. Saltando...
🧐 Procesando 5098/17048 - 73ee3a18-1d41-4dee-9b03-9b225b825f0d | Idioma detectado: en
✅ 73ee3a18-1d41-4dee-9b03-9b225b825f0d ya está en inglés. Saltando...
🧐 Procesando 5099/17048 - 50abbe31-27b9-415c-9b57-187a72b4756b | Idioma detectado: en
✅ 50abbe31-27b9-415c-9b57-187a72b4756b ya está en inglés. Saltando...
🧐 Procesando 5100/17048 - c88de5cb-a096-47df-a13d-3a3a30fac584 | Idioma detectado: fr

🔄 Traduciendo canciones:  30%|███       | 5131/17048 [06:30<4:04:07,  1.23s/it]

🧐 Procesando 5119/17048 - a04ba73a-89c9-457c-9a48-6e4fa674812c | Idioma detectado: en
✅ a04ba73a-89c9-457c-9a48-6e4fa674812c ya está en inglés. Saltando...
🧐 Procesando 5120/17048 - 86776421-cc7d-4ba5-a136-bd0ee7fdb5b8 | Idioma detectado: en
✅ 86776421-cc7d-4ba5-a136-bd0ee7fdb5b8 ya está en inglés. Saltando...
🧐 Procesando 5121/17048 - 667c3657-502a-402f-a1e1-2f968a1235d9 | Idioma detectado: en
✅ 667c3657-502a-402f-a1e1-2f968a1235d9 ya está en inglés. Saltando...
🧐 Procesando 5122/17048 - e189f8a2-cab1-468d-8ad2-68a822efb268 | Idioma detectado: en
✅ e189f8a2-cab1-468d-8ad2-68a822efb268 ya está en inglés. Saltando...
🧐 Procesando 5123/17048 - 59530959-323e-41f4-a324-9e9341ed8ef1 | Idioma detectado: en
✅ 59530959-323e-41f4-a324-9e9341ed8ef1 ya está en inglés. Saltando...
🧐 Procesando 5124/17048 - 8eecf29d-de07-4e95-b6e0-3be00e8e914a | Idioma detectado: en
✅ 8eecf29d-de07-4e95-b6e0-3be00e8e914a ya está en inglés. Saltando...
🧐 Procesando 5125/17048 - bfc3aa95-506b-4f8a-ba92-e4b10098dcef | Idioma detectado: en
✅ bfc3aa95-506b-4f8a-ba92-e4b10098dcef ya está en inglés. Saltando...
🧐 Procesando 5126/17048 - ebe540d2-72c1-4afc-9f5c-b3d022380137 | Idioma detectado: en
✅ ebe540d2-72c1-4afc-9f5c-b3d022380137 ya está en inglés. Saltando...
🧐 Procesando 5127/17048 - a89873c4-61e8-48a0-926c-67cfd1092c4f | Idioma detectado: de
🧐 Procesando 5128/17048 - 1d351ca4-6251-4b13-aa01-f210ad1a0059 | Idioma detectado: de
🧐 Procesando 5129/17048 - 6e397b51-2c10-4b67-9c85-511aabdee156 | Idioma detectado: de
🧐 Procesando 5130/17048 - b0b2911a-349b-4821-b9c6-22ac9ae68f8b | Idioma detectado: de

🔄 Traduciendo canciones:  30%|███       | 5181/17048 [07:57<9:31:45,  2.89s/it]

🧐 Procesando 5168/17048 - e86f8ce9-596d-47df-b09b-05199a38334b | Idioma detectado: en
✅ e86f8ce9-596d-47df-b09b-05199a38334b ya está en inglés. Saltando...
🧐 Procesando 5169/17048 - f05d7670-173b-48a8-8a20-888121cb1641 | Idioma detectado: fr
🧐 Procesando 5170/17048 - 3d4e83a9-1eb0-4367-9224-4369019b4e10 | Idioma detectado: en
✅ 3d4e83a9-1eb0-4367-9224-4369019b4e10 ya está en inglés. Saltando...
🧐 Procesando 5171/17048 - f5b2706a-9b51-4f92-a832-888d48c6d712 | Idioma detectado: en
✅ f5b2706a-9b51-4f92-a832-888d48c6d712 ya está en inglés. Saltando...
🧐 Procesando 5172/17048 - 5c1bc116-d8d4-409d-bd81-8cbda2e14dbe | Idioma detectado: en
✅ 5c1bc116-d8d4-409d-bd81-8cbda2e14dbe ya está en inglés. Saltando...
🧐 Procesando 5173/17048 - d1bd8677-6b20-4c3e-8df3-3207a605a678 | Idioma detectado: en
✅ d1bd8677-6b20-4c3e-8df3-3207a605a678 ya está en inglés. Saltando...
🧐 Procesando 5174/17048 - 4bbbdd4c-6c9e-4522-b0ed-671fc3be81ac | Idioma detectado: fr
🧐 Procesando 5175/17048 - b4158d52-58f4-4832-8e45-09ce5c4e9516 | Idioma detectado: en
✅ b4158d52-58f4-4832-8e45-09ce5c4e9516 ya está en inglés. Saltando...
🧐 Procesando 5176/17048 - 9872e0af-8da7-45bf-9a51-66d374e4dc2a | Idioma detectado: fr
🧐 Procesando 5177/17048 - 5ff50a7d-2180-41d2-8823-34c8c03f2748 | Idioma detectado: fr
🧐 Procesando 5178/17048 - 9bc4b43f-e2c4-4137-b981-90c1c5638eee | Idioma detectado: fr
🧐 Procesando 5179/17048 - e88b2b9b-7bd5-4b6c-8a12-61d4447f084a | Idioma detectado: en
✅ e88b2b9b-7bd5-4b6c-8a12-61d4447f084a ya está en inglés. Saltando...
🧐 Procesando 5180/17048 - 05af511b-5701-4ab9-a4a8-43cff8df301b | Idioma detectado: fr

🔄 Traduciendo canciones:  31%|███       | 5203/17048 [08:37<5:05:20,  1.55s/it]

🧐 Procesando 5200/17048 - 70e6e673-4455-4072-a075-2f0aff4682f9 | Idioma detectado: en
✅ 70e6e673-4455-4072-a075-2f0aff4682f9 ya está en inglés. Saltando...
🧐 Procesando 5201/17048 - 585c1568-e55a-40a1-bd47-87a289660184 | Idioma detectado: en
✅ 585c1568-e55a-40a1-bd47-87a289660184 ya está en inglés. Saltando...
🧐 Procesando 5202/17048 - 618f5e1a-3df9-4b16-b7d8-4309bd7a59c9 | Idioma detectado: fr
🧐 Procesando 5203/17048 - 9e0eca5c-ead8-413a-b6b2-eb7b7f375def | Idioma detectado: en
✅ 9e0eca5c-ead8-413a-b6b2-eb7b7f375def ya está en inglés. Saltando...
🧐 Procesando 5204/17048 - d342f41f-d995-4185-92bc-4c2db314e5c5 | Idioma detectado: en
✅ d342f41f-d995-4185-92bc-4c2db314e5c5 ya está en inglés. Saltando...
🧐 Procesando 5205/17048 - 647bde0c-7626-4285-996f-5b20ebd9e3fd | Idioma detectado: en
✅ 647bde0c-7626-4285-996f-5b20ebd9e3fd ya está en inglés. Saltando...
🧐 Procesando 5206/17048 - dcf8d7a5-998c-4901-a7ac-5c453f6f1820 | Idioma detectado: en
✅ dcf8d7a5-998c-4901-a7ac-5c453f6f1820 ya está en inglés. Saltando...
🧐 Procesando 5207/17048 - 92444a7c-3694-47de-a440-1f97d2372c14 | Idioma detectado: en
✅ 92444a7c-3694-47de-a440-1f97d2372c14 ya está en inglés. Saltando...
🧐 Procesando 5208/17048 - fd8040c3-ba98-42a5-84ce-058c34182ee3 | Idioma detectado: en
✅ fd8040c3-ba98-42a5-84ce-058c34182ee3 ya está en inglés. Saltando...
🧐 Procesando 5209/17048 - cfa134a3-2887-4407-8f6c-01208844f01d | Idioma detectado: en
✅ cfa134a3-2887-4407-8f6c-01208844f01d ya está en inglés. Saltando...
🧐 Procesando 5210/17048 - 66e41137-878e-4ef4-899d-4dca4eb3974c | Idioma detectado: de

🔄 Traduciendo canciones:  31%|███       | 5320/17048 [10:18<2:40:48,  1.22it/s]

🧐 Procesando 5309/17048 - 39e2149b-ddb3-4b2d-8458-b5c6f8b34651 | Idioma detectado: fr
🧐 Procesando 5310/17048 - a8b59aac-c126-4f7b-a1a1-b3a4c8f5d95b | Idioma detectado: en
✅ a8b59aac-c126-4f7b-a1a1-b3a4c8f5d95b ya está en inglés. Saltando...
🧐 Procesando 5311/17048 - b0da3c10-9f01-4ca2-895c-e493a7ff5893 | Idioma detectado: en
✅ b0da3c10-9f01-4ca2-895c-e493a7ff5893 ya está en inglés. Saltando...
🧐 Procesando 5312/17048 - 73e0303b-db81-4c4a-943f-6ffc4b79660c | Idioma detectado: en
✅ 73e0303b-db81-4c4a-943f-6ffc4b79660c ya está en inglés. Saltando...
🧐 Procesando 5313/17048 - daff024f-80ad-407e-b008-e1e6f242dce3 | Idioma detectado: en
✅ daff024f-80ad-407e-b008-e1e6f242dce3 ya está en inglés. Saltando...
🧐 Procesando 5314/17048 - 027d65ff-f5e7-441c-bdd8-86bac6f1c064 | Idioma detectado: en
✅ 027d65ff-f5e7-441c-bdd8-86bac6f1c064 ya está en inglés. Saltando...
🧐 Procesando 5315/17048 - 8521cf6b-ea66-4d06-95c8-18799a3f8fc8 | Idioma detectado: en
✅ 8521cf6b-ea66-4d06-95c8-18799a3f8fc8 ya está en inglés. Saltando...
🧐 Procesando 5316/17048 - 07cc10f6-0180-4f7a-9a93-bc2de205a8c3 | Idioma detectado: en
✅ 07cc10f6-0180-4f7a-9a93-bc2de205a8c3 ya está en inglés. Saltando...
🧐 Procesando 5317/17048 - 0780b792-bd08-4779-be7b-04851e97b66b | Idioma detectado: en
✅ 0780b792-bd08-4779-be7b-04851e97b66b ya está en inglés. Saltando...
🧐 Procesando 5318/17048 - 70348c22-0f9c-48ba-8a76-bc7a54de8701 | Idioma detectado: fr
🧐 Procesando 5319/17048 - 38eb9c55-3982-47f5-a635-47b08a0c982a | Idioma detectado: fr
🧐 Procesando 5320/17048 - 44df9720-3f8d-4678-8b6c-8f4ec5005c39 | Idioma detectado: fr

🔄 Traduciendo canciones:  32%|███▏      | 5379/17048 [11:02<2:01:42,  1.60it/s]

🧐 Procesando 5370/17048 - 71f3f07e-009d-4a1a-84b8-99c2829cbb85 | Idioma detectado: en
✅ 71f3f07e-009d-4a1a-84b8-99c2829cbb85 ya está en inglés. Saltando...
🧐 Procesando 5371/17048 - d3b3492a-d0bb-4ab0-aa00-5cf32c272a3b | Idioma detectado: en
✅ d3b3492a-d0bb-4ab0-aa00-5cf32c272a3b ya está en inglés. Saltando...
🧐 Procesando 5372/17048 - 49923b75-004b-4af4-8269-ad77b5aa8674 | Idioma detectado: en
✅ 49923b75-004b-4af4-8269-ad77b5aa8674 ya está en inglés. Saltando...
🧐 Procesando 5373/17048 - 0fd754ba-6224-4448-8119-ff30291153d4 | Idioma detectado: en
✅ 0fd754ba-6224-4448-8119-ff30291153d4 ya está en inglés. Saltando...
🧐 Procesando 5374/17048 - a5f6133b-5d76-4584-a8a6-89169fe58f13 | Idioma detectado: en
✅ a5f6133b-5d76-4584-a8a6-89169fe58f13 ya está en inglés. Saltando...
🧐 Procesando 5375/17048 - a4c35483-edce-42bb-b6ac-0d64dfec96e9 | Idioma detectado: en
✅ a4c35483-edce-42bb-b6ac-0d64dfec96e9 ya está en inglés. Saltando...
🧐 Procesando 5376/17048 - 9b5d8a7d-05fe-4f3d-ba09-2025858fb122 | Idioma detectado: en
✅ 9b5d8a7d-05fe-4f3d-ba09-2025858fb122 ya está en inglés. Saltando...
🧐 Procesando 5377/17048 - 1620b15f-40b1-40dd-9d62-d09bc1795a10 | Idioma detectado: en
✅ 1620b15f-40b1-40dd-9d62-d09bc1795a10 ya está en inglés. Saltando...
🧐 Procesando 5378/17048 - 3b451400-79f5-4306-a9d6-6e00a536ab6d | Idioma detectado: fr
🧐 Procesando 5379/17048 - e5270d74-0729-4397-8c04-d440f9d6bd52 | Idioma detectado: en
✅ e5270d74-0729-4397-8c04-d440f9d6bd52 ya está en inglés. Saltando...
🧐 Procesando 5380/17048 - 79944266-63fb-471b-8712-837cb01f6c53 | Idioma detectado: fr

🔄 Traduciendo canciones:  32%|███▏      | 5388/17048 [11:18<3:48:53,  1.18s/it]

🧐 Procesando 5378/17048 - 3b451400-79f5-4306-a9d6-6e00a536ab6d | Idioma detectado: fr
🧐 Procesando 5379/17048 - e5270d74-0729-4397-8c04-d440f9d6bd52 | Idioma detectado: en
✅ e5270d74-0729-4397-8c04-d440f9d6bd52 ya está en inglés. Saltando...
🧐 Procesando 5380/17048 - 79944266-63fb-471b-8712-837cb01f6c53 | Idioma detectado: fr
🧐 Procesando 5381/17048 - c6273d4c-12e3-4d2c-b932-99f046ab0edc | Idioma detectado: fr
🧐 Procesando 5382/17048 - d6922892-1c20-4a5a-99d0-51d6fe9a3fc8 | Idioma detectado: en
✅ d6922892-1c20-4a5a-99d0-51d6fe9a3fc8 ya está en inglés. Saltando...
🧐 Procesando 5383/17048 - 89b7bae6-44b4-41a1-acad-c1d210a39941 | Idioma detectado: en
✅ 89b7bae6-44b4-41a1-acad-c1d210a39941 ya está en inglés. Saltando...
🧐 Procesando 5384/17048 - 6f7291ff-22f7-410f-8cdb-c44bf489a658 | Idioma detectado: fr
🧐 Procesando 5385/17048 - cbd6155c-747f-4cc1-8f7c-92328200de61 | Idioma detectado: en
✅ cbd6155c-747f-4cc1-8f7c-92328200de61 ya está en inglés. Saltando...
🧐 Procesando 5386/17048 - a025a632-2dab-430a-b512-11833b098140 | Idioma detectado: en
✅ a025a632-2dab-430a-b512-11833b098140 ya está en inglés. Saltando...
🧐 Procesando 5387/17048 - 32c92b27-7135-4e20-9e0f-83fafcd9d18c | Idioma detectado: fr
🧐 Procesando 5388/17048 - 334e10d3-bc7e-464c-adf3-3175578da046 | Idioma detectado: en
✅ 334e10d3-bc7e-464c-adf3-3175578da046 ya está en inglés. Saltando...
🧐 Procesando 5389/17048 - f3783645-2137-4f99-9c19-1fcc62d0460f | Idioma detectado: en
✅ f3783645-2137-4f99-9c19-1fcc62d0460f ya está en inglés. Saltando...
🧐 Procesando 5390/17048 - 759c9be2-31a5-4a47-8623-8b669a655484 | Idioma detectado: fr

🔄 Traduciendo canciones:  32%|███▏      | 5448/17048 [11:56<2:42:18,  1.19it/s]

✅ 7795bd6c-1187-493f-8a8c-ea17cb61686b ya está en inglés. Saltando...
🧐 Procesando 5439/17048 - 8bfb621c-6f06-44d3-b735-5cb06ff15c56 | Idioma detectado: en
✅ 8bfb621c-6f06-44d3-b735-5cb06ff15c56 ya está en inglés. Saltando...
🧐 Procesando 5440/17048 - ebb22ca9-51c8-4a3c-ba67-81760784bc6b | Idioma detectado: en
✅ ebb22ca9-51c8-4a3c-ba67-81760784bc6b ya está en inglés. Saltando...
🧐 Procesando 5441/17048 - 5b13fc0b-90c6-4980-ad2f-6b353e9e1400 | Idioma detectado: fr
🧐 Procesando 5442/17048 - 6b54321a-b2d4-49c6-8ab7-7fc2f7215a23 | Idioma detectado: en
✅ 6b54321a-b2d4-49c6-8ab7-7fc2f7215a23 ya está en inglés. Saltando...
🧐 Procesando 5443/17048 - c30a1368-a7dc-45d7-aae4-ce787ffec04f | Idioma detectado: en
✅ c30a1368-a7dc-45d7-aae4-ce787ffec04f ya está en inglés. Saltando...
🧐 Procesando 5444/17048 - f251d2ee-f0c0-4d40-bafa-c0fb421b3ef9 | Idioma detectado: en
✅ f251d2ee-f0c0-4d40-bafa-c0fb421b3ef9 ya está en inglés. Saltando...
🧐 Procesando 5445/17048 - b91df705-c3f7-4233-8026-8cdcae1d01e4 | Idioma detectado: fr
🧐 Procesando 5446/17048 - f00e6de2-2e9a-4456-92c2-4311dcff1f5d | Idioma detectado: fr
🧐 Procesando 5447/17048 - 99d845ef-cb9a-48b9-82d9-5c227f21d3dc | Idioma detectado: fr
🧐 Procesando 5448/17048 - 0d15dd20-527c-4b99-85bc-e5af133c3a20 | Idioma detectado: en
✅ 0d15dd20-527c-4b99-85bc-e5af133c3a20 ya está en inglés. Saltando...
🧐 Procesando 5449/17048 - 32f2591e-57b5-4df9-bf86-76789eeb9a27 | Idioma detectado: en
✅ 32f2591e-57b5-4df9-bf86-76789eeb9a27 ya está en inglés. Saltando...
🧐 Procesando 5450/17048 - b77e338e-1eac-4466-93e6-5ef67fab32e3 | Idioma detectado: fr

🔄 Traduciendo canciones:  32%|███▏      | 5460/17048 [12:27<7:34:19,  2.35s/it]

🧐 Procesando 5447/17048 - 99d845ef-cb9a-48b9-82d9-5c227f21d3dc | Idioma detectado: fr
🧐 Procesando 5448/17048 - 0d15dd20-527c-4b99-85bc-e5af133c3a20 | Idioma detectado: en
✅ 0d15dd20-527c-4b99-85bc-e5af133c3a20 ya está en inglés. Saltando...
🧐 Procesando 5449/17048 - 32f2591e-57b5-4df9-bf86-76789eeb9a27 | Idioma detectado: en
✅ 32f2591e-57b5-4df9-bf86-76789eeb9a27 ya está en inglés. Saltando...
🧐 Procesando 5450/17048 - b77e338e-1eac-4466-93e6-5ef67fab32e3 | Idioma detectado: fr
🧐 Procesando 5451/17048 - 68ab302c-f8e7-4f19-813b-9e5e9dc0b36b | Idioma detectado: fr
🧐 Procesando 5452/17048 - fc5decfa-ac43-4569-91bf-5b7f7d8bd47e | Idioma detectado: en
✅ fc5decfa-ac43-4569-91bf-5b7f7d8bd47e ya está en inglés. Saltando...
🧐 Procesando 5453/17048 - 94224142-ab96-43fc-9dc2-3d8b462814a1 | Idioma detectado: en
✅ 94224142-ab96-43fc-9dc2-3d8b462814a1 ya está en inglés. Saltando...
🧐 Procesando 5454/17048 - 36bbf94f-59b0-46de-a15d-299208ffbf82 | Idioma detectado: en
✅ 36bbf94f-59b0-46de-a15d-299208ffbf82 ya está en inglés. Saltando...
🧐 Procesando 5455/17048 - 2ba0f166-b156-4d98-9793-03b5fe892837 | Idioma detectado: en
✅ 2ba0f166-b156-4d98-9793-03b5fe892837 ya está en inglés. Saltando...
🧐 Procesando 5456/17048 - 2498fbf4-d27d-43b6-a573-1ec164e9f54b | Idioma detectado: fr
🧐 Procesando 5457/17048 - ef14d4f1-afb5-4cb5-9436-ab782538522e | Idioma detectado: fr
🧐 Procesando 5458/17048 - eca5ea62-7a44-49e3-bdb0-e1e4944740f9 | Idioma detectado: fr
🧐 Procesando 5459/17048 - e23b564b-dc4b-47bf-90bf-3f6a50ca64b9 | Idioma detectado: fr
🧐 Procesando 5460/17048 - b372c427-c657-447d-aee3-3e39f58d9a72 | Idioma detectado: fr

🔄 Traduciendo canciones:  32%|███▏      | 5471/17048 [12:52<6:00:50,  1.87s/it]

🧐 Procesando 5456/17048 - 2498fbf4-d27d-43b6-a573-1ec164e9f54b | Idioma detectado: fr
🧐 Procesando 5457/17048 - ef14d4f1-afb5-4cb5-9436-ab782538522e | Idioma detectado: fr
🧐 Procesando 5458/17048 - eca5ea62-7a44-49e3-bdb0-e1e4944740f9 | Idioma detectado: fr
🧐 Procesando 5459/17048 - e23b564b-dc4b-47bf-90bf-3f6a50ca64b9 | Idioma detectado: fr
🧐 Procesando 5460/17048 - b372c427-c657-447d-aee3-3e39f58d9a72 | Idioma detectado: fr
🧐 Procesando 5461/17048 - dceb5deb-5994-41dc-9ef1-2177bef1cbe2 | Idioma detectado: fr
🧐 Procesando 5462/17048 - 9973080c-9145-4a3e-b307-cdf12b77ee78 | Idioma detectado: fr
🧐 Procesando 5463/17048 - 5f94fb46-91b0-4a18-98c5-c7b73fadcdaf | Idioma detectado: fr
🧐 Procesando 5464/17048 - 613ef6b5-25de-4e0d-b93b-ff1946c4128e | Idioma detectado: fr
🧐 Procesando 5465/17048 - 822abc2c-f433-464f-8169-3183713571af | Idioma detectado: en
✅ 822abc2c-f433-464f-8169-3183713571af ya está en inglés. Saltando...
🧐 Procesando 5466/17048 - c69301f3-65ab-4736-b292-7ea3ef7f9924 | Idioma detectado: en
✅ c69301f3-65ab-4736-b292-7ea3ef7f9924 ya está en inglés. Saltando...
🧐 Procesando 5467/17048 - 47edd51c-a79c-4a12-84c2-0ac3286b5ce9 | Idioma detectado: en
✅ 47edd51c-a79c-4a12-84c2-0ac3286b5ce9 ya está en inglés. Saltando...
🧐 Procesando 5468/17048 - 9d128cc8-b09c-4142-8aef-85532a411269 | Idioma detectado: en
✅ 9d128cc8-b09c-4142-8aef-85532a411269 ya está en inglés. Saltando...
🧐 Procesando 5469/17048 - 1b96a34e-e0fe-4fca-87b2-d0121d1025ce | Idioma detectado: en
✅ 1b96a34e-e0fe-4fca-87b2-d0121d1025ce ya está en inglés. Saltando...
🧐 Procesando 5470/17048 - 86171a17-8d81-4b2d-b5fa-2c8fc43fd350 | Idioma detectado: fr

🔄 Traduciendo canciones:  33%|███▎      | 5670/17048 [14:19<2:38:15,  1.20it/s]

✅ 681e8a48-5b4d-4655-b9b1-819fc7ea5d37 ya está en inglés. Saltando...
🧐 Procesando 5660/17048 - cafb1de1-0bf9-41c5-8d3c-5fff5a5c0e1e | Idioma detectado: en
✅ cafb1de1-0bf9-41c5-8d3c-5fff5a5c0e1e ya está en inglés. Saltando...
🧐 Procesando 5661/17048 - 639e901c-3ee3-43b1-b4ed-9b6b0782eb5b | Idioma detectado: en
✅ 639e901c-3ee3-43b1-b4ed-9b6b0782eb5b ya está en inglés. Saltando...
🧐 Procesando 5662/17048 - 5b558519-0719-4e02-a753-0aef518b39f8 | Idioma detectado: en
✅ 5b558519-0719-4e02-a753-0aef518b39f8 ya está en inglés. Saltando...
🧐 Procesando 5663/17048 - ab6c6220-70fa-4fce-9c40-ff138d928da1 | Idioma detectado: en
✅ ab6c6220-70fa-4fce-9c40-ff138d928da1 ya está en inglés. Saltando...
🧐 Procesando 5664/17048 - 5947b164-6517-4896-9484-7349f3aeec47 | Idioma detectado: en
✅ 5947b164-6517-4896-9484-7349f3aeec47 ya está en inglés. Saltando...
🧐 Procesando 5665/17048 - 47673cb0-7ca3-410c-8cbb-790ac2991705 | Idioma detectado: en
✅ 47673cb0-7ca3-410c-8cbb-790ac2991705 ya está en inglés. Saltando...
🧐 Procesando 5666/17048 - 061fc54b-3842-4494-9dfc-a964afa3f0d7 | Idioma detectado: en
✅ 061fc54b-3842-4494-9dfc-a964afa3f0d7 ya está en inglés. Saltando...
🧐 Procesando 5667/17048 - 154cc784-d62d-41b3-9b8f-b089c5aeccf8 | Idioma detectado: en
✅ 154cc784-d62d-41b3-9b8f-b089c5aeccf8 ya está en inglés. Saltando...
🧐 Procesando 5668/17048 - 67bc328b-e147-4406-b7e8-85242ede43ed | Idioma detectado: fr
🧐 Procesando 5669/17048 - 8b4068b0-69f3-4d52-91c8-57ed4aa223ee | Idioma detectado: de
🧐 Procesando 5670/17048 - 6e7f157e-84fb-4f1f-b797-0889c20ac529 | Idioma detectado: de

🔄 Traduciendo canciones:  35%|███▍      | 5902/17048 [15:53<35:14,  5.27it/s]

🧐 Procesando 5900/17048 - 41e3d4a6-52ed-4133-9c64-64fde0860829 | Idioma detectado: en
✅ 41e3d4a6-52ed-4133-9c64-64fde0860829 ya está en inglés. Saltando...
🧐 Procesando 5901/17048 - 909e3f8d-bb0c-4cca-b6ac-2a31cad260be | Idioma detectado: fr
🧐 Procesando 5902/17048 - 1621f703-96b0-4456-8372-3b9207ac76f3 | Idioma detectado: en
✅ 1621f703-96b0-4456-8372-3b9207ac76f3 ya está en inglés. Saltando...
🧐 Procesando 5903/17048 - b77083e3-06ea-4c33-b37a-d85f217cbe82 | Idioma detectado: en
✅ b77083e3-06ea-4c33-b37a-d85f217cbe82 ya está en inglés. Saltando...
🧐 Procesando 5904/17048 - ed7a08d7-4c94-49bb-8de4-40990ff3649a | Idioma detectado: en
✅ ed7a08d7-4c94-49bb-8de4-40990ff3649a ya está en inglés. Saltando...
🧐 Procesando 5905/17048 - a42940f7-6207-484b-b146-6dbde18c6d0f | Idioma detectado: en
✅ a42940f7-6207-484b-b146-6dbde18c6d0f ya está en inglés. Saltando...
🧐 Procesando 5906/17048 - c61e070b-7b07-454f-92a1-f2132811e25f | Idioma detectado: en
✅ c61e070b-7b07-454f-92a1-f2132811e25f ya está en inglés. Saltando...
🧐 Procesando 5907/17048 - 049ba3be-e419-4b9e-9a5f-ef6d14e0da00 | Idioma detectado: en
✅ 049ba3be-e419-4b9e-9a5f-ef6d14e0da00 ya está en inglés. Saltando...
🧐 Procesando 5908/17048 - dcc4b7e8-c6d1-440f-a009-b572d80f943a | Idioma detectado: en
✅ dcc4b7e8-c6d1-440f-a009-b572d80f943a ya está en inglés. Saltando...
🧐 Procesando 5909/17048 - a58234f2-b197-4f60-908c-42d6ab354ea3 | Idioma detectado: en
✅ a58234f2-b197-4f60-908c-42d6ab354ea3 ya está en inglés. Saltando...
🧐 Procesando 5910/17048 - 42fbba90-bb02-48d1-8b59-951d593b110d | Idioma detectado: fr

🔄 Traduciendo canciones:  35%|███▌      | 6033/17048 [16:47<1:44:40,  1.75it/s]

🧐 Procesando 6030/17048 - 44252100-5ef2-4ddb-9084-53f72625d678 | Idioma detectado: en
✅ 44252100-5ef2-4ddb-9084-53f72625d678 ya está en inglés. Saltando...
🧐 Procesando 6031/17048 - 9daaf721-8a94-4ef0-98c6-197948901706 | Idioma detectado: en
✅ 9daaf721-8a94-4ef0-98c6-197948901706 ya está en inglés. Saltando...
🧐 Procesando 6032/17048 - 699c61f7-1351-496b-89d3-c9280a3f746c | Idioma detectado: fr
🧐 Procesando 6033/17048 - a02248e3-1566-4f06-a8ab-821c33655175 | Idioma detectado: en
✅ a02248e3-1566-4f06-a8ab-821c33655175 ya está en inglés. Saltando...
🧐 Procesando 6034/17048 - 112d6ce9-6909-4aeb-a9f7-1ae8d77cc59b | Idioma detectado: en
✅ 112d6ce9-6909-4aeb-a9f7-1ae8d77cc59b ya está en inglés. Saltando...
🧐 Procesando 6035/17048 - a83d3b90-00e0-495e-b017-2c51bf511495 | Idioma detectado: en
✅ a83d3b90-00e0-495e-b017-2c51bf511495 ya está en inglés. Saltando...
🧐 Procesando 6036/17048 - fbd66781-a86f-4d25-91ee-467555fbb932 | Idioma detectado: en
✅ fbd66781-a86f-4d25-91ee-467555fbb932 ya está en inglés. Saltando...
🧐 Procesando 6037/17048 - 26007ac1-0d99-468a-8fc9-bc04b02e842a | Idioma detectado: en
✅ 26007ac1-0d99-468a-8fc9-bc04b02e842a ya está en inglés. Saltando...
🧐 Procesando 6038/17048 - bc066858-2232-497f-9907-228a7010f91c | Idioma detectado: en
✅ bc066858-2232-497f-9907-228a7010f91c ya está en inglés. Saltando...
🧐 Procesando 6039/17048 - ade12e4a-b3a6-4c65-ab33-7fbbf6472f56 | Idioma detectado: en
✅ ade12e4a-b3a6-4c65-ab33-7fbbf6472f56 ya está en inglés. Saltando...
🧐 Procesando 6040/17048 - 9f862d24-ecd3-4cdf-b2d1-3748787f2275 | Idioma detectado: fr

🔄 Traduciendo canciones:  41%|████      | 6940/17048 [19:06<15:50, 10.64it/s]

🧐 Procesando 6929/17048 - cacdbe3e-feff-4445-aff6-2d78f9fa1da6 | Idioma detectado: en
✅ cacdbe3e-feff-4445-aff6-2d78f9fa1da6 ya está en inglés. Saltando...
🧐 Procesando 6930/17048 - 678d854d-34e7-4a9d-8cb0-6ec4c4bf577d | Idioma detectado: en
✅ 678d854d-34e7-4a9d-8cb0-6ec4c4bf577d ya está en inglés. Saltando...
🧐 Procesando 6931/17048 - ce21c97d-f2ac-4827-8102-97902a18e2ac | Idioma detectado: en
✅ ce21c97d-f2ac-4827-8102-97902a18e2ac ya está en inglés. Saltando...
🧐 Procesando 6932/17048 - 5c6e84d9-d536-41f7-8bfa-30c219ca17a9 | Idioma detectado: en
✅ 5c6e84d9-d536-41f7-8bfa-30c219ca17a9 ya está en inglés. Saltando...
🧐 Procesando 6933/17048 - 23172268-ab10-4fb8-a258-c909142b4a3c | Idioma detectado: pt
🧐 Procesando 6934/17048 - 2c6321e7-b969-40f2-aefe-bd412ee91348 | Idioma detectado: en
✅ 2c6321e7-b969-40f2-aefe-bd412ee91348 ya está en inglés. Saltando...
🧐 Procesando 6935/17048 - c38b5ef1-8f28-43e2-8331-d19afd66358e | Idioma detectado: en
✅ c38b5ef1-8f28-43e2-8331-d19afd66358e ya está en inglés. Saltando...
🧐 Procesando 6936/17048 - 52a5e124-1cc2-41e0-b785-aaa7079a445f | Idioma detectado: en
✅ 52a5e124-1cc2-41e0-b785-aaa7079a445f ya está en inglés. Saltando...
🧐 Procesando 6937/17048 - d151e3e9-209e-48ab-b454-570f9b379fb7 | Idioma detectado: en
✅ d151e3e9-209e-48ab-b454-570f9b379fb7 ya está en inglés. Saltando...
🧐 Procesando 6938/17048 - 98334b63-006b-4231-90d4-e2d733ca4b74 | Idioma detectado: es
🧐 Procesando 6939/17048 - b6c075b2-28eb-45cd-bf36-004b29984f1f | Idioma detectado: es
🧐 Procesando 6940/17048 - 3368f013-56d3-4a47-be67-119114fdf586 | Idioma detectado: es

🔄 Traduciendo canciones:  41%|████      | 6949/17048 [19:36<1:30:31,  1.86it/s]

✅ 2c6321e7-b969-40f2-aefe-bd412ee91348 ya está en inglés. Saltando...
🧐 Procesando 6935/17048 - c38b5ef1-8f28-43e2-8331-d19afd66358e | Idioma detectado: en
✅ c38b5ef1-8f28-43e2-8331-d19afd66358e ya está en inglés. Saltando...
🧐 Procesando 6936/17048 - 52a5e124-1cc2-41e0-b785-aaa7079a445f | Idioma detectado: en
✅ 52a5e124-1cc2-41e0-b785-aaa7079a445f ya está en inglés. Saltando...
🧐 Procesando 6937/17048 - d151e3e9-209e-48ab-b454-570f9b379fb7 | Idioma detectado: en
✅ d151e3e9-209e-48ab-b454-570f9b379fb7 ya está en inglés. Saltando...
🧐 Procesando 6938/17048 - 98334b63-006b-4231-90d4-e2d733ca4b74 | Idioma detectado: es
🧐 Procesando 6939/17048 - b6c075b2-28eb-45cd-bf36-004b29984f1f | Idioma detectado: es
🧐 Procesando 6940/17048 - 3368f013-56d3-4a47-be67-119114fdf586 | Idioma detectado: es
🧐 Procesando 6941/17048 - fdbe6d61-2ba5-4047-a18a-301a7dbd2dfa | Idioma detectado: es
🧐 Procesando 6942/17048 - aaabd785-d5bb-46c1-8872-dd21e4bf9ec5 | Idioma detectado: es
🧐 Procesando 6943/17048 - 0fad0ab6-d487-402e-be9e-f4422003f3cc | Idioma detectado: es
🧐 Procesando 6944/17048 - b51ec374-69c0-4a37-8321-e9c0ebf9740e | Idioma detectado: es
🧐 Procesando 6945/17048 - 08fdb888-26ef-43a9-9b7c-0e6a16941998 | Idioma detectado: es
🧐 Procesando 6946/17048 - a561fa5a-e0f1-46e1-8ac7-76c9a2b11cb9 | Idioma detectado: es
🧐 Procesando 6947/17048 - f9f2a3d4-762a-44ad-8be1-ebd9e2110ffc | Idioma detectado: es
🧐 Procesando 6948/17048 - 4ae16f3a-ac9b-4e3b-97af-cc49efcda44e | Idioma detectado: es
🧐 Procesando 6949/17048 - a89239cf-b8d2-4b47-b1b9-6b27f170f23e | Idioma detectado: es
🧐 Procesando 6950/17048 - c4b2bbd7-b2e1-4dfb-9d82-b9a02f13048f | Idioma detectado: es

🔄 Traduciendo canciones:  41%|████      | 6951/17048 [19:42<2:02:46,  1.37it/s]

✅ f39f20d9-c8e7-4674-93cd-7e8cf86b88dc ya está en inglés. Saltando...
🧐 Procesando 6961/17048 - f6ff6766-1f6d-499a-88d7-bc94ba919d9a | Idioma detectado: en
✅ f6ff6766-1f6d-499a-88d7-bc94ba919d9a ya está en inglés. Saltando...
🧐 Procesando 6962/17048 - 14cfbef9-5ff3-4009-b608-6ecfcd506f73 | Idioma detectado: en
✅ 14cfbef9-5ff3-4009-b608-6ecfcd506f73 ya está en inglés. Saltando...
🧐 Procesando 6963/17048 - 07749ea2-0927-489b-998f-4f8425e68389 | Idioma detectado: en
✅ 07749ea2-0927-489b-998f-4f8425e68389 ya está en inglés. Saltando...
🧐 Procesando 6964/17048 - 7e3b8240-6b2a-4fc7-806d-5e5dbeab2131 | Idioma detectado: en
✅ 7e3b8240-6b2a-4fc7-806d-5e5dbeab2131 ya está en inglés. Saltando...
🧐 Procesando 6965/17048 - d8f347c1-31e4-486b-9a1a-abe06e8c8871 | Idioma detectado: en
✅ d8f347c1-31e4-486b-9a1a-abe06e8c8871 ya está en inglés. Saltando...
🧐 Procesando 6966/17048 - 8b075059-68e7-488e-a4e8-adb179347c4a | Idioma detectado: en
✅ 8b075059-68e7-488e-a4e8-adb179347c4a ya está en inglés. Saltando...
🧐 Procesando 6967/17048 - d9dd473a-5774-406d-a375-2fafefe9e976 | Idioma detectado: en
✅ d9dd473a-5774-406d-a375-2fafefe9e976 ya está en inglés. Saltando...
🧐 Procesando 6968/17048 - 072570ae-03ac-4e47-9239-f5ed2d401226 | Idioma detectado: en
✅ 072570ae-03ac-4e47-9239-f5ed2d401226 ya está en inglés. Saltando...
🧐 Procesando 6969/17048 - 67ab6216-d189-483a-a966-77c4b557fffb | Idioma detectado: en
✅ 67ab6216-d189-483a-a966-77c4b557fffb ya está en inglés. Saltando...
🧐 Procesando 6970/17048 - f075aad6-ea9a-487e-805b-9483dbbfc411 | Idioma detectado: fr

🔄 Traduciendo canciones:  42%|████▏     | 7231/17048 [20:23<39:10,  4.18it/s]

✅ a61edea7-07f0-4841-9176-39a42b3201be ya está en inglés. Saltando...
🧐 Procesando 7219/17048 - 1f09694b-a92c-4c68-b15e-5de2594a787a | Idioma detectado: en
✅ 1f09694b-a92c-4c68-b15e-5de2594a787a ya está en inglés. Saltando...
🧐 Procesando 7220/17048 - 54bab73a-f5d5-40b3-9af3-d5381533ef28 | Idioma detectado: en
✅ 54bab73a-f5d5-40b3-9af3-d5381533ef28 ya está en inglés. Saltando...
🧐 Procesando 7221/17048 - 4cceb1c9-e152-4c0c-86b6-252dfe6efe48 | Idioma detectado: en
✅ 4cceb1c9-e152-4c0c-86b6-252dfe6efe48 ya está en inglés. Saltando...
🧐 Procesando 7222/17048 - 805c3e2d-1883-4a82-bafa-34b7a84175f6 | Idioma detectado: en
✅ 805c3e2d-1883-4a82-bafa-34b7a84175f6 ya está en inglés. Saltando...
🧐 Procesando 7223/17048 - c3666618-cc84-42cc-915b-96554e7d2935 | Idioma detectado: en
✅ c3666618-cc84-42cc-915b-96554e7d2935 ya está en inglés. Saltando...
🧐 Procesando 7224/17048 - f78d9e71-536f-4a8e-aac6-a6f1ca12fb4a | Idioma detectado: en
✅ f78d9e71-536f-4a8e-aac6-a6f1ca12fb4a ya está en inglés. Saltando...
🧐 Procesando 7225/17048 - bc1fddef-895a-432f-85c1-43fe83f29852 | Idioma detectado: es
🧐 Procesando 7226/17048 - 6bc4cde9-03c3-4b97-b35d-0f9edf994294 | Idioma detectado: es
🧐 Procesando 7227/17048 - 9b255722-c7c8-4746-a435-8d4521fd132c | Idioma detectado: es
🧐 Procesando 7228/17048 - 8200af38-2199-4ebd-9e9c-c7d4f5c6a0aa | Idioma detectado: en
✅ 8200af38-2199-4ebd-9e9c-c7d4f5c6a0aa ya está en inglés. Saltando...
🧐 Procesando 7229/17048 - d0444c19-cbec-4ee5-850e-b5da44273297 | Idioma detectado: es
🧐 Procesando 7230/17048 - ca989660-bfac-4453-88a3-6a93d5a8cee4 | Idioma detectado: es

🔄 Traduciendo canciones:  42%|████▏     | 7241/17048 [20:44<2:24:14,  1.13it/s]

🧐 Procesando 7228/17048 - 8200af38-2199-4ebd-9e9c-c7d4f5c6a0aa | Idioma detectado: en
✅ 8200af38-2199-4ebd-9e9c-c7d4f5c6a0aa ya está en inglés. Saltando...
🧐 Procesando 7229/17048 - d0444c19-cbec-4ee5-850e-b5da44273297 | Idioma detectado: es
🧐 Procesando 7230/17048 - ca989660-bfac-4453-88a3-6a93d5a8cee4 | Idioma detectado: es
🧐 Procesando 7231/17048 - 915d8c58-3ee5-4941-8622-d29df29035c8 | Idioma detectado: en
✅ 915d8c58-3ee5-4941-8622-d29df29035c8 ya está en inglés. Saltando...
🧐 Procesando 7232/17048 - 0e4f6b09-814e-445f-8a25-54992604200a | Idioma detectado: en
✅ 0e4f6b09-814e-445f-8a25-54992604200a ya está en inglés. Saltando...
🧐 Procesando 7233/17048 - fe8c6b54-73fd-4972-9266-01cd241b9f4d | Idioma detectado: en
✅ fe8c6b54-73fd-4972-9266-01cd241b9f4d ya está en inglés. Saltando...
🧐 Procesando 7234/17048 - be28caf2-c68f-4176-9c22-f9aea4409340 | Idioma detectado: en
✅ be28caf2-c68f-4176-9c22-f9aea4409340 ya está en inglés. Saltando...
🧐 Procesando 7235/17048 - a2224736-d2bb-4dbc-b796-5840e08d5c3f | Idioma detectado: en
✅ a2224736-d2bb-4dbc-b796-5840e08d5c3f ya está en inglés. Saltando...
🧐 Procesando 7236/17048 - 5d5274a4-02fc-41cf-8dd5-2b5b9da849c7 | Idioma detectado: en
✅ 5d5274a4-02fc-41cf-8dd5-2b5b9da849c7 ya está en inglés. Saltando...
🧐 Procesando 7237/17048 - 5c1329cf-91e8-46d7-aa6e-0b5dd153e8c8 | Idioma detectado: pt
🧐 Procesando 7238/17048 - 5fccdbfb-d912-4d35-a976-3943afe21f7e | Idioma detectado: pt
🧐 Procesando 7239/17048 - edaf3df5-9d58-48c9-bacf-8a2358df0dfc | Idioma detectado: pt
🧐 Procesando 7240/17048 - 6dbbecc5-20b9-43e4-9602-53e15c770cb7 | Idioma detectado: pt

🔄 Traduciendo canciones:  43%|████▎     | 7260/17048 [21:10<6:43:20,  2.47s/it]

🧐 Procesando 7246/17048 - 5bf4dd6b-eec5-48c2-961c-e37df3a1f902 | Idioma detectado: en
✅ 5bf4dd6b-eec5-48c2-961c-e37df3a1f902 ya está en inglés. Saltando...
🧐 Procesando 7247/17048 - da093980-1a7a-40e6-9320-02e20558f57d | Idioma detectado: en
✅ da093980-1a7a-40e6-9320-02e20558f57d ya está en inglés. Saltando...
🧐 Procesando 7248/17048 - fb506b9f-b7d3-4bdd-b6fc-fa0bf6c1e459 | Idioma detectado: en
✅ fb506b9f-b7d3-4bdd-b6fc-fa0bf6c1e459 ya está en inglés. Saltando...
🧐 Procesando 7249/17048 - 43015471-3fa6-4d73-8c98-297d646884a6 | Idioma detectado: en
✅ 43015471-3fa6-4d73-8c98-297d646884a6 ya está en inglés. Saltando...
🧐 Procesando 7250/17048 - da894699-84d4-4851-ad6d-1f52ae790586 | Idioma detectado: en
✅ da894699-84d4-4851-ad6d-1f52ae790586 ya está en inglés. Saltando...
🧐 Procesando 7251/17048 - d83fdaa7-f3b1-45e8-9202-eb8aef46f203 | Idioma detectado: es
🧐 Procesando 7252/17048 - e93c7dd2-fd09-4b67-925f-09c0fc35bcfc | Idioma detectado: es
🧐 Procesando 7253/17048 - 7a9eecaa-2c65-4629-b24d-b69ac9c892d0 | Idioma detectado: es
🧐 Procesando 7254/17048 - fe145a9a-8768-498c-8619-f77f65049682 | Idioma detectado: es
🧐 Procesando 7255/17048 - c02e4def-eb04-4631-9bf1-6ad513ba6e3f | Idioma detectado: es
🧐 Procesando 7256/17048 - d2116d9b-ae43-4ba4-8f76-0055e4362351 | Idioma detectado: es
🧐 Procesando 7257/17048 - b66c654f-e62d-4119-b341-905bb6fac6a7 | Idioma detectado: es
🧐 Procesando 7258/17048 - aeb32a62-73aa-4150-a0f9-2e976a03064e | Idioma detectado: es
🧐 Procesando 7259/17048 - acb79a04-7d7c-43b5-87db-f5b9ee99f95e | Idioma detectado: es
🧐 Procesando 7260/17048 - 06e161d9-22c1-4200-b988-5558ed988ec2 | Idioma detectado: es

🔄 Traduciendo canciones:  43%|████▎     | 7291/17048 [21:40<5:04:35,  1.87s/it]

✅ 6bc5f1e5-1f82-4d5b-b3ec-28d6de1a5c74 ya está en inglés. Saltando...
🧐 Procesando 7278/17048 - 53897bff-578b-494c-aa06-0b99e336f30d | Idioma detectado: en
✅ 53897bff-578b-494c-aa06-0b99e336f30d ya está en inglés. Saltando...
🧐 Procesando 7279/17048 - fc5a3e23-0c11-4925-bcb8-c455bdfd66fc | Idioma detectado: en
✅ fc5a3e23-0c11-4925-bcb8-c455bdfd66fc ya está en inglés. Saltando...
🧐 Procesando 7280/17048 - 525334f6-600a-464d-8b64-b99ecf507f4f | Idioma detectado: en
✅ 525334f6-600a-464d-8b64-b99ecf507f4f ya está en inglés. Saltando...
🧐 Procesando 7281/17048 - ef495231-fb04-408e-86da-5c9bd26054e8 | Idioma detectado: en
✅ ef495231-fb04-408e-86da-5c9bd26054e8 ya está en inglés. Saltando...
🧐 Procesando 7282/17048 - 6e234488-5c9b-4ac1-83f3-02334f39f158 | Idioma detectado: en
✅ 6e234488-5c9b-4ac1-83f3-02334f39f158 ya está en inglés. Saltando...
🧐 Procesando 7283/17048 - fb57dd06-3ef3-45ab-bd5a-ffc33972d37f | Idioma detectado: en
✅ fb57dd06-3ef3-45ab-bd5a-ffc33972d37f ya está en inglés. Saltando...
🧐 Procesando 7284/17048 - 021c5ea3-eee4-480e-91d5-f1b6cc621f5d | Idioma detectado: es
🧐 Procesando 7285/17048 - 82fd5ad3-bacd-44af-bf14-73238c81ea03 | Idioma detectado: es
🧐 Procesando 7286/17048 - 6deb186a-6c95-4ce5-b07b-0f938e36b503 | Idioma detectado: es
🧐 Procesando 7287/17048 - 55cedcc9-6fac-47b2-ad30-93fd880f37a5 | Idioma detectado: es
🧐 Procesando 7288/17048 - 5a967c14-1078-4b80-a320-afcc20d4d625 | Idioma detectado: es
🧐 Procesando 7289/17048 - 7f4ebba0-9257-499d-b073-d68b75a03615 | Idioma detectado: es
🧐 Procesando 7290/17048 - d6c11de3-50e0-45f3-82d2-eaa02b03e5ed | Idioma detectado: es

🔄 Traduciendo canciones:  44%|████▍     | 7461/17048 [22:15<18:34,  8.60it/s]

🧐 Procesando 7449/17048 - 5fcab33e-25dd-479e-a1c2-6e3fd8546831 | Idioma detectado: en
✅ 5fcab33e-25dd-479e-a1c2-6e3fd8546831 ya está en inglés. Saltando...
🧐 Procesando 7450/17048 - 325ca6d8-8769-4702-b20f-55783ead18db | Idioma detectado: en
✅ 325ca6d8-8769-4702-b20f-55783ead18db ya está en inglés. Saltando...
🧐 Procesando 7451/17048 - 176e8931-e8aa-4b79-a8d5-8e54f507a8b0 | Idioma detectado: en
✅ 176e8931-e8aa-4b79-a8d5-8e54f507a8b0 ya está en inglés. Saltando...
🧐 Procesando 7452/17048 - cb6bec2b-a8db-4e6e-9ff4-1db1fb6d99c8 | Idioma detectado: en
✅ cb6bec2b-a8db-4e6e-9ff4-1db1fb6d99c8 ya está en inglés. Saltando...
🧐 Procesando 7453/17048 - 694d72dd-8c58-467a-87ab-e5225b2e2718 | Idioma detectado: en
✅ 694d72dd-8c58-467a-87ab-e5225b2e2718 ya está en inglés. Saltando...
🧐 Procesando 7454/17048 - 2f0c6679-3bc8-4bc9-a80f-d98083f1bc34 | Idioma detectado: en
✅ 2f0c6679-3bc8-4bc9-a80f-d98083f1bc34 ya está en inglés. Saltando...
🧐 Procesando 7455/17048 - e5ceb33f-1614-4a77-8412-2fb9ea0b4636 | Idioma detectado: de
🧐 Procesando 7456/17048 - a4239228-7487-413c-b55d-0616af280cb2 | Idioma detectado: en
✅ a4239228-7487-413c-b55d-0616af280cb2 ya está en inglés. Saltando...
🧐 Procesando 7457/17048 - 4010e914-ffa9-4547-93f1-57ca2b3b945a | Idioma detectado: en
✅ 4010e914-ffa9-4547-93f1-57ca2b3b945a ya está en inglés. Saltando...
🧐 Procesando 7458/17048 - 37b252f2-6a65-47dc-b88f-1b18cbfef673 | Idioma detectado: de
🧐 Procesando 7459/17048 - a0db012e-40b2-429d-9c1d-8677fde77e15 | Idioma detectado: de
🧐 Procesando 7460/17048 - 27672cb2-fe1a-4159-a40a-6afd4cfa8688 | Idioma detectado: da

🔄 Traduciendo canciones:  44%|████▍     | 7471/17048 [22:45<2:11:22,  1.21it/s]

🧐 Procesando 7456/17048 - a4239228-7487-413c-b55d-0616af280cb2 | Idioma detectado: en
✅ a4239228-7487-413c-b55d-0616af280cb2 ya está en inglés. Saltando...
🧐 Procesando 7457/17048 - 4010e914-ffa9-4547-93f1-57ca2b3b945a | Idioma detectado: en
✅ 4010e914-ffa9-4547-93f1-57ca2b3b945a ya está en inglés. Saltando...
🧐 Procesando 7458/17048 - 37b252f2-6a65-47dc-b88f-1b18cbfef673 | Idioma detectado: de
🧐 Procesando 7459/17048 - a0db012e-40b2-429d-9c1d-8677fde77e15 | Idioma detectado: de
🧐 Procesando 7460/17048 - 27672cb2-fe1a-4159-a40a-6afd4cfa8688 | Idioma detectado: da
🧐 Procesando 7461/17048 - 169ecbc7-d188-4280-b5f3-b191015f9983 | Idioma detectado: da
🧐 Procesando 7462/17048 - 72e1cb24-914a-457b-9d92-a5270da6feb4 | Idioma detectado: da
🧐 Procesando 7463/17048 - c6deff22-670e-4f86-9798-d05992173754 | Idioma detectado: en
✅ c6deff22-670e-4f86-9798-d05992173754 ya está en inglés. Saltando...
🧐 Procesando 7464/17048 - f1cf2e7b-b046-43ca-8887-74f762a1206d | Idioma detectado: en
✅ f1cf2e7b-b046-43ca-8887-74f762a1206d ya está en inglés. Saltando...
🧐 Procesando 7465/17048 - 97154c6e-1351-4f0e-af61-65632154d971 | Idioma detectado: en
✅ 97154c6e-1351-4f0e-af61-65632154d971 ya está en inglés. Saltando...
🧐 Procesando 7466/17048 - 151b97cd-1642-4479-8e60-4af1923a5a97 | Idioma detectado: de
🧐 Procesando 7467/17048 - 9a656efc-f627-4524-90b9-72cad18c2017 | Idioma detectado: de
🧐 Procesando 7468/17048 - 32419471-8681-4f4b-883b-c3784e262337 | Idioma detectado: de
🧐 Procesando 7469/17048 - 9a55f9f8-643e-4055-813a-2a1b62cf52b7 | Idioma detectado: de
🧐 Procesando 7470/17048 - 17eff1f4-1fc6-48e7-8641-ddffa8f3c67a | Idioma detectado: de

🔄 Traduciendo canciones:  44%|████▍     | 7481/17048 [23:08<7:05:12,  2.67s/it]

✅ c6deff22-670e-4f86-9798-d05992173754 ya está en inglés. Saltando...
🧐 Procesando 7464/17048 - f1cf2e7b-b046-43ca-8887-74f762a1206d | Idioma detectado: en
✅ f1cf2e7b-b046-43ca-8887-74f762a1206d ya está en inglés. Saltando...
🧐 Procesando 7465/17048 - 97154c6e-1351-4f0e-af61-65632154d971 | Idioma detectado: en
✅ 97154c6e-1351-4f0e-af61-65632154d971 ya está en inglés. Saltando...
🧐 Procesando 7466/17048 - 151b97cd-1642-4479-8e60-4af1923a5a97 | Idioma detectado: de
🧐 Procesando 7467/17048 - 9a656efc-f627-4524-90b9-72cad18c2017 | Idioma detectado: de
🧐 Procesando 7468/17048 - 32419471-8681-4f4b-883b-c3784e262337 | Idioma detectado: de
🧐 Procesando 7469/17048 - 9a55f9f8-643e-4055-813a-2a1b62cf52b7 | Idioma detectado: de
🧐 Procesando 7470/17048 - 17eff1f4-1fc6-48e7-8641-ddffa8f3c67a | Idioma detectado: de
🧐 Procesando 7471/17048 - 56815acd-b1b5-41f3-8b37-778201968373 | Idioma detectado: de
🧐 Procesando 7472/17048 - 2a74acb6-9f1a-431b-a9a6-3180b311344d | Idioma detectado: de
🧐 Procesando 7473/17048 - 74e62fa5-36d4-452f-a88f-16e08b154870 | Idioma detectado: de
🧐 Procesando 7474/17048 - 62abe306-0010-46ba-b235-7b5bb3b88ab9 | Idioma detectado: de
🧐 Procesando 7475/17048 - 2152a382-af69-4a63-8a3c-5e028db05af0 | Idioma detectado: de
🧐 Procesando 7476/17048 - ecc34b38-dd2a-4692-9f86-ee61de84c1d1 | Idioma detectado: de
🧐 Procesando 7477/17048 - c33ef235-b233-4199-9535-c2b203f38de9 | Idioma detectado: de
🧐 Procesando 7478/17048 - 52db0635-602b-46f0-b81a-ad4a2238adba | Idioma detectado: de
🧐 Procesando 7479/17048 - d108381c-6a30-4089-a735-56ebf071f302 | Idioma detectado: de
🧐 Procesando 7480/17048 - 6fc02cfd-b67b-411a-a231-7fd4d812b7b3 | Idioma detectado: de

🔄 Traduciendo canciones:  44%|████▍     | 7530/17048 [23:26<34:50,  4.55it/s]

🧐 Procesando 7520/17048 - 2fc1ba05-d6dc-40bd-8937-281d8eead145 | Idioma detectado: en
✅ 2fc1ba05-d6dc-40bd-8937-281d8eead145 ya está en inglés. Saltando...
🧐 Procesando 7521/17048 - b6c6128f-4fdf-473d-9a4a-62083848b268 | Idioma detectado: en
✅ b6c6128f-4fdf-473d-9a4a-62083848b268 ya está en inglés. Saltando...
🧐 Procesando 7522/17048 - ba46b8ee-1400-4526-8e2e-8525ce4bbb7c | Idioma detectado: en
✅ ba46b8ee-1400-4526-8e2e-8525ce4bbb7c ya está en inglés. Saltando...
🧐 Procesando 7523/17048 - 8c6bb855-bf09-4f7f-aa88-3187affcd671 | Idioma detectado: en
✅ 8c6bb855-bf09-4f7f-aa88-3187affcd671 ya está en inglés. Saltando...
🧐 Procesando 7524/17048 - dd4b5665-4205-47d9-b760-d5a1866336eb | Idioma detectado: en
✅ dd4b5665-4205-47d9-b760-d5a1866336eb ya está en inglés. Saltando...
🧐 Procesando 7525/17048 - c2da2ea1-6bec-4879-9559-c0d640b001e4 | Idioma detectado: en
✅ c2da2ea1-6bec-4879-9559-c0d640b001e4 ya está en inglés. Saltando...
🧐 Procesando 7526/17048 - bc62e6d4-4c13-4957-b735-9fe0601f74d2 | Idioma detectado: en
✅ bc62e6d4-4c13-4957-b735-9fe0601f74d2 ya está en inglés. Saltando...
🧐 Procesando 7527/17048 - f1bf58c0-e700-4a0f-b26f-1e64d042af8b | Idioma detectado: en
✅ f1bf58c0-e700-4a0f-b26f-1e64d042af8b ya está en inglés. Saltando...
🧐 Procesando 7528/17048 - 2e111c68-52f1-4f5a-a960-d28fe207c4ad | Idioma detectado: en
✅ 2e111c68-52f1-4f5a-a960-d28fe207c4ad ya está en inglés. Saltando...
🧐 Procesando 7529/17048 - e2f50cea-1028-40d0-92fb-6f4f5ec39add | Idioma detectado: de
🧐 Procesando 7530/17048 - 1f5e1c61-8513-49c0-abc1-8b5005b96aff | Idioma detectado: de

🔄 Traduciendo canciones:  45%|████▍     | 7590/17048 [23:37<36:39,  4.30it/s]

🧐 Procesando 7579/17048 - c06cc73d-3338-4d0d-9740-5ebdfed27ea0 | Idioma detectado: en
✅ c06cc73d-3338-4d0d-9740-5ebdfed27ea0 ya está en inglés. Saltando...
🧐 Procesando 7580/17048 - 7c5daefa-f681-4948-9a93-724e55d8c058 | Idioma detectado: en
✅ 7c5daefa-f681-4948-9a93-724e55d8c058 ya está en inglés. Saltando...
🧐 Procesando 7581/17048 - a3c8d51b-65e8-4463-8a58-1f97b601124b | Idioma detectado: en
✅ a3c8d51b-65e8-4463-8a58-1f97b601124b ya está en inglés. Saltando...
🧐 Procesando 7582/17048 - bc09d257-3277-49ec-9365-42e0dbc6bb2b | Idioma detectado: en
✅ bc09d257-3277-49ec-9365-42e0dbc6bb2b ya está en inglés. Saltando...
🧐 Procesando 7583/17048 - 6f5cdb1a-41e7-4617-9c9d-8cab05d03e3d | Idioma detectado: en
✅ 6f5cdb1a-41e7-4617-9c9d-8cab05d03e3d ya está en inglés. Saltando...
🧐 Procesando 7584/17048 - 641b52d6-cd82-4494-83ca-cd983f2c759b | Idioma detectado: en
✅ 641b52d6-cd82-4494-83ca-cd983f2c759b ya está en inglés. Saltando...
🧐 Procesando 7585/17048 - 8e1f1116-dc78-45ce-961f-1e8b19fb8303 | Idioma detectado: en
✅ 8e1f1116-dc78-45ce-961f-1e8b19fb8303 ya está en inglés. Saltando...
🧐 Procesando 7586/17048 - 55434869-b331-470b-b585-1e80458304f9 | Idioma detectado: en
✅ 55434869-b331-470b-b585-1e80458304f9 ya está en inglés. Saltando...
🧐 Procesando 7587/17048 - 5f261ed2-50b9-4535-ab54-64ba85116b5f | Idioma detectado: de
🧐 Procesando 7588/17048 - d539fe77-02d6-44c5-aa91-ce9c582f8191 | Idioma detectado: de
🧐 Procesando 7589/17048 - d6d27aa3-8bca-4c35-b910-0c15ef0c3123 | Idioma detectado: de
🧐 Procesando 7590/17048 - e8b984b4-98ba-488c-99d7-9b0cb5695c1c | Idioma detectado: de

🔄 Traduciendo canciones:  45%|████▍     | 7601/17048 [24:04<3:42:55,  1.42s/it]

✅ 641b52d6-cd82-4494-83ca-cd983f2c759b ya está en inglés. Saltando...
🧐 Procesando 7585/17048 - 8e1f1116-dc78-45ce-961f-1e8b19fb8303 | Idioma detectado: en
✅ 8e1f1116-dc78-45ce-961f-1e8b19fb8303 ya está en inglés. Saltando...
🧐 Procesando 7586/17048 - 55434869-b331-470b-b585-1e80458304f9 | Idioma detectado: en
✅ 55434869-b331-470b-b585-1e80458304f9 ya está en inglés. Saltando...
🧐 Procesando 7587/17048 - 5f261ed2-50b9-4535-ab54-64ba85116b5f | Idioma detectado: de
🧐 Procesando 7588/17048 - d539fe77-02d6-44c5-aa91-ce9c582f8191 | Idioma detectado: de
🧐 Procesando 7589/17048 - d6d27aa3-8bca-4c35-b910-0c15ef0c3123 | Idioma detectado: de
🧐 Procesando 7590/17048 - e8b984b4-98ba-488c-99d7-9b0cb5695c1c | Idioma detectado: de
🧐 Procesando 7591/17048 - 7d81d421-7f5a-42a9-a1ae-c16d2f10251d | Idioma detectado: de
🧐 Procesando 7592/17048 - 903c09cd-c0de-4c6d-8c68-9050c8f6c1fd | Idioma detectado: de
🧐 Procesando 7593/17048 - 0f91ac4c-ddd1-4db1-b059-69e95da53871 | Idioma detectado: de
🧐 Procesando 7594/17048 - 3f7e83a9-e6f9-4810-9811-ba2aec207474 | Idioma detectado: de
🧐 Procesando 7595/17048 - e0535907-03c0-40ed-9647-7759f2b7a2b5 | Idioma detectado: de
🧐 Procesando 7596/17048 - 19270071-e6c8-4422-8c7f-758bd16eb6ea | Idioma detectado: de
🧐 Procesando 7597/17048 - c2715586-c018-464a-a256-e4791cd2bf57 | Idioma detectado: en
✅ c2715586-c018-464a-a256-e4791cd2bf57 ya está en inglés. Saltando...
🧐 Procesando 7598/17048 - 2cee9501-8471-4162-8d53-170284f007d8 | Idioma detectado: de
🧐 Procesando 7599/17048 - 3a23bcac-c659-473f-97e4-fce6bf0af04e | Idioma detectado: de
🧐 Procesando 7600/17048 - e199ddec-7c34-42e4-afe4-6d5348ea517c | Idioma detectado: de

🔄 Traduciendo canciones:  45%|████▍     | 7610/17048 [24:18<4:38:39,  1.77s/it]

🧐 Procesando 7593/17048 - 0f91ac4c-ddd1-4db1-b059-69e95da53871 | Idioma detectado: de
🧐 Procesando 7594/17048 - 3f7e83a9-e6f9-4810-9811-ba2aec207474 | Idioma detectado: de
🧐 Procesando 7595/17048 - e0535907-03c0-40ed-9647-7759f2b7a2b5 | Idioma detectado: de
🧐 Procesando 7596/17048 - 19270071-e6c8-4422-8c7f-758bd16eb6ea | Idioma detectado: de
🧐 Procesando 7597/17048 - c2715586-c018-464a-a256-e4791cd2bf57 | Idioma detectado: en
✅ c2715586-c018-464a-a256-e4791cd2bf57 ya está en inglés. Saltando...
🧐 Procesando 7598/17048 - 2cee9501-8471-4162-8d53-170284f007d8 | Idioma detectado: de
🧐 Procesando 7599/17048 - 3a23bcac-c659-473f-97e4-fce6bf0af04e | Idioma detectado: de
🧐 Procesando 7600/17048 - e199ddec-7c34-42e4-afe4-6d5348ea517c | Idioma detectado: de
🧐 Procesando 7601/17048 - 5f3a84ce-82cf-477b-a890-c34c1e8c28a3 | Idioma detectado: de
🧐 Procesando 7602/17048 - b5ec49ec-cc91-41d6-a931-a69f6a6750a4 | Idioma detectado: en
✅ b5ec49ec-cc91-41d6-a931-a69f6a6750a4 ya está en inglés. Saltando...
🧐 Procesando 7603/17048 - c87cff35-bc65-47e3-9b46-66a9c9b5dd9c | Idioma detectado: de
🧐 Procesando 7604/17048 - c57efd68-4290-4084-a18b-1d2be28a46cc | Idioma detectado: de
🧐 Procesando 7605/17048 - bde9b7d8-fd9c-4d17-973c-0c2d9a7f5c44 | Idioma detectado: de
🧐 Procesando 7606/17048 - 6168be19-2703-4916-ad4f-12517c2989c4 | Idioma detectado: de
🧐 Procesando 7607/17048 - 12cf7aeb-af5c-4e6d-a6f7-e454f83943f5 | Idioma detectado: de
🧐 Procesando 7608/17048 - e8fdb54d-25b8-4d21-bcb1-186c06f514c6 | Idioma detectado: de
🧐 Procesando 7609/17048 - 1122356b-43a1-46a3-9a2a-42473b455e97 | Idioma detectado: de
🧐 Procesando 7610/17048 - 9e58c2bc-187f-457b-b7ab-d862443e08be | Idioma detectado: de

🔄 Traduciendo canciones:  45%|████▍     | 7620/17048 [24:38<4:24:54,  1.69s/it]

✅ b5ec49ec-cc91-41d6-a931-a69f6a6750a4 ya está en inglés. Saltando...
🧐 Procesando 7603/17048 - c87cff35-bc65-47e3-9b46-66a9c9b5dd9c | Idioma detectado: de
🧐 Procesando 7604/17048 - c57efd68-4290-4084-a18b-1d2be28a46cc | Idioma detectado: de
🧐 Procesando 7605/17048 - bde9b7d8-fd9c-4d17-973c-0c2d9a7f5c44 | Idioma detectado: de
🧐 Procesando 7606/17048 - 6168be19-2703-4916-ad4f-12517c2989c4 | Idioma detectado: de
🧐 Procesando 7607/17048 - 12cf7aeb-af5c-4e6d-a6f7-e454f83943f5 | Idioma detectado: de
🧐 Procesando 7608/17048 - e8fdb54d-25b8-4d21-bcb1-186c06f514c6 | Idioma detectado: de
🧐 Procesando 7609/17048 - 1122356b-43a1-46a3-9a2a-42473b455e97 | Idioma detectado: de
🧐 Procesando 7610/17048 - 9e58c2bc-187f-457b-b7ab-d862443e08be | Idioma detectado: de
🧐 Procesando 7611/17048 - cd3547e5-6923-48f9-80ad-49c6baf3d794 | Idioma detectado: de
🧐 Procesando 7612/17048 - 665f4906-a039-45f0-bdc7-e4ebf589b199 | Idioma detectado: de
🧐 Procesando 7613/17048 - 8d9f20f4-187e-4488-8339-3cae63be017c | Idioma detectado: de
🧐 Procesando 7614/17048 - 07680b9c-936f-4f82-9f3d-6f3bc65c947d | Idioma detectado: en
✅ 07680b9c-936f-4f82-9f3d-6f3bc65c947d ya está en inglés. Saltando...
🧐 Procesando 7615/17048 - 6703e839-904b-4e33-a72c-641c204243b4 | Idioma detectado: de
🧐 Procesando 7616/17048 - 1bfd94cd-b826-4bf4-8469-06287ffefb9e | Idioma detectado: de
🧐 Procesando 7617/17048 - 61a9a2db-fe0c-43a1-9a3a-e1b37570220d | Idioma detectado: de
🧐 Procesando 7618/17048 - 57f830e2-bbe9-4ac9-a3bc-96ec0b16eaee | Idioma detectado: de
🧐 Procesando 7619/17048 - 51da8886-b28c-4874-b1b7-8a0b310baf0e | Idioma detectado: de
🧐 Procesando 7620/17048 - be5c8972-bd29-4e07-aacc-ec0f53f24d3f | Idioma detectado: de

🔄 Traduciendo canciones:  45%|████▍     | 7660/17048 [25:17<1:19:40,  1.96it/s]

🧐 Procesando 7650/17048 - 25d5ae78-a2d9-4e3e-b5d5-41e9df8c501b | Idioma detectado: en
✅ 25d5ae78-a2d9-4e3e-b5d5-41e9df8c501b ya está en inglés. Saltando...
🧐 Procesando 7651/17048 - ee5d2041-68c1-4622-bb6b-7e2e120e2c68 | Idioma detectado: en
✅ ee5d2041-68c1-4622-bb6b-7e2e120e2c68 ya está en inglés. Saltando...
🧐 Procesando 7652/17048 - ff358a63-da91-4b5a-a3bb-39bde478455c | Idioma detectado: en
✅ ff358a63-da91-4b5a-a3bb-39bde478455c ya está en inglés. Saltando...
🧐 Procesando 7653/17048 - 433cb50e-e9bf-4f85-870e-a3d7eb282107 | Idioma detectado: en
✅ 433cb50e-e9bf-4f85-870e-a3d7eb282107 ya está en inglés. Saltando...
🧐 Procesando 7654/17048 - 74ba74a1-d500-496c-8b62-2c12fb9bf494 | Idioma detectado: en
✅ 74ba74a1-d500-496c-8b62-2c12fb9bf494 ya está en inglés. Saltando...
🧐 Procesando 7655/17048 - 42763871-06ed-47d9-9666-65c7e29f02fe | Idioma detectado: en
✅ 42763871-06ed-47d9-9666-65c7e29f02fe ya está en inglés. Saltando...
🧐 Procesando 7656/17048 - b71d1533-6ab8-41ab-8240-6af3b5f402b4 | Idioma detectado: en
✅ b71d1533-6ab8-41ab-8240-6af3b5f402b4 ya está en inglés. Saltando...
🧐 Procesando 7657/17048 - 406da9a5-1e32-4339-9feb-ebf56b35150b | Idioma detectado: en
✅ 406da9a5-1e32-4339-9feb-ebf56b35150b ya está en inglés. Saltando...
🧐 Procesando 7658/17048 - d9d279ca-4bd1-4dbc-ac2c-532106c3b894 | Idioma detectado: en
✅ d9d279ca-4bd1-4dbc-ac2c-532106c3b894 ya está en inglés. Saltando...
🧐 Procesando 7659/17048 - d84906b6-082f-4717-91ae-2bcb0d0a9d4e | Idioma detectado: de
🧐 Procesando 7660/17048 - fe4265fd-6557-4dc6-8143-e49fa64453d9 | Idioma detectado: de

🔄 Traduciendo canciones:  45%|████▌     | 7673/17048 [25:27<1:22:41,  1.89it/s]

🧐 Procesando 7670/17048 - a2bdef7f-41cc-4b8f-97ca-bc5ad4c3c2f5 | Idioma detectado: en
✅ a2bdef7f-41cc-4b8f-97ca-bc5ad4c3c2f5 ya está en inglés. Saltando...
🧐 Procesando 7671/17048 - c29e9b02-8b7d-4950-a881-244ec3fedb32 | Idioma detectado: en
✅ c29e9b02-8b7d-4950-a881-244ec3fedb32 ya está en inglés. Saltando...
🧐 Procesando 7672/17048 - b184f530-43b1-44db-bed2-cabec0810b31 | Idioma detectado: de
🧐 Procesando 7673/17048 - 48311d00-588d-4e6b-9d8e-3a479703477e | Idioma detectado: en
✅ 48311d00-588d-4e6b-9d8e-3a479703477e ya está en inglés. Saltando...
🧐 Procesando 7674/17048 - b61d82ae-ee69-47e6-8303-7c941f2e6587 | Idioma detectado: en
✅ b61d82ae-ee69-47e6-8303-7c941f2e6587 ya está en inglés. Saltando...
🧐 Procesando 7675/17048 - b10d469a-aaa6-4275-99e0-c82c77ea4bd8 | Idioma detectado: en
✅ b10d469a-aaa6-4275-99e0-c82c77ea4bd8 ya está en inglés. Saltando...
🧐 Procesando 7676/17048 - f83b83c4-e98c-492b-a65d-584710ed20de | Idioma detectado: en
✅ f83b83c4-e98c-492b-a65d-584710ed20de ya está en inglés. Saltando...
🧐 Procesando 7677/17048 - 5be517ad-7b3b-48f7-b118-d92102ed44ec | Idioma detectado: en
✅ 5be517ad-7b3b-48f7-b118-d92102ed44ec ya está en inglés. Saltando...
🧐 Procesando 7678/17048 - fa1a6d52-7234-4d2a-91e0-d20d48d102ee | Idioma detectado: en
✅ fa1a6d52-7234-4d2a-91e0-d20d48d102ee ya está en inglés. Saltando...
🧐 Procesando 7679/17048 - 7c01176f-0b80-4785-848d-0c9b5774f118 | Idioma detectado: en
✅ 7c01176f-0b80-4785-848d-0c9b5774f118 ya está en inglés. Saltando...
🧐 Procesando 7680/17048 - 89a8b1b1-b162-4c04-aecb-fff0e220e4f2 | Idioma detectado: fr

🔄 Traduciendo canciones:  46%|████▌     | 7841/17048 [26:14<25:03,  6.12it/s]

✅ 17d1fc3f-ce7f-4d13-a38f-5b91b742c974 ya está en inglés. Saltando...
🧐 Procesando 7831/17048 - 3d5fddbd-a8c7-4f5b-a9c4-f4823643cf34 | Idioma detectado: en
✅ 3d5fddbd-a8c7-4f5b-a9c4-f4823643cf34 ya está en inglés. Saltando...
🧐 Procesando 7832/17048 - d17fd8be-912c-4ab9-bdf0-69b8f804753b | Idioma detectado: en
✅ d17fd8be-912c-4ab9-bdf0-69b8f804753b ya está en inglés. Saltando...
🧐 Procesando 7833/17048 - d4026b8b-62f0-40ad-8eee-f24ea4ad8da6 | Idioma detectado: en
✅ d4026b8b-62f0-40ad-8eee-f24ea4ad8da6 ya está en inglés. Saltando...
🧐 Procesando 7834/17048 - 0bbcb443-3796-40f5-bbf4-f53ce693c122 | Idioma detectado: en
✅ 0bbcb443-3796-40f5-bbf4-f53ce693c122 ya está en inglés. Saltando...
🧐 Procesando 7835/17048 - 88f01b54-d6c0-4b37-94b0-c0c90fef0c3e | Idioma detectado: en
✅ 88f01b54-d6c0-4b37-94b0-c0c90fef0c3e ya está en inglés. Saltando...
🧐 Procesando 7836/17048 - 3bd9c902-f98f-44a7-814b-db9179058120 | Idioma detectado: en
✅ 3bd9c902-f98f-44a7-814b-db9179058120 ya está en inglés. Saltando...
🧐 Procesando 7837/17048 - bcdca018-4f54-4ee6-8fdb-4ff32f6486fe | Idioma detectado: en
✅ bcdca018-4f54-4ee6-8fdb-4ff32f6486fe ya está en inglés. Saltando...
🧐 Procesando 7838/17048 - cf3aff33-9bd7-4bff-a1d3-3f25bf807c25 | Idioma detectado: en
✅ cf3aff33-9bd7-4bff-a1d3-3f25bf807c25 ya está en inglés. Saltando...
🧐 Procesando 7839/17048 - 2d374dfa-86c0-4d06-acef-3115317925b9 | Idioma detectado: en
✅ 2d374dfa-86c0-4d06-acef-3115317925b9 ya está en inglés. Saltando...
🧐 Procesando 7840/17048 - b1107b33-0931-4e97-82c6-18cc03e08850 | Idioma detectado: es

🔄 Traduciendo canciones:  46%|████▌     | 7861/17048 [26:15<22:07,  6.92it/s]

✅ ebabd140-68bd-4ac6-8fef-6b11965a3654 ya está en inglés. Saltando...
🧐 Procesando 7851/17048 - bb41f8e9-fc6e-4af7-86dd-da14f3a0da46 | Idioma detectado: en
✅ bb41f8e9-fc6e-4af7-86dd-da14f3a0da46 ya está en inglés. Saltando...
🧐 Procesando 7852/17048 - 1d26ddaf-5037-42be-b09d-df52fac29889 | Idioma detectado: en
✅ 1d26ddaf-5037-42be-b09d-df52fac29889 ya está en inglés. Saltando...
🧐 Procesando 7853/17048 - d76d6521-413c-478e-85c6-fc63d58da0f5 | Idioma detectado: en
✅ d76d6521-413c-478e-85c6-fc63d58da0f5 ya está en inglés. Saltando...
🧐 Procesando 7854/17048 - 92a96210-d365-4659-9c99-0807264df5a2 | Idioma detectado: en
✅ 92a96210-d365-4659-9c99-0807264df5a2 ya está en inglés. Saltando...
🧐 Procesando 7855/17048 - 12b3d6a6-f172-442e-8466-e12592b8ae86 | Idioma detectado: en
✅ 12b3d6a6-f172-442e-8466-e12592b8ae86 ya está en inglés. Saltando...
🧐 Procesando 7856/17048 - 13e1e39e-455a-4e9e-b51d-5ecd1a045b2d | Idioma detectado: en
✅ 13e1e39e-455a-4e9e-b51d-5ecd1a045b2d ya está en inglés. Saltando...
🧐 Procesando 7857/17048 - d53e1612-cb9c-41d0-8ff6-43dc024a6cfa | Idioma detectado: en
✅ d53e1612-cb9c-41d0-8ff6-43dc024a6cfa ya está en inglés. Saltando...
🧐 Procesando 7858/17048 - 4e2c486b-270c-47b4-b214-17faf298352a | Idioma detectado: en
✅ 4e2c486b-270c-47b4-b214-17faf298352a ya está en inglés. Saltando...
🧐 Procesando 7859/17048 - 73a721c0-86b5-4f5e-aa71-6d28938f39e5 | Idioma detectado: en
✅ 73a721c0-86b5-4f5e-aa71-6d28938f39e5 ya está en inglés. Saltando...
🧐 Procesando 7860/17048 - 68bc71c6-23cf-42a4-b180-635a5c407d1c | Idioma detectado: so

🔄 Traduciendo canciones:  48%|████▊     | 8160/17048 [28:28<3:57:17,  1.60s/it]

✅ 35409ff9-0e0b-4f48-8042-0bd7fb903829 ya está en inglés. Saltando...
🧐 Procesando 8147/17048 - 61d91128-f480-4f82-87ca-14789765f785 | Idioma detectado: en
✅ 61d91128-f480-4f82-87ca-14789765f785 ya está en inglés. Saltando...
🧐 Procesando 8148/17048 - 47e1d115-2454-404b-a726-b9d293255772 | Idioma detectado: en
✅ 47e1d115-2454-404b-a726-b9d293255772 ya está en inglés. Saltando...
🧐 Procesando 8149/17048 - 38dd09c7-924a-4aae-8315-bd5de552b860 | Idioma detectado: en
✅ 38dd09c7-924a-4aae-8315-bd5de552b860 ya está en inglés. Saltando...
🧐 Procesando 8150/17048 - cf206326-bd64-4ba6-8dc8-a190c08ea24e | Idioma detectado: en
✅ cf206326-bd64-4ba6-8dc8-a190c08ea24e ya está en inglés. Saltando...
🧐 Procesando 8151/17048 - f2d45ef2-fce3-443b-ac76-b49464eb0763 | Idioma detectado: en
✅ f2d45ef2-fce3-443b-ac76-b49464eb0763 ya está en inglés. Saltando...
🧐 Procesando 8152/17048 - f51e1a1a-544e-4da6-a416-d58de7bec50a | Idioma detectado: fr
🧐 Procesando 8153/17048 - 9914dde5-df1a-45a2-81f0-8d54ae57fae2 | Idioma detectado: fr
🧐 Procesando 8154/17048 - 718faee6-e03d-4b3f-ac85-ec8bc2c03666 | Idioma detectado: fr
🧐 Procesando 8155/17048 - 63c31250-f9d2-4c3c-8892-01dddcdf79dd | Idioma detectado: fr
🧐 Procesando 8156/17048 - 28dff41f-852a-4c99-9713-2568f57ad772 | Idioma detectado: fr
🧐 Procesando 8157/17048 - 3d8ee0ab-e842-4b26-ae0e-21f4932bb59b | Idioma detectado: fr
🧐 Procesando 8158/17048 - 813076ee-eaad-4347-9b8a-b6e96186fd24 | Idioma detectado: fr
🧐 Procesando 8159/17048 - 30b07f3b-812b-4595-9f0d-a1c371635bf7 | Idioma detectado: fr
🧐 Procesando 8160/17048 - af59cdba-744d-48ba-9321-51539f86a3d0 | Idioma detectado: fr

🔄 Traduciendo canciones:  48%|████▊     | 8194/17048 [28:45<1:11:15,  2.07it/s]

🧐 Procesando 8190/17048 - ecccf67f-00f0-4d87-944e-04f531aef09d | Idioma detectado: en
✅ ecccf67f-00f0-4d87-944e-04f531aef09d ya está en inglés. Saltando...
🧐 Procesando 8191/17048 - ef70f717-a0be-42fe-b32c-c79796c39ff9 | Idioma detectado: en
✅ ef70f717-a0be-42fe-b32c-c79796c39ff9 ya está en inglés. Saltando...
🧐 Procesando 8192/17048 - a435b2a3-25dc-4714-ab42-ee167b45af70 | Idioma detectado: en
✅ a435b2a3-25dc-4714-ab42-ee167b45af70 ya está en inglés. Saltando...
🧐 Procesando 8193/17048 - 1a8fdbfd-a485-4572-bc55-6fd1deaed2c5 | Idioma detectado: es
🧐 Procesando 8194/17048 - 5d63ce39-fb65-4817-8e8e-937954995a5a | Idioma detectado: en
✅ 5d63ce39-fb65-4817-8e8e-937954995a5a ya está en inglés. Saltando...
🧐 Procesando 8195/17048 - 597fe7f8-9368-40ca-99fe-46f95bb83954 | Idioma detectado: en
✅ 597fe7f8-9368-40ca-99fe-46f95bb83954 ya está en inglés. Saltando...
🧐 Procesando 8196/17048 - dd7dbc38-836c-427b-8fb7-6b1d58322a81 | Idioma detectado: en
✅ dd7dbc38-836c-427b-8fb7-6b1d58322a81 ya está en inglés. Saltando...
🧐 Procesando 8197/17048 - 866ce68b-9655-4696-be8f-91d8d522453a | Idioma detectado: en
✅ 866ce68b-9655-4696-be8f-91d8d522453a ya está en inglés. Saltando...
🧐 Procesando 8198/17048 - af935d18-9d43-49ef-bbc3-de33ad083c65 | Idioma detectado: en
✅ af935d18-9d43-49ef-bbc3-de33ad083c65 ya está en inglés. Saltando...
🧐 Procesando 8199/17048 - 384091df-89df-49cb-a774-147083256870 | Idioma detectado: en
✅ 384091df-89df-49cb-a774-147083256870 ya está en inglés. Saltando...
🧐 Procesando 8200/17048 - 04075a8a-ae79-4ae6-a77a-883b2f324fe5 | Idioma detectado: de

🔄 Traduciendo canciones:  48%|████▊     | 8206/17048 [29:07<2:53:17,  1.18s/it]

✅ af935d18-9d43-49ef-bbc3-de33ad083c65 ya está en inglés. Saltando...
🧐 Procesando 8199/17048 - 384091df-89df-49cb-a774-147083256870 | Idioma detectado: en
✅ 384091df-89df-49cb-a774-147083256870 ya está en inglés. Saltando...
🧐 Procesando 8200/17048 - 04075a8a-ae79-4ae6-a77a-883b2f324fe5 | Idioma detectado: de
🧐 Procesando 8201/17048 - 59c4027f-9aec-4f1a-b713-e2773bd8fca0 | Idioma detectado: en
✅ 59c4027f-9aec-4f1a-b713-e2773bd8fca0 ya está en inglés. Saltando...
🧐 Procesando 8202/17048 - 01896fc1-2453-4d6a-9688-4a9e3ac00bec | Idioma detectado: fr
🧐 Procesando 8203/17048 - 6fe4d600-71cb-47d1-9c69-46aeb17fac17 | Idioma detectado: es
🧐 Procesando 8204/17048 - 83b8bafc-8d89-4cb5-bb6a-ed44becc91a7 | Idioma detectado: en
✅ 83b8bafc-8d89-4cb5-bb6a-ed44becc91a7 ya está en inglés. Saltando...
🧐 Procesando 8205/17048 - cbf525c1-7b4c-47a5-bba1-4663fe5bc855 | Idioma detectado: pt
🧐 Procesando 8206/17048 - 46717bff-51ff-47f5-b878-73f631c86b24 | Idioma detectado: en
✅ 46717bff-51ff-47f5-b878-73f631c86b24 ya está en inglés. Saltando...
🧐 Procesando 8207/17048 - 6809986c-0014-4af0-a441-e159d18fc5c5 | Idioma detectado: en
✅ 6809986c-0014-4af0-a441-e159d18fc5c5 ya está en inglés. Saltando...
🧐 Procesando 8208/17048 - 88d55c18-cfb7-4f24-b0ec-fba4d73e1996 | Idioma detectado: en
✅ 88d55c18-cfb7-4f24-b0ec-fba4d73e1996 ya está en inglés. Saltando...
🧐 Procesando 8209/17048 - 09d5f6fa-344c-4c98-ba7d-17e161e1196b | Idioma detectado: en
✅ 09d5f6fa-344c-4c98-ba7d-17e161e1196b ya está en inglés. Saltando...
🧐 Procesando 8210/17048 - f07fc560-d647-4428-ac9b-5f8861aa00b4 | Idioma detectado: pt

🔄 Traduciendo canciones:  48%|████▊     | 8214/17048 [29:32<6:33:19,  2.67s/it]

✅ 88d55c18-cfb7-4f24-b0ec-fba4d73e1996 ya está en inglés. Saltando...
🧐 Procesando 8209/17048 - 09d5f6fa-344c-4c98-ba7d-17e161e1196b | Idioma detectado: en
✅ 09d5f6fa-344c-4c98-ba7d-17e161e1196b ya está en inglés. Saltando...
🧐 Procesando 8210/17048 - f07fc560-d647-4428-ac9b-5f8861aa00b4 | Idioma detectado: pt
🧐 Procesando 8211/17048 - f65a307c-edaa-40bc-a623-17136dee4c5f | Idioma detectado: pt
🧐 Procesando 8212/17048 - bcc01635-56c8-4cbd-be5f-5f7636a375aa | Idioma detectado: pt
🧐 Procesando 8213/17048 - 4aee47dc-ee41-4cb2-acd5-ca54a40101cb | Idioma detectado: de
🧐 Procesando 8214/17048 - 779e3fb9-6da3-4fd3-9356-57999d3b2205 | Idioma detectado: en
✅ 779e3fb9-6da3-4fd3-9356-57999d3b2205 ya está en inglés. Saltando...
🧐 Procesando 8215/17048 - 6f0c9f10-cf59-47e4-b1ae-0170bb4a24ad | Idioma detectado: en
✅ 6f0c9f10-cf59-47e4-b1ae-0170bb4a24ad ya está en inglés. Saltando...
🧐 Procesando 8216/17048 - 25388c63-2a84-49eb-a577-d61bd1ace228 | Idioma detectado: en
✅ 25388c63-2a84-49eb-a577-d61bd1ace228 ya está en inglés. Saltando...
🧐 Procesando 8217/17048 - de8218fc-4d90-4d2d-b156-4cb67b0f1876 | Idioma detectado: en
✅ de8218fc-4d90-4d2d-b156-4cb67b0f1876 ya está en inglés. Saltando...
🧐 Procesando 8218/17048 - fa6e0d2e-d256-4ef8-9b94-73a32071161a | Idioma detectado: en
✅ fa6e0d2e-d256-4ef8-9b94-73a32071161a ya está en inglés. Saltando...
🧐 Procesando 8219/17048 - 27e65069-8a1b-4082-803f-1bee6f938dc2 | Idioma detectado: en
✅ 27e65069-8a1b-4082-803f-1bee6f938dc2 ya está en inglés. Saltando...
🧐 Procesando 8220/17048 - eae0fdc3-bfd1-4d4c-96fe-62465a7ecf68 | Idioma detectado: es

🔄 Traduciendo canciones:  48%|████▊     | 8251/17048 [30:00<2:12:50,  1.10it/s]

🧐 Procesando 8240/17048 - 4d08a37a-6e71-401c-ad54-dbe5a8ae919c | Idioma detectado: en
✅ 4d08a37a-6e71-401c-ad54-dbe5a8ae919c ya está en inglés. Saltando...
🧐 Procesando 8241/17048 - 5cf50495-d7ba-421a-893b-6c21142601a8 | Idioma detectado: en
✅ 5cf50495-d7ba-421a-893b-6c21142601a8 ya está en inglés. Saltando...
🧐 Procesando 8242/17048 - 3b079c2b-14ac-4959-b52d-ee45c7d6e6f4 | Idioma detectado: en
✅ 3b079c2b-14ac-4959-b52d-ee45c7d6e6f4 ya está en inglés. Saltando...
🧐 Procesando 8243/17048 - b0a264b1-632b-40e5-81d6-18d2e9702303 | Idioma detectado: en
✅ b0a264b1-632b-40e5-81d6-18d2e9702303 ya está en inglés. Saltando...
🧐 Procesando 8244/17048 - 2d903548-0881-4ab6-96eb-de07b0bf3e0e | Idioma detectado: en
✅ 2d903548-0881-4ab6-96eb-de07b0bf3e0e ya está en inglés. Saltando...
🧐 Procesando 8245/17048 - 28d0d4c3-f935-4a83-b18c-eddab06bfb47 | Idioma detectado: en
✅ 28d0d4c3-f935-4a83-b18c-eddab06bfb47 ya está en inglés. Saltando...
🧐 Procesando 8246/17048 - 5b62d6ef-a4d8-457a-a481-6b569dc88ed4 | Idioma detectado: en
✅ 5b62d6ef-a4d8-457a-a481-6b569dc88ed4 ya está en inglés. Saltando...
🧐 Procesando 8247/17048 - 9540ce66-1221-4677-89ae-0e967e1ed277 | Idioma detectado: en
✅ 9540ce66-1221-4677-89ae-0e967e1ed277 ya está en inglés. Saltando...
🧐 Procesando 8248/17048 - 99887f7d-5a7d-4532-9c41-bad205159e44 | Idioma detectado: de
🧐 Procesando 8249/17048 - cfbf0529-f88c-4386-9c32-c4b298307065 | Idioma detectado: en
✅ cfbf0529-f88c-4386-9c32-c4b298307065 ya está en inglés. Saltando...
🧐 Procesando 8250/17048 - 35c41e5b-b8e8-4942-8ec1-a3e7053590a5 | Idioma detectado: pt

🔄 Traduciendo canciones:  49%|████▊     | 8300/17048 [31:18<3:02:13,  1.25s/it]

✅ 01492b0a-d09d-4164-9a2d-84106c76aa3e ya está en inglés. Saltando...
🧐 Procesando 8288/17048 - baa43cdc-5d0f-4671-9ff9-8550943a11a5 | Idioma detectado: en
✅ baa43cdc-5d0f-4671-9ff9-8550943a11a5 ya está en inglés. Saltando...
🧐 Procesando 8289/17048 - 83c964fd-d6dd-4f54-ac39-a2e9e3af6829 | Idioma detectado: en
✅ 83c964fd-d6dd-4f54-ac39-a2e9e3af6829 ya está en inglés. Saltando...
🧐 Procesando 8290/17048 - 6da0210b-8245-4d3b-945a-1de724c5e0d0 | Idioma detectado: en
✅ 6da0210b-8245-4d3b-945a-1de724c5e0d0 ya está en inglés. Saltando...
🧐 Procesando 8291/17048 - e953662f-f470-4a7a-9c68-fbb23a5d385e | Idioma detectado: en
✅ e953662f-f470-4a7a-9c68-fbb23a5d385e ya está en inglés. Saltando...
🧐 Procesando 8292/17048 - 58470dfa-ebe7-48a0-a870-78766e91d1d3 | Idioma detectado: en
✅ 58470dfa-ebe7-48a0-a870-78766e91d1d3 ya está en inglés. Saltando...
🧐 Procesando 8293/17048 - 8ee5b278-355e-4471-b0da-fd66aae9820f | Idioma detectado: en
✅ 8ee5b278-355e-4471-b0da-fd66aae9820f ya está en inglés. Saltando...
🧐 Procesando 8294/17048 - e1b8b50b-739c-4918-b1b6-b2d8df78a7ef | Idioma detectado: fr
🧐 Procesando 8295/17048 - fb75d8c3-2a54-4743-bb36-199d2030476c | Idioma detectado: fr
🧐 Procesando 8296/17048 - c732cc2a-1b15-4b92-aa75-14291fd04410 | Idioma detectado: fr
🧐 Procesando 8297/17048 - b3123645-16ed-4894-b274-c207b24922ec | Idioma detectado: fr
🧐 Procesando 8298/17048 - 474f8404-ea3e-4a67-baa3-ca5419a839a2 | Idioma detectado: fr
🧐 Procesando 8299/17048 - 8ee94850-16fa-462d-8b54-f0caf3890da3 | Idioma detectado: fr
🧐 Procesando 8300/17048 - e70aaaff-edf2-4a0e-8ba1-c6d88f8ff29d | Idioma detectado: fr

🔄 Traduciendo canciones:  49%|████▊     | 8310/17048 [31:39<4:02:24,  1.66s/it]

✅ 58470dfa-ebe7-48a0-a870-78766e91d1d3 ya está en inglés. Saltando...
🧐 Procesando 8293/17048 - 8ee5b278-355e-4471-b0da-fd66aae9820f | Idioma detectado: en
✅ 8ee5b278-355e-4471-b0da-fd66aae9820f ya está en inglés. Saltando...
🧐 Procesando 8294/17048 - e1b8b50b-739c-4918-b1b6-b2d8df78a7ef | Idioma detectado: fr
🧐 Procesando 8295/17048 - fb75d8c3-2a54-4743-bb36-199d2030476c | Idioma detectado: fr
🧐 Procesando 8296/17048 - c732cc2a-1b15-4b92-aa75-14291fd04410 | Idioma detectado: fr
🧐 Procesando 8297/17048 - b3123645-16ed-4894-b274-c207b24922ec | Idioma detectado: fr
🧐 Procesando 8298/17048 - 474f8404-ea3e-4a67-baa3-ca5419a839a2 | Idioma detectado: fr
🧐 Procesando 8299/17048 - 8ee94850-16fa-462d-8b54-f0caf3890da3 | Idioma detectado: fr
🧐 Procesando 8300/17048 - e70aaaff-edf2-4a0e-8ba1-c6d88f8ff29d | Idioma detectado: fr
🧐 Procesando 8301/17048 - 242337e0-8932-487f-8fc2-ae3543edcbab | Idioma detectado: fr
🧐 Procesando 8302/17048 - 7d6943a3-1865-4fd5-a457-be84f3910275 | Idioma detectado: fr
🧐 Procesando 8303/17048 - d86e1ca5-04f7-410b-9260-1009887dfddd | Idioma detectado: fr
🧐 Procesando 8304/17048 - 668d991f-9bbc-4209-b129-7730e2c755d6 | Idioma detectado: fr
🧐 Procesando 8305/17048 - 63102035-87ed-4da0-ba3a-b139054b34ff | Idioma detectado: fr
🧐 Procesando 8306/17048 - b77aa170-be57-4f77-8ed1-d05da19cae5c | Idioma detectado: fr
🧐 Procesando 8307/17048 - 200e303b-db68-4b96-bae0-0b13075d8b5f | Idioma detectado: fr
🧐 Procesando 8308/17048 - 181b0e66-7d5a-4e1e-b17f-f73f16050ab7 | Idioma detectado: fr
🧐 Procesando 8309/17048 - 1fa1f1eb-46d3-42e7-96f4-9db099fdc103 | Idioma detectado: fr
🧐 Procesando 8310/17048 - acbc9fb2-4c90-4307-a860-8090ddf5d29e | Idioma detectado: fr

🔄 Traduciendo canciones:  49%|████▉     | 8320/17048 [31:59<4:05:06,  1.68s/it]

🧐 Procesando 8302/17048 - 7d6943a3-1865-4fd5-a457-be84f3910275 | Idioma detectado: fr
🧐 Procesando 8303/17048 - d86e1ca5-04f7-410b-9260-1009887dfddd | Idioma detectado: fr
🧐 Procesando 8304/17048 - 668d991f-9bbc-4209-b129-7730e2c755d6 | Idioma detectado: fr
🧐 Procesando 8305/17048 - 63102035-87ed-4da0-ba3a-b139054b34ff | Idioma detectado: fr
🧐 Procesando 8306/17048 - b77aa170-be57-4f77-8ed1-d05da19cae5c | Idioma detectado: fr
🧐 Procesando 8307/17048 - 200e303b-db68-4b96-bae0-0b13075d8b5f | Idioma detectado: fr
🧐 Procesando 8308/17048 - 181b0e66-7d5a-4e1e-b17f-f73f16050ab7 | Idioma detectado: fr
🧐 Procesando 8309/17048 - 1fa1f1eb-46d3-42e7-96f4-9db099fdc103 | Idioma detectado: fr
🧐 Procesando 8310/17048 - acbc9fb2-4c90-4307-a860-8090ddf5d29e | Idioma detectado: fr
🧐 Procesando 8311/17048 - 829fc556-321a-4710-a838-b369edb5fdb8 | Idioma detectado: fr
🧐 Procesando 8312/17048 - 48e0e291-c4b2-430c-94e0-0a3f4098a307 | Idioma detectado: fr
🧐 Procesando 8313/17048 - 0922abd2-b815-45ca-8450-26dd090c82c4 | Idioma detectado: fr
🧐 Procesando 8314/17048 - cee49048-1666-4456-8df4-a3539103e637 | Idioma detectado: fr
🧐 Procesando 8315/17048 - 396ad4a7-1394-4bf9-9c20-ed338c8cb330 | Idioma detectado: fr
🧐 Procesando 8316/17048 - bd5fa42c-0903-4f26-87cc-a6736232bdde | Idioma detectado: fr
🧐 Procesando 8317/17048 - eb4bd627-423a-47af-9f88-022bff91f174 | Idioma detectado: fr
🧐 Procesando 8318/17048 - cfbfb04e-ccfd-4316-a5eb-5e4daa670905 | Idioma detectado: en
✅ cfbfb04e-ccfd-4316-a5eb-5e4daa670905 ya está en inglés. Saltando...
🧐 Procesando 8319/17048 - 3e498404-5e9d-49a9-9502-422834995bae | Idioma detectado: fr
🧐 Procesando 8320/17048 - ce3f9e2a-fd11-4a12-9b9d-323220ffa844 | Idioma detectado: fr

🔄 Traduciendo canciones:  49%|████▉     | 8381/17048 [32:52<1:17:31,  1.86it/s]

✅ 5469e95d-4dd3-45df-beb8-46eecad78e2f ya está en inglés. Saltando...
🧐 Procesando 8370/17048 - b3caafda-756b-4e97-a27f-5762d1be644f | Idioma detectado: en
✅ b3caafda-756b-4e97-a27f-5762d1be644f ya está en inglés. Saltando...
🧐 Procesando 8371/17048 - faebc159-908f-4ef5-a479-37759e0ef4df | Idioma detectado: en
✅ faebc159-908f-4ef5-a479-37759e0ef4df ya está en inglés. Saltando...
🧐 Procesando 8372/17048 - 8f6f3bfc-de8e-4fd6-8588-0837abebfa36 | Idioma detectado: en
✅ 8f6f3bfc-de8e-4fd6-8588-0837abebfa36 ya está en inglés. Saltando...
🧐 Procesando 8373/17048 - 79e17e25-7b7d-4d2f-b506-837878c6b64d | Idioma detectado: fr
🧐 Procesando 8374/17048 - f7e755e2-0870-4a40-8558-6e40a21c3ee5 | Idioma detectado: en
✅ f7e755e2-0870-4a40-8558-6e40a21c3ee5 ya está en inglés. Saltando...
🧐 Procesando 8375/17048 - b7275e08-0d57-4479-b8d7-99a0bc181683 | Idioma detectado: pt
🧐 Procesando 8376/17048 - 8004f414-e4b5-47be-9b06-da0fe8301884 | Idioma detectado: en
✅ 8004f414-e4b5-47be-9b06-da0fe8301884 ya está en inglés. Saltando...
🧐 Procesando 8377/17048 - 902454f3-4439-4dd5-a1f7-f36f6e1a8c26 | Idioma detectado: en
✅ 902454f3-4439-4dd5-a1f7-f36f6e1a8c26 ya está en inglés. Saltando...
🧐 Procesando 8378/17048 - f313da5a-60a3-4fa2-8176-52a8a3f30cd1 | Idioma detectado: en
✅ f313da5a-60a3-4fa2-8176-52a8a3f30cd1 ya está en inglés. Saltando...
🧐 Procesando 8379/17048 - 3b7349f6-c550-4ac7-9388-a871920dc8b0 | Idioma detectado: en
✅ 3b7349f6-c550-4ac7-9388-a871920dc8b0 ya está en inglés. Saltando...
🧐 Procesando 8380/17048 - d6411256-c492-4668-92b2-aab469727972 | Idioma detectado: fr

🔄 Traduciendo canciones:  49%|████▉     | 8401/17048 [33:12<2:13:49,  1.08it/s]

✅ 02faa356-e098-4145-9514-e6a09bee403c ya está en inglés. Saltando...
🧐 Procesando 8390/17048 - 929d87b8-10d9-4342-964a-2fd31f7eaa7f | Idioma detectado: en
✅ 929d87b8-10d9-4342-964a-2fd31f7eaa7f ya está en inglés. Saltando...
🧐 Procesando 8391/17048 - 7dcd29c0-7933-4a44-88cf-6d4cf666260d | Idioma detectado: en
✅ 7dcd29c0-7933-4a44-88cf-6d4cf666260d ya está en inglés. Saltando...
🧐 Procesando 8392/17048 - a54194d0-6cc3-415c-a83c-e16226ed57e6 | Idioma detectado: en
✅ a54194d0-6cc3-415c-a83c-e16226ed57e6 ya está en inglés. Saltando...
🧐 Procesando 8393/17048 - d40b095a-92cb-4b93-bbf9-7750e6450aa1 | Idioma detectado: en
✅ d40b095a-92cb-4b93-bbf9-7750e6450aa1 ya está en inglés. Saltando...
🧐 Procesando 8394/17048 - 7496e490-d7a9-40c8-be4c-db56e19d15d9 | Idioma detectado: en
✅ 7496e490-d7a9-40c8-be4c-db56e19d15d9 ya está en inglés. Saltando...
🧐 Procesando 8395/17048 - 75748b28-5383-489b-8764-6d05c8988671 | Idioma detectado: en
✅ 75748b28-5383-489b-8764-6d05c8988671 ya está en inglés. Saltando...
🧐 Procesando 8396/17048 - f8980b74-d798-4e7d-aa38-c2985804a2d5 | Idioma detectado: en
✅ f8980b74-d798-4e7d-aa38-c2985804a2d5 ya está en inglés. Saltando...
🧐 Procesando 8397/17048 - f0102a04-d7e7-4512-b3d0-0f87aecd73d7 | Idioma detectado: en
✅ f0102a04-d7e7-4512-b3d0-0f87aecd73d7 ya está en inglés. Saltando...
🧐 Procesando 8398/17048 - 21424255-6317-4e6a-97f3-fa9ad46e0f11 | Idioma detectado: es
🧐 Procesando 8399/17048 - a62f6769-a0ac-48e0-a76a-2cc5e02d82c8 | Idioma detectado: es
🧐 Procesando 8400/17048 - 62646ac5-0039-4d65-9d77-30fe81778885 | Idioma detectado: es

🔄 Traduciendo canciones:  49%|████▉     | 8428/17048 [33:58<2:28:32,  1.03s/it]

✅ 631e7218-d4f2-40c0-b869-c597a963b55c ya está en inglés. Saltando...
🧐 Procesando 8420/17048 - 04f46f0a-485a-49f9-a464-fd02c36247d8 | Idioma detectado: en
✅ 04f46f0a-485a-49f9-a464-fd02c36247d8 ya está en inglés. Saltando...
🧐 Procesando 8421/17048 - f1669515-6424-41cf-b79c-05c3b85ca973 | Idioma detectado: en
✅ f1669515-6424-41cf-b79c-05c3b85ca973 ya está en inglés. Saltando...
🧐 Procesando 8422/17048 - 8ccf7136-3676-4fb4-91fd-5cac3b281908 | Idioma detectado: en
✅ 8ccf7136-3676-4fb4-91fd-5cac3b281908 ya está en inglés. Saltando...
🧐 Procesando 8423/17048 - 510450e5-3475-400d-aead-f075ebd4c3b9 | Idioma detectado: en
✅ 510450e5-3475-400d-aead-f075ebd4c3b9 ya está en inglés. Saltando...
🧐 Procesando 8424/17048 - 9ee4168f-cdc1-4032-bc61-8bbc615d31b2 | Idioma detectado: en
✅ 9ee4168f-cdc1-4032-bc61-8bbc615d31b2 ya está en inglés. Saltando...
🧐 Procesando 8425/17048 - 6f537331-0d12-4fb5-9d70-7215bfb0aa3d | Idioma detectado: en
✅ 6f537331-0d12-4fb5-9d70-7215bfb0aa3d ya está en inglés. Saltando...
🧐 Procesando 8426/17048 - c2ba513e-42db-4085-9ae7-e78245d6ce03 | Idioma detectado: de
🧐 Procesando 8427/17048 - 77e379c6-b888-47b8-9da8-a367d8dea4d8 | Idioma detectado: tl
🧐 Procesando 8428/17048 - fb1833f5-fa74-4fee-8857-043d4e7c74cb | Idioma detectado: en
✅ fb1833f5-fa74-4fee-8857-043d4e7c74cb ya está en inglés. Saltando...
🧐 Procesando 8429/17048 - c7d94cf6-d7c1-47df-a244-4611b8b04a31 | Idioma detectado: en
✅ c7d94cf6-d7c1-47df-a244-4611b8b04a31 ya está en inglés. Saltando...
🧐 Procesando 8430/17048 - 01cf4af6-a4ad-46b1-8dd3-538f5cd1a739 | Idioma detectado: de

🔄 Traduciendo canciones:  49%|████▉     | 8436/17048 [34:16<4:16:10,  1.78s/it]

🧐 Procesando 8428/17048 - fb1833f5-fa74-4fee-8857-043d4e7c74cb | Idioma detectado: en
✅ fb1833f5-fa74-4fee-8857-043d4e7c74cb ya está en inglés. Saltando...
🧐 Procesando 8429/17048 - c7d94cf6-d7c1-47df-a244-4611b8b04a31 | Idioma detectado: en
✅ c7d94cf6-d7c1-47df-a244-4611b8b04a31 ya está en inglés. Saltando...
🧐 Procesando 8430/17048 - 01cf4af6-a4ad-46b1-8dd3-538f5cd1a739 | Idioma detectado: de
🧐 Procesando 8431/17048 - 85204365-bda4-4e7f-8d56-a95f287f2c5c | Idioma detectado: en
✅ 85204365-bda4-4e7f-8d56-a95f287f2c5c ya está en inglés. Saltando...
🧐 Procesando 8432/17048 - cdeea68e-604b-4003-aa47-271fb5d7272a | Idioma detectado: de
🧐 Procesando 8433/17048 - 7d3b6262-9445-4e7a-9645-8476207fadf5 | Idioma detectado: de
🧐 Procesando 8434/17048 - 44c5958f-2b43-410e-b1be-15c1c196dcd8 | Idioma detectado: de
🧐 Procesando 8435/17048 - 7c5992c6-6f62-4fc4-8b5f-fcd7c15b8ef2 | Idioma detectado: de
🧐 Procesando 8436/17048 - 872cd63f-2c02-4bc0-83d3-57003daad2a3 | Idioma detectado: en
✅ 872cd63f-2c02-4bc0-83d3-57003daad2a3 ya está en inglés. Saltando...
🧐 Procesando 8437/17048 - 37b16d1e-13f0-4296-b9b2-bf98b11fc55f | Idioma detectado: en
✅ 37b16d1e-13f0-4296-b9b2-bf98b11fc55f ya está en inglés. Saltando...
🧐 Procesando 8438/17048 - b4ff1d81-9345-49b6-a3b3-ac0f75faf707 | Idioma detectado: en
✅ b4ff1d81-9345-49b6-a3b3-ac0f75faf707 ya está en inglés. Saltando...
🧐 Procesando 8439/17048 - a803cabc-c2fa-4e80-aac8-916bd2fe5e50 | Idioma detectado: en
✅ a803cabc-c2fa-4e80-aac8-916bd2fe5e50 ya está en inglés. Saltando...
🧐 Procesando 8440/17048 - b9c769dd-0812-4223-8565-89f179e9f2d1 | Idioma detectado: de

🔄 Traduciendo canciones:  50%|████▉     | 8451/17048 [35:08<13:57:10,  5.84s/it]

🧐 Procesando 8435/17048 - 7c5992c6-6f62-4fc4-8b5f-fcd7c15b8ef2 | Idioma detectado: de
🧐 Procesando 8436/17048 - 872cd63f-2c02-4bc0-83d3-57003daad2a3 | Idioma detectado: en
✅ 872cd63f-2c02-4bc0-83d3-57003daad2a3 ya está en inglés. Saltando...
🧐 Procesando 8437/17048 - 37b16d1e-13f0-4296-b9b2-bf98b11fc55f | Idioma detectado: en
✅ 37b16d1e-13f0-4296-b9b2-bf98b11fc55f ya está en inglés. Saltando...
🧐 Procesando 8438/17048 - b4ff1d81-9345-49b6-a3b3-ac0f75faf707 | Idioma detectado: en
✅ b4ff1d81-9345-49b6-a3b3-ac0f75faf707 ya está en inglés. Saltando...
🧐 Procesando 8439/17048 - a803cabc-c2fa-4e80-aac8-916bd2fe5e50 | Idioma detectado: en
✅ a803cabc-c2fa-4e80-aac8-916bd2fe5e50 ya está en inglés. Saltando...
🧐 Procesando 8440/17048 - b9c769dd-0812-4223-8565-89f179e9f2d1 | Idioma detectado: de
🧐 Procesando 8441/17048 - dfa9f9f5-0c8e-40c7-880a-58d22c8780f5 | Idioma detectado: de
🧐 Procesando 8442/17048 - 2e05ce83-1f2e-48b2-b4fc-8ab620440ae0 | Idioma detectado: de
🧐 Procesando 8443/17048 - 22bc4cdc-a19b-472f-b308-4c03e4b95811 | Idioma detectado: de
🧐 Procesando 8444/17048 - 8b7d55a1-bb0f-481c-bdeb-c3d5e6f61a2e | Idioma detectado: de
🧐 Procesando 8445/17048 - 239794fb-a755-4612-91b1-2de7e622c016 | Idioma detectado: de
🧐 Procesando 8446/17048 - c5999579-00f2-4014-96b1-e9daffe9eb9f | Idioma detectado: de
🧐 Procesando 8447/17048 - 3e7ba1dc-acbb-445e-9053-07e742a59b7a | Idioma detectado: de
🧐 Procesando 8448/17048 - 3902b701-e9fd-400a-8a89-cebb982fa61c | Idioma detectado: de
🧐 Procesando 8449/17048 - 8ebc65b7-4a9d-4ee1-a943-3ede24e47fac | Idioma detectado: de
🧐 Procesando 8450/17048 - a0b6cd2b-8e30-4957-bc70-dcf44c7abe5d | Idioma detectado: de

🔄 Traduciendo canciones:  50%|█████     | 8601/17048 [36:35<2:54:54,  1.24s/it]

✅ af331173-5e2e-4f7c-8122-dc6c45ba4fee ya está en inglés. Saltando...
🧐 Procesando 8589/17048 - 93f292df-a60a-4af8-adb1-639ff557eb01 | Idioma detectado: en
✅ 93f292df-a60a-4af8-adb1-639ff557eb01 ya está en inglés. Saltando...
🧐 Procesando 8590/17048 - 5198d609-13dd-4f80-a49b-21903e7dc7a2 | Idioma detectado: en
✅ 5198d609-13dd-4f80-a49b-21903e7dc7a2 ya está en inglés. Saltando...
🧐 Procesando 8591/17048 - 5933b73d-0cb1-472a-9c8b-d22c18843b61 | Idioma detectado: en
✅ 5933b73d-0cb1-472a-9c8b-d22c18843b61 ya está en inglés. Saltando...
🧐 Procesando 8592/17048 - cd8b8f36-b055-4216-96da-9d5c057b8b59 | Idioma detectado: no
🧐 Procesando 8593/17048 - c1b2b7b1-a53e-4e8e-bab5-db50ddfcd697 | Idioma detectado: en
✅ c1b2b7b1-a53e-4e8e-bab5-db50ddfcd697 ya está en inglés. Saltando...
🧐 Procesando 8594/17048 - c60494c5-f223-46c4-873f-42b81e3f9a30 | Idioma detectado: en
✅ c60494c5-f223-46c4-873f-42b81e3f9a30 ya está en inglés. Saltando...
🧐 Procesando 8595/17048 - a4fc03ec-c723-4d92-8b90-981c41aecdca | Idioma detectado: es
🧐 Procesando 8596/17048 - 3aa16ddd-36da-402b-84f0-bf12dc1b1f52 | Idioma detectado: en
✅ 3aa16ddd-36da-402b-84f0-bf12dc1b1f52 ya está en inglés. Saltando...
🧐 Procesando 8597/17048 - a38a56b5-e958-4ed5-9c07-8f544e270569 | Idioma detectado: en
✅ a38a56b5-e958-4ed5-9c07-8f544e270569 ya está en inglés. Saltando...
🧐 Procesando 8598/17048 - 6a401910-b993-4db4-97e4-6aabd4ee9278 | Idioma detectado: es
🧐 Procesando 8599/17048 - f423f9ba-3908-4726-94a6-d0e88b5f18ec | Idioma detectado: es
🧐 Procesando 8600/17048 - 9e515fc0-6372-4553-8dc0-dd876e65ddd0 | Idioma detectado: es

🔄 Traduciendo canciones:  51%|█████     | 8610/17048 [36:56<4:57:37,  2.12s/it]

🧐 Procesando 8594/17048 - c60494c5-f223-46c4-873f-42b81e3f9a30 | Idioma detectado: en
✅ c60494c5-f223-46c4-873f-42b81e3f9a30 ya está en inglés. Saltando...
🧐 Procesando 8595/17048 - a4fc03ec-c723-4d92-8b90-981c41aecdca | Idioma detectado: es
🧐 Procesando 8596/17048 - 3aa16ddd-36da-402b-84f0-bf12dc1b1f52 | Idioma detectado: en
✅ 3aa16ddd-36da-402b-84f0-bf12dc1b1f52 ya está en inglés. Saltando...
🧐 Procesando 8597/17048 - a38a56b5-e958-4ed5-9c07-8f544e270569 | Idioma detectado: en
✅ a38a56b5-e958-4ed5-9c07-8f544e270569 ya está en inglés. Saltando...
🧐 Procesando 8598/17048 - 6a401910-b993-4db4-97e4-6aabd4ee9278 | Idioma detectado: es
🧐 Procesando 8599/17048 - f423f9ba-3908-4726-94a6-d0e88b5f18ec | Idioma detectado: es
🧐 Procesando 8600/17048 - 9e515fc0-6372-4553-8dc0-dd876e65ddd0 | Idioma detectado: es
🧐 Procesando 8601/17048 - dab46f51-53f9-449b-b4eb-b5fbc4c1005a | Idioma detectado: es
🧐 Procesando 8602/17048 - 77d9edd0-b313-4eb7-961a-6f9bb3d7f194 | Idioma detectado: es
🧐 Procesando 8603/17048 - 25b0c413-b69e-49b6-b091-686028225af8 | Idioma detectado: es
🧐 Procesando 8604/17048 - 4a61790a-dd82-48fe-bb51-b7d41855161b | Idioma detectado: es
🧐 Procesando 8605/17048 - c1912f9e-7124-4eac-9e03-282f18b80ae3 | Idioma detectado: es
🧐 Procesando 8606/17048 - 00b2aedd-e224-44b4-bbbe-c3d72bbe9cdb | Idioma detectado: es
🧐 Procesando 8607/17048 - 2c3cff71-79ec-408e-9ea5-15276a1aabb3 | Idioma detectado: es
🧐 Procesando 8608/17048 - d16d9f98-6671-4b86-9254-6bfedb0b59a8 | Idioma detectado: es
🧐 Procesando 8609/17048 - f078b980-b464-4c09-bd0a-10da122299a5 | Idioma detectado: es
🧐 Procesando 8610/17048 - 514cadc7-400b-464d-af1f-839e4f6c570e | Idioma detectado: es

🔄 Traduciendo canciones:  56%|█████▌    | 9470/17048 [39:21<45:05,  2.80it/s]

✅ 902886fb-4b78-48fe-acf8-5156c2ac375a ya está en inglés. Saltando...
🧐 Procesando 9459/17048 - 8b6df659-b96a-4f0e-bac5-9aac40bfc41c | Idioma detectado: en
✅ 8b6df659-b96a-4f0e-bac5-9aac40bfc41c ya está en inglés. Saltando...
🧐 Procesando 9460/17048 - 18c73e55-ebb6-4ab5-9399-a0b9f8dac31e | Idioma detectado: en
✅ 18c73e55-ebb6-4ab5-9399-a0b9f8dac31e ya está en inglés. Saltando...
🧐 Procesando 9461/17048 - e74c278c-968a-4d5b-a0e9-32f1128c205d | Idioma detectado: en
✅ e74c278c-968a-4d5b-a0e9-32f1128c205d ya está en inglés. Saltando...
🧐 Procesando 9462/17048 - 120c8cd0-d917-4f3f-a897-36eae398dfd7 | Idioma detectado: en
✅ 120c8cd0-d917-4f3f-a897-36eae398dfd7 ya está en inglés. Saltando...
🧐 Procesando 9463/17048 - d48a6f5e-8934-4341-928a-d385349e5a59 | Idioma detectado: en
✅ d48a6f5e-8934-4341-928a-d385349e5a59 ya está en inglés. Saltando...
🧐 Procesando 9464/17048 - 26646fbd-14b8-4662-8a4f-de088504bd76 | Idioma detectado: fr
🧐 Procesando 9465/17048 - 37e96a53-143b-4d1c-8768-a2521dc96450 | Idioma detectado: en
✅ 37e96a53-143b-4d1c-8768-a2521dc96450 ya está en inglés. Saltando...
🧐 Procesando 9466/17048 - fff28ac0-09ca-4085-a949-fdae983c3637 | Idioma detectado: fr
🧐 Procesando 9467/17048 - 28ba29c3-3a60-4148-90e7-c9dbb9e2c40a | Idioma detectado: en
✅ 28ba29c3-3a60-4148-90e7-c9dbb9e2c40a ya está en inglés. Saltando...
🧐 Procesando 9468/17048 - 674c2761-f172-4edf-a930-fed07f34518c | Idioma detectado: fr
🧐 Procesando 9469/17048 - f7e5884d-da08-4c1f-a2ec-887d49bc98af | Idioma detectado: fr
🧐 Procesando 9470/17048 - 52daeedd-f667-4d48-aaf8-b1baefac4449 | Idioma detectado: fr

🔄 Traduciendo canciones:  56%|█████▌    | 9541/17048 [41:00<1:32:34,  1.35it/s]

🧐 Procesando 9529/17048 - aa17674c-84a7-4467-bcfb-f3db5cdc75cb | Idioma detectado: en
✅ aa17674c-84a7-4467-bcfb-f3db5cdc75cb ya está en inglés. Saltando...
🧐 Procesando 9530/17048 - ed5d7c41-764e-496e-9d9d-1af503f5c6e6 | Idioma detectado: en
✅ ed5d7c41-764e-496e-9d9d-1af503f5c6e6 ya está en inglés. Saltando...
🧐 Procesando 9531/17048 - 627d9bba-a9ce-4f0b-ab24-0eb31ec43f93 | Idioma detectado: en
✅ 627d9bba-a9ce-4f0b-ab24-0eb31ec43f93 ya está en inglés. Saltando...
🧐 Procesando 9532/17048 - dbf48cae-1dcd-4cad-8bfb-ca3aa8752090 | Idioma detectado: en
✅ dbf48cae-1dcd-4cad-8bfb-ca3aa8752090 ya está en inglés. Saltando...
🧐 Procesando 9533/17048 - 17a936a9-8af3-4ef7-b176-7c1d9f3ad306 | Idioma detectado: en
✅ 17a936a9-8af3-4ef7-b176-7c1d9f3ad306 ya está en inglés. Saltando...
🧐 Procesando 9534/17048 - bd7be32b-3d63-46a1-8d75-27bf9e1dea39 | Idioma detectado: en
✅ bd7be32b-3d63-46a1-8d75-27bf9e1dea39 ya está en inglés. Saltando...
🧐 Procesando 9535/17048 - 86b0dd21-b148-4e72-88ba-330195222d2e | Idioma detectado: en
✅ 86b0dd21-b148-4e72-88ba-330195222d2e ya está en inglés. Saltando...
🧐 Procesando 9536/17048 - bbcc5042-2f03-406c-9ef7-43f800ac655e | Idioma detectado: en
✅ bbcc5042-2f03-406c-9ef7-43f800ac655e ya está en inglés. Saltando...
🧐 Procesando 9537/17048 - 4220b01d-5a88-400e-8c58-0a5c63eb480b | Idioma detectado: da
🧐 Procesando 9538/17048 - 276d50f9-efc2-449c-a41c-2c6f8f32e091 | Idioma detectado: pl
🧐 Procesando 9539/17048 - 71cec155-1796-4380-b070-7e02a6ec1ece | Idioma detectado: pl
🧐 Procesando 9540/17048 - cd87ba2b-9211-4d47-ac2b-3c368ab18154 | Idioma detectado: pl

🔄 Traduciendo canciones:  57%|█████▋    | 9661/17048 [42:38<2:08:44,  1.05s/it]

🧐 Procesando 9649/17048 - 2b10967e-a788-4db8-844f-fe10706ba193 | Idioma detectado: en
✅ 2b10967e-a788-4db8-844f-fe10706ba193 ya está en inglés. Saltando...
🧐 Procesando 9650/17048 - db47e721-d3d1-466d-b860-43a9a08440a2 | Idioma detectado: en
✅ db47e721-d3d1-466d-b860-43a9a08440a2 ya está en inglés. Saltando...
🧐 Procesando 9651/17048 - 4a4f06e8-f61b-49b2-969c-531a8aa5471b | Idioma detectado: en
✅ 4a4f06e8-f61b-49b2-969c-531a8aa5471b ya está en inglés. Saltando...
🧐 Procesando 9652/17048 - f3adf97c-0038-4c5f-90c0-7a029dc779ec | Idioma detectado: en
✅ f3adf97c-0038-4c5f-90c0-7a029dc779ec ya está en inglés. Saltando...
🧐 Procesando 9653/17048 - 7903cb6c-2402-4cab-afd9-9d9ae5482a7a | Idioma detectado: en
✅ 7903cb6c-2402-4cab-afd9-9d9ae5482a7a ya está en inglés. Saltando...
🧐 Procesando 9654/17048 - 6b056eb6-0b16-488b-bb16-2beceb092bef | Idioma detectado: en
✅ 6b056eb6-0b16-488b-bb16-2beceb092bef ya está en inglés. Saltando...
🧐 Procesando 9655/17048 - 3858e65f-eb32-45ea-ba1d-368ef637375f | Idioma detectado: fr
🧐 Procesando 9656/17048 - 0b94a779-b961-4f7a-9198-f4486ce4132a | Idioma detectado: fr
🧐 Procesando 9657/17048 - 32f7d317-a0f8-409e-8acd-b494310e3904 | Idioma detectado: en
✅ 32f7d317-a0f8-409e-8acd-b494310e3904 ya está en inglés. Saltando...
🧐 Procesando 9658/17048 - 6300c600-373b-457d-b8a7-cf3c5f430a24 | Idioma detectado: en
✅ 6300c600-373b-457d-b8a7-cf3c5f430a24 ya está en inglés. Saltando...
🧐 Procesando 9659/17048 - bbc5d3e1-fd3d-495e-a55d-bca4155b2e80 | Idioma detectado: fr
🧐 Procesando 9660/17048 - cbdb6dd1-cd72-490a-9303-2607510435f4 | Idioma detectado: pl

🔄 Traduciendo canciones:  57%|█████▋    | 9670/17048 [43:21<8:24:04,  4.10s/it]

🧐 Procesando 9656/17048 - 0b94a779-b961-4f7a-9198-f4486ce4132a | Idioma detectado: fr
🧐 Procesando 9657/17048 - 32f7d317-a0f8-409e-8acd-b494310e3904 | Idioma detectado: en
✅ 32f7d317-a0f8-409e-8acd-b494310e3904 ya está en inglés. Saltando...
🧐 Procesando 9658/17048 - 6300c600-373b-457d-b8a7-cf3c5f430a24 | Idioma detectado: en
✅ 6300c600-373b-457d-b8a7-cf3c5f430a24 ya está en inglés. Saltando...
🧐 Procesando 9659/17048 - bbc5d3e1-fd3d-495e-a55d-bca4155b2e80 | Idioma detectado: fr
🧐 Procesando 9660/17048 - cbdb6dd1-cd72-490a-9303-2607510435f4 | Idioma detectado: pl
🧐 Procesando 9661/17048 - 38020893-9cd1-443e-a303-968438440554 | Idioma detectado: de
🧐 Procesando 9662/17048 - d1d8ccd5-fc22-4676-94e0-7cc14ba94073 | Idioma detectado: en
✅ d1d8ccd5-fc22-4676-94e0-7cc14ba94073 ya está en inglés. Saltando...
🧐 Procesando 9663/17048 - 93f57fda-17ba-4e7f-a5c4-df7776fdfab5 | Idioma detectado: en
✅ 93f57fda-17ba-4e7f-a5c4-df7776fdfab5 ya está en inglés. Saltando...
🧐 Procesando 9664/17048 - 5312e1ae-02cf-4506-be4a-c9cb36c067b1 | Idioma detectado: en
✅ 5312e1ae-02cf-4506-be4a-c9cb36c067b1 ya está en inglés. Saltando...
🧐 Procesando 9665/17048 - b71095f9-05ad-4158-9515-f1abf52fd385 | Idioma detectado: de
🧐 Procesando 9666/17048 - 5b098921-1be6-4255-8609-7fa7a8e845c4 | Idioma detectado: fr
🧐 Procesando 9667/17048 - 28486145-74e0-467f-9300-f1d6bfd17883 | Idioma detectado: fr
🧐 Procesando 9668/17048 - 5337eb0c-2b41-4847-912c-58c65cc142e6 | Idioma detectado: fr
🧐 Procesando 9669/17048 - 044a32de-64ee-4c0b-a665-63c362ba9fe9 | Idioma detectado: fr
🧐 Procesando 9670/17048 - 7a8b3580-f4cb-45ff-97a2-1d6b55215a8a | Idioma detectado: fr

🔄 Traduciendo canciones:  57%|█████▋    | 9731/17048 [45:37<8:16:29,  4.07s/it]

🧐 Procesando 9717/17048 - ad378206-0067-466d-8c22-c8ac9c1ef974 | Idioma detectado: en
✅ ad378206-0067-466d-8c22-c8ac9c1ef974 ya está en inglés. Saltando...
🧐 Procesando 9718/17048 - 21fed04f-ae2e-496d-98cf-b59421fd22dd | Idioma detectado: en
✅ 21fed04f-ae2e-496d-98cf-b59421fd22dd ya está en inglés. Saltando...
🧐 Procesando 9719/17048 - 0cbfa7d1-fa44-42a6-8b3a-3970e1f8853b | Idioma detectado: en
✅ 0cbfa7d1-fa44-42a6-8b3a-3970e1f8853b ya está en inglés. Saltando...
🧐 Procesando 9720/17048 - b7459efb-5f4c-4e8f-8120-7099a996a33e | Idioma detectado: en
✅ b7459efb-5f4c-4e8f-8120-7099a996a33e ya está en inglés. Saltando...
🧐 Procesando 9721/17048 - a6db8c79-c2f3-4340-aba8-adcc55922237 | Idioma detectado: en
✅ a6db8c79-c2f3-4340-aba8-adcc55922237 ya está en inglés. Saltando...
🧐 Procesando 9722/17048 - 11d3c332-b615-47a5-9d9e-0d87b7e37ddc | Idioma detectado: fr
🧐 Procesando 9723/17048 - 7dcd680c-6266-4704-a17e-ce1b91c593fb | Idioma detectado: fr
🧐 Procesando 9724/17048 - f2d2b26b-d6d5-43d9-8c7c-6b16b92b9f65 | Idioma detectado: es
🧐 Procesando 9725/17048 - d2732306-536f-4af6-9a3a-71e30ffc541f | Idioma detectado: fr
🧐 Procesando 9726/17048 - 636c120f-fe32-44ee-b36e-d6c7441772b0 | Idioma detectado: fr
🧐 Procesando 9727/17048 - c325f6fb-57a3-4606-bcf0-edf44ac999e1 | Idioma detectado: fr
🧐 Procesando 9728/17048 - 78666ba1-bebe-48e8-9caa-25fd4c1595cf | Idioma detectado: en
✅ 78666ba1-bebe-48e8-9caa-25fd4c1595cf ya está en inglés. Saltando...
🧐 Procesando 9729/17048 - 3475d80e-d117-4e70-995b-c750b8b01971 | Idioma detectado: fr
🧐 Procesando 9730/17048 - 3fe368e8-2f3e-49bc-8e74-ef59823ae1bf | Idioma detectado: fr

🔄 Traduciendo canciones:  57%|█████▋    | 9740/17048 [46:13<8:32:11,  4.21s/it]

🧐 Procesando 9722/17048 - 11d3c332-b615-47a5-9d9e-0d87b7e37ddc | Idioma detectado: fr
🧐 Procesando 9723/17048 - 7dcd680c-6266-4704-a17e-ce1b91c593fb | Idioma detectado: fr
🧐 Procesando 9724/17048 - f2d2b26b-d6d5-43d9-8c7c-6b16b92b9f65 | Idioma detectado: es
🧐 Procesando 9725/17048 - d2732306-536f-4af6-9a3a-71e30ffc541f | Idioma detectado: fr
🧐 Procesando 9726/17048 - 636c120f-fe32-44ee-b36e-d6c7441772b0 | Idioma detectado: fr
🧐 Procesando 9727/17048 - c325f6fb-57a3-4606-bcf0-edf44ac999e1 | Idioma detectado: fr
🧐 Procesando 9728/17048 - 78666ba1-bebe-48e8-9caa-25fd4c1595cf | Idioma detectado: en
✅ 78666ba1-bebe-48e8-9caa-25fd4c1595cf ya está en inglés. Saltando...
🧐 Procesando 9729/17048 - 3475d80e-d117-4e70-995b-c750b8b01971 | Idioma detectado: fr
🧐 Procesando 9730/17048 - 3fe368e8-2f3e-49bc-8e74-ef59823ae1bf | Idioma detectado: fr
🧐 Procesando 9731/17048 - 01111f9b-c914-4eee-802e-0b11d84930f3 | Idioma detectado: fr
🧐 Procesando 9732/17048 - 80e5892c-849a-49e8-bd4f-dc31026b9655 | Idioma detectado: fr
🧐 Procesando 9733/17048 - 2e5d4cf2-ec92-451d-9928-f3f97f772ceb | Idioma detectado: fr
🧐 Procesando 9734/17048 - 42a57504-be1b-46d6-ad3a-20e82e246479 | Idioma detectado: fr
🧐 Procesando 9735/17048 - 1538c59f-f2e1-4f58-8ed0-96981a221556 | Idioma detectado: fr
🧐 Procesando 9736/17048 - 5a403b66-5c9d-4097-985a-d60d93a61652 | Idioma detectado: fr
🧐 Procesando 9737/17048 - 761d2231-77f2-4689-8538-237d0c2eb94b | Idioma detectado: fr
🧐 Procesando 9738/17048 - 3017ca79-bad5-4382-91de-895569ddc1ef | Idioma detectado: fr
🧐 Procesando 9739/17048 - f4f618d0-dd29-4671-b925-f57b89cd2946 | Idioma detectado: fr
🧐 Procesando 9740/17048 - b496a48a-2f68-4b19-aae3-9443634f1fab | Idioma detectado: fr

🔄 Traduciendo canciones:  57%|█████▋    | 9760/17048 [47:00<4:57:08,  2.45s/it]

🧐 Procesando 9748/17048 - 4ae0d9f1-91e5-48d9-912d-6751d59a4376 | Idioma detectado: fr
🧐 Procesando 9749/17048 - a2722303-ead2-47d6-92fe-21d0b6493305 | Idioma detectado: en
✅ a2722303-ead2-47d6-92fe-21d0b6493305 ya está en inglés. Saltando...
🧐 Procesando 9750/17048 - 1e329d34-6b2b-4cc9-a968-7812f4bd401b | Idioma detectado: en
✅ 1e329d34-6b2b-4cc9-a968-7812f4bd401b ya está en inglés. Saltando...
🧐 Procesando 9751/17048 - 7dfa1830-6e09-4497-9483-449aa73240b6 | Idioma detectado: en
✅ 7dfa1830-6e09-4497-9483-449aa73240b6 ya está en inglés. Saltando...
🧐 Procesando 9752/17048 - 4811aceb-6f3b-44ad-b55e-0144febce872 | Idioma detectado: en
✅ 4811aceb-6f3b-44ad-b55e-0144febce872 ya está en inglés. Saltando...
🧐 Procesando 9753/17048 - 693e29b1-d75b-467b-94fd-dc479991986e | Idioma detectado: en
✅ 693e29b1-d75b-467b-94fd-dc479991986e ya está en inglés. Saltando...
🧐 Procesando 9754/17048 - d59a8263-d95b-40f2-bbdf-701b138259fd | Idioma detectado: en
✅ d59a8263-d95b-40f2-bbdf-701b138259fd ya está en inglés. Saltando...
🧐 Procesando 9755/17048 - 7fb36ab1-1274-4087-97d6-9cfddcc94fdc | Idioma detectado: en
✅ 7fb36ab1-1274-4087-97d6-9cfddcc94fdc ya está en inglés. Saltando...
🧐 Procesando 9756/17048 - 69152c37-b32a-4635-b209-32bb3fe4ae64 | Idioma detectado: fr
🧐 Procesando 9757/17048 - f99629c2-2121-4dc5-85a4-38ac9b6640c9 | Idioma detectado: fr
🧐 Procesando 9758/17048 - 6b94041d-554c-4e70-8b71-d2110b8460e5 | Idioma detectado: fr
🧐 Procesando 9759/17048 - 29b782f9-1023-4b83-999a-c1012a6c46ab | Idioma detectado: fr
🧐 Procesando 9760/17048 - a678b96f-e6cc-494b-a458-d7da2f77f078 | Idioma detectado: fr

🔄 Traduciendo canciones:  57%|█████▋    | 9762/17048 [47:08<5:54:31,  2.92s/it]

🧐 Procesando 9759/17048 - 29b782f9-1023-4b83-999a-c1012a6c46ab | Idioma detectado: fr
🧐 Procesando 9760/17048 - a678b96f-e6cc-494b-a458-d7da2f77f078 | Idioma detectado: fr
🧐 Procesando 9761/17048 - ed527648-990d-46d3-a268-7fabf70144da | Idioma detectado: fr
🧐 Procesando 9762/17048 - 93d304a1-570a-40b5-b70d-99a924e12fcf | Idioma detectado: en
✅ 93d304a1-570a-40b5-b70d-99a924e12fcf ya está en inglés. Saltando...
🧐 Procesando 9763/17048 - bfac0121-f5bb-49ab-88a9-4eaee9bd9cc1 | Idioma detectado: en
✅ bfac0121-f5bb-49ab-88a9-4eaee9bd9cc1 ya está en inglés. Saltando...
🧐 Procesando 9764/17048 - e8a12bd2-af5a-4a81-ac5f-c77e0f1f9881 | Idioma detectado: en
✅ e8a12bd2-af5a-4a81-ac5f-c77e0f1f9881 ya está en inglés. Saltando...
🧐 Procesando 9765/17048 - cd327cf8-871a-42dc-a8b3-a0759bed4576 | Idioma detectado: en
✅ cd327cf8-871a-42dc-a8b3-a0759bed4576 ya está en inglés. Saltando...
🧐 Procesando 9766/17048 - 8bb93227-5edf-4db9-9f3a-3ec4451172b6 | Idioma detectado: en
✅ 8bb93227-5edf-4db9-9f3a-3ec4451172b6 ya está en inglés. Saltando...
🧐 Procesando 9767/17048 - 6795ec39-2dba-4eb3-b803-899d2b535c53 | Idioma detectado: en
✅ 6795ec39-2dba-4eb3-b803-899d2b535c53 ya está en inglés. Saltando...
🧐 Procesando 9768/17048 - 33b55cfb-f9d3-4243-8afe-b2e0daa2bcc2 | Idioma detectado: en
✅ 33b55cfb-f9d3-4243-8afe-b2e0daa2bcc2 ya está en inglés. Saltando...
🧐 Procesando 9769/17048 - b4415f7a-f5bb-4f39-8a8a-d9ad449662da | Idioma detectado: en
✅ b4415f7a-f5bb-4f39-8a8a-d9ad449662da ya está en inglés. Saltando...
🧐 Procesando 9770/17048 - 25f4cf2d-a0c0-4b11-a88e-cee7bb1c9b5b | Idioma detectado: fr

🔄 Traduciendo canciones:  59%|█████▉    | 10058/17048 [48:29<15:11,  7.67it/s]

✅ 52ba20a9-0261-4c9a-bcd2-78041fa33fa2 ya está en inglés. Saltando...
🧐 Procesando 10071/17048 - a3dc2a63-6568-4eeb-93fb-ac3656318f13 | Idioma detectado: en
✅ a3dc2a63-6568-4eeb-93fb-ac3656318f13 ya está en inglés. Saltando...
🧐 Procesando 10072/17048 - 1fe74b36-f81d-4e66-9667-fb4abe8a186a | Idioma detectado: en
✅ 1fe74b36-f81d-4e66-9667-fb4abe8a186a ya está en inglés. Saltando...
🧐 Procesando 10073/17048 - 074c1daa-1047-4e2c-af96-7afbdb198cab | Idioma detectado: en
✅ 074c1daa-1047-4e2c-af96-7afbdb198cab ya está en inglés. Saltando...
🧐 Procesando 10074/17048 - 3be0465a-8671-44ed-ab80-c6edc5e4f041 | Idioma detectado: en
✅ 3be0465a-8671-44ed-ab80-c6edc5e4f041 ya está en inglés. Saltando...
🧐 Procesando 10075/17048 - 2602896c-1200-4ebc-a0b5-7eb0c53301bf | Idioma detectado: en
✅ 2602896c-1200-4ebc-a0b5-7eb0c53301bf ya está en inglés. Saltando...
🧐 Procesando 10076/17048 - 082bc159-d809-46bc-a2e3-31f9ed6433d6 | Idioma detectado: en
✅ 082bc159-d809-46bc-a2e3-31f9ed6433d6 ya está en inglés. Saltando...
🧐 Procesando 10077/17048 - c640f775-4ada-494d-a5e0-b621d10e44e7 | Idioma detectado: en
✅ c640f775-4ada-494d-a5e0-b621d10e44e7 ya está en inglés. Saltando...
🧐 Procesando 10078/17048 - 80bbdb6c-fe1a-4d12-92df-95bf2626fa94 | Idioma detectado: en
✅ 80bbdb6c-fe1a-4d12-92df-95bf2626fa94 ya está en inglés. Saltando...
🧐 Procesando 10079/17048 - 03b36115-a63b-4685-a0b6-b339def03036 | Idioma detectado: en
✅ 03b36115-a63b-4685-a0b6-b339def03036 ya está en inglés. Saltando...
🧐 Procesando 10080/17048 - 9ea807cc-2571-4cef-a7e4-350ec9f9b16c | Idioma detectado: fr

🔄 Traduciendo canciones:  63%|██████▎   | 10690/17048 [49:37<27:11,  3.90it/s]

🧐 Procesando 10680/17048 - 8dee8cf5-a77b-4cfb-a64c-c9db0797d668 | Idioma detectado: en
✅ 8dee8cf5-a77b-4cfb-a64c-c9db0797d668 ya está en inglés. Saltando...
🧐 Procesando 10681/17048 - 376361f3-1007-499a-82c5-9c0b9d9417e3 | Idioma detectado: en
✅ 376361f3-1007-499a-82c5-9c0b9d9417e3 ya está en inglés. Saltando...
🧐 Procesando 10682/17048 - 6e134914-0365-4d7b-ab81-9cbc48b021f6 | Idioma detectado: en
✅ 6e134914-0365-4d7b-ab81-9cbc48b021f6 ya está en inglés. Saltando...
🧐 Procesando 10683/17048 - 3a4c0faf-8527-4bb9-b871-09f956fdbed5 | Idioma detectado: en
✅ 3a4c0faf-8527-4bb9-b871-09f956fdbed5 ya está en inglés. Saltando...
🧐 Procesando 10684/17048 - 88185cb6-4495-4b50-9a59-4c19afebb1b0 | Idioma detectado: en
✅ 88185cb6-4495-4b50-9a59-4c19afebb1b0 ya está en inglés. Saltando...
🧐 Procesando 10685/17048 - e2d141e5-ca65-4e9a-ac15-7768fd8a78dd | Idioma detectado: en
✅ e2d141e5-ca65-4e9a-ac15-7768fd8a78dd ya está en inglés. Saltando...
🧐 Procesando 10686/17048 - d5b21a86-5c51-461a-a28d-2120ae597324 | Idioma detectado: en
✅ d5b21a86-5c51-461a-a28d-2120ae597324 ya está en inglés. Saltando...
🧐 Procesando 10687/17048 - 78d701a3-ca1c-482d-bef7-6640cea6d0c7 | Idioma detectado: en
✅ 78d701a3-ca1c-482d-bef7-6640cea6d0c7 ya está en inglés. Saltando...
🧐 Procesando 10688/17048 - 93d5bcf8-53bf-40f3-a095-cdc95ee13688 | Idioma detectado: en
✅ 93d5bcf8-53bf-40f3-a095-cdc95ee13688 ya está en inglés. Saltando...
🧐 Procesando 10689/17048 - f79d33d8-209c-4c77-9c30-a34246f3f72c | Idioma detectado: es
🧐 Procesando 10690/17048 - b7a9f925-3efd-422d-a27d-921d1bb76625 | Idioma detectado: es

🔄 Traduciendo canciones:  63%|██████▎   | 10699/17048 [49:43<35:49,  2.95it/s]

✅ 93d5bcf8-53bf-40f3-a095-cdc95ee13688 ya está en inglés. Saltando...
🧐 Procesando 10689/17048 - f79d33d8-209c-4c77-9c30-a34246f3f72c | Idioma detectado: es
🧐 Procesando 10690/17048 - b7a9f925-3efd-422d-a27d-921d1bb76625 | Idioma detectado: es
🧐 Procesando 10691/17048 - 76f7e2e3-d8f4-4e7b-beae-2422877a734f | Idioma detectado: es
🧐 Procesando 10692/17048 - ae998e49-b166-4d31-9a36-77385f00a19c | Idioma detectado: en
✅ ae998e49-b166-4d31-9a36-77385f00a19c ya está en inglés. Saltando...
🧐 Procesando 10693/17048 - 90c20997-53d0-43e1-9cc7-930da80f824c | Idioma detectado: en
✅ 90c20997-53d0-43e1-9cc7-930da80f824c ya está en inglés. Saltando...
🧐 Procesando 10694/17048 - 15e84755-ce62-40e8-8288-cc0f9705c766 | Idioma detectado: en
✅ 15e84755-ce62-40e8-8288-cc0f9705c766 ya está en inglés. Saltando...
🧐 Procesando 10695/17048 - 5d9cf11a-4c76-4ddc-b50c-a0821c4a04f7 | Idioma detectado: en
✅ 5d9cf11a-4c76-4ddc-b50c-a0821c4a04f7 ya está en inglés. Saltando...
🧐 Procesando 10696/17048 - 5687967b-277c-4fda-8462-b5404bbb1b6d | Idioma detectado: en
✅ 5687967b-277c-4fda-8462-b5404bbb1b6d ya está en inglés. Saltando...
🧐 Procesando 10697/17048 - 6791dd49-a20e-4942-b8d3-68fe91c2d568 | Idioma detectado: en
✅ 6791dd49-a20e-4942-b8d3-68fe91c2d568 ya está en inglés. Saltando...
🧐 Procesando 10698/17048 - cc4724a6-b66b-43a3-9488-0110d5556623 | Idioma detectado: es
🧐 Procesando 10699/17048 - bed34077-0202-4ac7-8b24-5858e8de6b95 | Idioma detectado: en
✅ bed34077-0202-4ac7-8b24-5858e8de6b95 ya está en inglés. Saltando...
🧐 Procesando 10700/17048 - a63ae4f6-8745-4737-b7a5-84b1f073182c | Idioma detectado: es

🔄 Traduciendo canciones:  63%|██████▎   | 10730/17048 [50:05<2:28:16,  1.41s/it]

✅ e36246d1-e284-479c-aeca-acf8eefa06b0 ya está en inglés. Saltando...
🧐 Procesando 10717/17048 - 7af9aec2-35cc-4fa4-948d-8a7c207154ce | Idioma detectado: en
✅ 7af9aec2-35cc-4fa4-948d-8a7c207154ce ya está en inglés. Saltando...
🧐 Procesando 10718/17048 - cb0de221-80e6-406a-b627-a5adc0d3eaed | Idioma detectado: en
✅ cb0de221-80e6-406a-b627-a5adc0d3eaed ya está en inglés. Saltando...
🧐 Procesando 10719/17048 - 8c283ed0-ed06-4d55-8c0f-b48accf33ead | Idioma detectado: en
✅ 8c283ed0-ed06-4d55-8c0f-b48accf33ead ya está en inglés. Saltando...
🧐 Procesando 10720/17048 - 67f7de25-3b4e-421e-ae58-7ad7d6bb06dc | Idioma detectado: en
✅ 67f7de25-3b4e-421e-ae58-7ad7d6bb06dc ya está en inglés. Saltando...
🧐 Procesando 10721/17048 - 2c07ce3e-2925-45c9-ac9f-1f1d92743835 | Idioma detectado: es
🧐 Procesando 10722/17048 - 14f06dd0-5773-4030-8283-f9a6ddb6b60f | Idioma detectado: en
✅ 14f06dd0-5773-4030-8283-f9a6ddb6b60f ya está en inglés. Saltando...
🧐 Procesando 10723/17048 - d8818463-c058-4daa-91a0-397d1fc54032 | Idioma detectado: es
🧐 Procesando 10724/17048 - 5531656d-259b-4fb7-b966-b5a78efdb9f8 | Idioma detectado: es
🧐 Procesando 10725/17048 - 5f77068d-437f-4744-8910-06ac1b4a7314 | Idioma detectado: es
🧐 Procesando 10726/17048 - 5e516f7c-a49a-44e3-9d8e-54a22e3e3edd | Idioma detectado: es
🧐 Procesando 10727/17048 - c3f71a30-fbeb-45e9-b307-514295e47a75 | Idioma detectado: es
🧐 Procesando 10728/17048 - 45da702a-2bef-4866-a863-8d7958d9ebf1 | Idioma detectado: es
🧐 Procesando 10729/17048 - a1e39aae-c2ef-44ff-99b4-39375f63b464 | Idioma detectado: es
🧐 Procesando 10730/17048 - 47007b7b-e8e6-439d-adb7-d66a9faf55c7 | Idioma detectado: es

🔄 Traduciendo canciones:  63%|██████▎   | 10733/17048 [50:12<3:28:22,  1.98s/it]

🧐 Procesando 10728/17048 - 45da702a-2bef-4866-a863-8d7958d9ebf1 | Idioma detectado: es
🧐 Procesando 10729/17048 - a1e39aae-c2ef-44ff-99b4-39375f63b464 | Idioma detectado: es
🧐 Procesando 10730/17048 - 47007b7b-e8e6-439d-adb7-d66a9faf55c7 | Idioma detectado: es
🧐 Procesando 10731/17048 - dfb4c07d-8cda-414b-8986-7de4fc1a51ab | Idioma detectado: es
🧐 Procesando 10732/17048 - 3920e225-8f4a-40e3-a81f-8c6a5aeb0ee5 | Idioma detectado: es
🧐 Procesando 10733/17048 - b26754c7-3aff-4825-bdd3-728018d793c0 | Idioma detectado: en
✅ b26754c7-3aff-4825-bdd3-728018d793c0 ya está en inglés. Saltando...
🧐 Procesando 10734/17048 - 206d9e91-0b82-4a48-a2e1-7df52f6cfd63 | Idioma detectado: en
✅ 206d9e91-0b82-4a48-a2e1-7df52f6cfd63 ya está en inglés. Saltando...
🧐 Procesando 10735/17048 - 0d26e11f-0a14-4e91-a89b-2a823ce329e6 | Idioma detectado: en
✅ 0d26e11f-0a14-4e91-a89b-2a823ce329e6 ya está en inglés. Saltando...
🧐 Procesando 10736/17048 - ba4a9ad9-9dc6-4cd6-bb63-04f2eba94641 | Idioma detectado: en
✅ ba4a9ad9-9dc6-4cd6-bb63-04f2eba94641 ya está en inglés. Saltando...
🧐 Procesando 10737/17048 - cac678ef-565d-44d8-b310-80618d8db05c | Idioma detectado: en
✅ cac678ef-565d-44d8-b310-80618d8db05c ya está en inglés. Saltando...
🧐 Procesando 10738/17048 - 563b7c63-880a-4611-a3cf-f4115b16649e | Idioma detectado: en
✅ 563b7c63-880a-4611-a3cf-f4115b16649e ya está en inglés. Saltando...
🧐 Procesando 10739/17048 - 6eff0a22-1056-48cf-9dd7-3429a10ef757 | Idioma detectado: en
✅ 6eff0a22-1056-48cf-9dd7-3429a10ef757 ya está en inglés. Saltando...
🧐 Procesando 10740/17048 - 3af0dc05-ca36-4ebf-becd-12c5ba5f5c07 | Idioma detectado: sv

🔄 Traduciendo canciones:  67%|██████▋   | 11348/17048 [52:11<32:57,  2.88it/s]

✅ 5b56e737-655e-4b10-9ed6-9b5cd43a1d0f ya está en inglés. Saltando...
🧐 Procesando 11361/17048 - bf65ac26-b425-4c85-b7e1-096ef5b400d5 | Idioma detectado: en
✅ bf65ac26-b425-4c85-b7e1-096ef5b400d5 ya está en inglés. Saltando...
🧐 Procesando 11362/17048 - cb33b4db-474a-4991-87ab-c5f4a4b2d89a | Idioma detectado: en
✅ cb33b4db-474a-4991-87ab-c5f4a4b2d89a ya está en inglés. Saltando...
🧐 Procesando 11363/17048 - 459c79d4-f3e9-432e-961f-98f2b8a8e1ef | Idioma detectado: en
✅ 459c79d4-f3e9-432e-961f-98f2b8a8e1ef ya está en inglés. Saltando...
🧐 Procesando 11364/17048 - b29637b6-88cf-4dde-9375-9dedfa00329c | Idioma detectado: en
✅ b29637b6-88cf-4dde-9375-9dedfa00329c ya está en inglés. Saltando...
🧐 Procesando 11365/17048 - 53f0e659-d12c-42e5-b4a0-4a0166620db9 | Idioma detectado: en
✅ 53f0e659-d12c-42e5-b4a0-4a0166620db9 ya está en inglés. Saltando...
🧐 Procesando 11366/17048 - e020d0a4-71a2-47be-b161-765234c6b486 | Idioma detectado: en
✅ e020d0a4-71a2-47be-b161-765234c6b486 ya está en inglés. Saltando...
🧐 Procesando 11367/17048 - 4d3e22c5-6289-4884-a027-b4ec1e5a8257 | Idioma detectado: en
✅ 4d3e22c5-6289-4884-a027-b4ec1e5a8257 ya está en inglés. Saltando...
🧐 Procesando 11368/17048 - d2f0dee1-0110-4cad-93a0-e5b4a1a2dd72 | Idioma detectado: en
✅ d2f0dee1-0110-4cad-93a0-e5b4a1a2dd72 ya está en inglés. Saltando...
🧐 Procesando 11369/17048 - 7099e1c2-35a1-41ed-8972-dbc78462cdaf | Idioma detectado: en
✅ 7099e1c2-35a1-41ed-8972-dbc78462cdaf ya está en inglés. Saltando...
🧐 Procesando 11370/17048 - 1e7f8b76-20c3-4a9e-8548-a484b30e25ce | Idioma detectado: fr

🔄 Traduciendo canciones:  70%|███████   | 11999/17048 [53:15<07:57, 10.57it/s]

✅ d6e4ab63-35ab-4ff6-be34-523da1ee877b ya está en inglés. Saltando...
🧐 Procesando 11990/17048 - 15b86f2b-4aae-462e-9174-0f605e509f30 | Idioma detectado: en
✅ 15b86f2b-4aae-462e-9174-0f605e509f30 ya está en inglés. Saltando...
🧐 Procesando 11991/17048 - 35f79762-8fd1-41cd-a232-a72a2db8076b | Idioma detectado: en
✅ 35f79762-8fd1-41cd-a232-a72a2db8076b ya está en inglés. Saltando...
🧐 Procesando 11992/17048 - c182f6f6-dfc2-4f23-ada7-da88215e997c | Idioma detectado: en
✅ c182f6f6-dfc2-4f23-ada7-da88215e997c ya está en inglés. Saltando...
🧐 Procesando 11993/17048 - d57be135-8cb9-4ef3-8306-392a5f7d57ab | Idioma detectado: en
✅ d57be135-8cb9-4ef3-8306-392a5f7d57ab ya está en inglés. Saltando...
🧐 Procesando 11994/17048 - 2732e436-c4f8-44ee-8619-b60d0e79bdba | Idioma detectado: en
✅ 2732e436-c4f8-44ee-8619-b60d0e79bdba ya está en inglés. Saltando...
🧐 Procesando 11995/17048 - 2a25e2d9-9468-4030-befc-04a86bb7ba6b | Idioma detectado: en
✅ 2a25e2d9-9468-4030-befc-04a86bb7ba6b ya está en inglés. Saltando...
🧐 Procesando 11996/17048 - bddbf812-5947-47e9-b18a-e244c3335ee0 | Idioma detectado: en
✅ bddbf812-5947-47e9-b18a-e244c3335ee0 ya está en inglés. Saltando...
🧐 Procesando 11997/17048 - 3f2ea3f9-ed83-4b5a-bf54-0779a19495f1 | Idioma detectado: en
✅ 3f2ea3f9-ed83-4b5a-bf54-0779a19495f1 ya está en inglés. Saltando...
🧐 Procesando 11998/17048 - 68e423f3-1d95-492c-9b3a-43195f3f3897 | Idioma detectado: de
🧐 Procesando 11999/17048 - c4340de5-4f3a-440c-ba63-2e60853f1572 | Idioma detectado: de
🧐 Procesando 12000/17048 - 7698aaa3-6ccf-49d9-9ff9-557539168aba | Idioma detectado: de

🔄 Traduciendo canciones:  70%|███████   | 12008/17048 [53:30<1:17:25,  1.09it/s]

✅ 2a25e2d9-9468-4030-befc-04a86bb7ba6b ya está en inglés. Saltando...
🧐 Procesando 11996/17048 - bddbf812-5947-47e9-b18a-e244c3335ee0 | Idioma detectado: en
✅ bddbf812-5947-47e9-b18a-e244c3335ee0 ya está en inglés. Saltando...
🧐 Procesando 11997/17048 - 3f2ea3f9-ed83-4b5a-bf54-0779a19495f1 | Idioma detectado: en
✅ 3f2ea3f9-ed83-4b5a-bf54-0779a19495f1 ya está en inglés. Saltando...
🧐 Procesando 11998/17048 - 68e423f3-1d95-492c-9b3a-43195f3f3897 | Idioma detectado: de
🧐 Procesando 11999/17048 - c4340de5-4f3a-440c-ba63-2e60853f1572 | Idioma detectado: de
🧐 Procesando 12000/17048 - 7698aaa3-6ccf-49d9-9ff9-557539168aba | Idioma detectado: de
🧐 Procesando 12001/17048 - 8124d93b-3b83-4c9c-bb2c-fc532ebd508a | Idioma detectado: de
🧐 Procesando 12002/17048 - a63d5947-8dcb-4074-8a24-525359fc1a2e | Idioma detectado: de
🧐 Procesando 12003/17048 - 360cb244-07a7-4d98-a0a6-5b7571e63ab2 | Idioma detectado: de
🧐 Procesando 12004/17048 - 32980ac4-e35e-4ac9-9a50-66b5049047af | Idioma detectado: de
🧐 Procesando 12005/17048 - a8e00463-b3cc-4a66-8d88-cc5f349994ce | Idioma detectado: de
🧐 Procesando 12006/17048 - e3f16be4-6bef-4e6c-b64c-7683c7b40f8c | Idioma detectado: de
🧐 Procesando 12007/17048 - a0749466-676e-40ee-bcdc-6412a15ea2d0 | Idioma detectado: de
🧐 Procesando 12008/17048 - 1d76dda9-e64c-48d3-9613-4b870af22db7 | Idioma detectado: en
✅ 1d76dda9-e64c-48d3-9613-4b870af22db7 ya está en inglés. Saltando...
🧐 Procesando 12009/17048 - 8ac87770-3459-4206-9312-07b4de5e93b7 | Idioma detectado: en
✅ 8ac87770-3459-4206-9312-07b4de5e93b7 ya está en inglés. Saltando...
🧐 Procesando 12010/17048 - 48c92c6e-d7f4-4020-b478-15076ac0816d | Idioma detectado: de

🔄 Traduciendo canciones:  70%|███████   | 12011/17048 [53:32<1:03:30,  1.32it/s]

🧐 Procesando 12010/17048 - 48c92c6e-d7f4-4020-b478-15076ac0816d | Idioma detectado: de
🧐 Procesando 12011/17048 - e0507273-5a77-4a2c-b79b-f4be5449f3a5 | Idioma detectado: en
✅ e0507273-5a77-4a2c-b79b-f4be5449f3a5 ya está en inglés. Saltando...
🧐 Procesando 12012/17048 - 437ba340-cfea-4ff9-810e-5215de560106 | Idioma detectado: en
✅ 437ba340-cfea-4ff9-810e-5215de560106 ya está en inglés. Saltando...
🧐 Procesando 12013/17048 - 7202f642-adeb-4fa9-9f07-6ba60b3441f3 | Idioma detectado: en
✅ 7202f642-adeb-4fa9-9f07-6ba60b3441f3 ya está en inglés. Saltando...
🧐 Procesando 12014/17048 - 2925ac52-d7fd-434e-80c1-8461ddd39adf | Idioma detectado: en
✅ 2925ac52-d7fd-434e-80c1-8461ddd39adf ya está en inglés. Saltando...
🧐 Procesando 12015/17048 - 68c352ba-85e2-444d-a7bf-4e407fa871a1 | Idioma detectado: en
✅ 68c352ba-85e2-444d-a7bf-4e407fa871a1 ya está en inglés. Saltando...
🧐 Procesando 12016/17048 - 2ec2dbe3-3c7f-48f0-aadb-81f25d3a3122 | Idioma detectado: en
✅ 2ec2dbe3-3c7f-48f0-aadb-81f25d3a3122 ya está en inglés. Saltando...
🧐 Procesando 12017/17048 - c236b7b3-b6b8-4ff5-a62b-a7a965b96356 | Idioma detectado: en
✅ c236b7b3-b6b8-4ff5-a62b-a7a965b96356 ya está en inglés. Saltando...
🧐 Procesando 12018/17048 - 2fa76381-2e7f-4c71-bb60-a41ce285a944 | Idioma detectado: en
✅ 2fa76381-2e7f-4c71-bb60-a41ce285a944 ya está en inglés. Saltando...
🧐 Procesando 12019/17048 - afc0eb3c-bd4c-46d3-814e-a181fcea1f25 | Idioma detectado: en
✅ afc0eb3c-bd4c-46d3-814e-a181fcea1f25 ya está en inglés. Saltando...
🧐 Procesando 12020/17048 - 7b6a457d-cc12-4784-925a-cacc57efb35c | Idioma detectado: la

🔄 Traduciendo canciones:  71%|███████   | 12040/17048 [53:53<1:17:05,  1.08it/s]

✅ e3cfab4e-4cce-48af-a0dc-501238857917 ya está en inglés. Saltando...
🧐 Procesando 12028/17048 - 7dc7f59c-7d47-403b-8262-f0fcb398877c | Idioma detectado: en
✅ 7dc7f59c-7d47-403b-8262-f0fcb398877c ya está en inglés. Saltando...
🧐 Procesando 12029/17048 - 0a4f5636-410d-40f8-8839-836c7c77d54a | Idioma detectado: en
✅ 0a4f5636-410d-40f8-8839-836c7c77d54a ya está en inglés. Saltando...
🧐 Procesando 12030/17048 - 72a78f81-12f3-4fa0-acb7-af9e6a6df52a | Idioma detectado: en
✅ 72a78f81-12f3-4fa0-acb7-af9e6a6df52a ya está en inglés. Saltando...
🧐 Procesando 12031/17048 - de4f9216-571c-462b-a955-dfb0d30acee1 | Idioma detectado: en
✅ de4f9216-571c-462b-a955-dfb0d30acee1 ya está en inglés. Saltando...
🧐 Procesando 12032/17048 - e1f5d2eb-38ae-4827-8870-f7e20e66052b | Idioma detectado: de
🧐 Procesando 12033/17048 - a617734c-a8aa-4e8a-ae41-b50c1423f182 | Idioma detectado: de
🧐 Procesando 12034/17048 - febfd7c7-10b7-44a7-b49b-b72f9e0bd5d0 | Idioma detectado: en
✅ febfd7c7-10b7-44a7-b49b-b72f9e0bd5d0 ya está en inglés. Saltando...
🧐 Procesando 12035/17048 - a0865746-f438-42d9-8642-db8f1240afac | Idioma detectado: en
✅ a0865746-f438-42d9-8642-db8f1240afac ya está en inglés. Saltando...
🧐 Procesando 12036/17048 - 9b2da854-597e-4ed3-8b88-23d2c06b7a18 | Idioma detectado: de
🧐 Procesando 12037/17048 - d248bd4e-6aab-43d3-8e8a-30346c5c5e36 | Idioma detectado: de
🧐 Procesando 12038/17048 - 284981f3-10b8-478a-b41a-713ef3da6452 | Idioma detectado: de
🧐 Procesando 12039/17048 - 3eb9e39d-0c71-4af9-aeda-0c951580deb4 | Idioma detectado: de
🧐 Procesando 12040/17048 - 7d9bfec5-8434-4793-a2a0-b305c1814033 | Idioma detectado: de

🔄 Traduciendo canciones:  71%|███████   | 12050/17048 [54:01<1:06:37,  1.25it/s]

✅ a0865746-f438-42d9-8642-db8f1240afac ya está en inglés. Saltando...
🧐 Procesando 12036/17048 - 9b2da854-597e-4ed3-8b88-23d2c06b7a18 | Idioma detectado: de
🧐 Procesando 12037/17048 - d248bd4e-6aab-43d3-8e8a-30346c5c5e36 | Idioma detectado: de
🧐 Procesando 12038/17048 - 284981f3-10b8-478a-b41a-713ef3da6452 | Idioma detectado: de
🧐 Procesando 12039/17048 - 3eb9e39d-0c71-4af9-aeda-0c951580deb4 | Idioma detectado: de
🧐 Procesando 12040/17048 - 7d9bfec5-8434-4793-a2a0-b305c1814033 | Idioma detectado: de
🧐 Procesando 12041/17048 - b852380c-99d8-44fe-974d-555926c0f3bb | Idioma detectado: de
🧐 Procesando 12042/17048 - 72138ff7-41e6-4213-9d5e-6d0f99e9d680 | Idioma detectado: de
🧐 Procesando 12043/17048 - 07daec1e-dd62-40cc-9bbe-55f6066368f4 | Idioma detectado: de
🧐 Procesando 12044/17048 - dc6b9826-2c23-439d-8881-6fffd650cc58 | Idioma detectado: en
✅ dc6b9826-2c23-439d-8881-6fffd650cc58 ya está en inglés. Saltando...
🧐 Procesando 12045/17048 - da7b69e2-c390-4dc0-bf8c-e04331f2869a | Idioma detectado: en
✅ da7b69e2-c390-4dc0-bf8c-e04331f2869a ya está en inglés. Saltando...
🧐 Procesando 12046/17048 - 15b859d6-2f28-4182-9e73-c94973ec33c5 | Idioma detectado: en
✅ 15b859d6-2f28-4182-9e73-c94973ec33c5 ya está en inglés. Saltando...
🧐 Procesando 12047/17048 - 5ec28e2b-95d4-41f5-8044-492ce111e906 | Idioma detectado: en
✅ 5ec28e2b-95d4-41f5-8044-492ce111e906 ya está en inglés. Saltando...
🧐 Procesando 12048/17048 - a1816d58-64c1-489b-822f-1ae23dddae8f | Idioma detectado: de
🧐 Procesando 12049/17048 - 87b7b12f-e831-4648-9245-718981edefc9 | Idioma detectado: de
🧐 Procesando 12050/17048 - 67d8fefa-7b7c-4977-bc8c-c528c4085f7c | Idioma detectado: de

🔄 Traduciendo canciones:  71%|███████   | 12060/17048 [54:07<38:11,  2.18it/s]

✅ 5ec28e2b-95d4-41f5-8044-492ce111e906 ya está en inglés. Saltando...
🧐 Procesando 12048/17048 - a1816d58-64c1-489b-822f-1ae23dddae8f | Idioma detectado: de
🧐 Procesando 12049/17048 - 87b7b12f-e831-4648-9245-718981edefc9 | Idioma detectado: de
🧐 Procesando 12050/17048 - 67d8fefa-7b7c-4977-bc8c-c528c4085f7c | Idioma detectado: de
🧐 Procesando 12051/17048 - 67fadfaf-75ce-4d62-9209-05af06fc494a | Idioma detectado: de
🧐 Procesando 12052/17048 - b4f30026-7bf2-4a03-a033-4d07bc75eda3 | Idioma detectado: de
🧐 Procesando 12053/17048 - 12d75b70-3dca-45f1-ba48-72782d9b2bee | Idioma detectado: en
✅ 12d75b70-3dca-45f1-ba48-72782d9b2bee ya está en inglés. Saltando...
🧐 Procesando 12054/17048 - d1a75912-1a5b-4b0c-805b-af81394b5c2a | Idioma detectado: en
✅ d1a75912-1a5b-4b0c-805b-af81394b5c2a ya está en inglés. Saltando...
🧐 Procesando 12055/17048 - e62923ae-292d-43cc-8519-6706dd162dec | Idioma detectado: en
✅ e62923ae-292d-43cc-8519-6706dd162dec ya está en inglés. Saltando...
🧐 Procesando 12056/17048 - d399886c-4e35-4e54-b75f-7283546ab725 | Idioma detectado: en
✅ d399886c-4e35-4e54-b75f-7283546ab725 ya está en inglés. Saltando...
🧐 Procesando 12057/17048 - 0e0f4363-b08f-4592-ab37-ac73c193b818 | Idioma detectado: en
✅ 0e0f4363-b08f-4592-ab37-ac73c193b818 ya está en inglés. Saltando...
🧐 Procesando 12058/17048 - e20f910a-c9d4-48bc-ab69-92bd5b17edb6 | Idioma detectado: en
✅ e20f910a-c9d4-48bc-ab69-92bd5b17edb6 ya está en inglés. Saltando...
🧐 Procesando 12059/17048 - a5109a1c-8656-4c8c-84f8-12df1cbf44f9 | Idioma detectado: de
🧐 Procesando 12060/17048 - 34799e26-89be-41c6-9bcc-edf1198ca9fa | Idioma detectado: de

🔄 Traduciendo canciones:  71%|███████   | 12118/17048 [54:27<12:57,  6.34it/s]

🧐 Procesando 12110/17048 - beff72fb-283c-4607-a463-690557ab1430 | Idioma detectado: en
✅ beff72fb-283c-4607-a463-690557ab1430 ya está en inglés. Saltando...
🧐 Procesando 12111/17048 - 9afc83f9-e153-4b59-96b9-dec32d9bb3f4 | Idioma detectado: en
✅ 9afc83f9-e153-4b59-96b9-dec32d9bb3f4 ya está en inglés. Saltando...
🧐 Procesando 12112/17048 - 1e25523c-02b8-49d2-b70c-5e8dedf68b30 | Idioma detectado: en
✅ 1e25523c-02b8-49d2-b70c-5e8dedf68b30 ya está en inglés. Saltando...
🧐 Procesando 12113/17048 - 35ef7bc0-1ea0-4857-b4b5-d21f9c1ee9fd | Idioma detectado: en
✅ 35ef7bc0-1ea0-4857-b4b5-d21f9c1ee9fd ya está en inglés. Saltando...
🧐 Procesando 12114/17048 - 48f97e3c-7542-4a3b-9016-da8205b142a7 | Idioma detectado: en
✅ 48f97e3c-7542-4a3b-9016-da8205b142a7 ya está en inglés. Saltando...
🧐 Procesando 12115/17048 - 518fb1f5-4069-4b7e-a55e-fb6f16b1f235 | Idioma detectado: en
✅ 518fb1f5-4069-4b7e-a55e-fb6f16b1f235 ya está en inglés. Saltando...
🧐 Procesando 12116/17048 - 1afbbadf-595b-438a-9a20-33c57c4965f6 | Idioma detectado: en
✅ 1afbbadf-595b-438a-9a20-33c57c4965f6 ya está en inglés. Saltando...
🧐 Procesando 12117/17048 - a77be259-c9e1-4931-adfa-8d29555c36ee | Idioma detectado: de
🧐 Procesando 12118/17048 - 389b780e-8e57-4952-83ec-e9d55d533389 | Idioma detectado: en
✅ 389b780e-8e57-4952-83ec-e9d55d533389 ya está en inglés. Saltando...
🧐 Procesando 12119/17048 - 2bfe3dd8-b1d2-497d-88e1-b6dd44b3716e | Idioma detectado: en
✅ 2bfe3dd8-b1d2-497d-88e1-b6dd44b3716e ya está en inglés. Saltando...
🧐 Procesando 12120/17048 - b6695416-bbfa-4134-af1f-894700ec9667 | Idioma detectado: es

🔄 Traduciendo canciones:  73%|███████▎  | 12431/17048 [57:01<48:34,  1.58it/s]

✅ ca892e50-ba63-4cef-b517-04a40fcf0929 ya está en inglés. Saltando...
🧐 Procesando 12421/17048 - f885bcfc-e924-4d12-b05c-11c899d30d2a | Idioma detectado: en
✅ f885bcfc-e924-4d12-b05c-11c899d30d2a ya está en inglés. Saltando...
🧐 Procesando 12422/17048 - 2590e23a-2ebd-49c6-bc25-122c728ec6a4 | Idioma detectado: en
✅ 2590e23a-2ebd-49c6-bc25-122c728ec6a4 ya está en inglés. Saltando...
🧐 Procesando 12423/17048 - 05161397-1672-4fe5-b11e-ff0070405259 | Idioma detectado: en
✅ 05161397-1672-4fe5-b11e-ff0070405259 ya está en inglés. Saltando...
🧐 Procesando 12424/17048 - 310301c1-777b-4844-99e1-316e3fea1238 | Idioma detectado: en
✅ 310301c1-777b-4844-99e1-316e3fea1238 ya está en inglés. Saltando...
🧐 Procesando 12425/17048 - d300530a-ea51-43bf-9449-e69f6a4a8f7d | Idioma detectado: en
✅ d300530a-ea51-43bf-9449-e69f6a4a8f7d ya está en inglés. Saltando...
🧐 Procesando 12426/17048 - 47d9d137-0bae-4e8a-b545-99691dbe0d36 | Idioma detectado: en
✅ 47d9d137-0bae-4e8a-b545-99691dbe0d36 ya está en inglés. Saltando...
🧐 Procesando 12427/17048 - e1b88372-c3d6-47d0-a5ef-5fdbfba436cf | Idioma detectado: en
✅ e1b88372-c3d6-47d0-a5ef-5fdbfba436cf ya está en inglés. Saltando...
🧐 Procesando 12428/17048 - 1e950eab-884f-4802-b7f7-b2e012acbb85 | Idioma detectado: en
✅ 1e950eab-884f-4802-b7f7-b2e012acbb85 ya está en inglés. Saltando...
🧐 Procesando 12429/17048 - af258661-e507-4bd2-b689-7a59d96cab04 | Idioma detectado: en
✅ af258661-e507-4bd2-b689-7a59d96cab04 ya está en inglés. Saltando...
🧐 Procesando 12430/17048 - b3e694db-d78d-44d2-9d06-a4015f10d01b | Idioma detectado: de

🔄 Traduciendo canciones:  73%|███████▎  | 12511/17048 [57:01<09:33,  7.91it/s]

✅ 0a280b30-26c0-4782-acb2-14383daa0b4b ya está en inglés. Saltando...
🧐 Procesando 12501/17048 - ad9fb7c0-3c9a-44f0-879a-1cbe2e609ee6 | Idioma detectado: en
✅ ad9fb7c0-3c9a-44f0-879a-1cbe2e609ee6 ya está en inglés. Saltando...
🧐 Procesando 12502/17048 - 44f3f08b-9b40-4649-b6d5-bcc49442a361 | Idioma detectado: en
✅ 44f3f08b-9b40-4649-b6d5-bcc49442a361 ya está en inglés. Saltando...
🧐 Procesando 12503/17048 - 701d97fb-ee98-4fdc-b96c-21395c2dd0c7 | Idioma detectado: en
✅ 701d97fb-ee98-4fdc-b96c-21395c2dd0c7 ya está en inglés. Saltando...
🧐 Procesando 12504/17048 - 1fe7c514-8cec-482b-b22c-9bd2d43c7a3e | Idioma detectado: en
✅ 1fe7c514-8cec-482b-b22c-9bd2d43c7a3e ya está en inglés. Saltando...
🧐 Procesando 12505/17048 - 6b0401af-bf2e-4333-9834-b0d3f1c9102f | Idioma detectado: en
✅ 6b0401af-bf2e-4333-9834-b0d3f1c9102f ya está en inglés. Saltando...
🧐 Procesando 12506/17048 - 8d1a98ed-0562-4a41-8628-8dc83d620631 | Idioma detectado: en
✅ 8d1a98ed-0562-4a41-8628-8dc83d620631 ya está en inglés. Saltando...
🧐 Procesando 12507/17048 - 014f3540-09e0-465d-9ff0-ec817ff37e47 | Idioma detectado: en
✅ 014f3540-09e0-465d-9ff0-ec817ff37e47 ya está en inglés. Saltando...
🧐 Procesando 12508/17048 - 2d1fd7a3-3a9e-4727-83e7-9ec8c4ae4a75 | Idioma detectado: en
✅ 2d1fd7a3-3a9e-4727-83e7-9ec8c4ae4a75 ya está en inglés. Saltando...
🧐 Procesando 12509/17048 - 26e29456-823c-47b2-97a4-c180276c7cc1 | Idioma detectado: en
✅ 26e29456-823c-47b2-97a4-c180276c7cc1 ya está en inglés. Saltando...
🧐 Procesando 12510/17048 - 16ef202c-f261-41ec-97b0-2ea47dd4e91c | Idioma detectado: no

🔄 Traduciendo canciones:  73%|███████▎  | 12530/17048 [57:21<34:04,  2.21it/s]

🧐 Procesando 12519/17048 - b109b046-520d-48a6-b494-d0807dfe1c8d | Idioma detectado: pt
🧐 Procesando 12520/17048 - 55ce5d41-ef4a-4eb5-917a-1a097c6b1d2c | Idioma detectado: en
✅ 55ce5d41-ef4a-4eb5-917a-1a097c6b1d2c ya está en inglés. Saltando...
🧐 Procesando 12521/17048 - 1ac5f44d-5adf-4a81-9546-b9f6dfead37a | Idioma detectado: en
✅ 1ac5f44d-5adf-4a81-9546-b9f6dfead37a ya está en inglés. Saltando...
🧐 Procesando 12522/17048 - b186044d-99cb-4849-a0bf-cb9df147c4c7 | Idioma detectado: en
✅ b186044d-99cb-4849-a0bf-cb9df147c4c7 ya está en inglés. Saltando...
🧐 Procesando 12523/17048 - 0115aeb9-4f48-4521-bcc2-d1446d06c872 | Idioma detectado: en
✅ 0115aeb9-4f48-4521-bcc2-d1446d06c872 ya está en inglés. Saltando...
🧐 Procesando 12524/17048 - 067065eb-245b-47e6-bf93-e6d0cb3598b0 | Idioma detectado: en
✅ 067065eb-245b-47e6-bf93-e6d0cb3598b0 ya está en inglés. Saltando...
🧐 Procesando 12525/17048 - bf225975-7a7d-45d7-b939-c9e24bf645ee | Idioma detectado: en
✅ bf225975-7a7d-45d7-b939-c9e24bf645ee ya está en inglés. Saltando...
🧐 Procesando 12526/17048 - 46bd0d46-6b31-4c22-9631-2872f8f20375 | Idioma detectado: it
🧐 Procesando 12527/17048 - 85771851-34f4-47f6-8da2-279eaf2a8201 | Idioma detectado: en
✅ 85771851-34f4-47f6-8da2-279eaf2a8201 ya está en inglés. Saltando...
🧐 Procesando 12528/17048 - df121086-f736-4c04-8eeb-5ee943cc6392 | Idioma detectado: es
🧐 Procesando 12529/17048 - e37f1a34-7f5e-4ca2-ad8c-a988b85d4bac | Idioma detectado: en
✅ e37f1a34-7f5e-4ca2-ad8c-a988b85d4bac ya está en inglés. Saltando...
🧐 Procesando 12530/17048 - d0789390-a84f-4cb4-a628-d60ba95e41f9 | Idioma detectado: es

🔄 Traduciendo canciones:  75%|███████▍  | 12710/17048 [58:13<27:05,  2.67it/s]

✅ 6cb4b30f-4221-45b7-8930-35737e9d3ed0 ya está en inglés. Saltando...
🧐 Procesando 12699/17048 - eed6d7ee-d005-4cf5-ab58-28ac30f1d8fb | Idioma detectado: en
✅ eed6d7ee-d005-4cf5-ab58-28ac30f1d8fb ya está en inglés. Saltando...
🧐 Procesando 12700/17048 - 6a6dc554-363f-4e3e-a87c-3705b8b1fbaa | Idioma detectado: en
✅ 6a6dc554-363f-4e3e-a87c-3705b8b1fbaa ya está en inglés. Saltando...
🧐 Procesando 12701/17048 - 9fd9299a-b317-4431-89af-131306dda266 | Idioma detectado: en
✅ 9fd9299a-b317-4431-89af-131306dda266 ya está en inglés. Saltando...
🧐 Procesando 12702/17048 - 79ea714e-3972-442e-942c-e9bdc2b00780 | Idioma detectado: en
✅ 79ea714e-3972-442e-942c-e9bdc2b00780 ya está en inglés. Saltando...
🧐 Procesando 12703/17048 - fc4e6c4d-f1e5-4390-b504-dfa9ceac02fe | Idioma detectado: en
✅ fc4e6c4d-f1e5-4390-b504-dfa9ceac02fe ya está en inglés. Saltando...
🧐 Procesando 12704/17048 - 739bd20f-7fff-4151-b7e2-3302690f022a | Idioma detectado: en
✅ 739bd20f-7fff-4151-b7e2-3302690f022a ya está en inglés. Saltando...
🧐 Procesando 12705/17048 - ea9bef98-f4f7-4c5a-aa0e-a0a4dda19bf4 | Idioma detectado: en
✅ ea9bef98-f4f7-4c5a-aa0e-a0a4dda19bf4 ya está en inglés. Saltando...
🧐 Procesando 12706/17048 - e1e0ab02-045c-45b3-8229-5b5d448367ed | Idioma detectado: de
🧐 Procesando 12707/17048 - 16fbbc78-8055-4eca-9f45-8fd219606627 | Idioma detectado: de
🧐 Procesando 12708/17048 - 8424114d-9598-4293-9911-44bcd2bbc6ce | Idioma detectado: de
🧐 Procesando 12709/17048 - e585d9a8-c099-42f1-8c0b-7646535f1e31 | Idioma detectado: de
🧐 Procesando 12710/17048 - 59cb0e63-9736-47e8-9a2d-92b428dae974 | Idioma detectado: de

🔄 Traduciendo canciones:  75%|███████▍  | 12730/17048 [58:46<1:52:20,  1.56s/it]

🧐 Procesando 12717/17048 - 2130a103-fe98-4a32-a6cd-b5076765cc60 | Idioma detectado: en
✅ 2130a103-fe98-4a32-a6cd-b5076765cc60 ya está en inglés. Saltando...
🧐 Procesando 12718/17048 - cb080f4e-94f2-4bfd-9057-efd359596537 | Idioma detectado: en
✅ cb080f4e-94f2-4bfd-9057-efd359596537 ya está en inglés. Saltando...
🧐 Procesando 12719/17048 - 0720bbc3-7324-48ff-8d27-8a4ec8b24dbe | Idioma detectado: en
✅ 0720bbc3-7324-48ff-8d27-8a4ec8b24dbe ya está en inglés. Saltando...
🧐 Procesando 12720/17048 - 55a6c28b-bb2d-4992-b3d6-8553f94ac54e | Idioma detectado: en
✅ 55a6c28b-bb2d-4992-b3d6-8553f94ac54e ya está en inglés. Saltando...
🧐 Procesando 12721/17048 - ed81e0b1-cc42-45e5-a5ff-81ead1d042c9 | Idioma detectado: de
🧐 Procesando 12722/17048 - 49bae6b1-05e4-48ce-9ce4-2cffcdaba26d | Idioma detectado: de
🧐 Procesando 12723/17048 - f30ba582-d74b-4770-848b-7ee63dd299ff | Idioma detectado: de
🧐 Procesando 12724/17048 - 7de9c2c1-ffb2-4591-9fbb-fb188f0f53dd | Idioma detectado: de
🧐 Procesando 12725/17048 - c3a73a21-9f68-4274-9f63-47ca5a4b875a | Idioma detectado: de
🧐 Procesando 12726/17048 - fcdc953a-1ea1-48b9-a145-46508f020bf5 | Idioma detectado: en
✅ fcdc953a-1ea1-48b9-a145-46508f020bf5 ya está en inglés. Saltando...
🧐 Procesando 12727/17048 - cb4b8687-499d-4177-b4a8-a4459c4108a8 | Idioma detectado: de
🧐 Procesando 12728/17048 - aff4d042-6a7c-4629-affe-52242334b9fe | Idioma detectado: en
✅ aff4d042-6a7c-4629-affe-52242334b9fe ya está en inglés. Saltando...
🧐 Procesando 12729/17048 - 7f5acc2c-380d-4e75-8af4-8c101eea41bb | Idioma detectado: de
🧐 Procesando 12730/17048 - 2f3a3025-8ce3-474c-9743-7ff3219b8017 | Idioma detectado: de

🔄 Traduciendo canciones:  75%|███████▍  | 12746/17048 [59:05<1:03:50,  1.12it/s]

✅ 97485048-ef7a-4a2d-bf62-733e04bf5ece ya está en inglés. Saltando...
🧐 Procesando 12751/17048 - adb37f43-4144-42a7-bcae-31bd86f717c2 | Idioma detectado: en
✅ adb37f43-4144-42a7-bcae-31bd86f717c2 ya está en inglés. Saltando...
🧐 Procesando 12752/17048 - 869e7c3f-a6fc-4be4-a688-568e3f63dca8 | Idioma detectado: en
✅ 869e7c3f-a6fc-4be4-a688-568e3f63dca8 ya está en inglés. Saltando...
🧐 Procesando 12753/17048 - cc9b7ba5-49e1-4365-8c7b-a38e58838852 | Idioma detectado: en
✅ cc9b7ba5-49e1-4365-8c7b-a38e58838852 ya está en inglés. Saltando...
🧐 Procesando 12754/17048 - 6cfa6910-59cd-46c1-b247-0032eed9c3da | Idioma detectado: en
✅ 6cfa6910-59cd-46c1-b247-0032eed9c3da ya está en inglés. Saltando...
🧐 Procesando 12755/17048 - e38cba42-c45b-4225-a801-439165108467 | Idioma detectado: en
✅ e38cba42-c45b-4225-a801-439165108467 ya está en inglés. Saltando...
🧐 Procesando 12756/17048 - c806f385-2403-4ea8-9e74-0d54ed104d85 | Idioma detectado: en
✅ c806f385-2403-4ea8-9e74-0d54ed104d85 ya está en inglés. Saltando...
🧐 Procesando 12757/17048 - c4cb0452-d127-4c37-b24b-93d4e32d34bd | Idioma detectado: en
✅ c4cb0452-d127-4c37-b24b-93d4e32d34bd ya está en inglés. Saltando...
🧐 Procesando 12758/17048 - 52322d0f-100c-475b-a873-504ac127b0a0 | Idioma detectado: en
✅ 52322d0f-100c-475b-a873-504ac127b0a0 ya está en inglés. Saltando...
🧐 Procesando 12759/17048 - c8a78719-7c25-4a5f-ac37-8b14518b94a6 | Idioma detectado: en
✅ c8a78719-7c25-4a5f-ac37-8b14518b94a6 ya está en inglés. Saltando...
🧐 Procesando 12760/17048 - fc428ad0-15c0-4722-9ff4-38b05157efaa | Idioma detectado: fr

🔄 Traduciendo canciones:  75%|███████▌  | 12809/17048 [59:39<44:31,  1.59it/s]

🧐 Procesando 12799/17048 - 8821e5ab-550b-4ae2-8bf8-ceaa9c89f517 | Idioma detectado: en
✅ 8821e5ab-550b-4ae2-8bf8-ceaa9c89f517 ya está en inglés. Saltando...
🧐 Procesando 12800/17048 - 30a15fa1-3e57-4a18-8409-6643f7f216e3 | Idioma detectado: en
✅ 30a15fa1-3e57-4a18-8409-6643f7f216e3 ya está en inglés. Saltando...
🧐 Procesando 12801/17048 - 44d68edf-9ef5-4801-9a13-9da7d0719c07 | Idioma detectado: en
✅ 44d68edf-9ef5-4801-9a13-9da7d0719c07 ya está en inglés. Saltando...
🧐 Procesando 12802/17048 - d90c630a-6b25-4856-af30-79543f9bed99 | Idioma detectado: en
✅ d90c630a-6b25-4856-af30-79543f9bed99 ya está en inglés. Saltando...
🧐 Procesando 12803/17048 - c218d957-d781-4ae4-bd21-656e123c6150 | Idioma detectado: en
✅ c218d957-d781-4ae4-bd21-656e123c6150 ya está en inglés. Saltando...
🧐 Procesando 12804/17048 - 300f7d27-c6c1-43e7-8fc8-dd78b58d18e4 | Idioma detectado: en
✅ 300f7d27-c6c1-43e7-8fc8-dd78b58d18e4 ya está en inglés. Saltando...
🧐 Procesando 12805/17048 - a0333984-7ea9-4d61-ba32-2ee569505331 | Idioma detectado: pt
🧐 Procesando 12806/17048 - 41903325-2bf7-4f6f-a5a4-38f35f31b2da | Idioma detectado: de
🧐 Procesando 12807/17048 - 56a1f2c0-c298-44f3-ad05-9e508e296856 | Idioma detectado: en
✅ 56a1f2c0-c298-44f3-ad05-9e508e296856 ya está en inglés. Saltando...
🧐 Procesando 12808/17048 - 2468a3ee-23eb-4270-90aa-daf8931a2976 | Idioma detectado: fr
🧐 Procesando 12809/17048 - 2f71ace9-bfbb-4bd1-9154-f935504510bd | Idioma detectado: en
✅ 2f71ace9-bfbb-4bd1-9154-f935504510bd ya está en inglés. Saltando...
🧐 Procesando 12810/17048 - a3b7e529-d217-4a28-8e6e-106aefe43f78 | Idioma detectado: pt

🔄 Traduciendo canciones:  75%|███████▌  | 12818/17048 [59:51<1:01:32,  1.15it/s]

✅ 81cf13a1-15f8-4ce7-9781-f65d0902e027 ya está en inglés. Saltando...
🧐 Procesando 12831/17048 - 312a1da8-6152-474c-8493-ef39b348f18e | Idioma detectado: en
✅ 312a1da8-6152-474c-8493-ef39b348f18e ya está en inglés. Saltando...
🧐 Procesando 12832/17048 - 8576a1b2-08f6-4c67-8431-18d8704c2065 | Idioma detectado: en
✅ 8576a1b2-08f6-4c67-8431-18d8704c2065 ya está en inglés. Saltando...
🧐 Procesando 12833/17048 - be11f2f0-de43-48e9-bb0f-74bb82cfd5c7 | Idioma detectado: en
✅ be11f2f0-de43-48e9-bb0f-74bb82cfd5c7 ya está en inglés. Saltando...
🧐 Procesando 12834/17048 - 3b91b39e-ae73-4985-8582-838c724f6a74 | Idioma detectado: en
✅ 3b91b39e-ae73-4985-8582-838c724f6a74 ya está en inglés. Saltando...
🧐 Procesando 12835/17048 - 2b9a0ac1-c62f-41d4-8439-e4e4a498cc53 | Idioma detectado: en
✅ 2b9a0ac1-c62f-41d4-8439-e4e4a498cc53 ya está en inglés. Saltando...
🧐 Procesando 12836/17048 - 727a0073-6b61-4e42-86ab-fd5b6ce98593 | Idioma detectado: en
✅ 727a0073-6b61-4e42-86ab-fd5b6ce98593 ya está en inglés. Saltando...
🧐 Procesando 12837/17048 - 2379ead8-53aa-4dc4-9155-38cf59bf0b10 | Idioma detectado: en
✅ 2379ead8-53aa-4dc4-9155-38cf59bf0b10 ya está en inglés. Saltando...
🧐 Procesando 12838/17048 - 81e84100-ae11-4571-ab9a-137109f3a420 | Idioma detectado: en
✅ 81e84100-ae11-4571-ab9a-137109f3a420 ya está en inglés. Saltando...
🧐 Procesando 12839/17048 - b4fcc5fc-bb88-4e1c-8942-0208e14dd1c7 | Idioma detectado: en
✅ b4fcc5fc-bb88-4e1c-8942-0208e14dd1c7 ya está en inglés. Saltando...
🧐 Procesando 12840/17048 - 4844c155-b37b-4da1-b16f-3833ca6145d6 | Idioma detectado: de

🔄 Traduciendo canciones:  75%|███████▌  | 12851/17048 [1:00:17<2:39:46,  2.28s/it]

✅ 2b9a0ac1-c62f-41d4-8439-e4e4a498cc53 ya está en inglés. Saltando...
🧐 Procesando 12836/17048 - 727a0073-6b61-4e42-86ab-fd5b6ce98593 | Idioma detectado: en
✅ 727a0073-6b61-4e42-86ab-fd5b6ce98593 ya está en inglés. Saltando...
🧐 Procesando 12837/17048 - 2379ead8-53aa-4dc4-9155-38cf59bf0b10 | Idioma detectado: en
✅ 2379ead8-53aa-4dc4-9155-38cf59bf0b10 ya está en inglés. Saltando...
🧐 Procesando 12838/17048 - 81e84100-ae11-4571-ab9a-137109f3a420 | Idioma detectado: en
✅ 81e84100-ae11-4571-ab9a-137109f3a420 ya está en inglés. Saltando...
🧐 Procesando 12839/17048 - b4fcc5fc-bb88-4e1c-8942-0208e14dd1c7 | Idioma detectado: en
✅ b4fcc5fc-bb88-4e1c-8942-0208e14dd1c7 ya está en inglés. Saltando...
🧐 Procesando 12840/17048 - 4844c155-b37b-4da1-b16f-3833ca6145d6 | Idioma detectado: de
🧐 Procesando 12841/17048 - 3d3e066c-44f2-47b6-8b6d-94a03f202bb1 | Idioma detectado: de
🧐 Procesando 12842/17048 - 28012a10-0ad4-4538-8635-d31ed4cbf212 | Idioma detectado: de
🧐 Procesando 12843/17048 - c02fba11-6998-4dba-9889-89f0ea74e5fd | Idioma detectado: de
🧐 Procesando 12844/17048 - 321011e3-74c0-42a3-95b2-a6d9e68e8e8a | Idioma detectado: de
🧐 Procesando 12845/17048 - 06d38022-10d8-4c40-b41f-9beca2930b7d | Idioma detectado: de
🧐 Procesando 12846/17048 - cb6a7859-a9d6-4250-a590-728191e0fae0 | Idioma detectado: de
🧐 Procesando 12847/17048 - 0694136f-43bf-4bcc-8c0a-3d050fbdf33c | Idioma detectado: de
🧐 Procesando 12848/17048 - 8250ecdb-3203-439a-a671-5771f4b26c31 | Idioma detectado: de
🧐 Procesando 12849/17048 - 68088001-2aa4-4bb9-965a-e73165e3cefc | Idioma detectado: de
🧐 Procesando 12850/17048 - dc05ce21-74c1-4af7-a71e-af88ceab69e6 | Idioma detectado: de

🔄 Traduciendo canciones:  75%|███████▌  | 12867/17048 [1:00:21<37:32,  1.86it/s]

🧐 Procesando 12860/17048 - dcd8454a-addb-44a8-80d6-d31e8e94f397 | Idioma detectado: en
✅ dcd8454a-addb-44a8-80d6-d31e8e94f397 ya está en inglés. Saltando...
🧐 Procesando 12861/17048 - d9f95b92-6dec-4d49-9bec-8218bdf93e64 | Idioma detectado: en
✅ d9f95b92-6dec-4d49-9bec-8218bdf93e64 ya está en inglés. Saltando...
🧐 Procesando 12862/17048 - db244330-f9bc-42ca-b952-0bed6f6aab03 | Idioma detectado: en
✅ db244330-f9bc-42ca-b952-0bed6f6aab03 ya está en inglés. Saltando...
🧐 Procesando 12863/17048 - 68951f20-0007-4e7d-8b4c-d89ceb944915 | Idioma detectado: en
✅ 68951f20-0007-4e7d-8b4c-d89ceb944915 ya está en inglés. Saltando...
🧐 Procesando 12864/17048 - 81d12223-8f27-4cb5-adef-cc3a5bbd082c | Idioma detectado: en
✅ 81d12223-8f27-4cb5-adef-cc3a5bbd082c ya está en inglés. Saltando...
🧐 Procesando 12865/17048 - 536cff10-99e9-4711-8501-4cd967d3012e | Idioma detectado: en
✅ 536cff10-99e9-4711-8501-4cd967d3012e ya está en inglés. Saltando...
🧐 Procesando 12866/17048 - 091eeeb9-a78e-4d5d-a995-f049e7af8022 | Idioma detectado: de
🧐 Procesando 12867/17048 - ec60f02c-92ef-4479-a659-3ab1617e862a | Idioma detectado: en
✅ ec60f02c-92ef-4479-a659-3ab1617e862a ya está en inglés. Saltando...
🧐 Procesando 12868/17048 - 9e6d5e98-38d2-491f-aab6-a48c260eb00e | Idioma detectado: en
✅ 9e6d5e98-38d2-491f-aab6-a48c260eb00e ya está en inglés. Saltando...
🧐 Procesando 12869/17048 - 37f72abb-ced4-472b-b2e5-1a50a5044cbf | Idioma detectado: en
✅ 37f72abb-ced4-472b-b2e5-1a50a5044cbf ya está en inglés. Saltando...
🧐 Procesando 12870/17048 - 45129b52-afc5-42b7-bd9e-d7faacc4bfa0 | Idioma detectado: de

🔄 Traduciendo canciones:  76%|███████▌  | 12890/17048 [1:00:52<1:21:26,  1.18s/it]

✅ 489d97f7-3c86-4a5b-abde-b1a7fe627edd ya está en inglés. Saltando...
🧐 Procesando 12878/17048 - a147e4c5-b893-45c7-bcbd-291251d1d706 | Idioma detectado: en
✅ a147e4c5-b893-45c7-bcbd-291251d1d706 ya está en inglés. Saltando...
🧐 Procesando 12879/17048 - d1ed8776-92b3-480e-9778-a7e5a5ea238b | Idioma detectado: en
✅ d1ed8776-92b3-480e-9778-a7e5a5ea238b ya está en inglés. Saltando...
🧐 Procesando 12880/17048 - 10cedbba-ccc5-4f47-b541-8c6b9edd1bb6 | Idioma detectado: en
✅ 10cedbba-ccc5-4f47-b541-8c6b9edd1bb6 ya está en inglés. Saltando...
🧐 Procesando 12881/17048 - feaa192e-7e91-4198-8dee-9bc05ce69f98 | Idioma detectado: en
✅ feaa192e-7e91-4198-8dee-9bc05ce69f98 ya está en inglés. Saltando...
🧐 Procesando 12882/17048 - 4f31b421-0954-49ef-8a82-8be29e6f7d70 | Idioma detectado: en
✅ 4f31b421-0954-49ef-8a82-8be29e6f7d70 ya está en inglés. Saltando...
🧐 Procesando 12883/17048 - f2a02539-8b89-4a95-a833-31fc92fd4fa4 | Idioma detectado: en
✅ f2a02539-8b89-4a95-a833-31fc92fd4fa4 ya está en inglés. Saltando...
🧐 Procesando 12884/17048 - 3cb540d3-e021-41f4-b299-78b9a150b29d | Idioma detectado: de
🧐 Procesando 12885/17048 - 7eb6becc-51eb-4247-9500-4549f39b29dc | Idioma detectado: de
🧐 Procesando 12886/17048 - a68389ad-bd18-43c9-9572-c4ac6098346e | Idioma detectado: de
🧐 Procesando 12887/17048 - 8e75e068-a7d5-48be-82a8-2a4b3a026f0b | Idioma detectado: de
🧐 Procesando 12888/17048 - 5c2f3ea7-b0cf-4a5e-baeb-1ebf3b0e4b05 | Idioma detectado: de
🧐 Procesando 12889/17048 - efbfe0b8-5295-4091-a7a3-6e37b162885d | Idioma detectado: de
🧐 Procesando 12890/17048 - fb43aa22-b7b4-48c1-8883-dfd9a0b42710 | Idioma detectado: de

🔄 Traduciendo canciones:  76%|███████▌  | 12901/17048 [1:01:14<2:57:22,  2.57s/it]

🧐 Procesando 12884/17048 - 3cb540d3-e021-41f4-b299-78b9a150b29d | Idioma detectado: de
🧐 Procesando 12885/17048 - 7eb6becc-51eb-4247-9500-4549f39b29dc | Idioma detectado: de
🧐 Procesando 12886/17048 - a68389ad-bd18-43c9-9572-c4ac6098346e | Idioma detectado: de
🧐 Procesando 12887/17048 - 8e75e068-a7d5-48be-82a8-2a4b3a026f0b | Idioma detectado: de
🧐 Procesando 12888/17048 - 5c2f3ea7-b0cf-4a5e-baeb-1ebf3b0e4b05 | Idioma detectado: de
🧐 Procesando 12889/17048 - efbfe0b8-5295-4091-a7a3-6e37b162885d | Idioma detectado: de
🧐 Procesando 12890/17048 - fb43aa22-b7b4-48c1-8883-dfd9a0b42710 | Idioma detectado: de
🧐 Procesando 12891/17048 - d3a3e393-7af2-4b1f-a5a0-6b0090ba4d1d | Idioma detectado: de
🧐 Procesando 12892/17048 - 9f2803a3-97ce-4ce3-b97c-3c289e3784f3 | Idioma detectado: de
🧐 Procesando 12893/17048 - 549c7847-2a44-40fa-ba52-4ed9b275fd55 | Idioma detectado: de
🧐 Procesando 12894/17048 - dae483f1-df99-403e-bd1a-38df93ec32d6 | Idioma detectado: en
✅ dae483f1-df99-403e-bd1a-38df93ec32d6 ya está en inglés. Saltando...
🧐 Procesando 12895/17048 - 340a64fb-8cdd-4990-9af1-3837958cc340 | Idioma detectado: en
✅ 340a64fb-8cdd-4990-9af1-3837958cc340 ya está en inglés. Saltando...
🧐 Procesando 12896/17048 - 924acb9d-7dd8-4463-8dda-de813c503456 | Idioma detectado: en
✅ 924acb9d-7dd8-4463-8dda-de813c503456 ya está en inglés. Saltando...
🧐 Procesando 12897/17048 - 28b33b12-f7d3-4a36-abf3-02e8ea5d0bd1 | Idioma detectado: de
🧐 Procesando 12898/17048 - e119e5e6-bdcc-4178-b360-add7bf2100a8 | Idioma detectado: de
🧐 Procesando 12899/17048 - 4d53caf9-b0d2-4ee6-b936-a41463224125 | Idioma detectado: de
🧐 Procesando 12900/17048 - 0e470f2f-b367-4e56-a5f3-984e25a09fbc | Idioma detectado: de

🔄 Traduciendo canciones:  76%|███████▌  | 12940/17048 [1:02:05<51:09,  1.34it/s]

🧐 Procesando 12929/17048 - 75dd3511-6336-49be-ad6e-1e5abc1e595a | Idioma detectado: en
✅ 75dd3511-6336-49be-ad6e-1e5abc1e595a ya está en inglés. Saltando...
🧐 Procesando 12930/17048 - 8632caf8-3928-4c9b-9139-a88f731d4b2e | Idioma detectado: en
✅ 8632caf8-3928-4c9b-9139-a88f731d4b2e ya está en inglés. Saltando...
🧐 Procesando 12931/17048 - dac09ea5-5a92-43d2-8a80-c57ef542ef00 | Idioma detectado: de
🧐 Procesando 12932/17048 - ac610b93-f15c-4cfd-88a4-48d6dab66259 | Idioma detectado: en
✅ ac610b93-f15c-4cfd-88a4-48d6dab66259 ya está en inglés. Saltando...
🧐 Procesando 12933/17048 - 6ee04b8e-b974-4d53-8388-2717995e7aee | Idioma detectado: en
✅ 6ee04b8e-b974-4d53-8388-2717995e7aee ya está en inglés. Saltando...
🧐 Procesando 12934/17048 - 750199f7-dfab-462d-bcca-681cde68536a | Idioma detectado: de
🧐 Procesando 12935/17048 - 2da15d30-e45b-4077-8546-69e56aae2c35 | Idioma detectado: en
✅ 2da15d30-e45b-4077-8546-69e56aae2c35 ya está en inglés. Saltando...
🧐 Procesando 12936/17048 - 45b52995-7172-41b9-9ca7-1e3cd4644c3d | Idioma detectado: en
✅ 45b52995-7172-41b9-9ca7-1e3cd4644c3d ya está en inglés. Saltando...
🧐 Procesando 12937/17048 - efb3c2ec-44d0-456b-8164-67c816ab8d66 | Idioma detectado: en
✅ efb3c2ec-44d0-456b-8164-67c816ab8d66 ya está en inglés. Saltando...
🧐 Procesando 12938/17048 - 1e65516e-8845-427b-8f76-641828f54951 | Idioma detectado: en
✅ 1e65516e-8845-427b-8f76-641828f54951 ya está en inglés. Saltando...
🧐 Procesando 12939/17048 - 2a3cff62-2cbc-447f-b3ad-5eb67997f5bd | Idioma detectado: de
🧐 Procesando 12940/17048 - 9efb6267-c72d-4ada-8fe1-2f5a786d6edd | Idioma detectado: de

🔄 Traduciendo canciones:  76%|███████▌  | 12951/17048 [1:03:18<5:32:38,  4.87s/it]

✅ 2da15d30-e45b-4077-8546-69e56aae2c35 ya está en inglés. Saltando...
🧐 Procesando 12936/17048 - 45b52995-7172-41b9-9ca7-1e3cd4644c3d | Idioma detectado: en
✅ 45b52995-7172-41b9-9ca7-1e3cd4644c3d ya está en inglés. Saltando...
🧐 Procesando 12937/17048 - efb3c2ec-44d0-456b-8164-67c816ab8d66 | Idioma detectado: en
✅ efb3c2ec-44d0-456b-8164-67c816ab8d66 ya está en inglés. Saltando...
🧐 Procesando 12938/17048 - 1e65516e-8845-427b-8f76-641828f54951 | Idioma detectado: en
✅ 1e65516e-8845-427b-8f76-641828f54951 ya está en inglés. Saltando...
🧐 Procesando 12939/17048 - 2a3cff62-2cbc-447f-b3ad-5eb67997f5bd | Idioma detectado: de
🧐 Procesando 12940/17048 - 9efb6267-c72d-4ada-8fe1-2f5a786d6edd | Idioma detectado: de
🧐 Procesando 12941/17048 - 48e4a022-c139-41b5-a1a0-a59ed2de0813 | Idioma detectado: de
🧐 Procesando 12942/17048 - 6db41332-c1ad-49c5-9027-dd0a80ce871c | Idioma detectado: de
🧐 Procesando 12943/17048 - 5349f223-4724-4975-8e5b-967ff669e5e7 | Idioma detectado: de
🧐 Procesando 12944/17048 - 7e5ac541-3c55-4bcf-aced-4ae3ec581d89 | Idioma detectado: de
🧐 Procesando 12945/17048 - b6c0e5b8-974a-4e6c-98a6-65e60fb5aead | Idioma detectado: de
🧐 Procesando 12946/17048 - bd733dbc-e219-4aed-acaa-988721d629cf | Idioma detectado: de
🧐 Procesando 12947/17048 - 4b505a9d-8a66-43ab-a386-eb7e4b0d1989 | Idioma detectado: de
🧐 Procesando 12948/17048 - 3a3f8d7b-5b93-4e72-a1ef-b13a36688371 | Idioma detectado: de
🧐 Procesando 12949/17048 - f1c06d38-f45d-4ed1-9ff8-5f30b2c91396 | Idioma detectado: en
✅ f1c06d38-f45d-4ed1-9ff8-5f30b2c91396 ya está en inglés. Saltando...
🧐 Procesando 12950/17048 - 3454f2c4-4011-4fa5-b239-f02ca1072669 | Idioma detectado: de

🔄 Traduciendo canciones:  76%|███████▌  | 12971/17048 [1:03:41<1:28:10,  1.30s/it]

✅ 28599e48-f466-4bcf-9bb4-f6569969b2e5 ya está en inglés. Saltando...
🧐 Procesando 12959/17048 - 21411ed0-b565-405e-98ec-f13e5786e1b4 | Idioma detectado: en
✅ 21411ed0-b565-405e-98ec-f13e5786e1b4 ya está en inglés. Saltando...
🧐 Procesando 12960/17048 - c2891908-0f06-4f16-9c31-95458cf2d198 | Idioma detectado: en
✅ c2891908-0f06-4f16-9c31-95458cf2d198 ya está en inglés. Saltando...
🧐 Procesando 12961/17048 - fd7e5a54-d0c6-43c5-b18e-751bef93faa3 | Idioma detectado: de
🧐 Procesando 12962/17048 - d3910b0b-ff22-4413-b98a-95d5f7236728 | Idioma detectado: de
🧐 Procesando 12963/17048 - 166b0817-141d-422d-a8e8-0e1bad65d1d6 | Idioma detectado: en
✅ 166b0817-141d-422d-a8e8-0e1bad65d1d6 ya está en inglés. Saltando...
🧐 Procesando 12964/17048 - a9905e85-ac12-4e92-9294-8406e9b64361 | Idioma detectado: en
✅ a9905e85-ac12-4e92-9294-8406e9b64361 ya está en inglés. Saltando...
🧐 Procesando 12965/17048 - 127c4d1e-0dca-456a-96d6-a42a93557821 | Idioma detectado: en
✅ 127c4d1e-0dca-456a-96d6-a42a93557821 ya está en inglés. Saltando...
🧐 Procesando 12966/17048 - 847940c2-6935-4daf-9467-3079d805da93 | Idioma detectado: fr
🧐 Procesando 12967/17048 - eca528b4-c872-4512-808f-132cfc7cff0e | Idioma detectado: en
✅ eca528b4-c872-4512-808f-132cfc7cff0e ya está en inglés. Saltando...
🧐 Procesando 12968/17048 - c7578ec9-e209-42d0-b81b-f0aadc08a3b9 | Idioma detectado: en
✅ c7578ec9-e209-42d0-b81b-f0aadc08a3b9 ya está en inglés. Saltando...
🧐 Procesando 12969/17048 - 686b19a5-69b0-423c-b0da-c0927bafe20c | Idioma detectado: fr
🧐 Procesando 12970/17048 - ec64c085-c19e-4036-9fd2-0956b331b187 | Idioma detectado: fr

🔄 Traduciendo canciones:  76%|███████▋  | 13001/17048 [1:03:54<33:21,  2.02it/s]

🧐 Procesando 12990/17048 - 33f514c9-4550-4666-86e4-9f6ef888df20 | Idioma detectado: en
✅ 33f514c9-4550-4666-86e4-9f6ef888df20 ya está en inglés. Saltando...
🧐 Procesando 12991/17048 - 873763e6-be19-4fe9-bbf6-b395957a202a | Idioma detectado: en
✅ 873763e6-be19-4fe9-bbf6-b395957a202a ya está en inglés. Saltando...
🧐 Procesando 12992/17048 - 26772aff-3075-44e0-9d3d-6f690d577333 | Idioma detectado: en
✅ 26772aff-3075-44e0-9d3d-6f690d577333 ya está en inglés. Saltando...
🧐 Procesando 12993/17048 - 3f93c1c7-a78c-43e0-b7a5-a848c2e55a53 | Idioma detectado: en
✅ 3f93c1c7-a78c-43e0-b7a5-a848c2e55a53 ya está en inglés. Saltando...
🧐 Procesando 12994/17048 - 3038bc51-f532-46a9-be6d-bcdb957042a2 | Idioma detectado: en
✅ 3038bc51-f532-46a9-be6d-bcdb957042a2 ya está en inglés. Saltando...
🧐 Procesando 12995/17048 - 8ff7d14a-569d-4e40-a339-4ff53458c90e | Idioma detectado: en
✅ 8ff7d14a-569d-4e40-a339-4ff53458c90e ya está en inglés. Saltando...
🧐 Procesando 12996/17048 - 30c0427b-6413-4253-9caa-c1b49c0b1bb4 | Idioma detectado: en
✅ 30c0427b-6413-4253-9caa-c1b49c0b1bb4 ya está en inglés. Saltando...
🧐 Procesando 12997/17048 - e55bac92-ef82-4100-9991-da546c5c7c16 | Idioma detectado: en
✅ e55bac92-ef82-4100-9991-da546c5c7c16 ya está en inglés. Saltando...
🧐 Procesando 12998/17048 - 7938c29d-a709-433c-94df-7effe25bcf59 | Idioma detectado: de
🧐 Procesando 12999/17048 - f5bc3bc3-adaa-40ec-8fa2-0a38d6d40587 | Idioma detectado: en
✅ f5bc3bc3-adaa-40ec-8fa2-0a38d6d40587 ya está en inglés. Saltando...
🧐 Procesando 13000/17048 - 6b7406cc-b044-4129-8138-fd4a444b07aa | Idioma detectado: de

🔄 Traduciendo canciones:  76%|███████▋  | 13029/17048 [1:04:23<36:27,  1.84it/s]

✅ 5e5d3960-9a2b-4d5d-b544-ff8edd9086b2 ya está en inglés. Saltando...
🧐 Procesando 13031/17048 - 98654958-b13c-40ff-8c77-33b55057fe58 | Idioma detectado: en
✅ 98654958-b13c-40ff-8c77-33b55057fe58 ya está en inglés. Saltando...
🧐 Procesando 13032/17048 - 73fc0699-56ed-45a6-82aa-968b7e3e54e8 | Idioma detectado: en
✅ 73fc0699-56ed-45a6-82aa-968b7e3e54e8 ya está en inglés. Saltando...
🧐 Procesando 13033/17048 - d77fd8b1-c02f-49d8-9ed5-a2a9845eed26 | Idioma detectado: en
✅ d77fd8b1-c02f-49d8-9ed5-a2a9845eed26 ya está en inglés. Saltando...
🧐 Procesando 13034/17048 - 5a7165ed-5a6e-4c4e-af85-af876b987379 | Idioma detectado: en
✅ 5a7165ed-5a6e-4c4e-af85-af876b987379 ya está en inglés. Saltando...
🧐 Procesando 13035/17048 - 604409d6-d73f-4468-ba1a-3721256a6f96 | Idioma detectado: en
✅ 604409d6-d73f-4468-ba1a-3721256a6f96 ya está en inglés. Saltando...
🧐 Procesando 13036/17048 - 96a1bcf3-0020-467a-a308-1aa641083122 | Idioma detectado: en
✅ 96a1bcf3-0020-467a-a308-1aa641083122 ya está en inglés. Saltando...
🧐 Procesando 13037/17048 - 82651d8c-c7b2-4c38-8bc5-e5f580942b5a | Idioma detectado: en
✅ 82651d8c-c7b2-4c38-8bc5-e5f580942b5a ya está en inglés. Saltando...
🧐 Procesando 13038/17048 - 11ee6987-b89f-409d-b3b5-53caa0a8feaa | Idioma detectado: en
✅ 11ee6987-b89f-409d-b3b5-53caa0a8feaa ya está en inglés. Saltando...
🧐 Procesando 13039/17048 - 46fab129-33d1-4fa3-9ce8-1782312508a9 | Idioma detectado: en
✅ 46fab129-33d1-4fa3-9ce8-1782312508a9 ya está en inglés. Saltando...
🧐 Procesando 13040/17048 - 90b65af0-d742-4530-8072-d8a90aa277b2 | Idioma detectado: de

🔄 Traduciendo canciones:  77%|███████▋  | 13070/17048 [1:05:16<56:58,  1.16it/s]

🧐 Procesando 13059/17048 - 53af01ba-28e9-4492-8ec9-fec8f5381368 | Idioma detectado: en
✅ 53af01ba-28e9-4492-8ec9-fec8f5381368 ya está en inglés. Saltando...
🧐 Procesando 13060/17048 - 54bf4afb-9698-4eac-ba76-6ad76d1b59bb | Idioma detectado: en
✅ 54bf4afb-9698-4eac-ba76-6ad76d1b59bb ya está en inglés. Saltando...
🧐 Procesando 13061/17048 - be0ffea1-a911-4b57-b27c-c1b5b2a96e60 | Idioma detectado: en
✅ be0ffea1-a911-4b57-b27c-c1b5b2a96e60 ya está en inglés. Saltando...
🧐 Procesando 13062/17048 - b27df405-a160-44a7-8929-619d1f9bd7df | Idioma detectado: en
✅ b27df405-a160-44a7-8929-619d1f9bd7df ya está en inglés. Saltando...
🧐 Procesando 13063/17048 - 59921b3a-d861-48d4-8fb8-edc5760b273d | Idioma detectado: en
✅ 59921b3a-d861-48d4-8fb8-edc5760b273d ya está en inglés. Saltando...
🧐 Procesando 13064/17048 - 789dc5f7-0628-464b-9964-f9dd9cf31c51 | Idioma detectado: en
✅ 789dc5f7-0628-464b-9964-f9dd9cf31c51 ya está en inglés. Saltando...
🧐 Procesando 13065/17048 - 5b09b94d-a5e2-4fd1-8c61-a95d62bddc9e | Idioma detectado: en
✅ 5b09b94d-a5e2-4fd1-8c61-a95d62bddc9e ya está en inglés. Saltando...
🧐 Procesando 13066/17048 - e4c25264-0911-446e-8e29-c55764ca9661 | Idioma detectado: en
✅ e4c25264-0911-446e-8e29-c55764ca9661 ya está en inglés. Saltando...
🧐 Procesando 13067/17048 - bf75d510-9e64-4293-9f30-5f26fd4f2e8a | Idioma detectado: de
🧐 Procesando 13068/17048 - e6d5680a-92d2-4a3c-9a3a-d5407f5ed1c6 | Idioma detectado: de
🧐 Procesando 13069/17048 - 55ac325c-803a-4fe5-9c6e-095a0b1cc1ed | Idioma detectado: de
🧐 Procesando 13070/17048 - b803ec6e-ebc2-4ee0-a12b-b84fafc23c64 | Idioma detectado: de

🔄 Traduciendo canciones:  77%|███████▋  | 13088/17048 [1:05:51<2:40:19,  2.43s/it]

🧐 Procesando 13077/17048 - 536dba08-b304-4eb1-aa5a-2ceb5acae271 | Idioma detectado: de
🧐 Procesando 13078/17048 - 1566f05f-7573-455a-8c10-a6b88afb5bb0 | Idioma detectado: en
✅ 1566f05f-7573-455a-8c10-a6b88afb5bb0 ya está en inglés. Saltando...
🧐 Procesando 13079/17048 - fd515a5d-b6e7-4d34-87c3-b10b35ea542c | Idioma detectado: de
🧐 Procesando 13080/17048 - 86664076-5e58-4b0a-a14b-7ff2ca8e2e6f | Idioma detectado: en
✅ 86664076-5e58-4b0a-a14b-7ff2ca8e2e6f ya está en inglés. Saltando...
🧐 Procesando 13081/17048 - 7d9d86ea-1a67-4b34-9c2e-0ddd3bda5818 | Idioma detectado: de
🧐 Procesando 13082/17048 - 19e9d351-5cce-42a5-a011-293091ee7653 | Idioma detectado: en
✅ 19e9d351-5cce-42a5-a011-293091ee7653 ya está en inglés. Saltando...
🧐 Procesando 13083/17048 - b017720d-709b-45a6-b4b4-960146d84683 | Idioma detectado: de
🧐 Procesando 13084/17048 - ebe29d4c-62fb-4c60-a5af-1a1446709112 | Idioma detectado: en
✅ ebe29d4c-62fb-4c60-a5af-1a1446709112 ya está en inglés. Saltando...
🧐 Procesando 13085/17048 - dbfaaf37-245d-49b8-807e-37346c21599b | Idioma detectado: de
🧐 Procesando 13086/17048 - ae716a7c-57f7-4df9-b1a9-ef02bd117886 | Idioma detectado: de
🧐 Procesando 13087/17048 - 3e841f1a-0d68-4d74-b52d-b060a53b3fa0 | Idioma detectado: de
🧐 Procesando 13088/17048 - ad100a26-2de5-4201-a39f-68e59c0d64ef | Idioma detectado: en
✅ ad100a26-2de5-4201-a39f-68e59c0d64ef ya está en inglés. Saltando...
🧐 Procesando 13089/17048 - 5dae859c-7029-4724-9277-05a7ecf07a2f | Idioma detectado: en
✅ 5dae859c-7029-4724-9277-05a7ecf07a2f ya está en inglés. Saltando...
🧐 Procesando 13090/17048 - 350a6a63-c6a3-433b-a5fb-95074960174a | Idioma detectado: de

🔄 Traduciendo canciones:  77%|███████▋  | 13100/17048 [1:06:30<4:21:45,  3.98s/it]

🧐 Procesando 13084/17048 - ebe29d4c-62fb-4c60-a5af-1a1446709112 | Idioma detectado: en
✅ ebe29d4c-62fb-4c60-a5af-1a1446709112 ya está en inglés. Saltando...
🧐 Procesando 13085/17048 - dbfaaf37-245d-49b8-807e-37346c21599b | Idioma detectado: de
🧐 Procesando 13086/17048 - ae716a7c-57f7-4df9-b1a9-ef02bd117886 | Idioma detectado: de
🧐 Procesando 13087/17048 - 3e841f1a-0d68-4d74-b52d-b060a53b3fa0 | Idioma detectado: de
🧐 Procesando 13088/17048 - ad100a26-2de5-4201-a39f-68e59c0d64ef | Idioma detectado: en
✅ ad100a26-2de5-4201-a39f-68e59c0d64ef ya está en inglés. Saltando...
🧐 Procesando 13089/17048 - 5dae859c-7029-4724-9277-05a7ecf07a2f | Idioma detectado: en
✅ 5dae859c-7029-4724-9277-05a7ecf07a2f ya está en inglés. Saltando...
🧐 Procesando 13090/17048 - 350a6a63-c6a3-433b-a5fb-95074960174a | Idioma detectado: de
🧐 Procesando 13091/17048 - eccfdf8c-2615-4786-8260-31cfea446923 | Idioma detectado: de
🧐 Procesando 13092/17048 - 5f2e1d92-1ef7-4150-8bb0-4cac76232b4b | Idioma detectado: de
🧐 Procesando 13093/17048 - 4efa456d-8422-453e-a6d1-9672bf3de325 | Idioma detectado: de
🧐 Procesando 13094/17048 - 2a80514a-4a59-461f-a0de-29b2ee77e62a | Idioma detectado: de
🧐 Procesando 13095/17048 - e69918d7-e6eb-4d3a-992e-942aa383f00b | Idioma detectado: de
🧐 Procesando 13096/17048 - d6440299-06be-4ff5-9d03-718d3e5d1c81 | Idioma detectado: de
🧐 Procesando 13097/17048 - 7eb29e8d-2736-4e3e-a80b-21b193ae75ec | Idioma detectado: de
🧐 Procesando 13098/17048 - f71fa29a-7ff0-4173-9404-b5f97744c143 | Idioma detectado: de
🧐 Procesando 13099/17048 - 1fab4ff8-f1f5-4207-8bb4-e8b786138338 | Idioma detectado: de
🧐 Procesando 13100/17048 - c2b9b5d8-1b45-45b4-9f87-ed44ba408330 | Idioma detectado: de

🔄 Traduciendo canciones:  77%|███████▋  | 13121/17048 [1:07:17<3:09:03,  2.89s/it]

🧐 Procesando 13105/17048 - 1e3623fc-af55-4af1-b084-c22155ee40bd | Idioma detectado: de
🧐 Procesando 13106/17048 - 52663a51-b95c-4144-90eb-53deeb3ab149 | Idioma detectado: de
🧐 Procesando 13107/17048 - 6218b870-ae5b-4363-97f1-5ac8b49ed807 | Idioma detectado: de
🧐 Procesando 13108/17048 - 0856c5e8-6b4c-45eb-9ec3-375a4c21605b | Idioma detectado: de
🧐 Procesando 13109/17048 - 3851669b-99d5-4d58-8d8b-ac12c1d850c4 | Idioma detectado: de
🧐 Procesando 13110/17048 - 0c3937f6-a520-483c-99cf-949e243c1f3c | Idioma detectado: en
✅ 0c3937f6-a520-483c-99cf-949e243c1f3c ya está en inglés. Saltando...
🧐 Procesando 13111/17048 - cef74993-8039-461e-b3aa-10c6b731a01d | Idioma detectado: en
✅ cef74993-8039-461e-b3aa-10c6b731a01d ya está en inglés. Saltando...
🧐 Procesando 13112/17048 - 14350a10-4dbc-4896-82a6-1a60e5acda6b | Idioma detectado: en
✅ 14350a10-4dbc-4896-82a6-1a60e5acda6b ya está en inglés. Saltando...
🧐 Procesando 13113/17048 - 227cdac5-f6ab-47de-afae-5799dbfd91a2 | Idioma detectado: en
✅ 227cdac5-f6ab-47de-afae-5799dbfd91a2 ya está en inglés. Saltando...
🧐 Procesando 13114/17048 - 087fc1cc-8b1f-40ef-8f02-f0da47ecb359 | Idioma detectado: de
🧐 Procesando 13115/17048 - 135996df-3973-4a85-bf46-1407936bf73b | Idioma detectado: de
🧐 Procesando 13116/17048 - 86ffb281-b3bc-4c2d-bf36-16aa88300dc7 | Idioma detectado: de
🧐 Procesando 13117/17048 - 5f09f9ce-24a9-472b-8def-4b5f39979dbd | Idioma detectado: de
🧐 Procesando 13118/17048 - fb975e97-6595-4b55-8a6a-3528e2be1bf4 | Idioma detectado: de
🧐 Procesando 13119/17048 - 2a6586b0-9701-47f8-a10d-682283d16c80 | Idioma detectado: de
🧐 Procesando 13120/17048 - c5a1bacf-0eea-4f61-9fea-c219ab274a14 | Idioma detectado: de

🔄 Traduciendo canciones:  77%|███████▋  | 13130/17048 [1:07:41<3:12:57,  2.95s/it]

✅ 14350a10-4dbc-4896-82a6-1a60e5acda6b ya está en inglés. Saltando...
🧐 Procesando 13113/17048 - 227cdac5-f6ab-47de-afae-5799dbfd91a2 | Idioma detectado: en
✅ 227cdac5-f6ab-47de-afae-5799dbfd91a2 ya está en inglés. Saltando...
🧐 Procesando 13114/17048 - 087fc1cc-8b1f-40ef-8f02-f0da47ecb359 | Idioma detectado: de
🧐 Procesando 13115/17048 - 135996df-3973-4a85-bf46-1407936bf73b | Idioma detectado: de
🧐 Procesando 13116/17048 - 86ffb281-b3bc-4c2d-bf36-16aa88300dc7 | Idioma detectado: de
🧐 Procesando 13117/17048 - 5f09f9ce-24a9-472b-8def-4b5f39979dbd | Idioma detectado: de
🧐 Procesando 13118/17048 - fb975e97-6595-4b55-8a6a-3528e2be1bf4 | Idioma detectado: de
🧐 Procesando 13119/17048 - 2a6586b0-9701-47f8-a10d-682283d16c80 | Idioma detectado: de
🧐 Procesando 13120/17048 - c5a1bacf-0eea-4f61-9fea-c219ab274a14 | Idioma detectado: de
🧐 Procesando 13121/17048 - b825f3b4-8123-4b00-8201-fcec4ceb36c2 | Idioma detectado: de
🧐 Procesando 13122/17048 - e797739d-6ed4-4e0e-8470-703915f5f574 | Idioma detectado: de
🧐 Procesando 13123/17048 - 1f22278d-d74a-4fb7-b0a8-57a122151002 | Idioma detectado: de
🧐 Procesando 13124/17048 - 8289800f-acb5-4fff-b0d6-79105dc2b1ce | Idioma detectado: de
🧐 Procesando 13125/17048 - 990960f9-9e79-4e3f-aed2-24b9abe68bf6 | Idioma detectado: de
🧐 Procesando 13126/17048 - bad00d85-009a-4400-b35e-26d540a89280 | Idioma detectado: de
🧐 Procesando 13127/17048 - e9733e1c-e8c8-48f8-8f32-1875435fb62f | Idioma detectado: de
🧐 Procesando 13128/17048 - c7c1879a-4956-411e-8058-ddf813a4e14d | Idioma detectado: de
🧐 Procesando 13129/17048 - 8cd57e36-c97c-4dcb-a06f-2fe8000e9544 | Idioma detectado: de
🧐 Procesando 13130/17048 - 6c61e85a-d684-4dfe-bd33-7fecc2e2cc92 | Idioma detectado: de

🔄 Traduciendo canciones:  77%|███████▋  | 13140/17048 [1:08:13<3:13:43,  2.97s/it]

🧐 Procesando 13121/17048 - b825f3b4-8123-4b00-8201-fcec4ceb36c2 | Idioma detectado: de
🧐 Procesando 13122/17048 - e797739d-6ed4-4e0e-8470-703915f5f574 | Idioma detectado: de
🧐 Procesando 13123/17048 - 1f22278d-d74a-4fb7-b0a8-57a122151002 | Idioma detectado: de
🧐 Procesando 13124/17048 - 8289800f-acb5-4fff-b0d6-79105dc2b1ce | Idioma detectado: de
🧐 Procesando 13125/17048 - 990960f9-9e79-4e3f-aed2-24b9abe68bf6 | Idioma detectado: de
🧐 Procesando 13126/17048 - bad00d85-009a-4400-b35e-26d540a89280 | Idioma detectado: de
🧐 Procesando 13127/17048 - e9733e1c-e8c8-48f8-8f32-1875435fb62f | Idioma detectado: de
🧐 Procesando 13128/17048 - c7c1879a-4956-411e-8058-ddf813a4e14d | Idioma detectado: de
🧐 Procesando 13129/17048 - 8cd57e36-c97c-4dcb-a06f-2fe8000e9544 | Idioma detectado: de
🧐 Procesando 13130/17048 - 6c61e85a-d684-4dfe-bd33-7fecc2e2cc92 | Idioma detectado: de
🧐 Procesando 13131/17048 - af9f5ca0-d3fb-445e-bf0a-c195abba4758 | Idioma detectado: de
🧐 Procesando 13132/17048 - fda0ff8c-7d15-460b-a22e-fc47a898e70a | Idioma detectado: de
🧐 Procesando 13133/17048 - f00784d1-a909-45ea-a75a-b2aecc293e32 | Idioma detectado: de
🧐 Procesando 13134/17048 - ebbe460e-367b-4f47-ae04-ef44435fcde3 | Idioma detectado: de
🧐 Procesando 13135/17048 - dc309228-6b7c-47d3-bda3-d88efde1eb76 | Idioma detectado: de
🧐 Procesando 13136/17048 - daf7784f-88a4-41af-ae18-5c9facf7116a | Idioma detectado: de
🧐 Procesando 13137/17048 - 22958837-4d62-4e1c-9ac3-ac592f9acbba | Idioma detectado: de
🧐 Procesando 13138/17048 - e39e8a72-168c-46d0-8d63-65801a3b8850 | Idioma detectado: de
🧐 Procesando 13139/17048 - 01874145-dec1-4896-8c60-a2be290e4e83 | Idioma detectado: de
🧐 Procesando 13140/17048 - f1ac6301-c3e0-4f31-91ee-3d0046b00d3f | Idioma detectado: de

🔄 Traduciendo canciones:  77%|███████▋  | 13150/17048 [1:08:37<3:07:59,  2.89s/it]

🧐 Procesando 13131/17048 - af9f5ca0-d3fb-445e-bf0a-c195abba4758 | Idioma detectado: de
🧐 Procesando 13132/17048 - fda0ff8c-7d15-460b-a22e-fc47a898e70a | Idioma detectado: de
🧐 Procesando 13133/17048 - f00784d1-a909-45ea-a75a-b2aecc293e32 | Idioma detectado: de
🧐 Procesando 13134/17048 - ebbe460e-367b-4f47-ae04-ef44435fcde3 | Idioma detectado: de
🧐 Procesando 13135/17048 - dc309228-6b7c-47d3-bda3-d88efde1eb76 | Idioma detectado: de
🧐 Procesando 13136/17048 - daf7784f-88a4-41af-ae18-5c9facf7116a | Idioma detectado: de
🧐 Procesando 13137/17048 - 22958837-4d62-4e1c-9ac3-ac592f9acbba | Idioma detectado: de
🧐 Procesando 13138/17048 - e39e8a72-168c-46d0-8d63-65801a3b8850 | Idioma detectado: de
🧐 Procesando 13139/17048 - 01874145-dec1-4896-8c60-a2be290e4e83 | Idioma detectado: de
🧐 Procesando 13140/17048 - f1ac6301-c3e0-4f31-91ee-3d0046b00d3f | Idioma detectado: de
🧐 Procesando 13141/17048 - fef0ee46-2867-4df4-92f7-8dc55982aef2 | Idioma detectado: de
🧐 Procesando 13142/17048 - ad24f26f-c826-4ae8-924b-20a0e72653e8 | Idioma detectado: de
🧐 Procesando 13143/17048 - 4a00db4b-2500-42b4-9d2c-a126acb1ecc7 | Idioma detectado: de
🧐 Procesando 13144/17048 - c27ce6ca-8d18-4bf1-8a74-bde397d0248c | Idioma detectado: de
🧐 Procesando 13145/17048 - 694600bc-ad81-41b1-bf65-184935800481 | Idioma detectado: de
🧐 Procesando 13146/17048 - 1c25e113-2b7c-4de9-bc15-eeeb594ca981 | Idioma detectado: de
🧐 Procesando 13147/17048 - a3f33aba-cf6c-44a9-b928-dad02c5308b8 | Idioma detectado: de
🧐 Procesando 13148/17048 - eb6839b4-e1d3-4f14-9562-b6ff0408a2c0 | Idioma detectado: de
🧐 Procesando 13149/17048 - be1f3007-e98b-4d67-bc73-92db1a2152b0 | Idioma detectado: de
🧐 Procesando 13150/17048 - 4e316109-e815-4f94-b636-d3a83ef7dbae | Idioma detectado: de

🔄 Traduciendo canciones:  77%|███████▋  | 13170/17048 [1:09:23<1:40:17,  1.55s/it]

🧐 Procesando 13157/17048 - aa162879-fa40-4407-b74d-63fbc76c9869 | Idioma detectado: de
🧐 Procesando 13158/17048 - b67cf106-6a37-41ed-9eb4-cf60c7a338ee | Idioma detectado: de
🧐 Procesando 13159/17048 - e7888ccd-8bc8-4a31-8f28-b5fcfc851d29 | Idioma detectado: de
🧐 Procesando 13160/17048 - 0085f81b-f02c-4d4d-9df1-5096f7dc8d8a | Idioma detectado: en
✅ 0085f81b-f02c-4d4d-9df1-5096f7dc8d8a ya está en inglés. Saltando...
🧐 Procesando 13161/17048 - 185ca972-6992-4730-9170-c7bac42eb497 | Idioma detectado: de
🧐 Procesando 13162/17048 - b531f637-9a08-4e67-b9b5-6792729e7361 | Idioma detectado: de
🧐 Procesando 13163/17048 - daa0a94e-1d4d-45fa-a82a-150230a92cfe | Idioma detectado: en
✅ daa0a94e-1d4d-45fa-a82a-150230a92cfe ya está en inglés. Saltando...
🧐 Procesando 13164/17048 - 8393ba9b-e694-4081-a96f-33b6e86352af | Idioma detectado: en
✅ 8393ba9b-e694-4081-a96f-33b6e86352af ya está en inglés. Saltando...
🧐 Procesando 13165/17048 - 78335697-db09-43b1-a9ef-1a4411317236 | Idioma detectado: en
✅ 78335697-db09-43b1-a9ef-1a4411317236 ya está en inglés. Saltando...
🧐 Procesando 13166/17048 - 5c922649-10d9-4417-b121-56d44eee859a | Idioma detectado: en
✅ 5c922649-10d9-4417-b121-56d44eee859a ya está en inglés. Saltando...
🧐 Procesando 13167/17048 - c3e1e006-d1e8-4f16-82b6-48d8fd74b238 | Idioma detectado: en
✅ c3e1e006-d1e8-4f16-82b6-48d8fd74b238 ya está en inglés. Saltando...
🧐 Procesando 13168/17048 - f92889ba-e2a9-41a3-a449-3e59d9b9b6a4 | Idioma detectado: de
🧐 Procesando 13169/17048 - 5dc33953-16dc-4257-be17-d40650c1641a | Idioma detectado: de
🧐 Procesando 13170/17048 - 0ac43c3d-1cef-46da-91ed-580f593c2e02 | Idioma detectado: de

🔄 Traduciendo canciones:  77%|███████▋  | 13180/17048 [1:10:05<4:54:13,  4.56s/it]

✅ 78335697-db09-43b1-a9ef-1a4411317236 ya está en inglés. Saltando...
🧐 Procesando 13166/17048 - 5c922649-10d9-4417-b121-56d44eee859a | Idioma detectado: en
✅ 5c922649-10d9-4417-b121-56d44eee859a ya está en inglés. Saltando...
🧐 Procesando 13167/17048 - c3e1e006-d1e8-4f16-82b6-48d8fd74b238 | Idioma detectado: en
✅ c3e1e006-d1e8-4f16-82b6-48d8fd74b238 ya está en inglés. Saltando...
🧐 Procesando 13168/17048 - f92889ba-e2a9-41a3-a449-3e59d9b9b6a4 | Idioma detectado: de
🧐 Procesando 13169/17048 - 5dc33953-16dc-4257-be17-d40650c1641a | Idioma detectado: de
🧐 Procesando 13170/17048 - 0ac43c3d-1cef-46da-91ed-580f593c2e02 | Idioma detectado: de
🧐 Procesando 13171/17048 - afd7c3ee-4a0b-478f-806f-be13465e6f1d | Idioma detectado: de
🧐 Procesando 13172/17048 - 2daafbf7-6fa7-4193-9b0d-57233e7cf2e3 | Idioma detectado: de
🧐 Procesando 13173/17048 - 2d9de5c5-68df-43bc-8772-596102fb4b40 | Idioma detectado: en
✅ 2d9de5c5-68df-43bc-8772-596102fb4b40 ya está en inglés. Saltando...
🧐 Procesando 13174/17048 - f68eea12-c379-4c1f-8bfa-0d58125e72d2 | Idioma detectado: en
✅ f68eea12-c379-4c1f-8bfa-0d58125e72d2 ya está en inglés. Saltando...
🧐 Procesando 13175/17048 - 5900acb7-85c8-41dc-895f-a78a2d4fef27 | Idioma detectado: fr
🧐 Procesando 13176/17048 - e82cfd84-ed20-4749-beda-433ff16c87e1 | Idioma detectado: de
🧐 Procesando 13177/17048 - a306f2d8-2a0f-4590-a406-7dc0a9cad1b5 | Idioma detectado: de
🧐 Procesando 13178/17048 - 7d12f206-fd63-440a-a3b0-9217c066fd96 | Idioma detectado: de
🧐 Procesando 13179/17048 - f43d1a4f-ca28-43f5-b2f2-eab982b45092 | Idioma detectado: de
🧐 Procesando 13180/17048 - f2a9d5e5-72a4-4030-b8cd-d9fa8c6b2222 | Idioma detectado: de

🔄 Traduciendo canciones:  78%|███████▊  | 13319/17048 [1:13:01<25:43,  2.42it/s]

✅ 0335e338-bbd4-4744-91e5-1d519bb92c43 ya está en inglés. Saltando...
🧐 Procesando 13451/17048 - 01eca772-35b6-4d75-b6ca-9ea9093dd9bc | Idioma detectado: en
✅ 01eca772-35b6-4d75-b6ca-9ea9093dd9bc ya está en inglés. Saltando...
🧐 Procesando 13452/17048 - 360a8f2f-fd45-418c-a717-7aa034cc811f | Idioma detectado: en
✅ 360a8f2f-fd45-418c-a717-7aa034cc811f ya está en inglés. Saltando...
🧐 Procesando 13453/17048 - 7ac55188-7936-4903-898c-c1acea128543 | Idioma detectado: en
✅ 7ac55188-7936-4903-898c-c1acea128543 ya está en inglés. Saltando...
🧐 Procesando 13454/17048 - 009f819c-b06b-479e-a7a8-ca09fbc55a1d | Idioma detectado: en
✅ 009f819c-b06b-479e-a7a8-ca09fbc55a1d ya está en inglés. Saltando...
🧐 Procesando 13455/17048 - 103e6d4f-5f00-42b6-8524-10e7f1d7628a | Idioma detectado: en
✅ 103e6d4f-5f00-42b6-8524-10e7f1d7628a ya está en inglés. Saltando...
🧐 Procesando 13456/17048 - c2f18f83-540a-4719-a3b7-c4a4bb45dce4 | Idioma detectado: en
✅ c2f18f83-540a-4719-a3b7-c4a4bb45dce4 ya está en inglés. Saltando...
🧐 Procesando 13457/17048 - c2880f95-ff7a-4a95-a1e9-a71c782a0568 | Idioma detectado: en
✅ c2880f95-ff7a-4a95-a1e9-a71c782a0568 ya está en inglés. Saltando...
🧐 Procesando 13458/17048 - 744853c0-6b9d-4856-9695-6f05cf827706 | Idioma detectado: en
✅ 744853c0-6b9d-4856-9695-6f05cf827706 ya está en inglés. Saltando...
🧐 Procesando 13459/17048 - 01d0b698-80a4-4e6a-9e2f-f2543aa8fa31 | Idioma detectado: en
✅ 01d0b698-80a4-4e6a-9e2f-f2543aa8fa31 ya está en inglés. Saltando...
🧐 Procesando 13460/17048 - 314d8b12-891a-4428-aadf-345f545d068b | Idioma detectado: de

🔄 Traduciendo canciones:  79%|███████▉  | 13461/17048 [1:13:03<04:34, 13.05it/s]

✅ a8e10fc9-5622-4a61-80e9-c687d5377e28 ya está en inglés. Saltando...
🧐 Procesando 13481/17048 - 1ab628eb-ed3b-450d-9068-f65333da7c55 | Idioma detectado: en
✅ 1ab628eb-ed3b-450d-9068-f65333da7c55 ya está en inglés. Saltando...
🧐 Procesando 13482/17048 - 0029810c-a2df-4e09-b68c-d9d2e64f4ee3 | Idioma detectado: en
✅ 0029810c-a2df-4e09-b68c-d9d2e64f4ee3 ya está en inglés. Saltando...
🧐 Procesando 13483/17048 - fff7b6da-67cc-46ed-a8c6-2261e1d41204 | Idioma detectado: en
✅ fff7b6da-67cc-46ed-a8c6-2261e1d41204 ya está en inglés. Saltando...
🧐 Procesando 13484/17048 - 9ab9f6c2-3b6e-48e2-a79a-760ba55f5a12 | Idioma detectado: en
✅ 9ab9f6c2-3b6e-48e2-a79a-760ba55f5a12 ya está en inglés. Saltando...
🧐 Procesando 13485/17048 - b48c5200-7ae7-473f-9d6f-b635933b5df8 | Idioma detectado: en
✅ b48c5200-7ae7-473f-9d6f-b635933b5df8 ya está en inglés. Saltando...
🧐 Procesando 13486/17048 - a74d53a2-b08a-42c1-aa3f-49aec3f3c887 | Idioma detectado: en
✅ a74d53a2-b08a-42c1-aa3f-49aec3f3c887 ya está en inglés. Saltando...
🧐 Procesando 13487/17048 - 9447a324-9331-4f37-8886-4162c5920373 | Idioma detectado: en
✅ 9447a324-9331-4f37-8886-4162c5920373 ya está en inglés. Saltando...
🧐 Procesando 13488/17048 - 9eff3d0d-aa5f-4286-aa06-4bb0d4681f7a | Idioma detectado: en
✅ 9eff3d0d-aa5f-4286-aa06-4bb0d4681f7a ya está en inglés. Saltando...
🧐 Procesando 13489/17048 - 15af8b5d-98ae-4df5-a293-826936c55011 | Idioma detectado: en
✅ 15af8b5d-98ae-4df5-a293-826936c55011 ya está en inglés. Saltando...
🧐 Procesando 13490/17048 - 2676c8c1-fb9c-46c9-a457-af7e8bf4fa50 | Idioma detectado: fr

🔄 Traduciendo canciones:  79%|███████▉  | 13550/17048 [1:13:20<15:18,  3.81it/s]

✅ e15a4863-2f6f-4043-b14a-1cc4b278ff13 ya está en inglés. Saltando...
🧐 Procesando 13540/17048 - a8db281a-227b-4654-a30f-737b8a591808 | Idioma detectado: en
✅ a8db281a-227b-4654-a30f-737b8a591808 ya está en inglés. Saltando...
🧐 Procesando 13541/17048 - 9e60f5f3-7a4f-4e68-8045-12879a55def8 | Idioma detectado: en
✅ 9e60f5f3-7a4f-4e68-8045-12879a55def8 ya está en inglés. Saltando...
🧐 Procesando 13542/17048 - 99f82da2-bca8-43cd-bcae-e28ed4fa4371 | Idioma detectado: en
✅ 99f82da2-bca8-43cd-bcae-e28ed4fa4371 ya está en inglés. Saltando...
🧐 Procesando 13543/17048 - 2330dd62-67e1-482f-89f6-55bc76638cb7 | Idioma detectado: it
🧐 Procesando 13544/17048 - 5ef73003-fc15-41ba-80b7-72566c331912 | Idioma detectado: en
✅ 5ef73003-fc15-41ba-80b7-72566c331912 ya está en inglés. Saltando...
🧐 Procesando 13545/17048 - 3576e170-edab-42df-bb5a-e6308ae97511 | Idioma detectado: en
✅ 3576e170-edab-42df-bb5a-e6308ae97511 ya está en inglés. Saltando...
🧐 Procesando 13546/17048 - 35a75a95-c842-40df-9c45-2c6397ec6581 | Idioma detectado: en
✅ 35a75a95-c842-40df-9c45-2c6397ec6581 ya está en inglés. Saltando...
🧐 Procesando 13547/17048 - 3ca7e77d-f1fc-4b1f-8ea1-21f68fe3bfb1 | Idioma detectado: en
✅ 3ca7e77d-f1fc-4b1f-8ea1-21f68fe3bfb1 ya está en inglés. Saltando...
🧐 Procesando 13548/17048 - 1c663036-8a42-437e-9034-97d06b250e3a | Idioma detectado: en
✅ 1c663036-8a42-437e-9034-97d06b250e3a ya está en inglés. Saltando...
🧐 Procesando 13549/17048 - efad4a10-fa98-436e-be3e-9f4279944b07 | Idioma detectado: it
🧐 Procesando 13550/17048 - bd885598-c107-4e29-8d87-7738b1e9139d | Idioma detectado: fr

🔄 Traduciendo canciones:  80%|████████  | 13660/17048 [1:13:49<19:42,  2.86it/s]

✅ ec559c91-6dd0-450b-9483-b5c61bc0bc32 ya está en inglés. Saltando...
🧐 Procesando 13650/17048 - c0540412-b0d4-41db-a58e-8192facec399 | Idioma detectado: en
✅ c0540412-b0d4-41db-a58e-8192facec399 ya está en inglés. Saltando...
🧐 Procesando 13651/17048 - c3885160-d2f1-4146-8d27-0d42ccd03ba7 | Idioma detectado: en
✅ c3885160-d2f1-4146-8d27-0d42ccd03ba7 ya está en inglés. Saltando...
🧐 Procesando 13652/17048 - 80932843-6d29-4f6a-b247-e5a5851fb868 | Idioma detectado: en
✅ 80932843-6d29-4f6a-b247-e5a5851fb868 ya está en inglés. Saltando...
🧐 Procesando 13653/17048 - 90c07497-982d-48d3-8afe-c8364cdcd23e | Idioma detectado: en
✅ 90c07497-982d-48d3-8afe-c8364cdcd23e ya está en inglés. Saltando...
🧐 Procesando 13654/17048 - 4677fe3f-0462-497f-9c77-abe14ba15184 | Idioma detectado: en
✅ 4677fe3f-0462-497f-9c77-abe14ba15184 ya está en inglés. Saltando...
🧐 Procesando 13655/17048 - 5f9af69f-8804-4ecd-bfec-460383aa8ccb | Idioma detectado: en
✅ 5f9af69f-8804-4ecd-bfec-460383aa8ccb ya está en inglés. Saltando...
🧐 Procesando 13656/17048 - 7ea75536-9718-4b5b-8a78-1828004c752b | Idioma detectado: en
✅ 7ea75536-9718-4b5b-8a78-1828004c752b ya está en inglés. Saltando...
🧐 Procesando 13657/17048 - 8ef78f64-c198-4c59-a91b-c231db924c91 | Idioma detectado: fr
🧐 Procesando 13658/17048 - c36837e0-7ca1-423e-98f5-fd43ade3a3e0 | Idioma detectado: en
✅ c36837e0-7ca1-423e-98f5-fd43ade3a3e0 ya está en inglés. Saltando...
🧐 Procesando 13659/17048 - 7e977dcd-6fc7-4f78-b2cc-c1e3caac0cc0 | Idioma detectado: de
🧐 Procesando 13660/17048 - b9a78349-7bf7-457f-856e-7b4a1d98a029 | Idioma detectado: de

🔄 Traduciendo canciones:  80%|████████  | 13661/17048 [1:14:00<34:15,  1.65it/s]

🧐 Procesando 13660/17048 - b9a78349-7bf7-457f-856e-7b4a1d98a029 | Idioma detectado: de
🧐 Procesando 13661/17048 - 18b9f80a-749c-443a-983f-a637d913cbdd | Idioma detectado: en
✅ 18b9f80a-749c-443a-983f-a637d913cbdd ya está en inglés. Saltando...
🧐 Procesando 13662/17048 - 983eca0f-398a-4ee7-930c-83f3a0a270a4 | Idioma detectado: en
✅ 983eca0f-398a-4ee7-930c-83f3a0a270a4 ya está en inglés. Saltando...
🧐 Procesando 13663/17048 - 1ed7d357-0796-41bd-a4fa-32358132abfe | Idioma detectado: en
✅ 1ed7d357-0796-41bd-a4fa-32358132abfe ya está en inglés. Saltando...
🧐 Procesando 13664/17048 - 7e7c97ca-8b83-4890-a5c6-1dcea50403a6 | Idioma detectado: en
✅ 7e7c97ca-8b83-4890-a5c6-1dcea50403a6 ya está en inglés. Saltando...
🧐 Procesando 13665/17048 - 40ede8db-d467-48dd-b47f-cfd4f03989ab | Idioma detectado: en
✅ 40ede8db-d467-48dd-b47f-cfd4f03989ab ya está en inglés. Saltando...
🧐 Procesando 13666/17048 - 1019e8d1-8922-4f2f-a176-2a99370a84e6 | Idioma detectado: en
✅ 1019e8d1-8922-4f2f-a176-2a99370a84e6 ya está en inglés. Saltando...
🧐 Procesando 13667/17048 - 58dacde5-755b-40c5-ac57-520b3505464f | Idioma detectado: en
✅ 58dacde5-755b-40c5-ac57-520b3505464f ya está en inglés. Saltando...
🧐 Procesando 13668/17048 - 076bb892-c878-4dfa-8810-87d1c7d2a5d5 | Idioma detectado: en
✅ 076bb892-c878-4dfa-8810-87d1c7d2a5d5 ya está en inglés. Saltando...
🧐 Procesando 13669/17048 - 59d61192-f940-4da9-ad63-2283f5363041 | Idioma detectado: en
✅ 59d61192-f940-4da9-ad63-2283f5363041 ya está en inglés. Saltando...
🧐 Procesando 13670/17048 - 1202386b-9e0a-41e8-8255-e953ce195aef | Idioma detectado: de

🔄 Traduciendo canciones:  81%|████████  | 13829/17048 [1:15:30<46:44,  1.15it/s]

🧐 Procesando 13820/17048 - 58d30579-2892-4d6e-9703-47d1d747ae3b | Idioma detectado: en
✅ 58d30579-2892-4d6e-9703-47d1d747ae3b ya está en inglés. Saltando...
🧐 Procesando 13821/17048 - 24dfbfd3-eb59-4676-a69f-5a4e3c2c6b71 | Idioma detectado: en
✅ 24dfbfd3-eb59-4676-a69f-5a4e3c2c6b71 ya está en inglés. Saltando...
🧐 Procesando 13822/17048 - 5fd61ecf-52f6-4419-bddf-3f1157c5eae9 | Idioma detectado: en
✅ 5fd61ecf-52f6-4419-bddf-3f1157c5eae9 ya está en inglés. Saltando...
🧐 Procesando 13823/17048 - 4f6a5159-bc9c-4e6a-873d-cc01529763e4 | Idioma detectado: en
✅ 4f6a5159-bc9c-4e6a-873d-cc01529763e4 ya está en inglés. Saltando...
🧐 Procesando 13824/17048 - 91dc9fab-b349-474a-8c0d-7713b8bcaebb | Idioma detectado: en
✅ 91dc9fab-b349-474a-8c0d-7713b8bcaebb ya está en inglés. Saltando...
🧐 Procesando 13825/17048 - fbd04721-3413-4fc9-b8af-8fc5298ea90f | Idioma detectado: en
✅ fbd04721-3413-4fc9-b8af-8fc5298ea90f ya está en inglés. Saltando...
🧐 Procesando 13826/17048 - df40f42e-a05b-45ba-b929-1a8567cb3bc3 | Idioma detectado: en
✅ df40f42e-a05b-45ba-b929-1a8567cb3bc3 ya está en inglés. Saltando...
🧐 Procesando 13827/17048 - 4515bdca-539a-4f19-acb9-09717f9dcbe6 | Idioma detectado: en
✅ 4515bdca-539a-4f19-acb9-09717f9dcbe6 ya está en inglés. Saltando...
🧐 Procesando 13828/17048 - 22bf3114-8e8d-422e-9874-0c49ec8c483b | Idioma detectado: it
🧐 Procesando 13829/17048 - d96682dd-c662-4c6d-809c-ea82ab676c0b | Idioma detectado: en
✅ d96682dd-c662-4c6d-809c-ea82ab676c0b ya está en inglés. Saltando...
🧐 Procesando 13830/17048 - 7fd5f606-060b-419a-80a3-f9a2275d6032 | Idioma detectado: pt

🔄 Traduciendo canciones:  82%|████████▏ | 13919/17048 [1:15:34<05:29,  9.49it/s]

✅ 8406579e-ee14-474e-9a83-e65f85dbb9dd ya está en inglés. Saltando...
🧐 Procesando 13910/17048 - 93598d82-8d38-49a3-b979-9a3ecddd5465 | Idioma detectado: en
✅ 93598d82-8d38-49a3-b979-9a3ecddd5465 ya está en inglés. Saltando...
🧐 Procesando 13911/17048 - 19357c68-bd04-4873-a60b-f52e8b12d15b | Idioma detectado: en
✅ 19357c68-bd04-4873-a60b-f52e8b12d15b ya está en inglés. Saltando...
🧐 Procesando 13912/17048 - 64b74500-7bf6-4c6d-b1c3-cea2a8faa9df | Idioma detectado: en
✅ 64b74500-7bf6-4c6d-b1c3-cea2a8faa9df ya está en inglés. Saltando...
🧐 Procesando 13913/17048 - c69f333d-5a08-48fd-af85-8b349922caa1 | Idioma detectado: en
✅ c69f333d-5a08-48fd-af85-8b349922caa1 ya está en inglés. Saltando...
🧐 Procesando 13914/17048 - f1bc5847-05b3-454a-a897-5c9b86bf5bb4 | Idioma detectado: en
✅ f1bc5847-05b3-454a-a897-5c9b86bf5bb4 ya está en inglés. Saltando...
🧐 Procesando 13915/17048 - 047017b1-a66b-40c1-a3f2-3f804128ed19 | Idioma detectado: en
✅ 047017b1-a66b-40c1-a3f2-3f804128ed19 ya está en inglés. Saltando...
🧐 Procesando 13916/17048 - 20c13a67-9e88-4d53-86bb-80aefee5edf4 | Idioma detectado: en
✅ 20c13a67-9e88-4d53-86bb-80aefee5edf4 ya está en inglés. Saltando...
🧐 Procesando 13917/17048 - caa93d38-b0c1-4a1f-98e2-979bdc02a770 | Idioma detectado: en
✅ caa93d38-b0c1-4a1f-98e2-979bdc02a770 ya está en inglés. Saltando...
🧐 Procesando 13918/17048 - 0bec7762-bee4-4290-8c05-51ddf45d12e6 | Idioma detectado: de
🧐 Procesando 13919/17048 - 1d73bf0b-89dc-4919-af78-e1b39b8d2adb | Idioma detectado: de
🧐 Procesando 13920/17048 - 8bd9a7ad-8edd-458c-8a4d-25dfc45b970a | Idioma detectado: de

🔄 Traduciendo canciones:  82%|████████▏ | 13931/17048 [1:15:59<53:28,  1.03s/it]

🧐 Procesando 13915/17048 - 047017b1-a66b-40c1-a3f2-3f804128ed19 | Idioma detectado: en
✅ 047017b1-a66b-40c1-a3f2-3f804128ed19 ya está en inglés. Saltando...
🧐 Procesando 13916/17048 - 20c13a67-9e88-4d53-86bb-80aefee5edf4 | Idioma detectado: en
✅ 20c13a67-9e88-4d53-86bb-80aefee5edf4 ya está en inglés. Saltando...
🧐 Procesando 13917/17048 - caa93d38-b0c1-4a1f-98e2-979bdc02a770 | Idioma detectado: en
✅ caa93d38-b0c1-4a1f-98e2-979bdc02a770 ya está en inglés. Saltando...
🧐 Procesando 13918/17048 - 0bec7762-bee4-4290-8c05-51ddf45d12e6 | Idioma detectado: de
🧐 Procesando 13919/17048 - 1d73bf0b-89dc-4919-af78-e1b39b8d2adb | Idioma detectado: de
🧐 Procesando 13920/17048 - 8bd9a7ad-8edd-458c-8a4d-25dfc45b970a | Idioma detectado: de
🧐 Procesando 13921/17048 - 7e7673f7-6048-41e0-9fec-41b1ee71d9a8 | Idioma detectado: de
🧐 Procesando 13922/17048 - 94040afd-ead2-4034-9f7b-df130a60f49d | Idioma detectado: en
✅ 94040afd-ead2-4034-9f7b-df130a60f49d ya está en inglés. Saltando...
🧐 Procesando 13923/17048 - 73f7145f-7f20-49fa-8e05-5c0c5507c885 | Idioma detectado: de
🧐 Procesando 13924/17048 - 155df0cb-2fe8-4453-90ae-3c251f8880ab | Idioma detectado: de
🧐 Procesando 13925/17048 - c6bc1470-f365-4d4f-9509-efd3c1f6d38c | Idioma detectado: de
🧐 Procesando 13926/17048 - ab88bfab-d4e8-41e1-822c-4c21ae1bd52f | Idioma detectado: de
🧐 Procesando 13927/17048 - a1b6194c-9a5f-420d-9c8c-5cefc5a658e5 | Idioma detectado: de
🧐 Procesando 13928/17048 - 9924d7f6-2efa-4945-9a84-24fe81f2c109 | Idioma detectado: de
🧐 Procesando 13929/17048 - 8e7beba8-0b69-4e84-bcc2-4135df698a69 | Idioma detectado: de
🧐 Procesando 13930/17048 - f19c623b-dc68-4e81-8b6d-039ea54a9ecf | Idioma detectado: de

🔄 Traduciendo canciones:  82%|████████▏ | 13940/17048 [1:16:17<1:44:14,  2.01s/it]

🧐 Procesando 13927/17048 - a1b6194c-9a5f-420d-9c8c-5cefc5a658e5 | Idioma detectado: de
🧐 Procesando 13928/17048 - 9924d7f6-2efa-4945-9a84-24fe81f2c109 | Idioma detectado: de
🧐 Procesando 13929/17048 - 8e7beba8-0b69-4e84-bcc2-4135df698a69 | Idioma detectado: de
🧐 Procesando 13930/17048 - f19c623b-dc68-4e81-8b6d-039ea54a9ecf | Idioma detectado: de
🧐 Procesando 13931/17048 - ebd743a7-0f8a-49d1-9735-2958403d2da8 | Idioma detectado: en
✅ ebd743a7-0f8a-49d1-9735-2958403d2da8 ya está en inglés. Saltando...
🧐 Procesando 13932/17048 - d9d5fe85-4618-4410-8d03-05cfc55e7666 | Idioma detectado: en
✅ d9d5fe85-4618-4410-8d03-05cfc55e7666 ya está en inglés. Saltando...
🧐 Procesando 13933/17048 - 9a0561ca-e69b-45a9-bba7-60407f5d3ca6 | Idioma detectado: en
✅ 9a0561ca-e69b-45a9-bba7-60407f5d3ca6 ya está en inglés. Saltando...
🧐 Procesando 13934/17048 - 019df6af-f3a9-4d89-b74f-44a2d9f3c4a6 | Idioma detectado: en
✅ 019df6af-f3a9-4d89-b74f-44a2d9f3c4a6 ya está en inglés. Saltando...
🧐 Procesando 13935/17048 - 77d8827e-26bc-49d1-a7c5-6ce4c5935596 | Idioma detectado: en
✅ 77d8827e-26bc-49d1-a7c5-6ce4c5935596 ya está en inglés. Saltando...
🧐 Procesando 13936/17048 - 0f378d8a-f45a-4f4e-935d-3bfb7b25a727 | Idioma detectado: en
✅ 0f378d8a-f45a-4f4e-935d-3bfb7b25a727 ya está en inglés. Saltando...
🧐 Procesando 13937/17048 - 8e18f02d-626a-4d85-a15f-808c202695f0 | Idioma detectado: de
🧐 Procesando 13938/17048 - cdaf01be-f581-4df2-871c-6f57460e1785 | Idioma detectado: de
🧐 Procesando 13939/17048 - 173778fd-9337-49f2-92b2-1569306da964 | Idioma detectado: de
🧐 Procesando 13940/17048 - 96bb32a5-fc0e-428a-8c7b-6c7ba4fb3314 | Idioma detectado: de

🔄 Traduciendo canciones:  82%|████████▏ | 13950/17048 [1:16:37<2:05:29,  2.43s/it]

🧐 Procesando 13934/17048 - 019df6af-f3a9-4d89-b74f-44a2d9f3c4a6 | Idioma detectado: en
✅ 019df6af-f3a9-4d89-b74f-44a2d9f3c4a6 ya está en inglés. Saltando...
🧐 Procesando 13935/17048 - 77d8827e-26bc-49d1-a7c5-6ce4c5935596 | Idioma detectado: en
✅ 77d8827e-26bc-49d1-a7c5-6ce4c5935596 ya está en inglés. Saltando...
🧐 Procesando 13936/17048 - 0f378d8a-f45a-4f4e-935d-3bfb7b25a727 | Idioma detectado: en
✅ 0f378d8a-f45a-4f4e-935d-3bfb7b25a727 ya está en inglés. Saltando...
🧐 Procesando 13937/17048 - 8e18f02d-626a-4d85-a15f-808c202695f0 | Idioma detectado: de
🧐 Procesando 13938/17048 - cdaf01be-f581-4df2-871c-6f57460e1785 | Idioma detectado: de
🧐 Procesando 13939/17048 - 173778fd-9337-49f2-92b2-1569306da964 | Idioma detectado: de
🧐 Procesando 13940/17048 - 96bb32a5-fc0e-428a-8c7b-6c7ba4fb3314 | Idioma detectado: de
🧐 Procesando 13941/17048 - 03d71fbf-b95c-4153-a9d8-30d9b86f3163 | Idioma detectado: de
🧐 Procesando 13942/17048 - f49000d8-970a-4fc7-b1a5-2fc5e86afa44 | Idioma detectado: de
🧐 Procesando 13943/17048 - 489727d6-3bb7-4e9f-8bcb-41c30b22548b | Idioma detectado: de
🧐 Procesando 13944/17048 - 3d492d2f-0d47-4fa5-be8e-ca483fcb79fc | Idioma detectado: de
🧐 Procesando 13945/17048 - 41f7d6f2-1f6e-4092-ab44-8b9a0f76614a | Idioma detectado: de
🧐 Procesando 13946/17048 - 39b19196-bb33-4689-8da3-fa3574d19a56 | Idioma detectado: de
🧐 Procesando 13947/17048 - b1de2838-cd33-4f54-99be-d89f5725fad2 | Idioma detectado: de
🧐 Procesando 13948/17048 - f3c7cc06-8ff5-4875-b514-ffe91bf4a3a6 | Idioma detectado: de
🧐 Procesando 13949/17048 - 50845319-45e9-4ea0-870d-d663b777ef1d | Idioma detectado: fr
🧐 Procesando 13950/17048 - c88acf63-f53d-4031-b1f8-8ef7e3cec10a | Idioma detectado: fr

🔄 Traduciendo canciones:  82%|████████▏ | 13960/17048 [1:16:48<1:16:23,  1.48s/it]

🧐 Procesando 13947/17048 - b1de2838-cd33-4f54-99be-d89f5725fad2 | Idioma detectado: de
🧐 Procesando 13948/17048 - f3c7cc06-8ff5-4875-b514-ffe91bf4a3a6 | Idioma detectado: de
🧐 Procesando 13949/17048 - 50845319-45e9-4ea0-870d-d663b777ef1d | Idioma detectado: fr
🧐 Procesando 13950/17048 - c88acf63-f53d-4031-b1f8-8ef7e3cec10a | Idioma detectado: fr
🧐 Procesando 13951/17048 - 5a4b6e4e-a955-4107-90d1-9db657b18a41 | Idioma detectado: en
✅ 5a4b6e4e-a955-4107-90d1-9db657b18a41 ya está en inglés. Saltando...
🧐 Procesando 13952/17048 - d00a2323-45a9-4785-9590-99dc4683faa7 | Idioma detectado: en
✅ d00a2323-45a9-4785-9590-99dc4683faa7 ya está en inglés. Saltando...
🧐 Procesando 13953/17048 - aed1c865-eb2c-45e9-8a27-b8b9c7897ac3 | Idioma detectado: en
✅ aed1c865-eb2c-45e9-8a27-b8b9c7897ac3 ya está en inglés. Saltando...
🧐 Procesando 13954/17048 - 471ea160-1ca9-4530-bc83-ac0134bb7d4d | Idioma detectado: en
✅ 471ea160-1ca9-4530-bc83-ac0134bb7d4d ya está en inglés. Saltando...
🧐 Procesando 13955/17048 - da9e455f-2d54-470e-a7bb-6fe0b43f9bd6 | Idioma detectado: en
✅ da9e455f-2d54-470e-a7bb-6fe0b43f9bd6 ya está en inglés. Saltando...
🧐 Procesando 13956/17048 - 2d3b1d1f-5f6e-425a-b3cd-cddf4ae55c2a | Idioma detectado: en
✅ 2d3b1d1f-5f6e-425a-b3cd-cddf4ae55c2a ya está en inglés. Saltando...
🧐 Procesando 13957/17048 - c23a261d-179f-4fb1-91be-93c4fc65a9b7 | Idioma detectado: ja
🧐 Procesando 13958/17048 - 0ea18263-9fa3-4e65-97ac-1d7d6bead551 | Idioma detectado: de
🧐 Procesando 13959/17048 - 7fd79b0d-345c-4956-814c-fc08201d9723 | Idioma detectado: de
🧐 Procesando 13960/17048 - 5cbcc764-19c1-42f3-844c-ba9d38ba1a67 | Idioma detectado: de

🔄 Traduciendo canciones:  82%|████████▏ | 13980/17048 [1:17:42<1:54:56,  2.25s/it]

🧐 Procesando 13964/17048 - 04c9c421-1dcc-4be7-a443-69ad69650c41 | Idioma detectado: de
🧐 Procesando 13965/17048 - b0a408c0-7588-4fe8-a608-36662525aa7a | Idioma detectado: de
🧐 Procesando 13966/17048 - 2507c0dc-1e0a-4272-bd18-f6cd32c67672 | Idioma detectado: de
🧐 Procesando 13967/17048 - 3d2e9599-8a56-49bb-ad7b-d1b04827c017 | Idioma detectado: de
🧐 Procesando 13968/17048 - a103e457-9e57-45a2-b879-8be4785f8735 | Idioma detectado: en
✅ a103e457-9e57-45a2-b879-8be4785f8735 ya está en inglés. Saltando...
🧐 Procesando 13969/17048 - c59f2c0b-8a5e-40b1-908c-c4077a5d6087 | Idioma detectado: en
✅ c59f2c0b-8a5e-40b1-908c-c4077a5d6087 ya está en inglés. Saltando...
🧐 Procesando 13970/17048 - 392fe615-c95d-4c1b-b7e3-48ad1c873dfc | Idioma detectado: en
✅ 392fe615-c95d-4c1b-b7e3-48ad1c873dfc ya está en inglés. Saltando...
🧐 Procesando 13971/17048 - 34c9c977-a605-4039-bbd3-14ba96da9437 | Idioma detectado: de
🧐 Procesando 13972/17048 - 09250dd9-2a99-4d46-afd9-b2abd34fd8da | Idioma detectado: de
🧐 Procesando 13973/17048 - a133ba1c-9af5-4ba1-bf3f-4037edd85ea0 | Idioma detectado: de
🧐 Procesando 13974/17048 - 3e5c9589-3caa-4e9c-a94a-9286b9f60a2c | Idioma detectado: de
🧐 Procesando 13975/17048 - 3c617284-05a9-44a7-b562-91dbfbebbd63 | Idioma detectado: de
🧐 Procesando 13976/17048 - 8dd44092-06a7-430c-a1f3-34afc2def92d | Idioma detectado: de
🧐 Procesando 13977/17048 - e64819bc-36e9-48b0-8883-805ad763845e | Idioma detectado: de
🧐 Procesando 13978/17048 - c7731ce7-b267-4823-8135-34d55a14319f | Idioma detectado: de
🧐 Procesando 13979/17048 - 798f59ae-86ef-42aa-9233-4a1192161623 | Idioma detectado: de
🧐 Procesando 13980/17048 - f61d57ae-74fe-4e09-bf0b-f4a1852072c2 | Idioma detectado: de

🔄 Traduciendo canciones:  83%|████████▎ | 14099/17048 [1:18:15<08:16,  5.93it/s]

🧐 Procesando 14089/17048 - efaf88e9-f821-4db9-9376-a75e326b5599 | Idioma detectado: en
✅ efaf88e9-f821-4db9-9376-a75e326b5599 ya está en inglés. Saltando...
🧐 Procesando 14090/17048 - e13dc42d-dab7-4f07-87fa-06dfc648ebb7 | Idioma detectado: en
✅ e13dc42d-dab7-4f07-87fa-06dfc648ebb7 ya está en inglés. Saltando...
🧐 Procesando 14091/17048 - c1b45692-6a74-4d25-b782-9491bd8006f1 | Idioma detectado: en
✅ c1b45692-6a74-4d25-b782-9491bd8006f1 ya está en inglés. Saltando...
🧐 Procesando 14092/17048 - c5565570-0cb6-4898-878a-da5a4f6c7eb6 | Idioma detectado: en
✅ c5565570-0cb6-4898-878a-da5a4f6c7eb6 ya está en inglés. Saltando...
🧐 Procesando 14093/17048 - adf65fd0-5f76-4c63-ab3d-6673e7b08849 | Idioma detectado: en
✅ adf65fd0-5f76-4c63-ab3d-6673e7b08849 ya está en inglés. Saltando...
🧐 Procesando 14094/17048 - cdcbacb6-ee3d-4b03-985a-c83052a1f52f | Idioma detectado: en
✅ cdcbacb6-ee3d-4b03-985a-c83052a1f52f ya está en inglés. Saltando...
🧐 Procesando 14095/17048 - 916473b5-3c9f-45e7-81c4-db167d4b9dc9 | Idioma detectado: en
✅ 916473b5-3c9f-45e7-81c4-db167d4b9dc9 ya está en inglés. Saltando...
🧐 Procesando 14096/17048 - 3fc62429-07e8-41f9-9d8d-9f5a437933d4 | Idioma detectado: de
🧐 Procesando 14097/17048 - ba6ef21c-6fbc-4993-8538-f2f3da975758 | Idioma detectado: de
🧐 Procesando 14098/17048 - 89889f90-eb12-4908-9954-ade1b5e382ee | Idioma detectado: de
🧐 Procesando 14099/17048 - 33589ebc-5901-43db-ad5d-a82c9231fbe2 | Idioma detectado: en
✅ 33589ebc-5901-43db-ad5d-a82c9231fbe2 ya está en inglés. Saltando...
🧐 Procesando 14100/17048 - 2111a003-3a78-435a-ad64-414727bd9b68 | Idioma detectado: de

🔄 Traduciendo canciones:  84%|████████▍ | 14340/17048 [1:19:49<1:17:02,  1.71s/it]

🧐 Procesando 14327/17048 - 3517a9d3-aa97-418c-988a-b9735617f72f | Idioma detectado: en
✅ 3517a9d3-aa97-418c-988a-b9735617f72f ya está en inglés. Saltando...
🧐 Procesando 14328/17048 - fb67f4ed-618d-4e8b-a9f2-482c54b68778 | Idioma detectado: en
✅ fb67f4ed-618d-4e8b-a9f2-482c54b68778 ya está en inglés. Saltando...
🧐 Procesando 14329/17048 - 62238c89-cb30-49ea-94cf-4b5244dfb143 | Idioma detectado: en
✅ 62238c89-cb30-49ea-94cf-4b5244dfb143 ya está en inglés. Saltando...
🧐 Procesando 14330/17048 - 3e2fcaca-0d95-4dcf-87b7-864b8d39cc5b | Idioma detectado: en
✅ 3e2fcaca-0d95-4dcf-87b7-864b8d39cc5b ya está en inglés. Saltando...
🧐 Procesando 14331/17048 - ec012b2f-a038-46d9-a8cb-552e5b9492dd | Idioma detectado: en
✅ ec012b2f-a038-46d9-a8cb-552e5b9492dd ya está en inglés. Saltando...
🧐 Procesando 14332/17048 - c1972424-9512-4e8e-8776-cd76c03dcefe | Idioma detectado: en
✅ c1972424-9512-4e8e-8776-cd76c03dcefe ya está en inglés. Saltando...
🧐 Procesando 14333/17048 - d5ba9195-179f-4e47-b31b-cccfbc025f74 | Idioma detectado: de
🧐 Procesando 14334/17048 - 350bb820-4b4b-4805-9c06-fd14ec507267 | Idioma detectado: de
🧐 Procesando 14335/17048 - deb8988c-5833-4bd1-9935-f864ba530665 | Idioma detectado: de
🧐 Procesando 14336/17048 - 0bebd803-bfbd-4c70-a2f6-8b784655e6de | Idioma detectado: de
🧐 Procesando 14337/17048 - 0e143ccb-f1f8-49a5-8bc1-e571b32d4c6e | Idioma detectado: de
🧐 Procesando 14338/17048 - 4e17d4fd-ed26-4e59-9bf2-481526e13c96 | Idioma detectado: fr
🧐 Procesando 14339/17048 - 95663170-aaef-4fee-8dac-3c121a52ee5f | Idioma detectado: de
🧐 Procesando 14340/17048 - 45467778-6692-491c-9182-7864aff2d8f2 | Idioma detectado: de

🔄 Traduciendo canciones:  84%|████████▍ | 14350/17048 [1:20:14<1:50:04,  2.45s/it]

🧐 Procesando 14335/17048 - deb8988c-5833-4bd1-9935-f864ba530665 | Idioma detectado: de
🧐 Procesando 14336/17048 - 0bebd803-bfbd-4c70-a2f6-8b784655e6de | Idioma detectado: de
🧐 Procesando 14337/17048 - 0e143ccb-f1f8-49a5-8bc1-e571b32d4c6e | Idioma detectado: de
🧐 Procesando 14338/17048 - 4e17d4fd-ed26-4e59-9bf2-481526e13c96 | Idioma detectado: fr
🧐 Procesando 14339/17048 - 95663170-aaef-4fee-8dac-3c121a52ee5f | Idioma detectado: de
🧐 Procesando 14340/17048 - 45467778-6692-491c-9182-7864aff2d8f2 | Idioma detectado: de
🧐 Procesando 14341/17048 - 2b9ea76f-9f95-4678-b776-301749db85cc | Idioma detectado: de
🧐 Procesando 14342/17048 - 30381e66-95c0-4045-87c1-d6631caa6132 | Idioma detectado: en
✅ 30381e66-95c0-4045-87c1-d6631caa6132 ya está en inglés. Saltando...
🧐 Procesando 14343/17048 - e2ec78c3-aac3-42db-a00e-e84c5574faa0 | Idioma detectado: en
✅ e2ec78c3-aac3-42db-a00e-e84c5574faa0 ya está en inglés. Saltando...
🧐 Procesando 14344/17048 - 07979ebb-790f-4e1d-b234-623a439d1b00 | Idioma detectado: fr
🧐 Procesando 14345/17048 - 26e1a684-5cd8-443b-9ff8-d63072de4cec | Idioma detectado: fr
🧐 Procesando 14346/17048 - 827d9367-28e3-49f8-9185-43f3768f9c86 | Idioma detectado: fr
🧐 Procesando 14347/17048 - a3023c09-8c2c-4fd1-8033-853a4448be02 | Idioma detectado: en
✅ a3023c09-8c2c-4fd1-8033-853a4448be02 ya está en inglés. Saltando...
🧐 Procesando 14348/17048 - d23b92cf-6c80-4460-a8b4-13d41a62b24a | Idioma detectado: en
✅ d23b92cf-6c80-4460-a8b4-13d41a62b24a ya está en inglés. Saltando...
🧐 Procesando 14349/17048 - bd88ac9b-b172-4d99-ad9b-26e3a670d790 | Idioma detectado: fr
🧐 Procesando 14350/17048 - 6a6d4d7d-cec1-4fa9-ad75-04cd2b53f45e | Idioma detectado: fr

🔄 Traduciendo canciones:  84%|████████▍ | 14371/17048 [1:20:43<1:10:45,  1.59s/it]

🧐 Procesando 14357/17048 - d7d33423-0ae3-4b42-ab52-36559b24a04e | Idioma detectado: en
✅ d7d33423-0ae3-4b42-ab52-36559b24a04e ya está en inglés. Saltando...
🧐 Procesando 14358/17048 - 1ded0437-7fec-425c-a8f2-8f4c6a0fda18 | Idioma detectado: en
✅ 1ded0437-7fec-425c-a8f2-8f4c6a0fda18 ya está en inglés. Saltando...
🧐 Procesando 14359/17048 - 6f96ee46-a486-4b62-ba16-e26fdf5c210e | Idioma detectado: en
✅ 6f96ee46-a486-4b62-ba16-e26fdf5c210e ya está en inglés. Saltando...
🧐 Procesando 14360/17048 - 39caa392-8eb6-4e90-b151-9611631b11e8 | Idioma detectado: en
✅ 39caa392-8eb6-4e90-b151-9611631b11e8 ya está en inglés. Saltando...
🧐 Procesando 14361/17048 - 70bd5473-7023-4dda-890c-d850874f685a | Idioma detectado: en
✅ 70bd5473-7023-4dda-890c-d850874f685a ya está en inglés. Saltando...
🧐 Procesando 14362/17048 - 028daf18-7940-4338-95ac-b2737fd80517 | Idioma detectado: en
✅ 028daf18-7940-4338-95ac-b2737fd80517 ya está en inglés. Saltando...
🧐 Procesando 14363/17048 - 408832b3-41c0-49b1-9af2-a36a009672da | Idioma detectado: fr
🧐 Procesando 14364/17048 - b7e3b486-7d9f-4ce6-97f2-9aa44978f61d | Idioma detectado: fr
🧐 Procesando 14365/17048 - fac81fdc-283a-4dc0-adec-0b961551e75d | Idioma detectado: fr
🧐 Procesando 14366/17048 - c2afb418-51ec-4304-8b6a-3abacfc0a9fb | Idioma detectado: fr
🧐 Procesando 14367/17048 - be4d142b-2589-4b29-8593-e07d675a4134 | Idioma detectado: fr
🧐 Procesando 14368/17048 - 875a938a-3dfc-403f-871b-eb0bed86a50b | Idioma detectado: de
🧐 Procesando 14369/17048 - ceac6a5b-1444-4c40-a20a-1af01bf64285 | Idioma detectado: de
🧐 Procesando 14370/17048 - 46ccf551-424a-4213-bd48-501d07149257 | Idioma detectado: de

🔄 Traduciendo canciones:  84%|████████▍ | 14381/17048 [1:20:52<52:00,  1.17s/it]

🧐 Procesando 14366/17048 - c2afb418-51ec-4304-8b6a-3abacfc0a9fb | Idioma detectado: fr
🧐 Procesando 14367/17048 - be4d142b-2589-4b29-8593-e07d675a4134 | Idioma detectado: fr
🧐 Procesando 14368/17048 - 875a938a-3dfc-403f-871b-eb0bed86a50b | Idioma detectado: de
🧐 Procesando 14369/17048 - ceac6a5b-1444-4c40-a20a-1af01bf64285 | Idioma detectado: de
🧐 Procesando 14370/17048 - 46ccf551-424a-4213-bd48-501d07149257 | Idioma detectado: de
🧐 Procesando 14371/17048 - a1ea3da4-9a98-4ccc-86ad-68e022fa1083 | Idioma detectado: de
🧐 Procesando 14372/17048 - e59b9abd-24b0-42eb-a1dc-df2212848fe1 | Idioma detectado: en
✅ e59b9abd-24b0-42eb-a1dc-df2212848fe1 ya está en inglés. Saltando...
🧐 Procesando 14373/17048 - fb6ae3d4-afb4-4d23-a6c5-a5687a055e18 | Idioma detectado: en
✅ fb6ae3d4-afb4-4d23-a6c5-a5687a055e18 ya está en inglés. Saltando...
🧐 Procesando 14374/17048 - bf720b4a-d55f-46e2-bc2f-cf15319ee11a | Idioma detectado: en
✅ bf720b4a-d55f-46e2-bc2f-cf15319ee11a ya está en inglés. Saltando...
🧐 Procesando 14375/17048 - 21831893-8e5b-4625-9d2c-e53553de0d68 | Idioma detectado: en
✅ 21831893-8e5b-4625-9d2c-e53553de0d68 ya está en inglés. Saltando...
🧐 Procesando 14376/17048 - b03a526e-635b-4ed6-b433-f1e24a3d3fbd | Idioma detectado: en
✅ b03a526e-635b-4ed6-b433-f1e24a3d3fbd ya está en inglés. Saltando...
🧐 Procesando 14377/17048 - e6a5b599-e470-4287-8d26-cd3cce791f7b | Idioma detectado: fr
🧐 Procesando 14378/17048 - 7c69fa68-3f42-47a2-b2c9-c33efb9cce24 | Idioma detectado: de
🧐 Procesando 14379/17048 - 425529b0-10e7-4cca-b543-2a21163f7f76 | Idioma detectado: de
🧐 Procesando 14380/17048 - bb4b85e2-2522-49b9-9e03-f1f5a6bc6225 | Idioma detectado: de

🔄 Traduciendo canciones:  85%|████████▌ | 14545/17048 [1:22:33<17:28,  2.39it/s]

🧐 Procesando 14539/17048 - 408fe285-5f46-4284-8708-86896ab81b71 | Idioma detectado: en
✅ 408fe285-5f46-4284-8708-86896ab81b71 ya está en inglés. Saltando...
🧐 Procesando 14540/17048 - 1856b4de-2e7f-459a-9139-38e797dce8fa | Idioma detectado: en
✅ 1856b4de-2e7f-459a-9139-38e797dce8fa ya está en inglés. Saltando...
🧐 Procesando 14541/17048 - c6e3d643-3784-405a-94be-3f2d4887b349 | Idioma detectado: es
🧐 Procesando 14542/17048 - 24790820-a668-4208-9a50-0b47bd0d2fe7 | Idioma detectado: en
✅ 24790820-a668-4208-9a50-0b47bd0d2fe7 ya está en inglés. Saltando...
🧐 Procesando 14543/17048 - 0f2e85be-c648-4a25-874b-bbdb83f15167 | Idioma detectado: pt
🧐 Procesando 14544/17048 - 6074f2fc-973d-4f18-aca3-e1c6bacc32a7 | Idioma detectado: es
🧐 Procesando 14545/17048 - e9c0d00b-722f-416a-8f9d-ef5ff9519e41 | Idioma detectado: en
✅ e9c0d00b-722f-416a-8f9d-ef5ff9519e41 ya está en inglés. Saltando...
🧐 Procesando 14546/17048 - e97ac68f-da36-40a3-a393-097fe19d2701 | Idioma detectado: en
✅ e97ac68f-da36-40a3-a393-097fe19d2701 ya está en inglés. Saltando...
🧐 Procesando 14547/17048 - eb9f1b58-a5d1-4e77-ac5f-3d5410712cd7 | Idioma detectado: en
✅ eb9f1b58-a5d1-4e77-ac5f-3d5410712cd7 ya está en inglés. Saltando...
🧐 Procesando 14548/17048 - e29dcd6e-e6ae-45b3-8da8-d7bb57b3cced | Idioma detectado: en
✅ e29dcd6e-e6ae-45b3-8da8-d7bb57b3cced ya está en inglés. Saltando...
🧐 Procesando 14549/17048 - f38b72e8-7b6b-47bd-aa10-a048586ac3b2 | Idioma detectado: en
✅ f38b72e8-7b6b-47bd-aa10-a048586ac3b2 ya está en inglés. Saltando...
🧐 Procesando 14550/17048 - 6cccd55c-89d3-4eb6-be71-0c969037c305 | Idioma detectado: fr

🔄 Traduciendo canciones:  86%|████████▌ | 14577/17048 [1:22:48<25:36,  1.61it/s]

🧐 Procesando 14569/17048 - 29ebd6dd-a136-4b8e-9f5b-f36efe71ed56 | Idioma detectado: en
✅ 29ebd6dd-a136-4b8e-9f5b-f36efe71ed56 ya está en inglés. Saltando...
🧐 Procesando 14570/17048 - 617ed3c5-431b-44a1-8dce-c2579d9d3c97 | Idioma detectado: en
✅ 617ed3c5-431b-44a1-8dce-c2579d9d3c97 ya está en inglés. Saltando...
🧐 Procesando 14571/17048 - ad82ce92-cd90-4272-a0c0-07e1ab7f61f2 | Idioma detectado: fr
🧐 Procesando 14572/17048 - 983765ff-b31f-4a58-a250-71a1d7be9bcb | Idioma detectado: en
✅ 983765ff-b31f-4a58-a250-71a1d7be9bcb ya está en inglés. Saltando...
🧐 Procesando 14573/17048 - c81fd8ef-fdd7-45be-a70e-0273e205953c | Idioma detectado: it
🧐 Procesando 14574/17048 - d180ea6c-a916-4231-b98e-f1bc355587af | Idioma detectado: en
✅ d180ea6c-a916-4231-b98e-f1bc355587af ya está en inglés. Saltando...
🧐 Procesando 14575/17048 - e969398c-7cc5-43d2-924e-b91b4a009554 | Idioma detectado: en
✅ e969398c-7cc5-43d2-924e-b91b4a009554 ya está en inglés. Saltando...
🧐 Procesando 14576/17048 - 1ea32177-e91c-4521-9bd4-a4ae18728237 | Idioma detectado: de
🧐 Procesando 14577/17048 - c78737bf-54af-4bbf-8e8c-ee437fe97c28 | Idioma detectado: en
✅ c78737bf-54af-4bbf-8e8c-ee437fe97c28 ya está en inglés. Saltando...
🧐 Procesando 14578/17048 - c3dcca9b-572f-4dcd-bcbf-330dfb4d766e | Idioma detectado: en
✅ c3dcca9b-572f-4dcd-bcbf-330dfb4d766e ya está en inglés. Saltando...
🧐 Procesando 14579/17048 - 714114c3-6e97-4caa-9dd3-d032a08d41ff | Idioma detectado: en
✅ 714114c3-6e97-4caa-9dd3-d032a08d41ff ya está en inglés. Saltando...
🧐 Procesando 14580/17048 - f1b799a4-9f60-4b70-ab0c-c1ec0f31809b | Idioma detectado: fr

🔄 Traduciendo canciones:  86%|████████▌ | 14630/17048 [1:23:17<17:09,  2.35it/s]

🧐 Procesando 14620/17048 - fbb73035-5e98-48bc-a553-2ba1e3c09bf7 | Idioma detectado: en
✅ fbb73035-5e98-48bc-a553-2ba1e3c09bf7 ya está en inglés. Saltando...
🧐 Procesando 14621/17048 - 743db633-926e-4722-b904-f0377f5ed7f4 | Idioma detectado: en
✅ 743db633-926e-4722-b904-f0377f5ed7f4 ya está en inglés. Saltando...
🧐 Procesando 14622/17048 - 396fd2dc-f7be-4e19-92d8-96d779422e51 | Idioma detectado: en
✅ 396fd2dc-f7be-4e19-92d8-96d779422e51 ya está en inglés. Saltando...
🧐 Procesando 14623/17048 - a28fc213-d83d-49bd-9595-49c9f671e6bf | Idioma detectado: en
✅ a28fc213-d83d-49bd-9595-49c9f671e6bf ya está en inglés. Saltando...
🧐 Procesando 14624/17048 - 7d445278-85eb-4441-90aa-9cc27e608d4c | Idioma detectado: en
✅ 7d445278-85eb-4441-90aa-9cc27e608d4c ya está en inglés. Saltando...
🧐 Procesando 14625/17048 - e0435b57-ec6e-4a2a-be89-2aed220bad99 | Idioma detectado: en
✅ e0435b57-ec6e-4a2a-be89-2aed220bad99 ya está en inglés. Saltando...
🧐 Procesando 14626/17048 - 112d680d-5da9-4b72-bea3-04cd903e56f2 | Idioma detectado: en
✅ 112d680d-5da9-4b72-bea3-04cd903e56f2 ya está en inglés. Saltando...
🧐 Procesando 14627/17048 - cf0a70ee-d107-4a5c-ad4b-74241cafeadb | Idioma detectado: en
✅ cf0a70ee-d107-4a5c-ad4b-74241cafeadb ya está en inglés. Saltando...
🧐 Procesando 14628/17048 - d2981b1e-cfd3-4f92-84b7-de38e418d987 | Idioma detectado: en
✅ d2981b1e-cfd3-4f92-84b7-de38e418d987 ya está en inglés. Saltando...
🧐 Procesando 14629/17048 - b3a0d183-566e-4e73-b865-e87771683096 | Idioma detectado: ru
🧐 Procesando 14630/17048 - 3cc52dc3-8377-4285-8b98-2959ec7fa755 | Idioma detectado: pt

🔄 Traduciendo canciones:  86%|████████▌ | 14691/17048 [1:23:34<08:31,  4.61it/s]

✅ 9b41b95f-06cd-494e-87d5-a2ddc5c0573d ya está en inglés. Saltando...
🧐 Procesando 14681/17048 - 5d81af76-fe1a-41e5-a046-931fa5cd484a | Idioma detectado: en
✅ 5d81af76-fe1a-41e5-a046-931fa5cd484a ya está en inglés. Saltando...
🧐 Procesando 14682/17048 - f2a628ac-8bb3-4ffe-bae6-0999758e9c61 | Idioma detectado: en
✅ f2a628ac-8bb3-4ffe-bae6-0999758e9c61 ya está en inglés. Saltando...
🧐 Procesando 14683/17048 - eb6a1b2c-9752-4e9a-8882-8d46ebb441d3 | Idioma detectado: en
✅ eb6a1b2c-9752-4e9a-8882-8d46ebb441d3 ya está en inglés. Saltando...
🧐 Procesando 14684/17048 - 9ea65198-9c21-4ef3-b98a-9559ce71aec7 | Idioma detectado: en
✅ 9ea65198-9c21-4ef3-b98a-9559ce71aec7 ya está en inglés. Saltando...
🧐 Procesando 14685/17048 - f4b25c5d-66e1-4eca-b567-e585ef33cf73 | Idioma detectado: en
✅ f4b25c5d-66e1-4eca-b567-e585ef33cf73 ya está en inglés. Saltando...
🧐 Procesando 14686/17048 - 2543198d-940c-45ba-99f0-d6c4349da840 | Idioma detectado: en
✅ 2543198d-940c-45ba-99f0-d6c4349da840 ya está en inglés. Saltando...
🧐 Procesando 14687/17048 - 544cb196-2bbc-42d7-8cea-66472fdb00cd | Idioma detectado: en
✅ 544cb196-2bbc-42d7-8cea-66472fdb00cd ya está en inglés. Saltando...
🧐 Procesando 14688/17048 - da7f2253-b5d7-4edd-83a3-74b87761c44f | Idioma detectado: en
✅ da7f2253-b5d7-4edd-83a3-74b87761c44f ya está en inglés. Saltando...
🧐 Procesando 14689/17048 - 4d4fdfa1-01b8-457d-881c-0d991cdf4ac8 | Idioma detectado: en
✅ 4d4fdfa1-01b8-457d-881c-0d991cdf4ac8 ya está en inglés. Saltando...
🧐 Procesando 14690/17048 - f9cdf0eb-5250-4b52-ab2e-4972a96c09db | Idioma detectado: es

🔄 Traduciendo canciones:  86%|████████▋ | 14740/17048 [1:23:58<23:53,  1.61it/s]

✅ 3f2c0384-0931-4b3f-bfdf-08ce3cbb5284 ya está en inglés. Saltando...
🧐 Procesando 14729/17048 - 5d0db0db-4b4d-4c44-8b05-d07162055c03 | Idioma detectado: en
✅ 5d0db0db-4b4d-4c44-8b05-d07162055c03 ya está en inglés. Saltando...
🧐 Procesando 14730/17048 - feaf5e08-c3df-4b97-a49b-3a7a4153e872 | Idioma detectado: en
✅ feaf5e08-c3df-4b97-a49b-3a7a4153e872 ya está en inglés. Saltando...
🧐 Procesando 14731/17048 - 2c388353-6d72-447b-8012-54d94c331dda | Idioma detectado: en
✅ 2c388353-6d72-447b-8012-54d94c331dda ya está en inglés. Saltando...
🧐 Procesando 14732/17048 - 9afbcd62-3691-4698-943f-37093ea2a54f | Idioma detectado: en
✅ 9afbcd62-3691-4698-943f-37093ea2a54f ya está en inglés. Saltando...
🧐 Procesando 14733/17048 - b600d145-9fc6-42c6-bc85-5226930863ac | Idioma detectado: fr
🧐 Procesando 14734/17048 - 6ed0dff3-6484-429e-a039-ee7793ff6857 | Idioma detectado: en
✅ 6ed0dff3-6484-429e-a039-ee7793ff6857 ya está en inglés. Saltando...
🧐 Procesando 14735/17048 - 502235b3-2ff2-49d4-98e8-1835b34bc2dc | Idioma detectado: fr
🧐 Procesando 14736/17048 - aa34d66b-0a03-45eb-bca3-113a3b52b4ee | Idioma detectado: en
✅ aa34d66b-0a03-45eb-bca3-113a3b52b4ee ya está en inglés. Saltando...
🧐 Procesando 14737/17048 - 9e84ef5e-fc8f-4d0d-b6cf-628b3a4bfe43 | Idioma detectado: en
✅ 9e84ef5e-fc8f-4d0d-b6cf-628b3a4bfe43 ya está en inglés. Saltando...
🧐 Procesando 14738/17048 - fa1eb811-b5e0-4fa3-aab4-6ab9ae451cf2 | Idioma detectado: de
🧐 Procesando 14739/17048 - 68dbf92b-9c76-4032-8c8b-f87f6df016f4 | Idioma detectado: de
🧐 Procesando 14740/17048 - bd1cdc1b-99cb-4d1a-a218-58e3d0895724 | Idioma detectado: de

🔄 Traduciendo canciones:  87%|████████▋ | 14748/17048 [1:24:15<1:10:54,  1.85s/it]

🧐 Procesando 14735/17048 - 502235b3-2ff2-49d4-98e8-1835b34bc2dc | Idioma detectado: fr
🧐 Procesando 14736/17048 - aa34d66b-0a03-45eb-bca3-113a3b52b4ee | Idioma detectado: en
✅ aa34d66b-0a03-45eb-bca3-113a3b52b4ee ya está en inglés. Saltando...
🧐 Procesando 14737/17048 - 9e84ef5e-fc8f-4d0d-b6cf-628b3a4bfe43 | Idioma detectado: en
✅ 9e84ef5e-fc8f-4d0d-b6cf-628b3a4bfe43 ya está en inglés. Saltando...
🧐 Procesando 14738/17048 - fa1eb811-b5e0-4fa3-aab4-6ab9ae451cf2 | Idioma detectado: de
🧐 Procesando 14739/17048 - 68dbf92b-9c76-4032-8c8b-f87f6df016f4 | Idioma detectado: de
🧐 Procesando 14740/17048 - bd1cdc1b-99cb-4d1a-a218-58e3d0895724 | Idioma detectado: de
🧐 Procesando 14741/17048 - d2f32283-cf6b-4b8c-8bb8-49e7e1499978 | Idioma detectado: de
🧐 Procesando 14742/17048 - b6d25916-a9f5-4547-8e6c-dd6fd134d6d0 | Idioma detectado: de
🧐 Procesando 14743/17048 - 0ae5d797-dbc9-41da-b54a-3ad30b4bf555 | Idioma detectado: de
🧐 Procesando 14744/17048 - 376bf1e0-11d5-4131-8449-fc343cc02ea9 | Idioma detectado: de
🧐 Procesando 14745/17048 - 13c57d16-48cd-4683-a379-007c7c10b678 | Idioma detectado: de
🧐 Procesando 14746/17048 - 2bd6d210-646d-47f2-a22a-1eda4ee28d32 | Idioma detectado: de
🧐 Procesando 14747/17048 - 169c3a24-880e-4d1a-aed6-e42b41571edc | Idioma detectado: de
🧐 Procesando 14748/17048 - c70bfa21-fc3d-42ce-860e-6a970133fdf6 | Idioma detectado: en
✅ c70bfa21-fc3d-42ce-860e-6a970133fdf6 ya está en inglés. Saltando...
🧐 Procesando 14749/17048 - 75250a18-17c9-4ce7-83c5-ce030fdc28c4 | Idioma detectado: en
✅ 75250a18-17c9-4ce7-83c5-ce030fdc28c4 ya está en inglés. Saltando...
🧐 Procesando 14750/17048 - e3028b7e-a954-43c6-b983-6605f96f43b2 | Idioma detectado: fr

🔄 Traduciendo canciones:  87%|████████▋ | 14770/17048 [1:24:38<41:05,  1.08s/it]

🧐 Procesando 14759/17048 - 4b401485-ec4f-43a5-b3f1-11dc10427eb0 | Idioma detectado: en
✅ 4b401485-ec4f-43a5-b3f1-11dc10427eb0 ya está en inglés. Saltando...
🧐 Procesando 14760/17048 - 1619357a-1f6d-4fe2-a0da-6654b0c2172a | Idioma detectado: en
✅ 1619357a-1f6d-4fe2-a0da-6654b0c2172a ya está en inglés. Saltando...
🧐 Procesando 14761/17048 - ebc66021-5bce-4acd-b15c-a14ea85f898d | Idioma detectado: en
✅ ebc66021-5bce-4acd-b15c-a14ea85f898d ya está en inglés. Saltando...
🧐 Procesando 14762/17048 - dbd21d6f-394d-4e3c-aa24-79386e97b1ae | Idioma detectado: en
✅ dbd21d6f-394d-4e3c-aa24-79386e97b1ae ya está en inglés. Saltando...
🧐 Procesando 14763/17048 - 86519b7c-b499-4049-97ad-c8caa82e774c | Idioma detectado: en
✅ 86519b7c-b499-4049-97ad-c8caa82e774c ya está en inglés. Saltando...
🧐 Procesando 14764/17048 - 0390db3a-31cf-40db-8332-47a86d1e7cf0 | Idioma detectado: en
✅ 0390db3a-31cf-40db-8332-47a86d1e7cf0 ya está en inglés. Saltando...
🧐 Procesando 14765/17048 - c2bdc1c9-6fd4-4efb-b488-a03fbf6504e7 | Idioma detectado: en
✅ c2bdc1c9-6fd4-4efb-b488-a03fbf6504e7 ya está en inglés. Saltando...
🧐 Procesando 14766/17048 - 8c8b736d-0682-4026-8027-39fe7a117ad3 | Idioma detectado: en
✅ 8c8b736d-0682-4026-8027-39fe7a117ad3 ya está en inglés. Saltando...
🧐 Procesando 14767/17048 - 1642162a-d991-409f-be1a-2c590ada1aa2 | Idioma detectado: de
🧐 Procesando 14768/17048 - 2040d2d0-447a-4b10-b19e-0ae7b15188db | Idioma detectado: de
🧐 Procesando 14769/17048 - f78eadc5-fce0-40c0-ba55-88897d1dbbf9 | Idioma detectado: de
🧐 Procesando 14770/17048 - 42f832ea-1701-48f0-8af9-d82434ba8f33 | Idioma detectado: de

🔄 Traduciendo canciones:  87%|████████▋ | 14904/17048 [1:25:02<02:33, 14.00it/s]

✅ 63ad6eb4-0f31-45a0-b24f-7df1eb8fe7e6 ya está en inglés. Saltando...
🧐 Procesando 14911/17048 - e2fc45fe-efb2-4b44-b2da-16e9d4a113d5 | Idioma detectado: en
✅ e2fc45fe-efb2-4b44-b2da-16e9d4a113d5 ya está en inglés. Saltando...
🧐 Procesando 14912/17048 - 17f34a6e-0596-4dbc-8a18-05253f746817 | Idioma detectado: en
✅ 17f34a6e-0596-4dbc-8a18-05253f746817 ya está en inglés. Saltando...
🧐 Procesando 14913/17048 - 618dbda5-bd9d-4f68-ad04-1f903a41a72d | Idioma detectado: en
✅ 618dbda5-bd9d-4f68-ad04-1f903a41a72d ya está en inglés. Saltando...
🧐 Procesando 14914/17048 - 3dd7a791-56bd-4811-9ed6-e3ff72c6698b | Idioma detectado: en
✅ 3dd7a791-56bd-4811-9ed6-e3ff72c6698b ya está en inglés. Saltando...
🧐 Procesando 14915/17048 - 673d66b5-1d61-4293-a489-2f5ae737f6e4 | Idioma detectado: en
✅ 673d66b5-1d61-4293-a489-2f5ae737f6e4 ya está en inglés. Saltando...
🧐 Procesando 14916/17048 - b705a185-1893-4347-81fe-17311cb3fb41 | Idioma detectado: en
✅ b705a185-1893-4347-81fe-17311cb3fb41 ya está en inglés. Saltando...
🧐 Procesando 14917/17048 - 4e26b9ca-3410-499c-b9f9-b8ca9fc26ed5 | Idioma detectado: en
✅ 4e26b9ca-3410-499c-b9f9-b8ca9fc26ed5 ya está en inglés. Saltando...
🧐 Procesando 14918/17048 - 5a03789f-d79a-478e-b043-af5b3eeb1904 | Idioma detectado: en
✅ 5a03789f-d79a-478e-b043-af5b3eeb1904 ya está en inglés. Saltando...
🧐 Procesando 14919/17048 - 77bd33a9-7164-4ead-b242-a1a6a8b7d87c | Idioma detectado: en
✅ 77bd33a9-7164-4ead-b242-a1a6a8b7d87c ya está en inglés. Saltando...
🧐 Procesando 14920/17048 - 65137178-fbd6-416f-bbca-1c6226d7fed3 | Idioma detectado: fr

🔄 Traduciendo canciones:  88%|████████▊ | 14946/17048 [1:25:39<36:15,  1.03s/it]

🧐 Procesando 14939/17048 - 56812551-478f-411e-8fbb-1647a9790c2b | Idioma detectado: en
✅ 56812551-478f-411e-8fbb-1647a9790c2b ya está en inglés. Saltando...
🧐 Procesando 14940/17048 - ef7b8a0e-03c4-4ccc-a216-673577aa492e | Idioma detectado: en
✅ ef7b8a0e-03c4-4ccc-a216-673577aa492e ya está en inglés. Saltando...
🧐 Procesando 14941/17048 - 4166d845-b93e-4738-af14-b2e110966458 | Idioma detectado: en
✅ 4166d845-b93e-4738-af14-b2e110966458 ya está en inglés. Saltando...
🧐 Procesando 14942/17048 - c1dee290-49e1-447c-91a0-71683376ab2d | Idioma detectado: fi
🧐 Procesando 14943/17048 - 4f8099f8-89dd-4cd1-8b02-b381684f72a6 | Idioma detectado: fi
🧐 Procesando 14944/17048 - 2a24cd50-f142-48a6-aaa5-f0a351e6640f | Idioma detectado: en
✅ 2a24cd50-f142-48a6-aaa5-f0a351e6640f ya está en inglés. Saltando...
🧐 Procesando 14945/17048 - 1242d5f9-8827-4397-a255-cdc2f807ad8a | Idioma detectado: fi
🧐 Procesando 14946/17048 - 2da042e6-1b82-45af-a159-549fcc4bdde6 | Idioma detectado: en
✅ 2da042e6-1b82-45af-a159-549fcc4bdde6 ya está en inglés. Saltando...
🧐 Procesando 14947/17048 - d3b9219d-890b-4046-88ba-094dabc6bf88 | Idioma detectado: en
✅ d3b9219d-890b-4046-88ba-094dabc6bf88 ya está en inglés. Saltando...
🧐 Procesando 14948/17048 - f62f80c0-543c-47bd-9c8d-789d761bc769 | Idioma detectado: en
✅ f62f80c0-543c-47bd-9c8d-789d761bc769 ya está en inglés. Saltando...
🧐 Procesando 14949/17048 - 8a4e32a1-9df4-4268-9610-cefc25ec2f6e | Idioma detectado: en
✅ 8a4e32a1-9df4-4268-9610-cefc25ec2f6e ya está en inglés. Saltando...
🧐 Procesando 14950/17048 - 8698d940-8199-43e7-9394-914a38846588 | Idioma detectado: fi

🔄 Traduciendo canciones:  88%|████████▊ | 14982/17048 [1:25:51<13:24,  2.57it/s]

✅ b8275050-73fd-4202-8879-6381fd7baaed ya está en inglés. Saltando...
🧐 Procesando 15001/17048 - 4c9fcf4f-d092-4dcb-8de6-0cd16d5f2f71 | Idioma detectado: en
✅ 4c9fcf4f-d092-4dcb-8de6-0cd16d5f2f71 ya está en inglés. Saltando...
🧐 Procesando 15002/17048 - b5dfa162-9582-4005-9e73-104f90136d56 | Idioma detectado: en
✅ b5dfa162-9582-4005-9e73-104f90136d56 ya está en inglés. Saltando...
🧐 Procesando 15003/17048 - 5a71a89f-ef98-4fb6-ac54-5b6f99952bbc | Idioma detectado: en
✅ 5a71a89f-ef98-4fb6-ac54-5b6f99952bbc ya está en inglés. Saltando...
🧐 Procesando 15004/17048 - d04d0fb5-64a5-417b-a597-0373dfeffbca | Idioma detectado: en
✅ d04d0fb5-64a5-417b-a597-0373dfeffbca ya está en inglés. Saltando...
🧐 Procesando 15005/17048 - c185dae4-0740-4721-b275-cb83978b3543 | Idioma detectado: en
✅ c185dae4-0740-4721-b275-cb83978b3543 ya está en inglés. Saltando...
🧐 Procesando 15006/17048 - aa99ef93-406d-4be9-b180-af34e11b8fad | Idioma detectado: en
✅ aa99ef93-406d-4be9-b180-af34e11b8fad ya está en inglés. Saltando...
🧐 Procesando 15007/17048 - ec5d929d-262c-4e1a-ac45-bb7d9e4e1119 | Idioma detectado: en
✅ ec5d929d-262c-4e1a-ac45-bb7d9e4e1119 ya está en inglés. Saltando...
🧐 Procesando 15008/17048 - d3e55ffd-562f-45d9-9211-f81632e73a15 | Idioma detectado: en
✅ d3e55ffd-562f-45d9-9211-f81632e73a15 ya está en inglés. Saltando...
🧐 Procesando 15009/17048 - 1c0f60e2-e93a-4be6-8b9e-b3ab26dec336 | Idioma detectado: en
✅ 1c0f60e2-e93a-4be6-8b9e-b3ab26dec336 ya está en inglés. Saltando...
🧐 Procesando 15010/17048 - 21c1ef03-ff32-42f4-b8cd-5c55d8f99f7c | Idioma detectado: it

🔄 Traduciendo canciones:  88%|████████▊ | 15080/17048 [1:26:08<08:38,  3.80it/s]

🧐 Procesando 15069/17048 - 6fafa158-7a6a-428b-a368-42b647e5458e | Idioma detectado: en
✅ 6fafa158-7a6a-428b-a368-42b647e5458e ya está en inglés. Saltando...
🧐 Procesando 15070/17048 - 03df653a-3f1a-44af-a091-53425e8ed432 | Idioma detectado: en
✅ 03df653a-3f1a-44af-a091-53425e8ed432 ya está en inglés. Saltando...
🧐 Procesando 15071/17048 - f621d7f4-f013-4b9d-b32a-6897a7f7b77c | Idioma detectado: en
✅ f621d7f4-f013-4b9d-b32a-6897a7f7b77c ya está en inglés. Saltando...
🧐 Procesando 15072/17048 - d9c764c6-bbe1-4944-a9a3-deb6bf824277 | Idioma detectado: pt
🧐 Procesando 15073/17048 - 789324e1-8caa-4cae-851f-98811e02dcc9 | Idioma detectado: en
✅ 789324e1-8caa-4cae-851f-98811e02dcc9 ya está en inglés. Saltando...
🧐 Procesando 15074/17048 - a53a028b-2647-4c46-bcc2-27d9110870d3 | Idioma detectado: de
🧐 Procesando 15075/17048 - 6ca76a73-ca26-4bac-b279-1ceccd839634 | Idioma detectado: en
✅ 6ca76a73-ca26-4bac-b279-1ceccd839634 ya está en inglés. Saltando...
🧐 Procesando 15076/17048 - 8b2985de-4c2b-4161-9bea-5d203c48fc9a | Idioma detectado: en
✅ 8b2985de-4c2b-4161-9bea-5d203c48fc9a ya está en inglés. Saltando...
🧐 Procesando 15077/17048 - 3824f76e-855c-4e28-8b31-f426ab4c635b | Idioma detectado: en
✅ 3824f76e-855c-4e28-8b31-f426ab4c635b ya está en inglés. Saltando...
🧐 Procesando 15078/17048 - c216d91d-f5a4-48d9-8281-3028090beeda | Idioma detectado: en
✅ c216d91d-f5a4-48d9-8281-3028090beeda ya está en inglés. Saltando...
🧐 Procesando 15079/17048 - ec04a7b1-5566-4a9e-b0de-5e4675710541 | Idioma detectado: nl
🧐 Procesando 15080/17048 - 83d019bb-a551-4db2-a96d-fbaab094c7ec | Idioma detectado: pt

🔄 Traduciendo canciones:  89%|████████▊ | 15089/17048 [1:26:16<15:02,  2.17it/s]

✅ c216d91d-f5a4-48d9-8281-3028090beeda ya está en inglés. Saltando...
🧐 Procesando 15079/17048 - ec04a7b1-5566-4a9e-b0de-5e4675710541 | Idioma detectado: nl
🧐 Procesando 15080/17048 - 83d019bb-a551-4db2-a96d-fbaab094c7ec | Idioma detectado: pt
🧐 Procesando 15081/17048 - 694ffcdd-f92b-46cb-98a7-852d4429277c | Idioma detectado: en
✅ 694ffcdd-f92b-46cb-98a7-852d4429277c ya está en inglés. Saltando...
🧐 Procesando 15082/17048 - f1b473df-b993-45cf-a1a7-c81abff917af | Idioma detectado: nl
🧐 Procesando 15083/17048 - d6562c86-1720-414d-88fa-fb0ac59dce44 | Idioma detectado: en
✅ d6562c86-1720-414d-88fa-fb0ac59dce44 ya está en inglés. Saltando...
🧐 Procesando 15084/17048 - 26108703-2df3-4f01-9558-c9133ad1c5e3 | Idioma detectado: en
✅ 26108703-2df3-4f01-9558-c9133ad1c5e3 ya está en inglés. Saltando...
🧐 Procesando 15085/17048 - 1c297988-c9ac-49b8-b2fa-1a5f486b38ef | Idioma detectado: en
✅ 1c297988-c9ac-49b8-b2fa-1a5f486b38ef ya está en inglés. Saltando...
🧐 Procesando 15086/17048 - c8222055-c252-46f1-9b87-d4f649e0f37b | Idioma detectado: en
✅ c8222055-c252-46f1-9b87-d4f649e0f37b ya está en inglés. Saltando...
🧐 Procesando 15087/17048 - d42b83a7-0230-4a6d-8920-048eac17710b | Idioma detectado: en
✅ d42b83a7-0230-4a6d-8920-048eac17710b ya está en inglés. Saltando...
🧐 Procesando 15088/17048 - 5ac426a6-704a-49f0-be53-5c48ac7c5a6b | Idioma detectado: es
🧐 Procesando 15089/17048 - 5c05e045-1bfd-4bb9-a70f-ab900faf020d | Idioma detectado: en
✅ 5c05e045-1bfd-4bb9-a70f-ab900faf020d ya está en inglés. Saltando...
🧐 Procesando 15090/17048 - c8e04d79-147c-41fb-909f-f15449fd12cf | Idioma detectado: es

🔄 Traduciendo canciones:  89%|████████▉ | 15160/17048 [1:26:37<07:12,  4.37it/s]

🧐 Procesando 15150/17048 - 82c33431-8afe-4463-9ae5-087f4697dca5 | Idioma detectado: en
✅ 82c33431-8afe-4463-9ae5-087f4697dca5 ya está en inglés. Saltando...
🧐 Procesando 15151/17048 - 0ce2a532-4c43-4357-9aaa-1e4dcc300aa2 | Idioma detectado: en
✅ 0ce2a532-4c43-4357-9aaa-1e4dcc300aa2 ya está en inglés. Saltando...
🧐 Procesando 15152/17048 - 6e4f9285-e6fb-423b-b751-d8d48261cd2f | Idioma detectado: en
✅ 6e4f9285-e6fb-423b-b751-d8d48261cd2f ya está en inglés. Saltando...
🧐 Procesando 15153/17048 - 4886b301-7b1e-4aac-a391-361f87cbc739 | Idioma detectado: en
✅ 4886b301-7b1e-4aac-a391-361f87cbc739 ya está en inglés. Saltando...
🧐 Procesando 15154/17048 - 5ad82359-b7d0-4587-8913-c646c1a76136 | Idioma detectado: en
✅ 5ad82359-b7d0-4587-8913-c646c1a76136 ya está en inglés. Saltando...
🧐 Procesando 15155/17048 - 7a2e4566-2eb7-4d09-a53d-c5b58aa188c4 | Idioma detectado: en
✅ 7a2e4566-2eb7-4d09-a53d-c5b58aa188c4 ya está en inglés. Saltando...
🧐 Procesando 15156/17048 - 088d8cd6-b266-44d7-b83a-6dc4d42109ae | Idioma detectado: en
✅ 088d8cd6-b266-44d7-b83a-6dc4d42109ae ya está en inglés. Saltando...
🧐 Procesando 15157/17048 - 837d46cc-e01e-4753-acca-2193a2949799 | Idioma detectado: en
✅ 837d46cc-e01e-4753-acca-2193a2949799 ya está en inglés. Saltando...
🧐 Procesando 15158/17048 - b39203ca-9f35-48fc-b9db-ad5b8b7e4066 | Idioma detectado: en
✅ b39203ca-9f35-48fc-b9db-ad5b8b7e4066 ya está en inglés. Saltando...
🧐 Procesando 15159/17048 - 662559e4-bc8e-4769-b692-ba61c3200ea0 | Idioma detectado: nl
🧐 Procesando 15160/17048 - e062fc8a-6442-4886-99d8-e8407c569676 | Idioma detectado: es

🔄 Traduciendo canciones:  89%|████████▉ | 15173/17048 [1:26:49<19:28,  1.61it/s]

🧐 Procesando 15170/17048 - 7482b63e-e7ee-4725-8242-af806d26cc6b | Idioma detectado: en
✅ 7482b63e-e7ee-4725-8242-af806d26cc6b ya está en inglés. Saltando...
🧐 Procesando 15171/17048 - 3ae668e5-998b-4781-a191-278cf003906a | Idioma detectado: en
✅ 3ae668e5-998b-4781-a191-278cf003906a ya está en inglés. Saltando...
🧐 Procesando 15172/17048 - ca290bf5-c79a-4315-a60d-1fcaad1ddff3 | Idioma detectado: nl
🧐 Procesando 15173/17048 - 5934f143-c316-4c8e-baf4-e4b4f865d486 | Idioma detectado: en
✅ 5934f143-c316-4c8e-baf4-e4b4f865d486 ya está en inglés. Saltando...
🧐 Procesando 15174/17048 - 71791223-ded4-413d-9696-e196cab05ff2 | Idioma detectado: en
✅ 71791223-ded4-413d-9696-e196cab05ff2 ya está en inglés. Saltando...
🧐 Procesando 15175/17048 - 2f9dfb55-16c1-4308-8582-2742da43dca6 | Idioma detectado: en
✅ 2f9dfb55-16c1-4308-8582-2742da43dca6 ya está en inglés. Saltando...
🧐 Procesando 15176/17048 - 83d2135d-9fd5-4558-b319-a2bc3703b686 | Idioma detectado: en
✅ 83d2135d-9fd5-4558-b319-a2bc3703b686 ya está en inglés. Saltando...
🧐 Procesando 15177/17048 - d0913f4b-3e2d-408e-9003-7492ebb4a487 | Idioma detectado: en
✅ d0913f4b-3e2d-408e-9003-7492ebb4a487 ya está en inglés. Saltando...
🧐 Procesando 15178/17048 - 39aa218a-6c8c-4cfb-83dc-e398c2f1916d | Idioma detectado: en
✅ 39aa218a-6c8c-4cfb-83dc-e398c2f1916d ya está en inglés. Saltando...
🧐 Procesando 15179/17048 - 702eb3cf-ee94-4a91-bb7d-660aeb452765 | Idioma detectado: en
✅ 702eb3cf-ee94-4a91-bb7d-660aeb452765 ya está en inglés. Saltando...
🧐 Procesando 15180/17048 - afc9979a-da7d-4b27-aa93-0e69b6b5f033 | Idioma detectado: es

🔄 Traduciendo canciones:  89%|████████▉ | 15219/17048 [1:27:02<08:30,  3.59it/s]

🧐 Procesando 15210/17048 - 8c7559b5-418c-40b8-a987-99dc167731dd | Idioma detectado: en
✅ 8c7559b5-418c-40b8-a987-99dc167731dd ya está en inglés. Saltando...
🧐 Procesando 15211/17048 - a45439c9-6300-4eb2-b160-5660106c7996 | Idioma detectado: en
✅ a45439c9-6300-4eb2-b160-5660106c7996 ya está en inglés. Saltando...
🧐 Procesando 15212/17048 - c8a1bc0f-ab26-44df-827a-2e1e3e65aa7e | Idioma detectado: en
✅ c8a1bc0f-ab26-44df-827a-2e1e3e65aa7e ya está en inglés. Saltando...
🧐 Procesando 15213/17048 - 7856da1f-2582-4d2e-922b-2f7e5fe7f672 | Idioma detectado: en
✅ 7856da1f-2582-4d2e-922b-2f7e5fe7f672 ya está en inglés. Saltando...
🧐 Procesando 15214/17048 - df0b0d8e-0c13-497b-8dcd-7c4ded79b246 | Idioma detectado: en
✅ df0b0d8e-0c13-497b-8dcd-7c4ded79b246 ya está en inglés. Saltando...
🧐 Procesando 15215/17048 - a4af5f9e-738c-41c3-9d63-bffc35673eb0 | Idioma detectado: en
✅ a4af5f9e-738c-41c3-9d63-bffc35673eb0 ya está en inglés. Saltando...
🧐 Procesando 15216/17048 - c519cd07-2498-41f3-809b-ec191f223132 | Idioma detectado: en
✅ c519cd07-2498-41f3-809b-ec191f223132 ya está en inglés. Saltando...
🧐 Procesando 15217/17048 - 6c955e3c-bb11-47d2-a23c-e3e92786e57b | Idioma detectado: en
✅ 6c955e3c-bb11-47d2-a23c-e3e92786e57b ya está en inglés. Saltando...
🧐 Procesando 15218/17048 - 8f07132b-bb4f-4144-8f88-64a33ae7a31a | Idioma detectado: es
🧐 Procesando 15219/17048 - 8949fb44-2c50-45e5-9305-b1f24afe78ac | Idioma detectado: en
✅ 8949fb44-2c50-45e5-9305-b1f24afe78ac ya está en inglés. Saltando...
🧐 Procesando 15220/17048 - 851eea78-ff9d-489c-b4f6-73f2a6be97c1 | Idioma detectado: co

🔄 Traduciendo canciones:  89%|████████▉ | 15243/17048 [1:27:06<06:02,  4.99it/s]

🧐 Procesando 15240/17048 - acd563b4-ef7f-4436-a04c-b33db6b9caf8 | Idioma detectado: en
✅ acd563b4-ef7f-4436-a04c-b33db6b9caf8 ya está en inglés. Saltando...
🧐 Procesando 15241/17048 - bceb9a06-8787-4940-b938-ab1cad796bff | Idioma detectado: en
✅ bceb9a06-8787-4940-b938-ab1cad796bff ya está en inglés. Saltando...
🧐 Procesando 15242/17048 - 0dd68c38-1649-474f-9216-f932547d074c | Idioma detectado: co
🧐 Procesando 15243/17048 - e7c8d1ef-1dc5-43b9-9d91-8f9dd1b5042d | Idioma detectado: en
✅ e7c8d1ef-1dc5-43b9-9d91-8f9dd1b5042d ya está en inglés. Saltando...
🧐 Procesando 15244/17048 - 8c7ef54d-6ec4-4d5c-857c-0141a9eda6db | Idioma detectado: en
✅ 8c7ef54d-6ec4-4d5c-857c-0141a9eda6db ya está en inglés. Saltando...
🧐 Procesando 15245/17048 - 0658eda8-150c-41c9-9eec-a02cf2921b1b | Idioma detectado: en
✅ 0658eda8-150c-41c9-9eec-a02cf2921b1b ya está en inglés. Saltando...
🧐 Procesando 15246/17048 - f3be3af6-1059-4fdd-95c6-b25afbcaed70 | Idioma detectado: en
✅ f3be3af6-1059-4fdd-95c6-b25afbcaed70 ya está en inglés. Saltando...
🧐 Procesando 15247/17048 - 774ff15e-f79c-462c-80e3-8470ad6f699d | Idioma detectado: en
✅ 774ff15e-f79c-462c-80e3-8470ad6f699d ya está en inglés. Saltando...
🧐 Procesando 15248/17048 - b5ddfce4-8717-4333-9901-d086070a4b91 | Idioma detectado: en
✅ b5ddfce4-8717-4333-9901-d086070a4b91 ya está en inglés. Saltando...
🧐 Procesando 15249/17048 - 8f2114a6-62f7-49a0-b300-e84604860dd7 | Idioma detectado: en
✅ 8f2114a6-62f7-49a0-b300-e84604860dd7 ya está en inglés. Saltando...
🧐 Procesando 15250/17048 - b48630a3-5117-47d2-82a7-1dc1eba7066b | Idioma detectado: nl

🔄 Traduciendo canciones:  89%|████████▉ | 15256/17048 [1:27:11<07:58,  3.75it/s]

✅ 8f2114a6-62f7-49a0-b300-e84604860dd7 ya está en inglés. Saltando...
🧐 Procesando 15250/17048 - b48630a3-5117-47d2-82a7-1dc1eba7066b | Idioma detectado: nl
🧐 Procesando 15251/17048 - 22ff9c1c-0445-4ca1-89c1-00812a853b92 | Idioma detectado: en
✅ 22ff9c1c-0445-4ca1-89c1-00812a853b92 ya está en inglés. Saltando...
🧐 Procesando 15252/17048 - c94adda0-8976-490b-8695-3a067210e32d | Idioma detectado: en
✅ c94adda0-8976-490b-8695-3a067210e32d ya está en inglés. Saltando...
🧐 Procesando 15253/17048 - f46cb927-649c-41da-9af2-c74d48467a84 | Idioma detectado: en
✅ f46cb927-649c-41da-9af2-c74d48467a84 ya está en inglés. Saltando...
🧐 Procesando 15254/17048 - ee3c4d49-0409-4833-a484-dec862b78c94 | Idioma detectado: en
✅ ee3c4d49-0409-4833-a484-dec862b78c94 ya está en inglés. Saltando...
🧐 Procesando 15255/17048 - 74ce39be-5a4e-4ea2-8798-cac1c8512d53 | Idioma detectado: nl
🧐 Procesando 15256/17048 - a81aabb4-5294-438d-bf14-b86cffe0edec | Idioma detectado: en
✅ a81aabb4-5294-438d-bf14-b86cffe0edec ya está en inglés. Saltando...
🧐 Procesando 15257/17048 - f3fe3791-4fe4-47ca-9c39-7b76584ed75b | Idioma detectado: en
✅ f3fe3791-4fe4-47ca-9c39-7b76584ed75b ya está en inglés. Saltando...
🧐 Procesando 15258/17048 - 987dcb36-5e80-4ff9-b20b-2214233fc333 | Idioma detectado: en
✅ 987dcb36-5e80-4ff9-b20b-2214233fc333 ya está en inglés. Saltando...
🧐 Procesando 15259/17048 - 039b410b-71ce-45ec-898d-a938233dc8c5 | Idioma detectado: en
✅ 039b410b-71ce-45ec-898d-a938233dc8c5 ya está en inglés. Saltando...
🧐 Procesando 15260/17048 - 8bd26860-bdaa-42c7-a51c-910e2302217c | Idioma detectado: fr

🔄 Traduciendo canciones:  90%|████████▉ | 15309/17048 [1:27:24<07:57,  3.64it/s]

✅ 11b6b1e4-64cb-4bb0-9290-87d5a8108059 ya está en inglés. Saltando...
🧐 Procesando 15300/17048 - 5e809ca0-9450-4c99-97b4-8345d12937e5 | Idioma detectado: en
✅ 5e809ca0-9450-4c99-97b4-8345d12937e5 ya está en inglés. Saltando...
🧐 Procesando 15301/17048 - 3a6a2a53-b4cc-4592-97e4-8e6b5ab23b7f | Idioma detectado: en
✅ 3a6a2a53-b4cc-4592-97e4-8e6b5ab23b7f ya está en inglés. Saltando...
🧐 Procesando 15302/17048 - 3cee768f-d8cb-42ec-8b0f-12a6c380cca0 | Idioma detectado: en
✅ 3cee768f-d8cb-42ec-8b0f-12a6c380cca0 ya está en inglés. Saltando...
🧐 Procesando 15303/17048 - c51e2b90-6b94-4b64-8e9c-a5651e9fe3f3 | Idioma detectado: en
✅ c51e2b90-6b94-4b64-8e9c-a5651e9fe3f3 ya está en inglés. Saltando...
🧐 Procesando 15304/17048 - 40b30f1a-f34e-45bc-9118-8343fe4dfc92 | Idioma detectado: en
✅ 40b30f1a-f34e-45bc-9118-8343fe4dfc92 ya está en inglés. Saltando...
🧐 Procesando 15305/17048 - 0ae25909-1d66-47e5-be3e-032e23f9b6eb | Idioma detectado: pt
🧐 Procesando 15306/17048 - a71f197e-0d10-4256-bd14-d9d2c81c0ba7 | Idioma detectado: en
✅ a71f197e-0d10-4256-bd14-d9d2c81c0ba7 ya está en inglés. Saltando...
🧐 Procesando 15307/17048 - 809cc625-bb38-4d9d-b559-f8af30d79b48 | Idioma detectado: en
✅ 809cc625-bb38-4d9d-b559-f8af30d79b48 ya está en inglés. Saltando...
🧐 Procesando 15308/17048 - dbf1416b-9e33-4d04-b703-6b370d6870b5 | Idioma detectado: pt
🧐 Procesando 15309/17048 - e5177273-c704-4490-9a3d-0824f71c8d63 | Idioma detectado: en
✅ e5177273-c704-4490-9a3d-0824f71c8d63 ya está en inglés. Saltando...
🧐 Procesando 15310/17048 - 71f1fa64-12d5-4d31-ad18-d57b98fc53eb | Idioma detectado: pt

🔄 Traduciendo canciones:  90%|████████▉ | 15330/17048 [1:27:39<11:38,  2.46it/s]

🧐 Procesando 15320/17048 - 587d2eaf-4ab2-4e62-8994-f0239ac0a91e | Idioma detectado: en
✅ 587d2eaf-4ab2-4e62-8994-f0239ac0a91e ya está en inglés. Saltando...
🧐 Procesando 15321/17048 - ff395ec4-746c-4353-91ea-1f5f906cae11 | Idioma detectado: en
✅ ff395ec4-746c-4353-91ea-1f5f906cae11 ya está en inglés. Saltando...
🧐 Procesando 15322/17048 - be118186-8c19-46d3-a71e-9406ee1926f7 | Idioma detectado: en
✅ be118186-8c19-46d3-a71e-9406ee1926f7 ya está en inglés. Saltando...
🧐 Procesando 15323/17048 - 30fd61ba-0b09-4e2d-9b75-c884b5c659ea | Idioma detectado: en
✅ 30fd61ba-0b09-4e2d-9b75-c884b5c659ea ya está en inglés. Saltando...
🧐 Procesando 15324/17048 - 52654b09-9efa-4244-b509-c6ed047a87b8 | Idioma detectado: en
✅ 52654b09-9efa-4244-b509-c6ed047a87b8 ya está en inglés. Saltando...
🧐 Procesando 15325/17048 - f5228298-3ed2-4db9-b2de-440d95724747 | Idioma detectado: en
✅ f5228298-3ed2-4db9-b2de-440d95724747 ya está en inglés. Saltando...
🧐 Procesando 15326/17048 - ce8e09d3-5ebe-4be0-a0b7-622dcb989fae | Idioma detectado: en
✅ ce8e09d3-5ebe-4be0-a0b7-622dcb989fae ya está en inglés. Saltando...
🧐 Procesando 15327/17048 - f57a6aa4-f794-4b77-ab9e-52647550867d | Idioma detectado: en
✅ f57a6aa4-f794-4b77-ab9e-52647550867d ya está en inglés. Saltando...
🧐 Procesando 15328/17048 - 52df5820-1ead-414e-b202-17d69e066040 | Idioma detectado: en
✅ 52df5820-1ead-414e-b202-17d69e066040 ya está en inglés. Saltando...
🧐 Procesando 15329/17048 - 338348fd-c542-42ac-8215-8548658eded2 | Idioma detectado: pt
🧐 Procesando 15330/17048 - 1d62498d-3e1e-49c5-a0d4-c6e3eeee74d7 | Idioma detectado: es

🔄 Traduciendo canciones:  90%|█████████ | 15405/17048 [1:28:11<12:04,  2.27it/s]

✅ 389cba0c-e7f8-4cab-b09e-e2963bbdc013 ya está en inglés. Saltando...
🧐 Procesando 15411/17048 - 5f0cc690-6661-44bc-a568-9697aaa218d2 | Idioma detectado: en
✅ 5f0cc690-6661-44bc-a568-9697aaa218d2 ya está en inglés. Saltando...
🧐 Procesando 15412/17048 - 77a4d55e-0a97-4c9c-a779-ece9d077bf35 | Idioma detectado: en
✅ 77a4d55e-0a97-4c9c-a779-ece9d077bf35 ya está en inglés. Saltando...
🧐 Procesando 15413/17048 - f4791fbf-e166-4d56-af9e-3accca7e15fd | Idioma detectado: en
✅ f4791fbf-e166-4d56-af9e-3accca7e15fd ya está en inglés. Saltando...
🧐 Procesando 15414/17048 - 95e1dd92-c9c2-4511-ad09-060962c06fb4 | Idioma detectado: en
✅ 95e1dd92-c9c2-4511-ad09-060962c06fb4 ya está en inglés. Saltando...
🧐 Procesando 15415/17048 - 651dcc45-240f-4385-ad6b-ab1786e5611f | Idioma detectado: en
✅ 651dcc45-240f-4385-ad6b-ab1786e5611f ya está en inglés. Saltando...
🧐 Procesando 15416/17048 - 9244f26a-6c13-4c47-9339-ee5adc1a99d9 | Idioma detectado: en
✅ 9244f26a-6c13-4c47-9339-ee5adc1a99d9 ya está en inglés. Saltando...
🧐 Procesando 15417/17048 - d09ecae3-8394-4aa6-b8e1-20d5f239c40b | Idioma detectado: en
✅ d09ecae3-8394-4aa6-b8e1-20d5f239c40b ya está en inglés. Saltando...
🧐 Procesando 15418/17048 - ffa28a3e-cc64-4cfe-9d86-b22500c063d3 | Idioma detectado: en
✅ ffa28a3e-cc64-4cfe-9d86-b22500c063d3 ya está en inglés. Saltando...
🧐 Procesando 15419/17048 - 6f8d7f8e-6afc-4047-8116-110cea7a5f48 | Idioma detectado: en
✅ 6f8d7f8e-6afc-4047-8116-110cea7a5f48 ya está en inglés. Saltando...
🧐 Procesando 15420/17048 - bdc6fe7d-f99e-4dd4-b78b-fa99f24b90c9 | Idioma detectado: de

🔄 Traduciendo canciones:  91%|█████████ | 15432/17048 [1:28:14<05:51,  4.59it/s]

✅ dffb1aea-40a3-4645-be87-12f3d336dcb4 ya está en inglés. Saltando...
🧐 Procesando 15441/17048 - 0eff7230-9444-43f7-811e-dcf7c30996da | Idioma detectado: en
✅ 0eff7230-9444-43f7-811e-dcf7c30996da ya está en inglés. Saltando...
🧐 Procesando 15442/17048 - 6f675437-13a5-4005-adf1-31b362915c45 | Idioma detectado: en
✅ 6f675437-13a5-4005-adf1-31b362915c45 ya está en inglés. Saltando...
🧐 Procesando 15443/17048 - 98198a94-0b42-4d6c-977e-9364cc8506f3 | Idioma detectado: en
✅ 98198a94-0b42-4d6c-977e-9364cc8506f3 ya está en inglés. Saltando...
🧐 Procesando 15444/17048 - 75cacd17-1517-4e14-9a62-95856eeacd9d | Idioma detectado: en
✅ 75cacd17-1517-4e14-9a62-95856eeacd9d ya está en inglés. Saltando...
🧐 Procesando 15445/17048 - 599944df-5afc-4470-be80-a41bca1a429f | Idioma detectado: en
✅ 599944df-5afc-4470-be80-a41bca1a429f ya está en inglés. Saltando...
🧐 Procesando 15446/17048 - dcb6f5be-4447-47d0-afac-385fc7287767 | Idioma detectado: en
✅ dcb6f5be-4447-47d0-afac-385fc7287767 ya está en inglés. Saltando...
🧐 Procesando 15447/17048 - 04365b0d-f15c-485e-94b1-95b0c357d473 | Idioma detectado: en
✅ 04365b0d-f15c-485e-94b1-95b0c357d473 ya está en inglés. Saltando...
🧐 Procesando 15448/17048 - 5bb62066-509f-435f-bd2b-5f1360d9310e | Idioma detectado: en
✅ 5bb62066-509f-435f-bd2b-5f1360d9310e ya está en inglés. Saltando...
🧐 Procesando 15449/17048 - bf5491b1-3808-4c41-82d0-a3aaffd517d4 | Idioma detectado: en
✅ bf5491b1-3808-4c41-82d0-a3aaffd517d4 ya está en inglés. Saltando...
🧐 Procesando 15450/17048 - 7b04e345-fcac-4718-8847-b74e8f3461ee | Idioma detectado: id

🔄 Traduciendo canciones:  91%|█████████▏| 15566/17048 [1:28:29<03:15,  7.59it/s]

✅ 930e4ac8-63c4-4854-9df9-02563a1f2477 ya está en inglés. Saltando...
🧐 Procesando 15560/17048 - 18f6cf15-6838-4799-a76b-4bf112dfeeb6 | Idioma detectado: en
✅ 18f6cf15-6838-4799-a76b-4bf112dfeeb6 ya está en inglés. Saltando...
🧐 Procesando 15561/17048 - 62af0606-da2f-4f90-bd53-46c357108edf | Idioma detectado: en
✅ 62af0606-da2f-4f90-bd53-46c357108edf ya está en inglés. Saltando...
🧐 Procesando 15562/17048 - 25ee792a-b895-480d-9a2e-61d8f6cafb03 | Idioma detectado: en
✅ 25ee792a-b895-480d-9a2e-61d8f6cafb03 ya está en inglés. Saltando...
🧐 Procesando 15563/17048 - d128ba8e-2562-45b5-a407-bbd5505eb112 | Idioma detectado: en
✅ d128ba8e-2562-45b5-a407-bbd5505eb112 ya está en inglés. Saltando...
🧐 Procesando 15564/17048 - 748e9a46-ce5a-40fd-9d5e-e620e710ce43 | Idioma detectado: fi
🧐 Procesando 15565/17048 - c2065ed5-83a2-4274-9422-96ce5bbbe90e | Idioma detectado: es
🧐 Procesando 15566/17048 - 9f80d3f7-25bb-4cda-a577-9e87d29eee4f | Idioma detectado: en
✅ 9f80d3f7-25bb-4cda-a577-9e87d29eee4f ya está en inglés. Saltando...
🧐 Procesando 15567/17048 - 6f07f1ca-921b-427b-a4b5-3ff59977daf0 | Idioma detectado: en
✅ 6f07f1ca-921b-427b-a4b5-3ff59977daf0 ya está en inglés. Saltando...
🧐 Procesando 15568/17048 - b97777a5-4367-4bf9-bc33-c3fe64df5308 | Idioma detectado: en
✅ b97777a5-4367-4bf9-bc33-c3fe64df5308 ya está en inglés. Saltando...
🧐 Procesando 15569/17048 - 9a910366-07e0-42c9-97ec-584654f38d3d | Idioma detectado: en
✅ 9a910366-07e0-42c9-97ec-584654f38d3d ya está en inglés. Saltando...
🧐 Procesando 15570/17048 - 728bc71b-7cf8-46da-8493-d9f690596992 | Idioma detectado: fi

🔄 Traduciendo canciones:  92%|█████████▏| 15635/17048 [1:29:11<10:10,  2.31it/s]

🧐 Procesando 15629/17048 - 69ae3628-ba1d-4f0a-b7c4-778da1575160 | Idioma detectado: fi
🧐 Procesando 15630/17048 - 934c6855-a25a-4e7a-bdb6-16f50c766817 | Idioma detectado: en
✅ 934c6855-a25a-4e7a-bdb6-16f50c766817 ya está en inglés. Saltando...
🧐 Procesando 15631/17048 - 06d1aaca-a105-4509-805d-32507915c375 | Idioma detectado: en
✅ 06d1aaca-a105-4509-805d-32507915c375 ya está en inglés. Saltando...
🧐 Procesando 15632/17048 - 76f387f4-4fce-426a-9e2a-47c3acd51534 | Idioma detectado: fi
🧐 Procesando 15633/17048 - 99c45b6f-130b-47e5-bc43-c8533af33af4 | Idioma detectado: en
✅ 99c45b6f-130b-47e5-bc43-c8533af33af4 ya está en inglés. Saltando...
🧐 Procesando 15634/17048 - 8a71d1a3-5d02-4b9b-bb66-ae8da9281f73 | Idioma detectado: fi
🧐 Procesando 15635/17048 - 1cec3bd7-fc5e-4df5-8662-dda84a0bf8b9 | Idioma detectado: en
✅ 1cec3bd7-fc5e-4df5-8662-dda84a0bf8b9 ya está en inglés. Saltando...
🧐 Procesando 15636/17048 - c1c7aa71-e77e-4876-a431-60834cc40ebd | Idioma detectado: en
✅ c1c7aa71-e77e-4876-a431-60834cc40ebd ya está en inglés. Saltando...
🧐 Procesando 15637/17048 - b774a9c2-167a-4a38-8117-f25defbce6f2 | Idioma detectado: en
✅ b774a9c2-167a-4a38-8117-f25defbce6f2 ya está en inglés. Saltando...
🧐 Procesando 15638/17048 - 3f1d3d20-0b39-4310-99b5-f5b4875303d8 | Idioma detectado: en
✅ 3f1d3d20-0b39-4310-99b5-f5b4875303d8 ya está en inglés. Saltando...
🧐 Procesando 15639/17048 - 7492225e-4231-4a23-b3c9-12155b888245 | Idioma detectado: en
✅ 7492225e-4231-4a23-b3c9-12155b888245 ya está en inglés. Saltando...
🧐 Procesando 15640/17048 - f9e45df7-afbe-4f4f-94e4-4dc547f1936a | Idioma detectado: fi

🔄 Traduciendo canciones:  92%|█████████▏| 15641/17048 [1:29:13<08:58,  2.61it/s]

🧐 Procesando 15640/17048 - f9e45df7-afbe-4f4f-94e4-4dc547f1936a | Idioma detectado: fi
🧐 Procesando 15641/17048 - 04d753b4-aa5e-4ce1-bf7d-b5ba524534ff | Idioma detectado: en
✅ 04d753b4-aa5e-4ce1-bf7d-b5ba524534ff ya está en inglés. Saltando...
🧐 Procesando 15642/17048 - 2249a557-2394-4d8a-b483-9ccc0baf3f5d | Idioma detectado: en
✅ 2249a557-2394-4d8a-b483-9ccc0baf3f5d ya está en inglés. Saltando...
🧐 Procesando 15643/17048 - ebaf131f-a080-4710-9f50-b37b0038c974 | Idioma detectado: en
✅ ebaf131f-a080-4710-9f50-b37b0038c974 ya está en inglés. Saltando...
🧐 Procesando 15644/17048 - eeceebeb-c897-49a5-a9f7-ffc410fced4b | Idioma detectado: en
✅ eeceebeb-c897-49a5-a9f7-ffc410fced4b ya está en inglés. Saltando...
🧐 Procesando 15645/17048 - c0645367-4341-454f-bdb8-e948e5be004d | Idioma detectado: en
✅ c0645367-4341-454f-bdb8-e948e5be004d ya está en inglés. Saltando...
🧐 Procesando 15646/17048 - 3f7fe3ae-a1d3-4bad-8e98-d1cd0c0e7c55 | Idioma detectado: en
✅ 3f7fe3ae-a1d3-4bad-8e98-d1cd0c0e7c55 ya está en inglés. Saltando...
🧐 Procesando 15647/17048 - e48106a5-163f-48e8-a4ff-02fdd7418ef1 | Idioma detectado: en
✅ e48106a5-163f-48e8-a4ff-02fdd7418ef1 ya está en inglés. Saltando...
🧐 Procesando 15648/17048 - cf228b96-0423-4617-a104-3724633355fc | Idioma detectado: en
✅ cf228b96-0423-4617-a104-3724633355fc ya está en inglés. Saltando...
🧐 Procesando 15649/17048 - 1bbb4e64-3b9a-4e70-a7fb-916ec7287f0d | Idioma detectado: en
✅ 1bbb4e64-3b9a-4e70-a7fb-916ec7287f0d ya está en inglés. Saltando...
🧐 Procesando 15650/17048 - a0d22489-f697-4da3-9b48-036231db65ab | Idioma detectado: fi

🔄 Traduciendo canciones:  92%|█████████▏| 15673/17048 [1:29:29<12:31,  1.83it/s]

🧐 Procesando 15670/17048 - 63aa0714-d36b-41d4-888d-00452001cfc8 | Idioma detectado: en
✅ 63aa0714-d36b-41d4-888d-00452001cfc8 ya está en inglés. Saltando...
🧐 Procesando 15671/17048 - 1981c2dc-f061-4627-8a42-92127a1ca955 | Idioma detectado: en
✅ 1981c2dc-f061-4627-8a42-92127a1ca955 ya está en inglés. Saltando...
🧐 Procesando 15672/17048 - da5dad29-40b1-4cf4-a08a-8c24d4e84b98 | Idioma detectado: fi
🧐 Procesando 15673/17048 - 69d4cf83-b8c2-46b9-b797-81f4a5624b1b | Idioma detectado: en
✅ 69d4cf83-b8c2-46b9-b797-81f4a5624b1b ya está en inglés. Saltando...
🧐 Procesando 15674/17048 - 5b84127c-cbba-4dc0-9645-466201782ff8 | Idioma detectado: en
✅ 5b84127c-cbba-4dc0-9645-466201782ff8 ya está en inglés. Saltando...
🧐 Procesando 15675/17048 - d44aa7ca-31ac-4887-96be-e1d2481629cc | Idioma detectado: en
✅ d44aa7ca-31ac-4887-96be-e1d2481629cc ya está en inglés. Saltando...
🧐 Procesando 15676/17048 - f654f5e5-63f4-4890-b459-91aeeb5ba922 | Idioma detectado: en
✅ f654f5e5-63f4-4890-b459-91aeeb5ba922 ya está en inglés. Saltando...
🧐 Procesando 15677/17048 - 8e1a69d4-aa64-48a9-b03e-89a160b49a06 | Idioma detectado: en
✅ 8e1a69d4-aa64-48a9-b03e-89a160b49a06 ya está en inglés. Saltando...
🧐 Procesando 15678/17048 - dd7ab013-50e5-4f31-872b-07b789609e5d | Idioma detectado: en
✅ dd7ab013-50e5-4f31-872b-07b789609e5d ya está en inglés. Saltando...
🧐 Procesando 15679/17048 - 79097336-edf2-4afc-b0b9-4ce3e604b7f7 | Idioma detectado: en
✅ 79097336-edf2-4afc-b0b9-4ce3e604b7f7 ya está en inglés. Saltando...
🧐 Procesando 15680/17048 - 0897ec84-0011-420f-9ecc-e8ed49806eb8 | Idioma detectado: fi

🔄 Traduciendo canciones:  92%|█████████▏| 15684/17048 [1:29:35<15:21,  1.48it/s]

🧐 Procesando 15679/17048 - 79097336-edf2-4afc-b0b9-4ce3e604b7f7 | Idioma detectado: en
✅ 79097336-edf2-4afc-b0b9-4ce3e604b7f7 ya está en inglés. Saltando...
🧐 Procesando 15680/17048 - 0897ec84-0011-420f-9ecc-e8ed49806eb8 | Idioma detectado: fi
🧐 Procesando 15681/17048 - cbab6e55-7c32-4e28-8f2b-bc95bb0d1189 | Idioma detectado: fi
🧐 Procesando 15682/17048 - d8fe08c7-4ae3-4e8b-ad1e-bac1c2bd447e | Idioma detectado: en
✅ d8fe08c7-4ae3-4e8b-ad1e-bac1c2bd447e ya está en inglés. Saltando...
🧐 Procesando 15683/17048 - ffadda55-f610-42e7-8f92-ea3ff854e1dc | Idioma detectado: fi
🧐 Procesando 15684/17048 - 36dfc448-4ac1-4159-b9e9-cf3a55d14bae | Idioma detectado: en
✅ 36dfc448-4ac1-4159-b9e9-cf3a55d14bae ya está en inglés. Saltando...
🧐 Procesando 15685/17048 - 0cf19b5d-8274-4af1-819f-4cf32b8f11fc | Idioma detectado: en
✅ 0cf19b5d-8274-4af1-819f-4cf32b8f11fc ya está en inglés. Saltando...
🧐 Procesando 15686/17048 - cc3130e7-b91b-4cdc-902e-5b0bf6c8fc63 | Idioma detectado: en
✅ cc3130e7-b91b-4cdc-902e-5b0bf6c8fc63 ya está en inglés. Saltando...
🧐 Procesando 15687/17048 - 24ebd05f-3ade-4111-b5e5-2b9f21563faf | Idioma detectado: en
✅ 24ebd05f-3ade-4111-b5e5-2b9f21563faf ya está en inglés. Saltando...
🧐 Procesando 15688/17048 - 7c6c405b-ae21-4363-af01-3521cc2c9396 | Idioma detectado: en
✅ 7c6c405b-ae21-4363-af01-3521cc2c9396 ya está en inglés. Saltando...
🧐 Procesando 15689/17048 - 474b07dd-af36-4c61-901e-88f2c4ee0183 | Idioma detectado: en
✅ 474b07dd-af36-4c61-901e-88f2c4ee0183 ya está en inglés. Saltando...
🧐 Procesando 15690/17048 - 8c1e92e7-0521-4b97-a64f-67a688adebc6 | Idioma detectado: fi

🔄 Traduciendo canciones:  92%|█████████▏| 15765/17048 [1:29:52<02:52,  7.44it/s]

✅ 8bc838b7-a447-4afb-89dd-6d87a4b0f6ea ya está en inglés. Saltando...
🧐 Procesando 15801/17048 - af9ce18b-8fbf-4d8f-9090-3cc58277fd37 | Idioma detectado: en
✅ af9ce18b-8fbf-4d8f-9090-3cc58277fd37 ya está en inglés. Saltando...
🧐 Procesando 15802/17048 - b372421b-40db-4c86-af2e-af1c82d3b4c3 | Idioma detectado: en
✅ b372421b-40db-4c86-af2e-af1c82d3b4c3 ya está en inglés. Saltando...
🧐 Procesando 15803/17048 - 34c423f5-473e-4e61-8e76-e0e06905164c | Idioma detectado: en
✅ 34c423f5-473e-4e61-8e76-e0e06905164c ya está en inglés. Saltando...
🧐 Procesando 15804/17048 - d95122b5-ec14-42f7-9121-47fb22d6af68 | Idioma detectado: en
✅ d95122b5-ec14-42f7-9121-47fb22d6af68 ya está en inglés. Saltando...
🧐 Procesando 15805/17048 - 4d63c94c-d428-41a2-8381-a82f3efd3507 | Idioma detectado: en
✅ 4d63c94c-d428-41a2-8381-a82f3efd3507 ya está en inglés. Saltando...
🧐 Procesando 15806/17048 - 480ea011-ac4e-48d8-b7de-5106e6fddc8c | Idioma detectado: en
✅ 480ea011-ac4e-48d8-b7de-5106e6fddc8c ya está en inglés. Saltando...
🧐 Procesando 15807/17048 - d6362909-7dab-45bf-9fc6-a54bff970f36 | Idioma detectado: en
✅ d6362909-7dab-45bf-9fc6-a54bff970f36 ya está en inglés. Saltando...
🧐 Procesando 15808/17048 - db27b0c4-3158-4ca4-9509-fbdf41f4f812 | Idioma detectado: en
✅ db27b0c4-3158-4ca4-9509-fbdf41f4f812 ya está en inglés. Saltando...
🧐 Procesando 15809/17048 - f619e04b-b0d1-4f59-935b-6f6194a34f30 | Idioma detectado: en
✅ f619e04b-b0d1-4f59-935b-6f6194a34f30 ya está en inglés. Saltando...
🧐 Procesando 15810/17048 - d9423d05-4dba-4832-9b3d-52aacfa21043 | Idioma detectado: es

🔄 Traduciendo canciones:  95%|█████████▍| 16145/17048 [1:30:37<01:41,  8.93it/s]

✅ 023b83a7-1d5a-4e48-b00c-a2523c3e8b49 ya está en inglés. Saltando...
🧐 Procesando 16151/17048 - 4ef1a4f0-6956-4791-9a15-259e42e792de | Idioma detectado: en
✅ 4ef1a4f0-6956-4791-9a15-259e42e792de ya está en inglés. Saltando...
🧐 Procesando 16152/17048 - 32f9d799-3214-45f4-b3ce-ee79e2d3cc09 | Idioma detectado: en
✅ 32f9d799-3214-45f4-b3ce-ee79e2d3cc09 ya está en inglés. Saltando...
🧐 Procesando 16153/17048 - 6b5d4e9b-4c72-419f-acc2-1d8271325dc9 | Idioma detectado: en
✅ 6b5d4e9b-4c72-419f-acc2-1d8271325dc9 ya está en inglés. Saltando...
🧐 Procesando 16154/17048 - d7fcbebb-eba0-4e79-bb30-d993ec925fd0 | Idioma detectado: en
✅ d7fcbebb-eba0-4e79-bb30-d993ec925fd0 ya está en inglés. Saltando...
🧐 Procesando 16155/17048 - fe2ca424-818c-4b6b-ad45-5ce76c00e207 | Idioma detectado: en
✅ fe2ca424-818c-4b6b-ad45-5ce76c00e207 ya está en inglés. Saltando...
🧐 Procesando 16156/17048 - 0a35c40c-0ccf-48cb-8e4e-5f4b1be644e3 | Idioma detectado: en
✅ 0a35c40c-0ccf-48cb-8e4e-5f4b1be644e3 ya está en inglés. Saltando...
🧐 Procesando 16157/17048 - 7f0dc258-21f3-499e-8701-cbc3f5e4fd88 | Idioma detectado: en
✅ 7f0dc258-21f3-499e-8701-cbc3f5e4fd88 ya está en inglés. Saltando...
🧐 Procesando 16158/17048 - c6427c57-f9bd-47d9-af2d-8064957ae1e8 | Idioma detectado: en
✅ c6427c57-f9bd-47d9-af2d-8064957ae1e8 ya está en inglés. Saltando...
🧐 Procesando 16159/17048 - cc1b1acf-8b66-4ec6-8d35-93f8ce0fed8d | Idioma detectado: en
✅ cc1b1acf-8b66-4ec6-8d35-93f8ce0fed8d ya está en inglés. Saltando...
🧐 Procesando 16160/17048 - caa992e4-60d5-41ac-84c6-1e1282067e48 | Idioma detectado: fr

🔄 Traduciendo canciones:  95%|█████████▌| 16236/17048 [1:31:05<03:50,  3.52it/s]

🧐 Procesando 16230/17048 - d5ad3dd2-8596-4432-ad90-65140e8c5938 | Idioma detectado: en
✅ d5ad3dd2-8596-4432-ad90-65140e8c5938 ya está en inglés. Saltando...
🧐 Procesando 16231/17048 - 2d3ffb6e-3228-4eee-a0b6-ce9277be8417 | Idioma detectado: en
✅ 2d3ffb6e-3228-4eee-a0b6-ce9277be8417 ya está en inglés. Saltando...
🧐 Procesando 16232/17048 - 7ceaa82c-5d25-4a7b-81ac-27afc0b57b5a | Idioma detectado: en
✅ 7ceaa82c-5d25-4a7b-81ac-27afc0b57b5a ya está en inglés. Saltando...
🧐 Procesando 16233/17048 - 4d8d61e8-db29-4dcd-9ace-9b5c2c571959 | Idioma detectado: en
✅ 4d8d61e8-db29-4dcd-9ace-9b5c2c571959 ya está en inglés. Saltando...
🧐 Procesando 16234/17048 - 40717867-e990-45cf-871f-97eea08497b3 | Idioma detectado: en
✅ 40717867-e990-45cf-871f-97eea08497b3 ya está en inglés. Saltando...
🧐 Procesando 16235/17048 - 8c279433-d3e7-4d5c-b159-9671319f3260 | Idioma detectado: es
🧐 Procesando 16236/17048 - 64544e0f-4115-499f-9fc9-8892ff23dbf2 | Idioma detectado: en
✅ 64544e0f-4115-499f-9fc9-8892ff23dbf2 ya está en inglés. Saltando...
🧐 Procesando 16237/17048 - 176fb9b5-10e1-435d-85bc-67b19e92d022 | Idioma detectado: en
✅ 176fb9b5-10e1-435d-85bc-67b19e92d022 ya está en inglés. Saltando...
🧐 Procesando 16238/17048 - 6807f2c1-3dd4-4f9d-92fb-a8852fc99531 | Idioma detectado: en
✅ 6807f2c1-3dd4-4f9d-92fb-a8852fc99531 ya está en inglés. Saltando...
🧐 Procesando 16239/17048 - 35c9c3df-67e8-487c-a754-a0506a7f298f | Idioma detectado: en
✅ 35c9c3df-67e8-487c-a754-a0506a7f298f ya está en inglés. Saltando...
🧐 Procesando 16240/17048 - 9dd73677-7855-4986-b8de-87c0212adad2 | Idioma detectado: es

🔄 Traduciendo canciones:  95%|█████████▌| 16241/17048 [1:31:09<05:05,  2.64it/s]

🧐 Procesando 16240/17048 - 9dd73677-7855-4986-b8de-87c0212adad2 | Idioma detectado: es
🧐 Procesando 16241/17048 - 921b6bde-7f50-44db-9c58-6dc25c0ed48e | Idioma detectado: en
✅ 921b6bde-7f50-44db-9c58-6dc25c0ed48e ya está en inglés. Saltando...
🧐 Procesando 16242/17048 - c54e160e-8a6b-4115-9ea3-82aa2b1bc190 | Idioma detectado: en
✅ c54e160e-8a6b-4115-9ea3-82aa2b1bc190 ya está en inglés. Saltando...
🧐 Procesando 16243/17048 - ebc2e33f-788d-493a-96ab-0bbb9eaa56a2 | Idioma detectado: en
✅ ebc2e33f-788d-493a-96ab-0bbb9eaa56a2 ya está en inglés. Saltando...
🧐 Procesando 16244/17048 - 68885a60-a398-4952-abb7-2e2338ed066b | Idioma detectado: en
✅ 68885a60-a398-4952-abb7-2e2338ed066b ya está en inglés. Saltando...
🧐 Procesando 16245/17048 - 2ccff43a-c82c-4e00-bb35-259bc939e520 | Idioma detectado: en
✅ 2ccff43a-c82c-4e00-bb35-259bc939e520 ya está en inglés. Saltando...
🧐 Procesando 16246/17048 - 29d7b586-cad1-4171-9bb7-66ebebe453af | Idioma detectado: en
✅ 29d7b586-cad1-4171-9bb7-66ebebe453af ya está en inglés. Saltando...
🧐 Procesando 16247/17048 - 829c5714-0ae7-4088-be88-f9f987000e45 | Idioma detectado: en
✅ 829c5714-0ae7-4088-be88-f9f987000e45 ya está en inglés. Saltando...
🧐 Procesando 16248/17048 - 7ef10e11-cfb6-483b-8582-664554319fb8 | Idioma detectado: en
✅ 7ef10e11-cfb6-483b-8582-664554319fb8 ya está en inglés. Saltando...
🧐 Procesando 16249/17048 - 62b004ee-eac8-4fbe-bfda-f4e528e3ce99 | Idioma detectado: en
✅ 62b004ee-eac8-4fbe-bfda-f4e528e3ce99 ya está en inglés. Saltando...
🧐 Procesando 16250/17048 - cb8638a4-06ed-4d55-973a-88fd7997c9ec | Idioma detectado: es

🔄 Traduciendo canciones:  95%|█████████▌| 16275/17048 [1:31:26<06:53,  1.87it/s]

✅ a1489e89-52c5-44fd-aa92-2c2559012a75 ya está en inglés. Saltando...
🧐 Procesando 16270/17048 - d3b6a9a4-4cff-43e3-b8db-87f67a05cd0b | Idioma detectado: en
✅ d3b6a9a4-4cff-43e3-b8db-87f67a05cd0b ya está en inglés. Saltando...
🧐 Procesando 16271/17048 - 1bb5482d-200a-4e18-a639-5e59ec5aade7 | Idioma detectado: es
🧐 Procesando 16272/17048 - 733566dc-6779-4771-ab85-5155bbde9d32 | Idioma detectado: en
✅ 733566dc-6779-4771-ab85-5155bbde9d32 ya está en inglés. Saltando...
🧐 Procesando 16273/17048 - 09e25b0c-6f75-4ca1-8761-3fc19f4b7021 | Idioma detectado: en
✅ 09e25b0c-6f75-4ca1-8761-3fc19f4b7021 ya está en inglés. Saltando...
🧐 Procesando 16274/17048 - 56d50e9e-f88c-488c-ab51-5f8fef07ca18 | Idioma detectado: es
🧐 Procesando 16275/17048 - 1cc13859-7f3e-45c6-9a27-68fb05f1ab42 | Idioma detectado: en
✅ 1cc13859-7f3e-45c6-9a27-68fb05f1ab42 ya está en inglés. Saltando...
🧐 Procesando 16276/17048 - 518e83f7-ebe7-4cb6-8aa7-ddef7f2bb420 | Idioma detectado: en
✅ 518e83f7-ebe7-4cb6-8aa7-ddef7f2bb420 ya está en inglés. Saltando...
🧐 Procesando 16277/17048 - 2768cdce-5cae-469c-b8ce-845b7e8ba564 | Idioma detectado: en
✅ 2768cdce-5cae-469c-b8ce-845b7e8ba564 ya está en inglés. Saltando...
🧐 Procesando 16278/17048 - cb24bc9c-a2ad-4844-b218-e862b8e160c3 | Idioma detectado: en
✅ cb24bc9c-a2ad-4844-b218-e862b8e160c3 ya está en inglés. Saltando...
🧐 Procesando 16279/17048 - 464a21db-76d4-406c-aa57-0cdad74f175e | Idioma detectado: en
✅ 464a21db-76d4-406c-aa57-0cdad74f175e ya está en inglés. Saltando...
🧐 Procesando 16280/17048 - 0fc07ea3-6046-4c1c-958e-ed8b086ddf0e | Idioma detectado: es

🔄 Traduciendo canciones:  96%|█████████▌| 16306/17048 [1:31:51<11:08,  1.11it/s]

✅ ab25b574-d77c-4f10-afd7-488c89a9d612 ya está en inglés. Saltando...
🧐 Procesando 16299/17048 - be44b0e0-f0b0-4122-ade9-0fe68792f531 | Idioma detectado: es
🧐 Procesando 16300/17048 - bc5bf5a6-7096-4889-8299-dd360b22d13c | Idioma detectado: en
✅ bc5bf5a6-7096-4889-8299-dd360b22d13c ya está en inglés. Saltando...
🧐 Procesando 16301/17048 - d321657e-bb6e-4837-97fe-1ab599ec5f5d | Idioma detectado: en
✅ d321657e-bb6e-4837-97fe-1ab599ec5f5d ya está en inglés. Saltando...
🧐 Procesando 16302/17048 - ad3fc655-9134-417e-9927-71d9092d73d6 | Idioma detectado: en
✅ ad3fc655-9134-417e-9927-71d9092d73d6 ya está en inglés. Saltando...
🧐 Procesando 16303/17048 - efc6284b-73cd-441d-9b7c-901a21960158 | Idioma detectado: es
🧐 Procesando 16304/17048 - 7e4a6b16-1114-45af-8b1d-8120db58d773 | Idioma detectado: es
🧐 Procesando 16305/17048 - 11e07a7f-3f23-4927-a76d-701e93a84f1c | Idioma detectado: es
🧐 Procesando 16306/17048 - 7a8324b8-98e0-43ed-983f-eb599507792a | Idioma detectado: en
✅ 7a8324b8-98e0-43ed-983f-eb599507792a ya está en inglés. Saltando...
🧐 Procesando 16307/17048 - 599d10c1-8b46-431e-a3a0-62f7b799e9a9 | Idioma detectado: en
✅ 599d10c1-8b46-431e-a3a0-62f7b799e9a9 ya está en inglés. Saltando...
🧐 Procesando 16308/17048 - d12bc1e4-aa22-4051-bc21-a6a500eaef5b | Idioma detectado: en
✅ d12bc1e4-aa22-4051-bc21-a6a500eaef5b ya está en inglés. Saltando...
🧐 Procesando 16309/17048 - 875c9f4d-9451-46d4-bf8c-4ecac7c940ea | Idioma detectado: en
✅ 875c9f4d-9451-46d4-bf8c-4ecac7c940ea ya está en inglés. Saltando...
🧐 Procesando 16310/17048 - 9203755f-dbbb-46de-bcd4-01bb1588af9a | Idioma detectado: es

🔄 Traduciendo canciones:  96%|█████████▌| 16327/17048 [1:32:11<15:06,  1.26s/it]

🧐 Procesando 16318/17048 - 433a9f05-c552-4f3d-b9c4-9613fa5e0545 | Idioma detectado: es
🧐 Procesando 16319/17048 - 12f5a5a0-3826-47fd-b64a-3f4f0010ce87 | Idioma detectado: en
✅ 12f5a5a0-3826-47fd-b64a-3f4f0010ce87 ya está en inglés. Saltando...
🧐 Procesando 16320/17048 - 407461e2-bf98-4c56-a22f-56f619f8be46 | Idioma detectado: en
✅ 407461e2-bf98-4c56-a22f-56f619f8be46 ya está en inglés. Saltando...
🧐 Procesando 16321/17048 - a56c8358-cf10-4c32-989b-768ba63ebbe5 | Idioma detectado: es
🧐 Procesando 16322/17048 - 2398c60e-d253-47b2-8636-46803b66c8f7 | Idioma detectado: es
🧐 Procesando 16323/17048 - 50fc321f-7705-40e6-955c-886d39d54897 | Idioma detectado: en
✅ 50fc321f-7705-40e6-955c-886d39d54897 ya está en inglés. Saltando...
🧐 Procesando 16324/17048 - a2ffa4ed-d2ad-4b78-bf24-84db6ceb258e | Idioma detectado: en
✅ a2ffa4ed-d2ad-4b78-bf24-84db6ceb258e ya está en inglés. Saltando...
🧐 Procesando 16325/17048 - 49e872b2-2ca3-47bc-91f9-43450fdba23d | Idioma detectado: es
🧐 Procesando 16326/17048 - 39541dbc-8ff9-48ee-ae99-0da27ef1e674 | Idioma detectado: es
🧐 Procesando 16327/17048 - 5db5acd7-ef9e-471f-a28b-7c0997750b63 | Idioma detectado: en
✅ 5db5acd7-ef9e-471f-a28b-7c0997750b63 ya está en inglés. Saltando...
🧐 Procesando 16328/17048 - fbc30301-8c80-4187-93e9-3fe410f74b25 | Idioma detectado: en
✅ fbc30301-8c80-4187-93e9-3fe410f74b25 ya está en inglés. Saltando...
🧐 Procesando 16329/17048 - 8d9c3698-6f1e-410d-be62-a4aac087b0ca | Idioma detectado: en
✅ 8d9c3698-6f1e-410d-be62-a4aac087b0ca ya está en inglés. Saltando...
🧐 Procesando 16330/17048 - 7364c5d6-b72f-4908-9d66-55a44f8d40b5 | Idioma detectado: es

🔄 Traduciendo canciones:  96%|█████████▌| 16340/17048 [1:32:33<22:59,  1.95s/it]

✅ 5db5acd7-ef9e-471f-a28b-7c0997750b63 ya está en inglés. Saltando...
🧐 Procesando 16328/17048 - fbc30301-8c80-4187-93e9-3fe410f74b25 | Idioma detectado: en
✅ fbc30301-8c80-4187-93e9-3fe410f74b25 ya está en inglés. Saltando...
🧐 Procesando 16329/17048 - 8d9c3698-6f1e-410d-be62-a4aac087b0ca | Idioma detectado: en
✅ 8d9c3698-6f1e-410d-be62-a4aac087b0ca ya está en inglés. Saltando...
🧐 Procesando 16330/17048 - 7364c5d6-b72f-4908-9d66-55a44f8d40b5 | Idioma detectado: es
🧐 Procesando 16331/17048 - 6274e251-75d1-4add-b1af-36bb094a2120 | Idioma detectado: es
🧐 Procesando 16332/17048 - fd0f68f7-3411-4178-9c17-f9cc40d133fd | Idioma detectado: es
🧐 Procesando 16333/17048 - 99077136-657a-4f90-8498-439c76caf5a5 | Idioma detectado: en
✅ 99077136-657a-4f90-8498-439c76caf5a5 ya está en inglés. Saltando...
🧐 Procesando 16334/17048 - 6de91eba-f72b-46a8-940b-d6b0582b1e0c | Idioma detectado: en
✅ 6de91eba-f72b-46a8-940b-d6b0582b1e0c ya está en inglés. Saltando...
🧐 Procesando 16335/17048 - f599da45-a86d-4c3d-b03c-202c7bc83531 | Idioma detectado: en
✅ f599da45-a86d-4c3d-b03c-202c7bc83531 ya está en inglés. Saltando...
🧐 Procesando 16336/17048 - 852e83da-dea0-4f71-96f6-61cc03cdfcf7 | Idioma detectado: es
🧐 Procesando 16337/17048 - 6cd8e861-8e15-452a-a5d7-0b3ac405f8a7 | Idioma detectado: en
✅ 6cd8e861-8e15-452a-a5d7-0b3ac405f8a7 ya está en inglés. Saltando...
🧐 Procesando 16338/17048 - 18174bfe-4386-484f-bb83-c1edfc5ebadb | Idioma detectado: es
🧐 Procesando 16339/17048 - 104e7780-67fc-4f50-b03b-e5275ae6f7ea | Idioma detectado: es
🧐 Procesando 16340/17048 - 67e844eb-ac6f-49ca-a615-0d8aa91dbb60 | Idioma detectado: es

🔄 Traduciendo canciones:  96%|█████████▌| 16351/17048 [1:32:49<19:40,  1.69s/it]

🧐 Procesando 16337/17048 - 6cd8e861-8e15-452a-a5d7-0b3ac405f8a7 | Idioma detectado: en
✅ 6cd8e861-8e15-452a-a5d7-0b3ac405f8a7 ya está en inglés. Saltando...
🧐 Procesando 16338/17048 - 18174bfe-4386-484f-bb83-c1edfc5ebadb | Idioma detectado: es
🧐 Procesando 16339/17048 - 104e7780-67fc-4f50-b03b-e5275ae6f7ea | Idioma detectado: es
🧐 Procesando 16340/17048 - 67e844eb-ac6f-49ca-a615-0d8aa91dbb60 | Idioma detectado: es
🧐 Procesando 16341/17048 - ad768e3e-5e5a-4d43-beb7-e956080c4e41 | Idioma detectado: en
✅ ad768e3e-5e5a-4d43-beb7-e956080c4e41 ya está en inglés. Saltando...
🧐 Procesando 16342/17048 - bc156086-fcf4-450a-90e9-65667e902d81 | Idioma detectado: en
✅ bc156086-fcf4-450a-90e9-65667e902d81 ya está en inglés. Saltando...
🧐 Procesando 16343/17048 - c8bd9297-26d3-42a4-bc47-c990097802a6 | Idioma detectado: es
🧐 Procesando 16344/17048 - cd240bf5-8bef-4fa4-b7c6-7a755be04742 | Idioma detectado: en
✅ cd240bf5-8bef-4fa4-b7c6-7a755be04742 ya está en inglés. Saltando...
🧐 Procesando 16345/17048 - 00176507-22cb-41b6-aa25-96a190d523f8 | Idioma detectado: es
🧐 Procesando 16346/17048 - a4c44920-47ee-466e-8334-b41de5deaf86 | Idioma detectado: en
✅ a4c44920-47ee-466e-8334-b41de5deaf86 ya está en inglés. Saltando...
🧐 Procesando 16347/17048 - 9931e3ed-f7ce-4023-a33f-19714cf270f4 | Idioma detectado: es
🧐 Procesando 16348/17048 - 5d2aa554-e3c9-4d28-9719-85e8ca46ccca | Idioma detectado: es
🧐 Procesando 16349/17048 - 45761bc8-c6c9-4e58-b3f2-202d53bbb735 | Idioma detectado: en
✅ 45761bc8-c6c9-4e58-b3f2-202d53bbb735 ya está en inglés. Saltando...
🧐 Procesando 16350/17048 - a4973fb2-0142-479c-8701-5382eff1d766 | Idioma detectado: es

🔄 Traduciendo canciones:  96%|█████████▌| 16376/17048 [1:33:06<08:42,  1.29it/s]

✅ 3033e284-2c1a-4280-9f6b-ab85d856c7e5 ya está en inglés. Saltando...
🧐 Procesando 16369/17048 - 356c9675-d71f-4753-a89c-d84a684f5618 | Idioma detectado: es
🧐 Procesando 16370/17048 - 56d1c1c9-ef0f-4bbb-b3e1-5d0edaa2d673 | Idioma detectado: en
✅ 56d1c1c9-ef0f-4bbb-b3e1-5d0edaa2d673 ya está en inglés. Saltando...
🧐 Procesando 16371/17048 - 51104fbd-6b26-45e7-bbcd-0339b41619d2 | Idioma detectado: es
🧐 Procesando 16372/17048 - b369b040-0de1-42b7-8db7-ec290348b28d | Idioma detectado: es
🧐 Procesando 16373/17048 - 48afbdf6-dc41-4d21-9f0b-cf17463376d5 | Idioma detectado: en
✅ 48afbdf6-dc41-4d21-9f0b-cf17463376d5 ya está en inglés. Saltando...
🧐 Procesando 16374/17048 - c3a713c0-c945-4199-8b0e-da8eafa100f9 | Idioma detectado: en
✅ c3a713c0-c945-4199-8b0e-da8eafa100f9 ya está en inglés. Saltando...
🧐 Procesando 16375/17048 - 7387e478-b421-4c84-b9ec-32a21e1afb7e | Idioma detectado: pt
🧐 Procesando 16376/17048 - df67e508-c0c7-4fcb-8b88-5b609f81fd0c | Idioma detectado: en
✅ df67e508-c0c7-4fcb-8b88-5b609f81fd0c ya está en inglés. Saltando...
🧐 Procesando 16377/17048 - 978e3f20-868a-42a2-b841-146437bff2d5 | Idioma detectado: en
✅ 978e3f20-868a-42a2-b841-146437bff2d5 ya está en inglés. Saltando...
🧐 Procesando 16378/17048 - d7be6135-5136-48d3-80c3-772253b26314 | Idioma detectado: en
✅ d7be6135-5136-48d3-80c3-772253b26314 ya está en inglés. Saltando...
🧐 Procesando 16379/17048 - 000d0334-e7f6-4b60-90e8-d063c0985c41 | Idioma detectado: en
✅ 000d0334-e7f6-4b60-90e8-d063c0985c41 ya está en inglés. Saltando...
🧐 Procesando 16380/17048 - 6f86a93c-7f91-49cc-bfd7-0fdc0c592cf2 | Idioma detectado: es

🔄 Traduciendo canciones:  96%|█████████▌| 16389/17048 [1:33:14<08:34,  1.28it/s]

🧐 Procesando 16378/17048 - d7be6135-5136-48d3-80c3-772253b26314 | Idioma detectado: en
✅ d7be6135-5136-48d3-80c3-772253b26314 ya está en inglés. Saltando...
🧐 Procesando 16379/17048 - 000d0334-e7f6-4b60-90e8-d063c0985c41 | Idioma detectado: en
✅ 000d0334-e7f6-4b60-90e8-d063c0985c41 ya está en inglés. Saltando...
🧐 Procesando 16380/17048 - 6f86a93c-7f91-49cc-bfd7-0fdc0c592cf2 | Idioma detectado: es
🧐 Procesando 16381/17048 - 1adf25ea-48fe-4fb3-a9f2-fbe97a19de6f | Idioma detectado: en
✅ 1adf25ea-48fe-4fb3-a9f2-fbe97a19de6f ya está en inglés. Saltando...
🧐 Procesando 16382/17048 - bc56692e-8a76-40d2-bb98-e2fcfef64c74 | Idioma detectado: en
✅ bc56692e-8a76-40d2-bb98-e2fcfef64c74 ya está en inglés. Saltando...
🧐 Procesando 16383/17048 - 239fa8e0-639e-481f-a73e-c3c29b1ca80e | Idioma detectado: pt
🧐 Procesando 16384/17048 - c20d9464-deb5-426c-8fa9-d3902e5a343a | Idioma detectado: en
✅ c20d9464-deb5-426c-8fa9-d3902e5a343a ya está en inglés. Saltando...
🧐 Procesando 16385/17048 - 1e92f043-ae99-461c-8099-695ac4edc4cd | Idioma detectado: en
✅ 1e92f043-ae99-461c-8099-695ac4edc4cd ya está en inglés. Saltando...
🧐 Procesando 16386/17048 - ba751fbc-2768-4cf3-935f-c50305eacac8 | Idioma detectado: es
🧐 Procesando 16387/17048 - c46f4a02-4a08-43ae-86a7-9e526895ed46 | Idioma detectado: pt
🧐 Procesando 16388/17048 - 8ac387bb-3992-4b12-a045-56c911df4f00 | Idioma detectado: pt
🧐 Procesando 16389/17048 - 7375caa9-b026-4bf6-b60a-60b790494bf0 | Idioma detectado: en
✅ 7375caa9-b026-4bf6-b60a-60b790494bf0 ya está en inglés. Saltando...
🧐 Procesando 16390/17048 - de71f03d-262a-470a-bb1f-2c13df0049fe | Idioma detectado: pt

🔄 Traduciendo canciones:  96%|█████████▌| 16395/17048 [1:33:23<13:28,  1.24s/it]

🧐 Procesando 16389/17048 - 7375caa9-b026-4bf6-b60a-60b790494bf0 | Idioma detectado: en
✅ 7375caa9-b026-4bf6-b60a-60b790494bf0 ya está en inglés. Saltando...
🧐 Procesando 16390/17048 - de71f03d-262a-470a-bb1f-2c13df0049fe | Idioma detectado: pt
🧐 Procesando 16391/17048 - f4c751f2-27b5-46ec-8ad0-956af70b55ed | Idioma detectado: en
✅ f4c751f2-27b5-46ec-8ad0-956af70b55ed ya está en inglés. Saltando...
🧐 Procesando 16392/17048 - 21a3bd82-ce89-4244-83fb-478117bd0f95 | Idioma detectado: pt
🧐 Procesando 16393/17048 - 9ea92354-1937-4b27-ad30-e354f5b8730f | Idioma detectado: en
✅ 9ea92354-1937-4b27-ad30-e354f5b8730f ya está en inglés. Saltando...
🧐 Procesando 16394/17048 - 23ff13c0-d7e3-425b-ac37-5b26806ef63c | Idioma detectado: es
🧐 Procesando 16395/17048 - 6d5d9898-6d8d-4779-91f7-0d2d2dfd3f72 | Idioma detectado: en
✅ 6d5d9898-6d8d-4779-91f7-0d2d2dfd3f72 ya está en inglés. Saltando...
🧐 Procesando 16396/17048 - ff4c9df3-c29e-43b7-8afc-ecb1c1eb9e27 | Idioma detectado: en
✅ ff4c9df3-c29e-43b7-8afc-ecb1c1eb9e27 ya está en inglés. Saltando...
🧐 Procesando 16397/17048 - 530f275e-3ef6-44e7-8585-ac390dfaf49c | Idioma detectado: en
✅ 530f275e-3ef6-44e7-8585-ac390dfaf49c ya está en inglés. Saltando...
🧐 Procesando 16398/17048 - 604ae7cb-0403-48b2-bd04-cc944aa0e0aa | Idioma detectado: en
✅ 604ae7cb-0403-48b2-bd04-cc944aa0e0aa ya está en inglés. Saltando...
🧐 Procesando 16399/17048 - ed4ae8f3-abb3-440a-8086-d368124a53f4 | Idioma detectado: en
✅ ed4ae8f3-abb3-440a-8086-d368124a53f4 ya está en inglés. Saltando...
🧐 Procesando 16400/17048 - 0072ec8b-78b6-4766-89ec-aa310546352d | Idioma detectado: pt

🔄 Traduciendo canciones:  97%|█████████▋| 16590/17048 [1:34:53<08:13,  1.08s/it]

✅ 00b6feac-0ff2-4268-b97e-4b7d327da330 ya está en inglés. Saltando...
🧐 Procesando 16577/17048 - 78128d89-ad71-41c7-b7f4-493ae718bfc7 | Idioma detectado: en
✅ 78128d89-ad71-41c7-b7f4-493ae718bfc7 ya está en inglés. Saltando...
🧐 Procesando 16578/17048 - a9c18d34-c47c-4c01-9587-a27247a23ba6 | Idioma detectado: it
🧐 Procesando 16579/17048 - 822bc111-a366-4053-8402-24d58c6dbf60 | Idioma detectado: it
🧐 Procesando 16580/17048 - 0fb5f6b5-32ef-49bb-9fc8-255c5988a1af | Idioma detectado: en
✅ 0fb5f6b5-32ef-49bb-9fc8-255c5988a1af ya está en inglés. Saltando...
🧐 Procesando 16581/17048 - b339581e-a58f-4275-843d-b8a6266e1daf | Idioma detectado: it
🧐 Procesando 16582/17048 - db97337b-7729-4793-9a86-e82b152b1f41 | Idioma detectado: it
🧐 Procesando 16583/17048 - 0a25dee2-cc72-4a67-aead-587c738132c6 | Idioma detectado: en
✅ 0a25dee2-cc72-4a67-aead-587c738132c6 ya está en inglés. Saltando...
🧐 Procesando 16584/17048 - 2402bd39-103d-4509-a5f6-14745c1e0eed | Idioma detectado: it
🧐 Procesando 16585/17048 - 3cfe2194-f783-4397-afcb-955232834f3b | Idioma detectado: it
🧐 Procesando 16586/17048 - 03537462-edb6-4d5f-8033-cdbbcd6ad41f | Idioma detectado: it
🧐 Procesando 16587/17048 - d2af6fcd-bc4e-4aa7-84ab-e8d083f0e3aa | Idioma detectado: en
✅ d2af6fcd-bc4e-4aa7-84ab-e8d083f0e3aa ya está en inglés. Saltando...
🧐 Procesando 16588/17048 - 02026255-583f-4ec2-9531-cf7a9488cf10 | Idioma detectado: en
✅ 02026255-583f-4ec2-9531-cf7a9488cf10 ya está en inglés. Saltando...
🧐 Procesando 16589/17048 - 3454998e-56cf-4610-a900-0141c43e7867 | Idioma detectado: it
🧐 Procesando 16590/17048 - 8e66904c-12c0-4f7b-8f81-ed0f416a0d2f | Idioma detectado: it

🔄 Traduciendo canciones:  97%|█████████▋| 16596/17048 [1:35:04<13:55,  1.85s/it]

🧐 Procesando 16587/17048 - d2af6fcd-bc4e-4aa7-84ab-e8d083f0e3aa | Idioma detectado: en
✅ d2af6fcd-bc4e-4aa7-84ab-e8d083f0e3aa ya está en inglés. Saltando...
🧐 Procesando 16588/17048 - 02026255-583f-4ec2-9531-cf7a9488cf10 | Idioma detectado: en
✅ 02026255-583f-4ec2-9531-cf7a9488cf10 ya está en inglés. Saltando...
🧐 Procesando 16589/17048 - 3454998e-56cf-4610-a900-0141c43e7867 | Idioma detectado: it
🧐 Procesando 16590/17048 - 8e66904c-12c0-4f7b-8f81-ed0f416a0d2f | Idioma detectado: it
🧐 Procesando 16591/17048 - 0a782e61-da00-4372-8cbc-4f5eb57a4708 | Idioma detectado: it
🧐 Procesando 16592/17048 - e6402e98-6e6c-4932-be63-1e8623bfefe7 | Idioma detectado: it
🧐 Procesando 16593/17048 - d429839d-9351-43e3-82d5-48da04aa7c2f | Idioma detectado: it
🧐 Procesando 16594/17048 - ceaa9e83-29e6-481d-b2a1-0db7879f1839 | Idioma detectado: it
🧐 Procesando 16595/17048 - 093f8928-6b8f-43d4-9110-196ee514d78e | Idioma detectado: it
🧐 Procesando 16596/17048 - d8f7d229-23d7-44f0-bc91-901b8256ed79 | Idioma detectado: en
✅ d8f7d229-23d7-44f0-bc91-901b8256ed79 ya está en inglés. Saltando...
🧐 Procesando 16597/17048 - 53811594-264e-4ba4-97fe-c5d68ae9c932 | Idioma detectado: en
✅ 53811594-264e-4ba4-97fe-c5d68ae9c932 ya está en inglés. Saltando...
🧐 Procesando 16598/17048 - e5b73a7a-6bc4-4fe2-8caa-9bc148191753 | Idioma detectado: en
✅ e5b73a7a-6bc4-4fe2-8caa-9bc148191753 ya está en inglés. Saltando...
🧐 Procesando 16599/17048 - a7d905c7-40d2-47f4-8d31-940e6bc6aa3f | Idioma detectado: en
✅ a7d905c7-40d2-47f4-8d31-940e6bc6aa3f ya está en inglés. Saltando...
🧐 Procesando 16600/17048 - 4d880240-560b-4a2f-a742-a86bbfc2acf8 | Idioma detectado: it

🔄 Traduciendo canciones:  98%|█████████▊| 16670/17048 [1:35:52<02:25,  2.60it/s]

🧐 Procesando 16660/17048 - cf4cf0b7-e770-40f4-9537-e7788d2791b8 | Idioma detectado: en
✅ cf4cf0b7-e770-40f4-9537-e7788d2791b8 ya está en inglés. Saltando...
🧐 Procesando 16661/17048 - 9d1df396-d017-44f4-b52f-cb56b87def5e | Idioma detectado: en
✅ 9d1df396-d017-44f4-b52f-cb56b87def5e ya está en inglés. Saltando...
🧐 Procesando 16662/17048 - a6a69fea-2b7c-4202-a225-657be61fb13d | Idioma detectado: en
✅ a6a69fea-2b7c-4202-a225-657be61fb13d ya está en inglés. Saltando...
🧐 Procesando 16663/17048 - bc304832-8b3a-4de3-8ce2-099cdaee0b7a | Idioma detectado: en
✅ bc304832-8b3a-4de3-8ce2-099cdaee0b7a ya está en inglés. Saltando...
🧐 Procesando 16664/17048 - 3dddb52a-c3b5-480a-b08a-98410d7eb341 | Idioma detectado: en
✅ 3dddb52a-c3b5-480a-b08a-98410d7eb341 ya está en inglés. Saltando...
🧐 Procesando 16665/17048 - 38b8d3b6-306a-41a3-96d0-5e43a24494fa | Idioma detectado: en
✅ 38b8d3b6-306a-41a3-96d0-5e43a24494fa ya está en inglés. Saltando...
🧐 Procesando 16666/17048 - 85af91fc-8a29-45cd-b87b-5b56a9b46e41 | Idioma detectado: en
✅ 85af91fc-8a29-45cd-b87b-5b56a9b46e41 ya está en inglés. Saltando...
🧐 Procesando 16667/17048 - d5ef4792-bb3e-4d50-a317-c69f78f55d09 | Idioma detectado: en
✅ d5ef4792-bb3e-4d50-a317-c69f78f55d09 ya está en inglés. Saltando...
🧐 Procesando 16668/17048 - d6ad653b-ea8b-4c0b-be11-fdade9c0157b | Idioma detectado: en
✅ d6ad653b-ea8b-4c0b-be11-fdade9c0157b ya está en inglés. Saltando...
🧐 Procesando 16669/17048 - 5c378af7-8114-4c7f-bbba-5e5b887efc22 | Idioma detectado: it
🧐 Procesando 16670/17048 - ac932808-5e70-4877-8163-013ca3f62d56 | Idioma detectado: la

🔄 Traduciendo canciones:  98%|█████████▊| 16739/17048 [1:36:29<02:02,  2.51it/s]

🧐 Procesando 16730/17048 - a0003c83-bda6-4a15-8c0c-52f265d725cc | Idioma detectado: en
✅ a0003c83-bda6-4a15-8c0c-52f265d725cc ya está en inglés. Saltando...
🧐 Procesando 16731/17048 - a1d48def-1a31-4f15-9453-385d471cdf1b | Idioma detectado: en
✅ a1d48def-1a31-4f15-9453-385d471cdf1b ya está en inglés. Saltando...
🧐 Procesando 16732/17048 - 54f3b888-18de-4ddb-b4af-07b2a5ab8f3b | Idioma detectado: en
✅ 54f3b888-18de-4ddb-b4af-07b2a5ab8f3b ya está en inglés. Saltando...
🧐 Procesando 16733/17048 - f6d85b27-2f32-4ea4-8941-673ef8a8b8e5 | Idioma detectado: en
✅ f6d85b27-2f32-4ea4-8941-673ef8a8b8e5 ya está en inglés. Saltando...
🧐 Procesando 16734/17048 - 57ed0c3c-aaa4-4001-9790-04435edfd16a | Idioma detectado: en
✅ 57ed0c3c-aaa4-4001-9790-04435edfd16a ya está en inglés. Saltando...
🧐 Procesando 16735/17048 - 6c5d5819-47c9-4fdb-9994-735d1822000d | Idioma detectado: en
✅ 6c5d5819-47c9-4fdb-9994-735d1822000d ya está en inglés. Saltando...
🧐 Procesando 16736/17048 - 47a2a1f9-0379-455b-9c29-57a02dde0a4b | Idioma detectado: en
✅ 47a2a1f9-0379-455b-9c29-57a02dde0a4b ya está en inglés. Saltando...
🧐 Procesando 16737/17048 - 5580ce95-c0c7-4dff-93ea-2708a3ff86cd | Idioma detectado: en
✅ 5580ce95-c0c7-4dff-93ea-2708a3ff86cd ya está en inglés. Saltando...
🧐 Procesando 16738/17048 - 9fcb0362-5e7b-4f5d-ac3b-b956d628956b | Idioma detectado: it
🧐 Procesando 16739/17048 - 279ac475-4295-40e5-ac28-c52263c5fdb6 | Idioma detectado: en
✅ 279ac475-4295-40e5-ac28-c52263c5fdb6 ya está en inglés. Saltando...
🧐 Procesando 16740/17048 - 2b7fd08f-6d1d-4038-938b-0df2daf7b781 | Idioma detectado: it

🔄 Traduciendo canciones:  99%|█████████▉| 16845/17048 [1:36:48<00:28,  7.23it/s]

✅ f6efef64-a44f-4b75-918d-4b9c420442a6 ya está en inglés. Saltando...
🧐 Procesando 16861/17048 - 63f95908-678f-427e-997b-20312e41791f | Idioma detectado: en
✅ 63f95908-678f-427e-997b-20312e41791f ya está en inglés. Saltando...
🧐 Procesando 16862/17048 - 6e164d7a-d3dd-4a7b-950f-f9ad424000ab | Idioma detectado: en
✅ 6e164d7a-d3dd-4a7b-950f-f9ad424000ab ya está en inglés. Saltando...
🧐 Procesando 16863/17048 - d3908498-597f-4cb0-9c36-1eb82fa6fbeb | Idioma detectado: en
✅ d3908498-597f-4cb0-9c36-1eb82fa6fbeb ya está en inglés. Saltando...
🧐 Procesando 16864/17048 - 953a2da3-982f-47b8-b138-4594b2d46991 | Idioma detectado: en
✅ 953a2da3-982f-47b8-b138-4594b2d46991 ya está en inglés. Saltando...
🧐 Procesando 16865/17048 - 0d27b9af-72d6-4be9-a314-f747e52c8892 | Idioma detectado: en
✅ 0d27b9af-72d6-4be9-a314-f747e52c8892 ya está en inglés. Saltando...
🧐 Procesando 16866/17048 - d28ad6bc-964b-491e-99a9-4132e053f5bb | Idioma detectado: en
✅ d28ad6bc-964b-491e-99a9-4132e053f5bb ya está en inglés. Saltando...
🧐 Procesando 16867/17048 - 83354d82-d1c4-46e8-bddc-34fba9eb53ae | Idioma detectado: en
✅ 83354d82-d1c4-46e8-bddc-34fba9eb53ae ya está en inglés. Saltando...
🧐 Procesando 16868/17048 - 87062a92-a810-4804-a4e6-10255259a799 | Idioma detectado: en
✅ 87062a92-a810-4804-a4e6-10255259a799 ya está en inglés. Saltando...
🧐 Procesando 16869/17048 - fc7e3e77-b795-4660-893d-5d6559c8354c | Idioma detectado: en
✅ fc7e3e77-b795-4660-893d-5d6559c8354c ya está en inglés. Saltando...
🧐 Procesando 16870/17048 - ebd83067-507c-4d03-8a2c-b0499c3a05e5 | Idioma detectado: pt

🔄 Traduciendo canciones: 100%|██████████| 17048/17048 [1:37:03<00:00,  2.93it/s]

✅ bb4d276f-64b0-426b-9a53-2542ebd7c1c4 ya está en inglés. Saltando...
🧐 Procesando 17038/17048 - 2fedcd61-5239-4db8-a928-1fb7ca2d60ec | Idioma detectado: en
✅ 2fedcd61-5239-4db8-a928-1fb7ca2d60ec ya está en inglés. Saltando...
🧐 Procesando 17039/17048 - 31bcf421-cb78-44c4-9929-91e3ff935496 | Idioma detectado: en
✅ 31bcf421-cb78-44c4-9929-91e3ff935496 ya está en inglés. Saltando...
🧐 Procesando 17040/17048 - c197e9a9-7ee1-47ce-98e4-560b6e089213 | Idioma detectado: en
✅ c197e9a9-7ee1-47ce-98e4-560b6e089213 ya está en inglés. Saltando...
🧐 Procesando 17041/17048 - ea2aaf32-448e-4485-95eb-7462f8fd06c5 | Idioma detectado: en
✅ ea2aaf32-448e-4485-95eb-7462f8fd06c5 ya está en inglés. Saltando...
🧐 Procesando 17042/17048 - 6e29798a-8363-4af4-8b20-1362b76c804f | Idioma detectado: en
✅ 6e29798a-8363-4af4-8b20-1362b76c804f ya está en inglés. Saltando...
🧐 Procesando 17043/17048 - 0a179d06-4747-4360-800a-8475320ca3d7 | Idioma detectado: it
🧐 Procesando 17044/17048 - 7426d47a-d3a1-4b85-becd-2d31414a4a31 | Idioma detectado: en
✅ 7426d47a-d3a1-4b85-becd-2d31414a4a31 ya está en inglés. Saltando...
🧐 Procesando 17045/17048 - 146bfc97-ec1e-4741-bb3a-60ef855268d7 | Idioma detectado: en
✅ 146bfc97-ec1e-4741-bb3a-60ef855268d7 ya está en inglés. Saltando...
🧐 Procesando 17046/17048 - b497c0a2-bf82-4222-9d56-aedcb2f7414e | Idioma detectado: en
✅ b497c0a2-bf82-4222-9d56-aedcb2f7414e ya está en inglés. Saltando...
🧐 Procesando 17047/17048 - a836589f-4d9e-47cd-823c-6f9ad78131a5 | Idioma detectado: en
✅ a836589f-4d9e-47cd-823c-6f9ad78131a5 ya está en inglés. Saltando...
✅ Proceso completado. Archivo traducido guardado en C:/Users/solan/MoodTune/data/procesando/df_80-200_p1_traducidas.csv

In [28]:
import pandas as pd
import os
import re

# Rutas de los archivos
original_file_path = r"C:\Users\solan\MoodTune\data\procesando\df_80-200_p1_with-lyrics.csv"
translated_file_path = r"C:\Users\solan\MoodTune\data\procesando\df_80-200_p1_traducidas.csv"
output_merged_file_path = r"C:\Users\solan\MoodTune\data\procesado\df_80-200_p1_traducidas_1.csv"

# Cargar datos originales y traducidos
original_data = pd.read_csv(original_file_path, encoding='utf-8')
translated_data = pd.read_csv(translated_file_path, encoding='utf-8')

# Realizar la unión de los DataFrames en base al recording_id
merged_data = pd.merge(original_data, translated_data[['recording_id', 'translated_lyrics', 'language']], on='recording_id', how='left')

# Actualizar las columnas 'translated_lyrics' y 'language' en el DataFrame original con los valores del DataFrame traducido
merged_data['translated_lyrics'] = merged_data['translated_lyrics_x'].fillna(merged_data['translated_lyrics_y'])
merged_data['language'] = merged_data['language_x'].fillna(merged_data['language_y'])

# Limpiar la columna 'lyrics' para eliminar solo los saltos de línea
merged_data['lyrics'] = merged_data['lyrics'].apply(lambda x: re.sub(r'\n+', ' ', str(x).strip()) if pd.notna(x) else x)

# Eliminar las columnas temporales 'translated_lyrics_x', 'translated_lyrics_y', 'language_x' y 'language_y'
merged_data.drop(columns=['translated_lyrics_x', 'translated_lyrics_y', 'language_x', 'language_y'], inplace=True)

# Guardar el resultado en un nuevo archivo CSV
merged_data.to_csv(output_merged_file_path, index=False, encoding='utf-8')

print(f"✅ Dataset combinado guardado en {output_merged_file_path}")

KeyError: 'translated_lyrics_x'

In [10]:
#ver hasta 200 letras de cada columna y fila completa
pd.set_option('display.max_colwidth', 200)

In [78]:
#ver si hay duplicados según recording_id en df
duplicates = df[df.duplicated(subset=['recording_id'], keep=False)]
print(f"🔍 Duplicados encontrados: {duplicates.shape[0]}")
duplicates
# eliminar duplicados
df = df.drop_duplicates(subset=['recording_id'], keep='first')
print(f"✅ Duplicados eliminados. Número de filas actual: {df.shape[0]}")

🔍 Duplicados encontrados: 2
✅ Duplicados eliminados. Número de filas actual: 12630

In [ ]:
# ver donde spotify url es nulo o vacío
missing_urls = df[df['spotify_url'].isnull() | (df['spotify_url'] == '')]
print(f"🔍 URLs de Spotify faltantes: {missing_urls.shape[0]}",
      missing_urls)
# eliminar filas con URLs faltantes
df = df.dropna(subset=['spotify_url'])
# guardar el archivo actualizado como 0_para_listas.csv
df.to_csv('C:\\Users\\solan\\MoodTune\\data\\procesando\\0_para_listas.csv', index=False, encoding='utf-8')


print(f"✅ Filas eliminadas con URLs faltantes. Número de filas actual: {df.shape[0]}")

🔍 URLs de Spotify faltantes: 0 Empty DataFrame
Columns: [artist_name, song_name, recording_id, danceable, not_danceable, male, female, timbre_bright, timbre_dark, tonal, atonal, instrumental, voice, dortmund_alternative, dortmund_blues, dortmund_electronic, dortmund_folkcountry, dortmund_funksoulrnb, dortmund_jazz, dortmund_pop, dortmund_raphiphop, dortmund_rock, electronic_ambient, electronic_dnb, electronic_house, electronic_techno, electronic_trance, rosamerica_cla, rosamerica_dan, rosamerica_hip, rosamerica_jaz, rosamerica_pop, rosamerica_rhy, rosamerica_roc, rosamerica_spe, tzanetakis_blu, tzanetakis_cla, tzanetakis_cou, tzanetakis_dis, tzanetakis_hip, tzanetakis_jaz, tzanetakis_met, tzanetakis_pop, tzanetakis_reg, tzanetakis_roc, ismir04_rhythm_ChaChaCha, ismir04_rhythm_Jive, ismir04_rhythm_Quickstep, ismir04_rhythm_Rumba-American, ismir04_rhythm_Rumba-International, ismir04_rhythm_Rumba-Misc, ismir04_rhythm_Samba, ismir04_rhythm_Tango, ismir04_rhythm_VienneseWaltz, ismir04_rhythm_Waltz, mood_acoustic, mood_not_acoustic, mood_aggressive, mood_not_aggressive, mood_electronic, mood_not_electronic, mood_happy, mood_not_happy, mood_party, mood_not_party, mood_relaxed, mood_not_relaxed, mood_sad, mood_not_sad, mood_mirex1, mood_mirex2, mood_mirex3, mood_mirex4, mood_mirex5, genre, lyrics, spotify_url, album_name, album_release_date, duration_ms, popularity, genres, tags, views, translated_lyrics, language]
Index: []

[0 rows x 86 columns]
✅ Filas eliminadas con URLs faltantes. Número de filas actual: 12098

In [74]:
# ejemplos con nombre artista, nombre canción, url spotify letra, letra traducida 
file = r"C:\Users\solan\MoodTune\data\procesado\0_spoti_last_traduc_filtered.csv"
df = pd.read_csv(file)
# ejemplos con nombre artista, nombre canción, url spotify letra, letra traducida
df[['artist_name', 'song_name', 'language', 'spotify_url', 'lyrics', 'translated_lyrics']].sample(10)

,artist_name,song_name,language,spotify_url,lyrics,translated_lyrics
9439,lyfe jennings,rock,en,https://open.spotify.com/track/4JHEq51TdSPjC4hXRRCppq,me channel marvin gaye on this one the universe baby pick a star any star baby bought myself a oneway flight to the nearest star traveling at the speed of light to get where you are ive been trave...,NaN
5736,austin wintory,underground,en,https://open.spotify.com/track/0fKWz3HVqBjWztAKI9UYRg,take a look round lively old london buzzing crowds we sweat and we revel redcheeked shouts and songs in the flicker of the gaslight eager blighty bursts from the cobblestones racing climbing bloom...,NaN
59,gwydion,triskelion horde is nigh,en,https://open.spotify.com/track/5qhhDaAig16oHwN837YIcV,three horns triskelion welcome moving mass of seasoned men that face rain and the wildest storms stoically with the same commotion of squashing a pile of worms we travel for miles miles yards not ...,NaN
2003,jeezy,i got what it takes,en,https://open.spotify.com/track/5NQRCj8bbpMYOgmYrfH77J,its hard out here for a pimp but u already rap a lil trap a lil so i hustle and flow everyday im hustlin tryna meet ma quota nextel chirpin said hey need dat quota 42 hundred look i got that fo ya...,NaN
5892,chris robinson brotherhood,meanwhile in the gods...,en,https://open.spotify.com/track/4O71PielTlrzZDVENrWBvi,older than the mountain younger that this day barefoot dreaming sleeping children dance a figure 8 lost soft velvet in a state of decay sweet tooth youth could take the abuse but not stand the cag...,NaN
7873,teleman,monday morning,en,https://open.spotify.com/track/1Nj57FJwrWgbCmlp8Hx9jF,verse 1 i dont care if its saturday night or monday morning under the plastic sky i fell asleep with the radio on i started dreaming you were in every song verse 2 and i dont care if you were yell...,NaN
8198,nielson,hoogste versnelling,nl,https://open.spotify.com/track/264g6cOU5uNfXLMj0QOnU4,intro hey hey hey hey chorus dus geloof in jezelf juist wanneer het lijkt alsof alsof het niet meer loopt je kan rennen rennen rennen met je hoofd omhoog hoog hoogste versnelling wordt wakker want...,intro hey hey hey hey chorus believe in yourself precisely when it looks like it is no longer running you can run with your head up with your head up high highest gear awake because this is your d...
7196,looptroop rockers,professional dreamers,en,https://open.spotify.com/track/72o9g0eQ81LlHE2txjisok,living the dream living living the dream dont wanna wake up verse 1 promoe i never dreamed about getting paid i dreamed that the people never forget the name looptroop i dreamed about getting fame...,NaN
260,dead by april,let the world know,en,https://open.spotify.com/track/3AVhvkX5a1VDcsMmNevi9P,trust the words i say im willing to go the distance but im a little bit fragile im just saying lets take this slow dont get me wrong let em know write it in magazines in the papers put it all over...,NaN
6108,cambriana,face to face,en,https://open.spotify.com/track/4AWDoGEhA1UnECtyDP0Bo6,wendy youre stuck in my game i know wouldnt be here without pain for sure 50 years on no one will know the delicate humdrum ways of this love if you can keep up someday finally face to face its so...,NaN

In [67]:
import pandas as pd

# Ruta del archivo
file_path = r"C:\Users\solan\MoodTune\data\procesado\0_spoti_last_traduc2.csv"

# Cargar el archivo CSV
df = pd.read_csv(file_path, encoding='utf-8')

# Seleccionar las filas que quiero eliminar según el recording_id y eliminarlas
recording_ids_to_remove = [
    'f35eec7b-8f08-4f6d-bed1-a67c4b9b0d4c', '9979b5a4-1a5d-4b6f-9004-234bbc82dc13', '4969c286-4ece-4c2b-96e6-df3527feba8a',
    '1faabf48-0822-4680-9678-2968f3de1a73', '914d3c88-d8df-4cdd-a6b2-2a610d2b6576', '645eaf75-1464-4e1d-974e-5b1c7391e710',
    '2e47fae9-38cb-41f0-967f-d06c5f4384af', '8cfcecc0-cac8-4dbb-ac06-2b3436b59a7f', 'eecf8953-eec0-4bf3-8245-b55e44a74dab',
    'e9b488c3-3134-464e-b163-79ffab430568', 'c774abd3-7323-4614-8a80-173ada2017ab', 'dcd8e392-9fe8-4e6e-9587-61f39d26faa2',
    '720dffee-082d-4624-ba14-c906794da152', '4608246e-012d-4f00-9182-6a239c014aa5', '8d3a78bf-db98-4476-aabf-326cf4bfb0c4',
    'afdc83d0-a815-4ce5-bb88-5ddb32886594', '75a3afb0-5cbe-47a1-90c9-086aadb432c6', '06e6e3d9-39d2-4c3d-97c4-d8ca3a44f08c',
    'ab5d00d4-d01e-4277-9bce-7bf9824225b1', '15683acf-b5ad-4502-939b-9cb3cae7b50e', '0345d4d6-a39d-47bf-acd4-3a5f4a315fd5',
    '65850282-7ec2-488a-935c-fb319f43da50', '517b5d24-9e13-4560-9d07-6237608bfe78'
]
df = df[~df['recording_id'].isin(recording_ids_to_remove)]

# Rellenar las filas restantes con valores nulos en la columna 'language' con 'en'
df['language'].fillna('en', inplace=True)

# Guardar el DataFrame actualizado en un nuevo archivo CSV
output_file_path = r"C:\Users\solan\MoodTune\data\procesado\0_spoti_last_traduc_filtered.csv"
df.to_csv(output_file_path, index=False, encoding='utf-8')

print(f"✅ Filas eliminadas y archivo guardado en {output_file_path}")

C:\Users\solan\AppData\Local\Temp\ipykernel_22936\293487216.py:23: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['language'].fillna('en', inplace=True)

✅ Filas eliminadas y archivo guardado en C:\Users\solan\MoodTune\data\procesado\0_spoti_last_traduc_filtered.csv

In [23]:
# ver todo el output en la consola de la celda
pd.set_option('display.max_rows', None)

In [71]:
#ver columnas únicas de df  y contar valores únicos viendo todas las filas

df.nunique()

artist_name                            6232
song_name                             11791
recording_id                          12630
danceable                               988
not_danceable                           988
male                                    988
female                                  988
timbre_bright                           987
timbre_dark                             987
tonal                                   989
atonal                                  989
instrumental                            986
voice                                   986
dortmund_alternative                    487
dortmund_blues                          388
dortmund_electronic                     996
dortmund_folkcountry                    621
dortmund_funksoulrnb                     69
dortmund_jazz                           244
dortmund_pop                            124
dortmund_raphiphop                      199
dortmund_rock                           519
electronic_ambient                      994
electronic_dnb                          334
electronic_house                        771
electronic_techno                       201
electronic_trance                       991
rosamerica_cla                          750
rosamerica_dan                          805
rosamerica_hip                          738
rosamerica_jaz                          663
rosamerica_pop                          879
rosamerica_rhy                          906
rosamerica_roc                          991
rosamerica_spe                          184
tzanetakis_blu                          147
tzanetakis_cla                          159
tzanetakis_cou                          151
tzanetakis_dis                          137
tzanetakis_hip                          257
tzanetakis_jaz                          404
tzanetakis_met                          122
tzanetakis_pop                          183
tzanetakis_reg                          164
tzanetakis_roc                          286
ismir04_rhythm_ChaChaCha                992
ismir04_rhythm_Jive                     466
ismir04_rhythm_Quickstep                123
ismir04_rhythm_Rumba-American           335
ismir04_rhythm_Rumba-International      436
ismir04_rhythm_Rumba-Misc               176
ismir04_rhythm_Samba                    250
ismir04_rhythm_Tango                    962
ismir04_rhythm_VienneseWaltz            992
ismir04_rhythm_Waltz                    307
mood_acoustic                           984
mood_not_acoustic                       984
mood_aggressive                         971
mood_not_aggressive                     971
mood_electronic                         988
mood_not_electronic                     988
mood_happy                              986
mood_not_happy                          986
mood_party                              986
mood_not_party                          986
mood_relaxed                            987
mood_not_relaxed                        987
mood_sad                                969
mood_not_sad                            969
mood_mirex1                             394
mood_mirex2                             628
mood_mirex3                             770
mood_mirex4                             435
mood_mirex5                             933
genre                                  1206
lyrics                                12629
spotify_url                           12091
album_name                             7620
album_release_date                     2516
duration_ms                           10438
popularity                               68
genres                                 6118
tags                                   5753
views                                     0
translated_lyrics                      1495
language                                 57
dtype: int64

In [72]:
# valores únicos de language
df['language'].unique()

array(['en', 'es', 'haw', 'ro', 'fi', 'de', 'fr', 'bn', 'fil', 'sv', 'la',
       'pt', 'it', 'ko', 'ca', 'so', 'hr', 'nl', 'da', 'ja', 'cy', 'ru',
       'ig', 'no', 'hi', 'ga', 'ht', 'jv', 'af', 'ms', 'fa', 'zh', 'id',
       'pl', 'ne', 'et', 'eo', 'az', 'sl', 'mg', 'tr', 'sw', 'is', 'sk',
       'co', 'yo', 'zu', 'tl', 'ha', 'hu', 'gl', 'lt', 'eu', 'mt', 'sm',
       'mi', 'th'], dtype=object)

In [70]:
#contar nulos en language
df['language'].isnull().sum()

np.int64(0)

In [69]:
# ver todas las columnas con nulos en language donde se vea 'artist_name', 'song_name', 'language', 'lyrics' y spotify url    
df[df['language'].isnull()][['artist_name', 'song_name', 'recording_id' , 'language', 'lyrics', 'spotify_url']]

Empty DataFrame
Columns: [artist_name, song_name, recording_id, language, lyrics, spotify_url]
Index: []

In [68]:
#ver ejemplos donde language es nulo y que se vea la letra  
# Filtrar las filas donde la columna 'language' es nula
# y mostrar las columnas 'artist_name', 'song_name', 'language', 'lyrics'   y canciones traducidas
# de las primeras filas
df[df['language'].isnull()][['artist_name', 'song_name', 'language', 'lyrics', 'translated_lyrics']].sample(5)

ValueError: a must be greater than 0 unless no samples are taken

In [37]:
#nulos idioma  en df
df[df['language'].isnull()]

,artist_name,song_name,recording_id,danceable,not_danceable,male,female,timbre_bright,timbre_dark,tonal,...,spotify_url,album_name,album_release_date,duration_ms,popularity,genres,tags,views,translated_lyrics,language
23,jb and the moonshine band,doin fine,c6804ef5-1496-4768-8e11-508b4bb04222,0.246,0.754,0.003,0.997,0.984,0.016,0.973,...,https://open.spotify.com/track/6HGN7nA0O2u63uRGn1AjfT,Jb and The Moonshine Band,2010-07-12,216097.0,2.0,"beer, kid rock, scat, racism, trump",Unknown,NaN,NaN,NaN
49,the limousines,triangle circle square,8e48e54c-3e8c-4a06-ba0c-e438e0cd00e8,0.930,0.070,0.997,0.003,0.161,0.839,0.755,...,https://open.spotify.com/track/4XNYWcyRl5helntSSJWlQr,Get Sharp,2011-04-26,156466.0,5.0,"indie, electronic, experimental, electronica, electropop","alternative rock, alternative pop, New Discoveries, groovunky",NaN,NaN,NaN
143,digitalism,no cash,5c3b3dc0-41ea-490d-a993-cb6608e0e19d,0.967,0.033,0.479,0.521,0.951,0.049,0.730,...,https://open.spotify.com/track/4XqvBvciliAIcxpi9vpAZi,Mirage,2016-05-13,350320.0,10.0,"electronic, electro, dance, seen live, german",Unknown,NaN,NaN,NaN
390,hanzel und gretyl,let the planets burn,83cb4e73-7d69-41dd-9751-211dbdab4c7c,1.000,0.000,0.619,0.381,0.098,0.902,0.258,...,https://open.spotify.com/track/4bA1PXPjsvoXVYyMyYUDpH,Uber Alles,2003-05-20,204173.0,9.0,"industrial metal, industrial, industrial rock, german, metal","industrial, industrial metal, metal, 9th evolution, heavy metal",NaN,NaN,NaN
421,mavado,cleara,cd3b2720-4be8-4613-9286-179fb8666759,0.985,0.015,0.414,0.586,0.835,0.165,0.005,...,https://open.spotify.com/track/4okA5cv1Q4gkLFt7KjmAe7,Cleara,2011-01-11,142666.0,4.0,"dancehall, reggae, gangsta, jamaican, Bashment","dancehall, mavado, gully god",NaN,NaN,NaN
668,ben caplan,i got me a woman,d3367565-c71a-4f77-9093-35274c79033a,0.992,0.008,0.183,0.817,0.132,0.868,0.906,...,https://open.spotify.com/track/6C5Vd7aQgpbTIVh3JGBJCg,Birds With Broken Wings,2015-09-18,186186.0,24.0,"seen live, folk, blues, Canadian, beard",Unknown,NaN,NaN,NaN
787,they might be giants,and mom and kid,5ea4c1ba-ee53-41a4-add4-9ad257fa22d8,0.919,0.081,0.171,0.829,0.976,0.024,0.409,...,https://open.spotify.com/track/6nn4RbxQa3LAllA9QBo57b,Why?,2015-11-27,82810.0,2.0,"alternative, indie, rock, seen live, geek rock",Unknown,NaN,NaN,NaN
812,chelsea wolfe,welt,c0dd0962-b882-40c8-a02b-fd5386294668,0.594,0.406,0.962,0.038,0.000,1.000,0.312,...,https://open.spotify.com/track/0NMjFAr3aJf4z4vIeFz6Vs,Hiss Spun,2017-09-22,114443.0,19.0,"experimental, folk, female vocalists, singer-songwriter, Gothic","noise, female vocalists, dark, drone, Gothic Rock",NaN,NaN,NaN
1107,rozwell kid,my saturn,a3394492-d770-482c-a539-4a329b8408f0,0.428,0.572,0.549,0.451,0.284,0.716,0.314,...,https://open.spotify.com/track/6Yx2lEL1L2Wgm57GBY5wIk,The Rozwell Kid LP,2011-09-06,180671.0,2.0,"alternative rock, power pop, indie rock, seen live, indie",Unknown,NaN,NaN,NaN
1118,fehrplay,everywhere you go,ba1ffecf-a3f6-443c-98bb-918ba4bed8f4,0.997,0.003,0.687,0.313,0.033,0.967,0.023,...,https://open.spotify.com/track/5qAr6loIEuuDMK25Lsjymq,Everywhere You Go (Radio Edit),2014-07-15,205740.0,13.0,"electronic, Progressive House, House, norwegian, house beach electronic",trance,NaN,NaN,NaN
1154,lapalux,flower,fadf0512-25bb-4122-9ff2-0d5ce4d7a6f8,0.000,1.000,0.625,0.375,0.035,0.965,0.149,...,https://open.spotify.com/track/5J2klYUvvMwNuum7DQh7Re,Nostalchic,2013-03-25,252013.0,17.0,"future garage, electronic, experimental, dubstep, Lo-Fi",experimental,NaN,NaN,NaN
1323,shirobon,perfect machine,60b8fb76-68ee-4231-a364-a1c9a178fb22,1.000,0.000,0.971,0.029,0.117,0.883,0.099,...,https://open.spotify.com/track/0l1AqnZeC0xZHBcJz3g54N,Distant Reality,2014-02-04,253090.0,19.0,"chiptune, 8-bit, electronic, 8bit, british",Unknown,NaN,NaN,NaN
1489,f(x),my style,f35eec7b-8f08-4f6d-bed1-a67c4b9b0d4c,1.000,0.000,0.898,0.102,0.755,0.245,0.397,...,https://open.spotify.com/track/0ZqrpZ1tHasnwrjkCcJk3M,Pinocchio -The 1st Album,2011-04-20,222493.0,16.0,"k-pop, Korean, female vocalists, dance, Kpop","k-pop, dance, Korean, fx, female",NaN,NaN,NaN
1540,susana baca,canta susana,9979b5a4-1a5d-4b6f-9004-234bbc82dc13,0.688,0.312,0.225,0.775,0.897,0.103,0.144,...,https://open.spotify.com/track/3NUWEzQ3uqn0qCdn22kw1y,Afrodiaspora,2011-01-01,207933.0,4.0,"latin, Peru, female vocalists, world, World Music",Unknown,NaN,NaN,NaN
1686,eden's bridge,spirit of the living god,2ca38dfd-3af2-406c-978c-d0a98cf1ca7a,0.016,0.984,0.976,0.024,0.843,0.157,0.212,...,https://open.spotify.com/track/0ghwLTb7ozaSy6cK2o0yBJ,Celtic Worship,1997-01-01,111733.0,6.0,"celtic, christian, worship, celtic worship, folk",Gospel Religious,NaN,NaN,NaN
1747,sweatshop,drug,fdb7db42-053d-4718-a78c-28a94709f52e,0.765,0.235,0.179,0.821,0.424,0.576,0.176,...,https://open.spotify.com/track/2kJJSp1XCVDt2nbJoYhUwo,Can We Get Hooked Up ?,2013-04-17,248058.0,14.0,"seen live, jazz, allaboutjazz, dour festival 2006, Hip-Hop","Hip-Hop, funk, Belgium, beats, fip",NaN,NaN,NaN
1842,beverly,out on a ride,0dff6e12-752a-459c-bcca-47968cb772db,0.000,1.000,0.616,0.384,0.060,0.940,0.489,...,https://open.spotify.com/track/6UKkFqXZkLWsBVkB7s0wwn,Careers,2014-07-01,128052.0,1.0,"shoegaze, indie pop, indie, dream pop, female vocalists",Unknown,NaN,NaN,NaN
1963,ringo deathstarr,california car collection,a0efe4e9-94e6-4e71-8471-f66511f68d24,0.003,0.997,0.823,0.177,0.634,0.366,0.741,...,https://open.spotify.com/track/52Xe2MlRXywaqSUZWE4dal,Pure Mood,2015-11-20,211285.0,4.0,"shoegaze, noise pop, indie, seen live, austin","indie, shoegaze, noise pop, dream pop, newgaze",NaN,NaN,NaN
2017,the radio dept.,the one,c4def85d-c87e-4ab3-a523-c1a06468ba5b,0.999,0.001,0.642,0.358,0.213,0.787,0.023,...,https://open.spotify.com/track/11Wk1DafAExRrg2ZMgh8ht,Passive Aggressive,2011-01-25,185040.0,13.0,"shoegaze, indie, swedish, indie pop, electronic","swedish, shoegaze, indie, pop, BIRP",NaN,NaN,NaN
2572,dead coast,jenny loves the sun,4a5ab3f5-180d-4753-9121-9b0701e70b2a,0.066,0.934,0.212,0.788,0.123,0.877,0.286,...,https://open.spotify.com/track/7kw7awLP9pdNP8sLRTZKt2,Shambolic,2016-02-05,146250.0,7.0,"Surf, seen live, rock, Garage Rock, Psychedelic Rock",Unknown,NaN,NaN,NaN
2738,chthonic,rage of my sword,4969c286-4ece-4c2b-96e6-df3527feba8a,0.000,1.000,0.622,0.378,0.023,0.977,0.000,...,https://open.spotify.com/track/3hJzaEaQFCshwSol7WBe9q,Bù-Tik,2013-01-01,278426.0,6.0,"black metal, Symphonic Black Metal, melodic black metal, taiwanese, metal","Symphonic Black Metal, melodic black/death metal",NaN,NaN,NaN
2741,chthonic,set fire to the island,1faabf48-0822-4680-9678-2968f3de1a73,0.000,1.000,0.622,0.378,0.001,0.999,0.005,...,https://open.spotify.com/track/289I1tx2ew5ViJRzIdFGU2,失竊千年,2014-12-30,256649.0,9.0,"black metal, Symphonic Black Metal, melodic black metal, taiwanese, metal","Symphonic Black Metal, d, melodic black/death metal",NaN,NaN,NaN
2843,ray wylie hubbard,opium,70066219-0f9e-424b-959b-ac19dec08342,0.154,0.846,0.668,0.332,0.824,0.176,0.035,...,https://open.spotify.com/track/6wNY6LOjNaEcC4G6MTnxHA,A: Enlightenment B: Endarkenment (Hint: There Is No C),2010-01-12,212640.0,3.0,"country, americana, Alt-country, singer-songwriter, texas",drugs,NaN,NaN,NaN
3016,crookers,birthday bash,b88c15b6-c601-452e-aacc-723983520e20,1.000,0.000,0.326,0.674,0.188,0.812,0.071,...,NaN,NaN,NaN,NaN,NaN,"electro, electronic, seen live, dirty electro, fidget house",1Live Fiehe,NaN,NaN,NaN
3057,james ferraro,dream on,6aeff4c3-ec8d-464f-9b3a-fa00d6788355,0.092,0.908,0.622,0.378,0.143,0.857,0.830,...,https://open.spotify.com/track/4qQZRnY1GWNYIbO1GVAHp6,Far Side Virtual,2011,187418.0,9.0,"experimental, ambient, drone, psychedelic, noise",vaporwave,NaN,NaN,NaN
3611,roland,somewhere down the lane,aca44d10-dcca-4a8e-b3e2-04809532b2aa,0.000,1.000,0.622,0.378,0.071,0.929,0.858,...,https://open.spotify.com/track/2XWNMLYFh7Pxo5MZFft8MW,Retaliate,2012-01-06,257419.0,27.0,"seen live, blues, belgian, Hip-Hop, electronic",Vanessa Hudgens,NaN,NaN,NaN
3748,peter frampton,the one in 901,516c15f4-174d-4b4c-8947-4cf0be61a206,0.812,0.188,0.599,0.401,0.739,0.261,0.253,...,NaN,NaN,NaN,NaN,NaN,"classic rock, rock, 70s, guitar, singer-songwriter",Unknown,NaN,NaN,NaN
3981,tut tut child,oracle,91761545-1802-4a71-8151-492297e9188c,1.000,0.000,0.934,0.066,0.018,0.982,0.029,...,https://open.spotify.com/track/4PTmyrVwLvTVP7IlFy8BCd,Come to the End; Then Stop,2016-02-24,207191.0,23.0,"dubstep, drumstep, electronic, glitch hop, electro","EDM, bass music, monstercat, edm trap",NaN,NaN,NaN
4181,birthh,interlude for the lifeless,4f31742b-6671-4326-b9d5-f4ef2277bfc3,0.009,0.991,0.599,0.401,0.744,0.256,0.290,...,https://open.spotify.com/track/0PvC3DPETOTLVGTdLscu6C,Born in the Woods,2016-03-18,181000.0,1.0,"pop, electronic, italian, folk, indie pop",Unknown,NaN,NaN,NaN
4425,minor victories,out to sea,843d7b19-3cfc-4592-b451-3569bffd1c4d,0.362,0.638,0.956,0.044,0.029,0.971,0.577,...,https://open.spotify.com/track/7I0IrVptFNO5XiN2N6ObHJ,Minor Victories,2016-06-03,249227.0,3.0,"shoegaze, post-rock, seen live, dream pop, indie rock",Unknown,NaN,NaN,NaN
4524,orange caramel,one love,4f81fd92-1953-406c-9ad6-6be7cc4050a3,0.999,0.001,0.983,0.017,0.745,0.255,0.072,...,https://open.spotify.com/track/0DMDJRy4j0K4QFEQfnCudr,LIPSTICK,2012-09-12,201874.0,22.0,"k-pop, Korean, Kpop, pop, after school","k-pop, Orange Caramel, Korean, Kpop, pop",NaN,NaN,NaN
4591,the daylights,terra firma,9b7ac411-ded3-453f-b7c3-98e3051abc68,0.797,0.203,0.704,0.296,0.648,0.352,0.857,...,https://open.spotify.com/track/29yLZIJmewKV4TXflrOS0o,The Daylights,2010-09-14,315333.0,2.0,"alternative rock, indie rock, indie, rock, seen live","electronic, pop, pop rock, calm, catchy",NaN,NaN,NaN
5072,usher,pianolude,14641950-6c43-4f04-b387-ea7bdab4ae53,0.233,0.767,0.154,0.846,0.980,0.020,0.946,...,https://open.spotify.com/track/6gcWu0UJ5D0N9Z4tHHSd88,Live,1999-03-23,212600.0,9.0,"rnb, Hip-Hop, pop, soul, rap","p, soul, rnb, Usher, r'n'b",NaN,NaN,NaN
5343,dotexe,turn on the radio,914d3c88-d8df-4cdd-a6b2-2a610d2b6576,0.987,0.013,0.988,0.012,0.239,0.761,0.010,...,https://open.spotify.com/track/68oLDV0B92A2hEzh1SuMTO,Classics.exe,2015-02-17,228022.0,4.0,"dubstep, electro house, electronic, trance, Liquid",Unknown,NaN,NaN,NaN
5511,lorn,sv_cheats 0,0aed479a-773c-4332-8ded-44cc80fb95c6,1.000,0.000,0.754,0.246,0.002,0.998,0.000,...,https://open.spotify.com/track/076YR7emgXxyyeGAXrm71U,The Maze To Nowhere,2015,230500.0,23.0,"idm, electronic, dubstep, black metal, electro",electronic,NaN,NaN,NaN
5766,jessica,summer storm,645eaf75-1464-4e1d-974e-5b1c7391e710,0.007,0.993,0.981,0.019,0.981,0.019,0.982,...,https://open.spotify.com/track/1529SgqRNt42kZDdLCSJ8d,My Decade,2017-08-09,201689.0,26.0,"pop, female vocalists, k-pop, Korean, Jessica","k-pop, 2017, pop, Asian, rnb",NaN,NaN,NaN
6327,capleton,lock up,b1c8c083-96aa-4f92-ac6d-bc72edc620f7,0.910,0.090,0.906,0.094,0.176,0.824,0.409,...,https://open.spotify.com/track/08A6R2kx6H0cAvepISefqq,Ragga Ragga Ragga 16,2011-03-09,205013.0,14.0,"reggae, dancehall, ragga, jamaica, roots","dancehall, reggae, 2002, Wicked, Bollywood Riddim",NaN,NaN,NaN
6401,screaming females,wrecking ball,6ad50dbd-395e-4aa7-b086-2e36c2e0788b,0.845,0.155,0.704,0.296,0.745,0.255,0.257,...,https://open.spotify.com/track/59BLpMeP13hZhmBR2pbLiH,Chalk Tape,2014-01-01,163278.0,2.0,"seen live, punk, rock, Lo-Fi, female vocalists",lol,NaN,NaN,NaN
6578,xilent,hysteria,33d065dc-dd19-4c38-b392-aed54ec631c3,1.000,0.000,0.633,0.367,0.010,0.990,0.048,...,https://open.spotify.com/track/1VemjoVxMgvfb9NTsbVOZV,We Are Virtual,2015-05-17,301620.0,4.0,"Drum and bass, dubstep, neurofunk, electronic, techstep","electronic, dubstep, electro house, EDM, Brostep",NaN,NaN,NaN
6654,iron reagan,broken bottles,9b2646d1-cc2e-440f-9af8-a50908eb7f39,0.902,0.098,0.175,0.825,0.001,0.999,0.911,...,https://open.spotify.com/track/5Gc8eEZL9XsXMyqly2JjNU,The Tyranny of Will (Deluxe Version),2014-09-16,128412.0,16.0,"thrash metal, crossover, hardcore punk, hardcore, crossover thrash","metal, punk, thrash metal, hardcore punk, crossover thrash",NaN,NaN,NaN
6802,gretchen peters,hello cruel world,5aa35c0f-ddb9-4f8e-8f0f-9f8f0035590a,0.137,0.863,0.280,0.720,0.228,0.772,0.245,...,https://open.spotify.com/track/3gar23XVQ9oXsa59BZcRQX,Hello Cruel World,2012,262786.0,24.0,"country, female vocalists, singer-songwriter, Alt-country, Female country","country, Alt-country, singer-songwriter, americana, double-ender 16",NaN,NaN,NaN
6836,sun glitters,feel it,421b0216-565d-4ae2-b0b4-04e0e3d4e156,0.872,0.128,0.695,0.305,0.128,0.872,0.011,...,https://open.spotify.com/track/0ni9v4ttAmZ1MbM6jFUzvk,Everything Could Be Remodeled And That's Fine,2011-10-17,222013.0,0.0,"chillwave, experimental, dubstep, shoegaze, wonky","chillwave, Luxembourg, vaporwave, chillout, electronic",NaN,NaN,NaN
7093,jmsn,everything fades,c7602e47-178c-4fc8-9292-2f01d487f526,0.038,0.962,0.745,0.255,0.328,0.672,0.972,...,https://open.spotify.com/track/4HE7QwcXLKSc084tbxDIAR,Pllajë,2013-11-05,130558.0,6.0,"rnb, alternative rnb, r&b, soul, romantic","2013, 4 Stars, contemporary r&b",NaN,NaN,NaN
7177,mindless self indulgence,memory of heaven,0ea35fdc-3537-4ab9-b29b-644d0a7d24ce,1.000,0.000,0.304,0.696,0.271,0.729,0.553,...,https://open.spotify.com/track/43wCJYjaSPFsTNPW1jlE6y,PINK,2015-09-18,181093.0,35.0,"industrial, industrial jungle pussy punk, punk, electronic, alternative",post-nerdcore,NaN,NaN,NaN
7235,miracle of sound,higher tonight,0ed6b8f8-875e-48a7-ac7c-a557230ecda1,1.000,0.000,0.318,0.682,0.113,0.887,0.500,...,https://open.spotify.com/track/7eJai4g69MDrFP7Kg3qb3V,Level 4,2013-11-21,203383.0,13.0,"rock, video game music, irish, male, metal",Unknown,NaN,NaN,NaN
7874,hanni el khatib,born brown,2e47fae9-38cb-41f0-967f-d06c5f4384af,0.971,0.029,0.270,0.730,0.021,0.979,0.058,...,https://open.spotify.com/track/6QdzM12DS0eqmRAJXTQjyS,Savage Times,2017-02-17,116986.0,5.0,"Garage Rock, blues rock, rock, blues, seen live",Unknown,NaN,NaN,NaN
8065,zee avi,nightlight medley,342d77cb-4c96-4d20-bee4-86bacc5a6332,0.004,0.996,0.678,0.322,0.996,0.004,0.854,...,https://open.spotify.com/track/2EhVjnbTYtwwG4yfazNbx2,Zee Avi's Nightlight,2014-04-22,257616.0,10.0,"indie, singer-songwriter, female vocalist, female vocalists, alternative",Unknown,NaN,NaN,NaN
8095,professor longhair,whole lot of loving,c00c41e7-9a4f-42c9-9056-c6b392166aaf,0.167,0.833,0.008,0.992,0.900,0.100,0.997,...,https://open.spotify.com/track/0duj9pzN8McNekgfeaWJrT,THE GREATEST HITS: Professor Longhair - Cry To Me,2022-11-18,336414.0,0.0,"blues, New Orleans, jazz, rhythm and blues, piano",Unknown,NaN,NaN,NaN
8207,sneaks,future,b40528d5-9d6c-4556-9ca6-e1e311f0e82c,0.990,0.010,0.618,0.382,0.001,0.999,0.025,...,https://open.spotify.com/track/7APwimjqlozgk7hgYib7IA,It's a Myth,2017-03-31,135800.0,29.0,"post-punk, Crank wave, spoken word, art punk, rap punk",Unknown,NaN,NaN,NaN
8262,belleruche,scratch my soul,2abce02d-f82c-4c69-a692-22a452febe04,0.996,0.004,0.928,0.072,0.156,0.844,0.121,...,https://open.spotify.com/track/2rPT4RLPtRLMbO2mKV5QPw,The Express,2008-10-13,215506.0,33.0,"trip-hop, nu jazz, soul, electronic, funk","trip-hop, soul, nu jazz, chillout, lounge",NaN,NaN,NaN
8561,biga ranx,liquid sunshine,ef9934ee-6499-484c-9854-dcae2ce42f25,0.708,0.292,0.569,0.431,0.708,0.292,0.826,...,https://open.spotify.com/track/0EsxNQzT43ufsPw4U7gK0l,1988,2017-06-09,193493.0,48.0,"reggae, french, hip hop, rap, electronic",Unknown,NaN,NaN,NaN
8731,daniel cavanagh,this music,1b8f5043-d735-4743-b3a1-8dd847e70dfe,0.054,0.946,0.628,0.372,0.938,0.062,0.808,...,https://open.spotify.com/track/0QCYKS2focxUzzPiRfCLyq,Monochrome,2017-10-13,292919.0,17.0,"acoustic, alternative rock, rock, singer-songwriter, seen live",beautiful,NaN,NaN,NaN
8732,daniel cavanagh,soho,be214bc4-d374-4aba-9fbb-0b38b666ad7a,0.025,0.975,0.833,0.167,0.486,0.514,0.028,...,https://open.spotify.com/track/08FM5N3CeJig093sudO0oN,Monochrome,2017-10-13,461725.0,13.0,"acoustic, alternative rock, rock, singer-songwriter, seen live",Unknown,NaN,NaN,NaN
8987,pink martini,kaj kolah khan,8cfcecc0-cac8-4dbb-ac06-2b3436b59a7f,0.328,0.672,0.639,0.361,0.980,0.020,0.953,...,https://open.spotify.com/track/2Vt2QAMmdUzayXGOgsLR1g,Je dis oui!,2016-11-18,189646.0,8.0,"jazz, lounge, chillout, latin, easy listening",fip,NaN,NaN,NaN
9003,pinkwash,sigh,4c4264e7-c52c-4a82-ad13-20f3e2d28cbd,0.286,0.714,0.888,0.112,0.514,0.486,0.005,...,https://open.spotify.com/track/0sYbuJbC5BThlIpHJYiHIV,COLLECTIVE SIGH,2016-05-13,253320.0,0.0,"punk, seen live, indie rock, noise rock, punk rock",Unknown,NaN,NaN,NaN
9009,dawn wall,if i smiled,eecf8953-eec0-4bf3-8245-b55e44a74dab,1.000,0.000,0.637,0.363,0.000,1.000,0.000,...,https://open.spotify.com/track/7rKNoKsC4wi2Bwbc6lhVzD,You Remember,2015-06-22,275862.0,16.0,"Drum and bass, dnb, electronic, british, funk",Unknown,NaN,NaN,NaN
9019,nic cowan,hard headed,c9999e6e-34a8-47c3-ac55-876a830286ac,0.981,0.019,0.441,0.559,0.458,0.542,0.398,...,NaN,NaN,NaN,NaN,NaN,"seen live, Southern Rock, singer-songwriter, atlanta, sxsw 2012","acoustic, blues rock, sxsw 2012, allboutguitar",NaN,NaN,NaN
9035,vhs head,the murder cycles,453aa89a-56cd-4e59-84a7-6267b2f02f39,1.000,0.000,0.622,0.378,0.001,0.999,0.069,...,https://open.spotify.com/track/73Z14T0xKPAtczrPNTuJiw,Trademark Ribbons of Gold,2010-09-03,282586.0,2.0,"idm, glitch, electronic, experimental, better than radiohead","experimental, nu rave",NaN,NaN,NaN
9037,vhs head,dpp39,e9b488c3-3134-464e-b163-79ffab430568,1.000,0.000,0.622,0.378,0.005,0.995,0.083,...,https://open.spotify.com/track/2oakrxZW47mozQVPLDbhNA,Trademark Ribbons of Gold,2010-09-03,185360.0,1.0,"idm, glitch, electronic, experimental, better than radiohead","Samplecore, experimental, downtempo, idm, glitch-hop",NaN,NaN,NaN
9038,vhs head,twitch of the nerve,c774abd3-7323-4614-8a80-173ada2017ab,1.000,0.000,0.622,0.378,0.012,0.988,0.215,...,https://open.spotify.com/track/4587fIQLwgmd9laAkx0LB7,Trademark Ribbons of Gold,2010-09-03,285000.0,1.0,"idm, glitch, electronic, experimental, better than radiohead","experimental, glitch core, Endgegnermusik, Somewhere Out There",NaN,NaN,NaN
9207,diana panton,in a world of my own,24765871-d226-48c6-9338-fc2a1680a6a6,0.025,0.975,0.947,0.053,0.843,0.157,0.705,...,https://open.spotify.com/track/3swn99nwQ7mXapf0z7Okos,I Believe In Little Things,2015-06-30,238106.0,32.0,"jazz, vocal jazz, female vocalists, Canadian, fmera jazz",Unknown,NaN,NaN,NaN
9263,orange caramel,so sorry,dcd8e392-9fe8-4e6e-9587-61f39d26faa2,0.999,0.001,0.807,0.193,0.952,0.048,0.051,...,https://open.spotify.com/track/4MnScTkmgWHVflkzKOhcZY,THE THIRD SINGLE CATALLENA,2014-03-12,182996.0,25.0,"k-pop, Korean, Kpop, pop, after school","k-pop, cute, Orange Caramel, favorite songs, female vocalists",NaN,NaN,NaN
9271,circulatory system,there is no time but now,7a23469a-2908-4081-aaac-797eaa2d0f7f,0.731,0.269,0.793,0.207,0.056,0.944,0.021,...,https://open.spotify.com/track/1Q21Hbs12bmoCCfMFVJwmF,Mosaics Within Mosaics,2014,209213.0,1.0,"Elephant 6, psychedelic, indie, Lo-Fi, indie pop",Unknown,NaN,NaN,NaN
9272,chelsea wolfe,move,720dffee-082d-4624-ba14-c906794da152,0.009,0.991,0.987,0.013,0.966,0.034,0.779,...,NaN,NaN,NaN,NaN,NaN,"experimental, folk, female vocalists, singer-songwriter, Gothic","indie, folk, experimental, Lo-Fi, ethereal",NaN,NaN,NaN
9618,devo,ohio,4608246e-012d-4f00-9182-6a239c014aa5,0.961,0.039,0.123,0.877,0.716,0.284,0.314,...,https://open.spotify.com/track/4r9vudoTZWsjn86drdQrAl,When Pigs Fly: Songs You Never Thought You'd Hear,2008-07-15,201000.0,3.0,"new wave, post-punk, 80s, alternative, rock","cover, covers, Ohio, The Covers Record, political",NaN,NaN,NaN
9646,helene fischer,feliz navidad,8d3a78bf-db98-4476-aabf-326cf4bfb0c4,0.963,0.037,0.996,0.004,0.832,0.168,0.562,...,https://open.spotify.com/track/1NrA4h7XNZ0UvtnzlR5U1r,Weihnachten,2016-11-18,213413.0,24.0,"Helene Fischer, Schlager, Deutsche Schlager, deutsch, Und morgen frueh kuess ich Dich wach",Unknown,NaN,NaN,NaN

In [ ]:
df_non_english.sample(20)

,artist_name,song_name,spotify_url,language,lyrics,translated_lyrics
61496,yelle,le grand saut,https://open.spotify.com/track/6ro7kKnnbgMVllC2ij5VCL,fr,cours ne te retourne pas le futur ouvre grand ses bras jour j pour faire le bon choix je monte a bord du vaisseau aujourdhui le grand saut cours ne te retourne pas le futur ouvre grand ses bras jour j pour faire le bon choix je monte a bord du vaisseau aujourdhui le grand saut le hasard sorganise et il suivra mes pas je mimmunise la pluie ne tombe pas sur moi mon hoodie en maille de fer lui resistera en un eclair je lui ouvre la voie le hasard sorganise et il suivra mes pas je mimmunise la pluie ne tombe pas sur moi mon hoodie en maille de fer lui resistera en un eclair je lui ouvre la voie cours ne te retourne pas le futur ouvre grand ses bras jour j pour faire le bon choix je monte a bord du vaisseau aujourdhui le grand saut le grand saut,lessons do not turn you around the future opens big day J to make the right choice I go up on board the ship today the big leap course does not turn you around the future opens big day D to make the right choice I go up on boardFrom the vessel today the big jump the sorganized chance and he will follow my steps I mimminate the rain does not fall on me my hoodie in iron mesh will resist him in an enclosure I opens the way to him the sorganized chance and he will follow my steps I mimmise theRain does not fall on me my hoodie in iron mesh will resist him in a light I opens the way to him does not turn you around the future opens his day jar to make the right choice I climb on board the ship today the big jumpThe big jump
74538,bisz,indygo,https://open.spotify.com/track/2XVzSdrpRpJN2PWeifnDet,pl,zwrotka 1 urodziłeś się królem pokaż wszystkim koronę kłów berło pięści wznieś jak księżyc nad morzem głów twój tron nosisz ze sobą ciągle na spodzie stóp nie szata czyni króla masz na sobie tylko spojrzeń rój niebo jest twoim dachem orszakiem ptaki o świcie błazny masy dla ciebie jak ty dla nich bo żyjesz poza ich pogonią i za czym za słoną cenę zapłaci każdy z nich gdy obudzi się za zasłoną nie ma nic poza spokojnym oddechem pierś bóstwa rozszerza się wszechświatem potem zapada się w punkt aby na nowo wziąć wdech i spokojnie się wzwyż wznieść cichy proces żaden wydumany big bang między ziemią a niebem jest człowiek z głową w chmurach stąpając twardo przewodzę przez moje życie tę siłę która czyni ciężkość lekką baranek który jest lwem jestem piękną bestią zmieszaj najjaśniejszy błękit z jak najgłębszą czernią refren wszyscy którzy wrócili z biegunów zawsze będą ze mną weź najciemniejszą czerń zmieszaj ją z jasnoniebieskim wyzwolony od zwycięstw i klęsk obserwuj ich zmierzch w indygo indygo indygo indygo indygo indygo indygo bridge gdy już nie wiesz dokąd iść słuchaj krwi która krąży w tobie daj się ponieść daj się ponieść w kolorze twojej krwi tkwi symbol i odpowiedź daj się ponieść daj się ponieść zwrotka 2 masz w sobie coś co możesz pokazać tylko wybranym wciąż jest nas zbyt mało by doprowadzić do zmiany lecz każdy z nas ma moc by zacząć powoli wsączać łzy w serce skały aby poruszyć monolit wiemy że możemy sprawić aby świat był lepszy i kto musi wziąć na barki trud nowi architekci my bo tu miejsca dla nas brak wciąż i gdy tylko chcesz otworzyć się słyszysz że masz się zamknąć lecz jeśli myśleli że mogą kazać ci cokolwiek tylko ze względu na twoją słabość biada im nauka dla ciebie i dla nich oby stąd wynikła nie wszyscy jeszcze się poddali chodnikowy wilk brat z otchłani bólu rozpaczy niewiary po szczyty nieba zrozumienia wolności i chwały stratowany fortuny kołem wiem jedno że to odległość pomiędzy górą a dołem jest pełnią refren outro gdy już nie wiesz dokąd iść słuchaj krwi która krąży w tobie daj się ponieść daj się ponieść w kolorze twojej krwi tkwi symbol i odpowiedź włóż koronę włóż koronę,"verse 1 You were born king. Show all the crown of fangs crown. ""Moon at the sea of ​​your head your throne.For them because you live beyond their pursuit and for what the salty price will pay each of them when he wakes up behind the veil, there is nothing but the calm breath of the deity breast expands the universe then falls into a point to breathe in and calmly rise up a quiet processNo dug -out big bang between the earth and the sky is a man with my head in the clouds, walking hard, lead through my life this strength which makes the heavyness of a light lamb which is a lion I am a beautiful beast mix the brightest blue with the deepest black chorus the chorus everyone who returned from the poles will always be with meTake the darkest black, mix it with a light blue liberated from victories and disaster, watch their twilight in indigo indigo indigo indigo indigo bridge when you don't know where to go listen to blood that circulates in you let yourself be carried away let yourself be carried away in the color of your bloodLet yourself be carried away by the verse 2 you have something that you can only show the chosen ones are still too little to lead to change, but each of us has the power to start slowly on the heart of the rock to move the monolith we know that we can make the world to be the worldbetter and who has to take the effort new architects, we because there is still no places for us and whenever you want to open up you can hear that you have to close, but if they thought that they can have anything because of your weakness woe to you and for you and for youLet them result from here not everyone surrendered to the pavement wolf brother from the abyss of the pain of disbelief to the heavenly of the sky of understanding of freedom and glory, the stratified fortune, I know one thing that this distance between the mountain and bottom is the right chorus outro when you do not know where to go to where you listen to the blood that circulatesLet yourself be carried away in the color of your blood lies the symbol and answer put the crown put the crown"
39152,azad,du fehlst mir,https://open.spotify.com/track/0MRzijtXBacxFou0IU3uiT,de,"[Part I] Ich trag dich in meinem Herzen Ganz egal, wo ich auch sein mag Du bist immer mit mir, das ist keine Frage Es ist schmerzlich, wenn mein Herz bricht Eine Hälfte ist bei dir, immer wenn du weit entfernt bist Bis zu dem Tag, wo wir uns wiedersehen und es zusammenwächst Und ich bete zu Gott, dass es für immer zusammenhält Mein Leben, du bist alles für mich Ich leg dir meine Welt zu Füßen, das ist alles für dich Glaub mir, wenn du da bist Gibt es nichts mehr, was ich brauche hier um glücklich zu sein Es gibt viele Träume, doch ich wünsch mir nur ein' Er ist, dich für immer lächeln zu sehen Ich bin immer für dich da, hab mein Versprechen gegeben Engel, Worte sind zu schwach Um dieses starke Gefühl zu beschreiben Das ich für dich fühle, ich kann es nur zeigen Bin zuweilen am verzweifeln, frag mich oft wie geht's ihr Ich bin nicht komplett ohne dich... [Hook] Du fehlst mir Fehlst mir so sehr Dieses Leben ohne dich, es ist so leer Du fehlst mir Wünsch du wärst hier Dieser Schmerz zerbricht dieses Herz hier Du fehlst mir Fehlst mir so sehr Dieses Leben ohne dich, es ist so schwer Du fehlst mir Fehlst mir mein Engel Ich denk nur an dich, bis an mein Ende [Part II] Ich schließ die Augen und ich seh dich vor mir Diese Liebe, die ich habe Engel, geb' ich nur dir Du bist mein Licht, es wird wieder gut, bitte wein nicht Es bringt mich um, tief im Innern wie ein Einstich Gott ist groß und seine Wege unergründlich Engel, hab Vertrauen, sieh nach vorn und sei glücklich Denn er wird uns wieder vereinen Mach dir keine Sorgen, denk dran, du bist niemals allein Ich bin bei dir, in Gedanken, bis du wieder kommst Fühl mich leer ohne dich, ich bin wie benommen Das ist tiefe Liebe Denk an deine schönen Augen Mein Herz, in deren Glanz ich mich widerspiegel Du bist mein Lebenselixier Dieses Herz in mir, wem soll ichs geben, wenn nicht dir? Es ist Sehnsucht pur, die mich quält hier Weiß nich', wie ich leben soll ohne dich [Hook] [Part III] Ich frag' mich was du machst, frag mich wo du bist Frag mich wie's dir geht, Engel, ich denk nur an dich Du fehlst mir! Fehlst mir so sehr! Dieser Stein auf meinem Herzen, er ist so schwer Herr, bitte gib mir Kraft, diese Last zu tragen Ich bin am Boden, es erdrückt mich an manchen Tagen Warum muss es immer so sein? Ich krieg Krisen Könnt 'ne Knarre nehmen und um mich schießen Tränen fließen über mein Gesicht Meine Welt ist verdunkelt ohne dein Licht Und ich bin nicht mehr ich Nur ein Schatten meiner selbst, der langsam in sich zerbricht Ich will den Schmerz ersticken im Rauch Will ihn ertränken im Alk, aber er kommt wieder rauf Es gibt kein Heil für das Leid, das ich jetzt durchleb' hier Außer dich, mein Licht, Engel, du fehlst mir [Hook]","[Part I] I wear you in my heart, wherever I may be you are always with me, that's no question, it is painful when my heart breaks a half with you, whenever you are far away up toThe day when we see each other again and it grows together and I pray to God that it holds my life together forever, you are everything for me I put my world to feet, that's all for you think to me when you are thereThere is nothing more that I need to be happy here there are many dreams, but I only want one 'he is to see you forever I am always there for you, gave my promise angels, words are too weakTo describe this strong feeling that I feel for you, I can only show it, sometimes I am despair, ask me often how are you I am not completely without you ... [hook] I miss you so much without this life withoutyou, it is so empty You miss you wish you would be this pain this heart breaks here you lack I miss this life so much this life without you, it is as difficult as I miss my angel I just think of you, up to youMy end [Part II] I close my eyes and I see you in front of me this love that I have angels, I only give you my light, it will be good again, please do not change my inside, deep insideLike a puncture God is great and his paths are unfathomable, have trust, look ahead and be happy because he will unite us again, do not worry, remember, you are never alone with you, in your thoughts until you are backcome empty without you, I am how dazzling that is deep love think of your beautiful eyes my heart, in whose glory I reflect you are my elixir of life this heart in me, who should I give if not?It is longing pure that torments me here doesn't know how I should live without you [hook] [part iii] I ask myself what you do, ask me where you are, ask me, angel, I just thinkI miss you!I miss so much!This stone on my heart, it is so heavy, please give me strength to wear this load I am on the ground, it crushes me on some days why does it always have to be like that?I get crises can take a creak and shoot tears flow over my face my world is darkened without your light and I am no longer a shadow of myself that brakes slowly I want to suffocate the pain in the smokeDrown in the alk, but he comes up again there is no salvation for the suffering that I am now lying through here except you, my light, angel, you are missing [hook]"
53007,eagulls,opaque,https://open.spotify.com/track/3U1mmFAFcc0qppvTIDcTVj,NaN,NaN,NaN
29099,still fresh,le même sort,https://open.spotify.com/track/167G8YzpXA7DJ4RH9Gd7mG,fr,intro ne peu importe le mode de vie on aura tous le même sort couplet 1 ok jai même pas un vélo sur le poignet jai peu vu les douaniers dans le métro je fraude ouais jme vois déjà à broadway came sous le kway jreste calme bien qulétat me uét limpression dêtre un pion dans un jeu de dames ouais jeune et djà fatigué sur les bons rails mais pas dticket gros jai lambition daudigier pullup pullup dj jveux partir sur une bonne note sans utiliser dantisèche jsuis celui qui veut grayer en période de disette refrain cherche la monnaie toute la life certains tisent toute la night tous coincés dans le même sort parce quon vit pas les mêmes galères touche pas le même salaire mais finit par le même sort parce quau bout du compte personne pour taider au fond dune teille de sky tu cherches des mayday peu importe le coût de la life quand séteint la night on en subit le même sort pont jsuis frappé par hé rattrapé par hé jsuis frappé par la réalité jsuis frappé par hé rattrapé par hé jsuis frappé par la réalité couplet 2 jsuis loin du féfé sur le poignet la misère ma empoigné mon coeur mon corps ont saigné jai pris des coups de poignards on ma dit garde ton calme attends mais jcrois plus en ces charlatans jvais péter un bleca maintenant cest en char que jattends personne ne vole son destin quil soit glorieux ou vulgaire plutôt quune mauvaise perte jpréfère quce soit de bonne guerre mon label simpatiente si jsors mon contrat tésau les enjeux nsont pas les mêmes donc remballe avec tes soces refrain pont couplet 3 parfois le coeur brisé criblé jaimerais me tirer jsuis pessimiste rare que la paix simisse jmattends au pire et jtiens encore en songeant à mon sort cest par la grande porte pas celle de derrière si jmen sort jmefforce dêtre patient même si jsais pas cqui mattend parfois atteint mais paré pour un bon plan jaimerais que tout passe vite ouais tout passe vite en un clin doeil avoir un carrière à la 2pac big refrain,Intro does not matter the lifestyle we will all have the same verse fate 1 ok I don't even have a bike on the wrist I have little seen the customs officers in the metro I fraud yeah I already see on Broadway Cam under the kway jreste calm althoughUtet of being a pawn in a game of ladies yeah young and djà tired on the right rails but not doticket big jai lambition daudigier poulup poulup dj jveux leave on a good note without using the jsuis jsuis who wantscurrency all the life certain all the night all stuck in the same fate because we do not live the same galleys do not touch the same salary but ends with the same fate because on the end of the account no one to the bottom of a sky you are looking forMayday regardless of the cost of the life when the Night Subsequently Suffices the same jsuis bridge fate struck by hey hey jsuis struck by the reality jsuis struck by hey caught by hey jsuis struck by reality verse 2 jsuis far from the féfé on féféThe wrist the misery my grab my heart my body has bled I took stabbings I was said to keep your calm waiting but I can more in these charlatans I fart a bleca now it is in chariot that jatrends no one steals his destiny that it is glorious orVulgar rather than a bad loss jpri that is good war my Simpatiente label if I have my contract for the stakes do not the same so booted with your chorus fabric soy sometimes the broken heart shunned I would like to shoot me jsuis pessimistic rare that peace similarat worst and still jet by thinking of my fate is by the big door not that behind if I go out to be patient even if I don't have a matter sometimes reached but adorned for a good plan I would like that everything goes quickly yeah everything goes quickly in aClin doeil have a career at 2Pac Big Réfrain
53430,holy wave,sir isaac nukem,https://open.spotify.com/track/42ASCwyFqut1to4IbB0VXe,es,mientras veías la porquería del mundo y nada más que su declive preferirías pensar que es absurdo que ya no te sirve y es mejor tirarlo y ves el potencial en la pérdida muere un poco para nacer mejor de un parto doloroso es el cambio y la celebración te guía la luna y te alimentas del sol crees que nada es real fuera de la dominación puro placer puro dolor aguanta el deseo sin consumarlo de piernas abiertas a la necesidad global y ves el potencial en la pérdida muere un poco para nacer mejor de un parto doloroso es el cambio y la celebración te guía la luna y te alimentas del sol muere un poco para nacer mejor de un parto doloroso es el cambio y la celebración te guía la luna y te alimentas del sol,While you saw the reason for the world and nothing more than its decline you would prefer to think that it is absurd that it no longer serves you and it is better to throw it and you see the potential in the loss dies a bit to be born better of a painful birth is the change and the celebration youGuide the moon and feed from the sun you think that nothing is real out of domination pure pleasure pure pain endures desire without consummating it open to global need and you see the potential in the loss dies a bit to be born better of a painful childbirthIt is the change and the celebration guides you the moon and you feed on the sun dies a bit to be born better of a painful birth is the change and the celebration guides you the moon and you feed on the sun
52352,booba,oklm,https://open.spotify.com/track/68XgYFn7NtFxvn8gZzqrEZ,fr,92 izi a coups dfusil se regla la querelle je ne fais ni dans la fantaisie ni dans la quenelle jtaurai demain ou apres demain cest du pareil au meme jsuis la branche alqaida du game jles fais sauter euxmemes jsuis la branche alqaida du game jles fais sauter euxmemes luna ma go sure sous les bras beni soit ce quelle devienne jai tout eu meme ce que je ne voulais pas jaime etre cque vous netes pas jai rien vu jai rien entendu mais jsais que vous ny etes pas sueur de taureau sous les draps nique ta mere on ty aidera vous jactez car vous nassumez pas tous ces millions sous mes pas non negro je nte connais pas si crime tu ne commets pas drapeau pirate sous les bras on se reconnaitra ma carriere est incroyable si jvais en enfer jpaie le voyage tu peux matteindre mais jsuis injoignable la hainezer que je trainezer est insoignable jsuis pas le negre ideal nan prison drogue sexe idealement jai quitte le terter au volant du rr loup de la casse jsuis un expert tas aime sucer jai aime cesaire au calme au calme au calme au calme au calme au calme au calme au calme jcontrole la zone jusquen guyana jai pose ltrone sur lfujiyama si je lattrape pauvre rihanna jvais la decouper sur place comme a benihana jtla mets dans le uczer en cas de ragnagna negro arme jamais vaincu sur la boitezer de banania on te trouvera dans une chicha tes quun sale rapiat tu vas faire ci tu vas faire ca arrete ton charabia jme suis jure detre loyal jsuis jnoune couronne cest ca detre royal mords a lhamecon ou cest la noyade je reste incompris ma carriere est incroyable,NaN

#### 🤔💼 Otros intentos, pruebas etc...

In [ ]:
from langdetect import detect
from googletrans import Translator
import pandas as pd
import sys
import csv

# Aumentar el límite del tamaño de campo
sys.setrecursionlimit(10000)
csv.field_size_limit(10**9) 

# Configuración inicial para prueba
file_path = r'C:\Users\solan\Downloads\get_data_from_songs\data\final_idiomas.csv'  # Ruta al archivo original
output_file_path = r'C:\Users\solan\Downloads\get_data_from_songs\data\archivo_prueba_traducido.csv'  # Ruta de salida para la prueba
error_file_path = r'C:\Users\solan\Downloads\get_data_from_songs\data\errors_log_prueba.csv'  # Ruta del archivo de errores para la prueba
translator = Translator()


# Cargar el archivo completo
data = pd.read_csv(file_path, encoding='utf-8', engine='python')

# Filtrar las filas que no están en inglés
non_english_rows = []
for index, row in data.iterrows():
    if pd.isna(row['language']) or row['language'] != 'en':
        non_english_rows.append(row)
    if len(non_english_rows) >= 100:  # Seleccionar solo las primeras 100
        break

# Crear un DataFrame con las primeras 100 filas que no son inglés
test_data = pd.DataFrame(non_english_rows)

# Añadir columna para letras traducidas si no existe
if 'translated_lyrics' not in test_data.columns:
    test_data['translated_lyrics'] = None

# Crear un DataFrame vacío para almacenar errores
errors = pd.DataFrame(columns=['index', 'lyrics', 'error_message'])

# Procesar y traducir
for index, row in test_data.iterrows():
    try:
        # Detectar idioma si no está indicado
        lang = row['language'] if pd.notnull(row['language']) else detect(row['lyrics'])
        
        # Traducir solo si no está en inglés
        if lang != 'en':
            translation = translator.translate(row['lyrics'], src=lang, dest='en')
            test_data.at[index, 'translated_lyrics'] = translation.text

    except Exception as e:
        # Registrar el error en el DataFrame de errores
        errors = pd.concat([errors, pd.DataFrame({'index': [index], 
                                                  'lyrics': [row['lyrics']], 
                                                  'error_message': [str(e)]})])

# Guardar los resultados de la prueba
test_data.to_csv(output_file_path, index=False, encoding='utf-8')
errors.to_csv(error_file_path, index=False, encoding='utf-8')
print("Prueba completada. Resultados y errores guardados.")

In [ ]:
import pandas as pd

# 📂 Ruta del archivo original
file_path = r"C:\Users\solan\Downloads\get_data_from_songs\src\functions b\df_lyrics_faltan_traduc.csv"
output_filtered_path = r"C:\Users\solan\Downloads\get_data_from_songs\data\filtrado_para_traduccion.csv"

# 🔹 Cargar el archivo original
df = pd.read_csv(file_path, low_memory=False)

# 🔹 Filtrar: donde `language` no sea "en" y `translated_lyrics` esté vacío o NaN
df_filtered = df[(df['language'] != "en") & (df['translated_lyrics'].isna())]

# 🔹 Guardar el nuevo CSV para usar en la traducción
df_filtered.to_csv(output_filtered_path, index=False, encoding="utf-8")

print(f"✅ Archivo filtrado guardado en: {output_filtered_path}")

✅ Archivo filtrado guardado en: C:\Users\solan\Downloads\get_data_from_songs\data\filtrado_para_traduccion.csv

In [ ]:
import sys
import csv
import pandas as pd
from langdetect import detect
from googletrans import Translator
import re
from tqdm import tqdm  # Importar tqdm para barra de progreso

# Aumentar el límite del tamaño de campo
sys.setrecursionlimit(10000)
csv.field_size_limit(10**9)

# Configuración inicial
file_path = r'C:\Users\solan\Downloads\get_data_from_songs\data\filtrado_para_traduccion.csvv'  # Ruta al archivo original
output_file_path = r'C:\Users\solan\Downloads\get_data_from_songs\data\df_scrap_traducido.csv'  # Ruta de salida
error_file_path = r'C:\Users\solan\Downloads\get_data_from_songs\data\errors_log_traduccion.csv'  # Archivo de errores
batch_size = 1000  # Guardar cada 1,000 filas procesadas
translator = Translator()

# Función para limpiar texto
def clean_text(text):
    if pd.isna(text):
        return ""
    # Reemplazar saltos de línea y espacios múltiples por un solo espacio
    text = re.sub(r'\s+', ' ', text.replace('\n', ' ').strip())
    return text

# Cargar datos
data = pd.read_csv(file_path, encoding='utf-8', engine='python')

# Añadir columna para letras traducidas si no existe
if 'translated_lyrics' not in data.columns:
    data['translated_lyrics'] = None

# Crear un DataFrame vacío para almacenar errores
errors = pd.DataFrame(columns=['index', 'lyrics', 'error_message'])

# Procesar y traducir con barra de progreso
for index, row in tqdm(data.iterrows(), total=data.shape[0], desc="Procesando letras de canciones"):
    try:
        # Verificar si ya existe una traducción
        if pd.notnull(row['translated_lyrics']):
            continue

        # Limpiar la letra antes de procesar
        lyrics_cleaned = clean_text(row['lyrics'])

        # Detectar idioma si no está indicado
        lang = row['language'] if pd.notnull(row['language']) else detect(lyrics_cleaned)

        # Traducir solo si no está en inglés
        if lang != 'en' and lyrics_cleaned:
            translation = translator.translate(lyrics_cleaned, src=lang, dest='en')
            data.at[index, 'translated_lyrics'] = translation.text

        # Guardar cada batch de filas procesadas
        if index % batch_size == 0:
            data.to_csv(output_file_path, index=False, encoding='utf-8')
            errors.to_csv(error_file_path, index=False, encoding='utf-8')

    except Exception as e:
        # Registrar el error en el DataFrame de errores
        errors = pd.concat([errors, pd.DataFrame({'index': [index], 
                                                  'lyrics': [row['lyrics']], 
                                                  'error_message': [str(e)]})])

# Guardar archivo final
data.to_csv(output_file_path, index=False, encoding='utf-8')
errors.to_csv(error_file_path, index=False, encoding='utf-8')
print("Proceso completado y archivo final guardado.")

Opcion deep trasnlator

In [ ]:
from deep_translator import GoogleTranslator

# Crear un traductor de español a inglés
translator = GoogleTranslator(source="auto", target="en")

# Traducir una frase de prueba
translation = translator.translate("Hola mundo")
print(translation)  # Output: "Hello world"

Hello world

In [ ]:
translated_data = translated_data.drop_duplicates(subset=['recording_id'])

data = data.merge(translated_data[['recording_id', 'translated_lyrics']], on='recording_id', how='left', suffixes=('', '_prev'))
data['translated_lyrics'] = data['translated_lyrics'].combine_first(data['translated_lyrics_prev'])
data.drop(columns=['translated_lyrics_prev'], inplace=True)

In [ ]:
if os.path.exists(output_file_path):
    translated_data = pd.read_csv(output_file_path, encoding='utf-8', engine='python', on_bad_lines="skip")
    print("📌 Columnas en traducidas.csv:", translated_data.columns)

NameError: name 'os' is not defined

otro modelo - no

In [ ]:
from transformers import MarianMTModel, MarianTokenizer
from langdetect import detect
import pandas as pd

# Configuración del modelo MarianMT
model_name = "Helsinki-NLP/opus-mt-es-en"  # Cambia el modelo según el idioma (ej. `es-en`, `fr-en`)
tokenizer = MarianTokenizer.from_pretrained(model_name)
model = MarianMTModel.from_pretrained(model_name)

# Función para traducir usando MarianMT
def translate_marian(texts, source_lang="es", target_lang="en"):
    inputs = tokenizer(texts, return_tensors="pt", padding=True, truncation=True)
    translated = model.generate(**inputs)
    return [tokenizer.decode(t, skip_special_tokens=True) for t in translated]

# Cargar datos del archivo
file_path = r'C:\ruta\a\final_idiomas.csv'  # Ruta del archivo original
output_file_path = r'C:\ruta\a\final_idiomas_traducido_marian.csv'  # Archivo de salida
data = pd.read_csv(file_path, encoding='utf-8')

# Añadir columna para letras traducidas si no existe
if 'translated_lyrics' not in data.columns:
    data['translated_lyrics'] = None

# Procesar y traducir
for index, row in data.iterrows():
    try:
        # Verificar si ya existe una traducción
        if pd.notnull(row['translated_lyrics']):
            continue
        
        # Detectar idioma si no está especificado
        lyrics = row['lyrics']
        lang = row['language'] if pd.notnull(row['language']) else detect(lyrics)

        # Traducir solo si el idioma no es inglés
        if lang != 'en' and pd.notnull(lyrics):
            translated_text = translate_marian([lyrics])[0]
            data.at[index, 'translated_lyrics'] = translated_text

    except Exception as e:
        print(f"Error al traducir en la fila {index}: {e}")

# Guardar archivo final con traducciones
data.to_csv(output_file_path, index=False, encoding='utf-8')
print(f"Traducciones completadas. Archivo guardado en {output_file_path}.")

In [ ]:
pd.set_option('display.max_colwidth', None)

NameError: name 'pd' is not defined

In [4]:
import pandas as pd
import csv

# 📂 Rutas de los archivos
final_url_path = r"C:\Users\solan\MoodTune\data\procesando\df_80-200_p2_last.csv"
translated_lyrics_path = r"C:\Users\solan\MoodTune\data\procesando\df_80-200_p2_last_traducidas.csv"
output_path = r"C:\Users\solan\MoodTune\data\procesando\df_80-200_p2_traducidas.csv"

# 1️⃣ Cargar los archivos CSV
df_final = pd.read_csv(final_url_path, low_memory=False)
df_translations = pd.read_csv(translated_lyrics_path, low_memory=False)

# 2️⃣ Verificar que 'recording_id' existe en ambos
if 'recording_id' not in df_final.columns or 'recording_id' not in df_translations.columns:
    raise KeyError("❌ ERROR: 'recording_id' no se encuentra en ambos datasets.")

# 3️⃣ Seleccionar solo la columna 'recording_id' y 'translated_lyrics' para fusionar
df_translations = df_translations[['recording_id', 'translated_lyrics']]

# 4️⃣ Reemplazar saltos de línea por un espacio simple y limpiar espacios extra
df_translations['translated_lyrics'] = df_translations['translated_lyrics'].astype(str).apply(lambda x: " ".join(x.split()))

# 5️⃣ Hacer el merge por 'recording_id'
df_merged = df_final.merge(df_translations, on='recording_id', how='left')

# 6️⃣ Guardar el archivo final con formato correcto
df_merged.to_csv(output_path, index=False, quoting=csv.QUOTE_ALL, lineterminator='\n')

print(f"✅ Archivo final guardado con las traducciones en: {output_path}")

✅ Archivo final guardado con las traducciones en: C:\Users\solan\MoodTune\data\procesando\df_80-200_p2_traducidas.csv

In [ ]:
df_non_english.head()